// c07-dp-final-carrier; parent 063bce8e plus four signed startup-record fields.
// Complete source family; no TU-state probes or wall-time truncation.
// 2 arms; 1.5832908032462 seconds; source restored.
// Artifacts: build/source-variant-batch/c07-dp-final-carrier/results.json
// Disposition and full native/retail verification: docs/reconstruction/C07.md.
// Per arm: trial; size; text hash; normalized relocation hash; exact/total blocks; graph exact.
// 0; 580; c8db9d0502d093fa; 2ed4c83da218f929; 21/22; True
// 1; 580; 2692174ccf5307f5; 2ed4c83da218f929; 21/22; True

/* Exact source axes:
{
  "schema": 1,
  "source": "src/SOURCE/dpnetwin.cpp",
  "rva": "0x36f33",
  "axes": [
    {
      "name": "carrier-boundary",
      "find": "void dpEvaluateMessage(u32l size, i32 sender) {\n    DirectPlayStartupMessage* startup = reinterpret_cast<DirectPlayStartupMessage*>(rcvBufIn + 1);\n    i32 i;\n\n    switch (static_cast<NetworkPacketType>(rcvBufIn[0])) {\n        case NETWORK_PACKET_DATA:\n            ppDPRcvBuffer[iDPRcvBufferHead] = static_cast<u8*>(H2_ALLOC(size - 1));\n            memcpy(ppDPRcvBuffer[iDPRcvBufferHead], rcvBufIn + 1, size - 1);\n            piDPRcvBufferSize[iDPRcvBufferHead] = size;\n            iDPRcvBufferHead = (iDPRcvBufferHead + 1) % DP_TRANSPORT_BUFFER_COUNT;\n            break;\n        case NETWORK_PACKET_GUEST_ARRIVED:\n            if (GameMode == REMOTE_GAME_NETWORK_HOST) {\n                for (i = 1; i < giNumHumanPlayers; i++) {\n                    if (giNetPosToDCOPos[i] == sender) {\n                        dpSendMessage(sender, NETWORK_PACKET_GUEST_ACCEPTED, 0, NULL);\n                        return;\n                    }\n                }\n                if (gbRemoteGameOpen != 0) {\n                    giNetPosToDCOPos[giNumHumanPlayers] = sender;\n                    gsNetPlayerInfo[giNumHumanPlayers] =\n                        *reinterpret_cast<SNetPlayerInfo*>(startup);\n                    if (gsNetPlayerInfo[giNumHumanPlayers].reserved[0] == 0)\n                        xNetHasOldPlayers = true;\n                    dpSendMessage(sender, NETWORK_PACKET_GUEST_ACCEPTED, 0, NULL);\n                    giNumHumanPlayers++;\n                } else {\n                    dpSendMessage(sender, NETWORK_PACKET_GUEST_REJECTED, 0, NULL);\n                }\n            }\n            break;\n        case NETWORK_PACKET_GUEST_ACCEPTED:\n            giHostAcceptStatus = HOST_ACCEPT_ACCEPTED;\n            break;\n        case NETWORK_PACKET_GUEST_REJECTED:\n            giHostAcceptStatus = HOST_ACCEPT_REJECTED;\n            break;\n        case NETWORK_PACKET_STARTUP:\n            giNumHumanPlayers = startup->playerCount;\n            giThisNetPos = startup->netPosition;\n            LogInt(\n                \"DPMSGSTARTUP\",\n                giThisNetPos,\n                sender,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE\n            );\n            memcpy(giNetPosToDCOPos, startup->playerIds, sizeof(giNetPosToDCOPos));\n            bStartUpInfoReceived = true;\n            break;\n        default:\n            sprintf(gText, \"Unknown message: %d\\n\", static_cast<i32>(rcvBufIn[0]));\n            LogStr(gText);\n            break;\n    }\n}\n",
      "options": [
        {
          "name": "erased-startup",
          "replace": "void dpEvaluateMessage(u32l size, i32 sender) {\n    void* startup = rcvBufIn + 1;\n    i32 i;\n\n    switch (static_cast<NetworkPacketType>(rcvBufIn[0])) {\n        case NETWORK_PACKET_DATA:\n            ppDPRcvBuffer[iDPRcvBufferHead] = static_cast<u8*>(H2_ALLOC(size - 1));\n            memcpy(ppDPRcvBuffer[iDPRcvBufferHead], rcvBufIn + 1, size - 1);\n            piDPRcvBufferSize[iDPRcvBufferHead] = size;\n            iDPRcvBufferHead = (iDPRcvBufferHead + 1) % DP_TRANSPORT_BUFFER_COUNT;\n            break;\n        case NETWORK_PACKET_GUEST_ARRIVED:\n            if (GameMode == REMOTE_GAME_NETWORK_HOST) {\n                for (i = 1; i < giNumHumanPlayers; i++) {\n                    if (giNetPosToDCOPos[i] == sender) {\n                        dpSendMessage(sender, NETWORK_PACKET_GUEST_ACCEPTED, 0, NULL);\n                        return;\n                    }\n                }\n                if (gbRemoteGameOpen != 0) {\n                    giNetPosToDCOPos[giNumHumanPlayers] = sender;\n                    gsNetPlayerInfo[giNumHumanPlayers] =\n                        *static_cast<SNetPlayerInfo*>(startup);\n                    if (gsNetPlayerInfo[giNumHumanPlayers].reserved[0] == 0)\n                        xNetHasOldPlayers = true;\n                    dpSendMessage(sender, NETWORK_PACKET_GUEST_ACCEPTED, 0, NULL);\n                    giNumHumanPlayers++;\n                } else {\n                    dpSendMessage(sender, NETWORK_PACKET_GUEST_REJECTED, 0, NULL);\n                }\n            }\n            break;\n        case NETWORK_PACKET_GUEST_ACCEPTED:\n            giHostAcceptStatus = HOST_ACCEPT_ACCEPTED;\n            break;\n        case NETWORK_PACKET_GUEST_REJECTED:\n            giHostAcceptStatus = HOST_ACCEPT_REJECTED;\n            break;\n        case NETWORK_PACKET_STARTUP:\n            giNumHumanPlayers = static_cast<DirectPlayStartupMessage*>(startup)->playerCount;\n            giThisNetPos = static_cast<DirectPlayStartupMessage*>(startup)->netPosition;\n            LogInt(\n                \"DPMSGSTARTUP\",\n                giThisNetPos,\n                sender,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE\n            );\n            memcpy(giNetPosToDCOPos, static_cast<DirectPlayStartupMessage*>(startup)->playerIds, sizeof(giNetPosToDCOPos));\n            bStartUpInfoReceived = true;\n            break;\n        default:\n            sprintf(gText, \"Unknown message: %d\\n\", static_cast<i32>(rcvBufIn[0]));\n            LogStr(gText);\n            break;\n    }\n}\n"
        },
        {
          "name": "erased-payload",
          "replace": "void dpEvaluateMessage(u32l size, i32 sender) {\n    void* payload = rcvBufIn + 1;\n    i32 i;\n\n    switch (static_cast<NetworkPacketType>(rcvBufIn[0])) {\n        case NETWORK_PACKET_DATA:\n            ppDPRcvBuffer[iDPRcvBufferHead] = static_cast<u8*>(H2_ALLOC(size - 1));\n            memcpy(ppDPRcvBuffer[iDPRcvBufferHead], rcvBufIn + 1, size - 1);\n            piDPRcvBufferSize[iDPRcvBufferHead] = size;\n            iDPRcvBufferHead = (iDPRcvBufferHead + 1) % DP_TRANSPORT_BUFFER_COUNT;\n            break;\n        case NETWORK_PACKET_GUEST_ARRIVED:\n            if (GameMode == REMOTE_GAME_NETWORK_HOST) {\n                for (i = 1; i < giNumHumanPlayers; i++) {\n                    if (giNetPosToDCOPos[i] == sender) {\n                        dpSendMessage(sender, NETWORK_PACKET_GUEST_ACCEPTED, 0, NULL);\n                        return;\n                    }\n                }\n                if (gbRemoteGameOpen != 0) {\n                    giNetPosToDCOPos[giNumHumanPlayers] = sender;\n                    gsNetPlayerInfo[giNumHumanPlayers] =\n                        *static_cast<SNetPlayerInfo*>(payload);\n                    if (gsNetPlayerInfo[giNumHumanPlayers].reserved[0] == 0)\n                        xNetHasOldPlayers = true;\n                    dpSendMessage(sender, NETWORK_PACKET_GUEST_ACCEPTED, 0, NULL);\n                    giNumHumanPlayers++;\n                } else {\n                    dpSendMessage(sender, NETWORK_PACKET_GUEST_REJECTED, 0, NULL);\n                }\n            }\n            break;\n        case NETWORK_PACKET_GUEST_ACCEPTED:\n            giHostAcceptStatus = HOST_ACCEPT_ACCEPTED;\n            break;\n        case NETWORK_PACKET_GUEST_REJECTED:\n            giHostAcceptStatus = HOST_ACCEPT_REJECTED;\n            break;\n        case NETWORK_PACKET_STARTUP:\n            giNumHumanPlayers = static_cast<DirectPlayStartupMessage*>(payload)->playerCount;\n            giThisNetPos = static_cast<DirectPlayStartupMessage*>(payload)->netPosition;\n            LogInt(\n                \"DPMSGSTARTUP\",\n                giThisNetPos,\n                sender,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE,\n                LOG_UNUSED_VALUE\n            );\n            memcpy(giNetPosToDCOPos, static_cast<DirectPlayStartupMessage*>(payload)->playerIds, sizeof(giNetPosToDCOPos));\n            bStartUpInfoReceived = true;\n            break;\n        default:\n            sprintf(gText, \"Unknown message: %d\\n\", static_cast<i32>(rcvBufIn[0]));\n            LogStr(gText);\n            break;\n    }\n}\n"
        }
      ]
    }
  ]
}
*/
