#!/usr/bin/env python3
"""configure.py - generate the matching build from config/units.toml.

Emits, from the one manifest:
  * build.ninja                  - native ninja graph: each unit's src/<tier>/<stem>.cpp
                                   -> build/objdiff/base/<unit>.obj via `wine cl`
                                   (scripts/homm2/build/cc_wrap.py).
  * build/objdiff/objdiff.json   - pairs each base obj against its delinked target
                                   obj (build/delink/<unit>.c.obj) BY SYMBOL NAME.

The delinked targets are produced once by `homm2 init` (synth_pdb -> vostok-delinker).
Run inside `nix develop .#build`:  python3 configure.py && ninja
"""
import json, sys, tomllib
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent / "scripts"))
from homm2.build import ninja_syntax

REPO = Path(__file__).resolve().parent
PY = "python3"


def main():
    m = tomllib.loads((REPO / "config/units.toml").read_text())
    build, flags, units = m.get("build", {}), m.get("flags", {}), m.get("unit", [])

    with open(REPO / "build.ninja", "w") as f:
        w = ninja_syntax.Writer(f)
        w.comment("generated by configure.py from config/units.toml - do not edit")
        w.variable("builddir", "build")
        w.rule("cl",
               command=f"{PY} -m homm2.build.cc_wrap --out $out --src $in -- $flags",
               description="cl $unit")
        objs = []
        for u in units:
            obj = f"build/objdiff/base/{u['unit']}.obj"
            w.build(obj, "cl", inputs=u["source"],
                    variables={"flags": " ".join(flags.get(u.get("flags", "base"), [])),
                               "unit": u["unit"]})
            objs.append(obj)
        w.build("all", "phony", inputs=objs)
        w.default("all")

    od = REPO / "build/objdiff"; od.mkdir(parents=True, exist_ok=True)
    # minimal VALID empty i386 COFF (.text, no symbols) for units the delinker emits
    # no target for (data-only TUs e.g. X_GLOBAL; editor-only TUs e.g. mapcell).
    import struct
    dummy = (struct.pack("<HHIIIHH", 0x14C, 1, 0, 20 + 40, 0, 0, 0)       # header (symtab @ 60)
             + struct.pack("<8sIIIIIIHHI", b".text\0\0\0", 0, 0, 0, 0, 0, 0, 0, 0, 0x60000020)
             + struct.pack("<I", 4))                                       # empty string table
    (od / "dummy.obj").write_bytes(dummy)
    delink = REPO / "build/delink"
    units_j = []
    for u in units:
        tgt = delink / f"{u['unit']}.c.obj"
        units_j.append({
            "name": u["unit"],
            "base_path": f"./base/{u['unit']}.obj",
            "target_path": f"../delink/{u['unit']}.c.obj" if tgt.exists() else "./dummy.obj",
            "scratch": {"platform": build.get("platform", "win32"),
                        "compiler": build.get("compiler", "msvc4.2")},
        })
    (od / "objdiff.json").write_text(json.dumps({
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "build_base": False, "build_target": False,
        "watch_patterns": ["*.obj"], "units": units_j,
    }, indent=2) + "\n")
    print(f"configure: {len(units)} units -> build.ninja + build/objdiff/objdiff.json")


if __name__ == "__main__":
    main()
