#!/usr/bin/env python3
"""configure.py - generate the matching build from config/units.toml.

Emits, from the one manifest:
  * build.ninja                  - native ninja graph: each unit's src/<tier>/<stem>.cpp
                                   -> build/objdiff/base/<unit>.obj via `wine cl`
                                   (scripts/homm2/build/cc_wrap.py).
  * build/objdiff/objdiff.json   - pairs each base obj against its delinked target
                                   obj (build/delink/<unit>.c.obj) BY SYMBOL NAME.

The delinked targets are produced once by `homm2 init` (synth_pdb -> vostok-delinker).
Run inside `nix develop .#build`:  python3 configure.py && ninja
"""
import csv, json, sys, tomllib
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent / "scripts"))
from homm2.build import ninja_syntax

REPO = Path(__file__).resolve().parent
PY = "python3"


def main():
    m = tomllib.loads((REPO / "config/units.toml").read_text())
    build, flags, units = m.get("build", {}), m.get("flags", {}), m.get("unit", [])

    with open(REPO / "build.ninja", "w") as f:
        w = ninja_syntax.Writer(f)
        w.comment("generated by configure.py from config/units.toml - do not edit")
        w.variable("builddir", "build")
        # depfile/deps=gcc: cc_wrap writes $out.d (repo headers this obj includes) so ninja
        # recompiles on header edits — MSVC 4.2 has no /showIncludes, so cc_wrap scans them.
        w.rule("cl",
               command=f"{PY} -m homm2.build.cc_wrap --out $out --src $in -- $flags",
               depfile="$out.d", deps="gcc",
               description="cl $unit")
        w.rule("link_exe",
               command=(f"{PY} -m homm2.build.link_exe --out $exe "
                        "--order build/link/objects.rsp "
                        "--resource build/link/HEROES2W.res "
                        "--imports build/link/vendor-imports-smack.lib "
                        "--imports build/link/vendor-imports-mss.lib "
                        "--imports build/link/vendor-imports-wing.lib "
                        "--imports build/link/system-imports-advapi.lib"),
               description="link HEROES2W.EXE")
        w.rule("link_order",
               command=f"{PY} -m homm2.build.link_exe --write-order $out",
               description="link-order objects.rsp")
        w.rule("link_imports",
               command=f"{PY} -m homm2.build.gen_vendor_imports --out-dir build/link",
               description="link-imports middleware libraries")
        w.rule("link_resources",
               command=(f"{PY} -m homm2.build.extract_resources "
                        "--exe build/orig/HEROES2W.EXE --out build/link/HEROES2W.res "
                        "--report build/link/HEROES2W.resources.json"),
               description="link-resources HEROES2W.res")
        objs = []
        for u in units:
            obj = f"build/objdiff/base/{u['unit']}.obj"
            w.build(obj, "cl", inputs=u["source"],
                    variables={"flags": " ".join(flags.get(u.get("flags", "base"), [])),
                               "unit": u["unit"]})
            objs.append(obj)
        w.build("all", "phony", inputs=objs)
        order_inputs = ["config/units.toml", "build/gen/symbol_names.csv",
                        "build/orig/HEROES2W.EXE", "scripts/homm2/build/link_exe.py"]
        w.build("build/link/objects.rsp", "link_order", inputs=order_inputs)
        import_outputs = ["build/link/vendor-imports-mss.lib",
                          "build/link/vendor-imports-smack.lib",
                          "build/link/vendor-imports-wing.lib",
                          "build/link/system-imports-advapi.lib"]
        w.build(import_outputs, "link_imports",
                inputs="scripts/homm2/build/gen_vendor_imports.py")
        resource_output = "build/link/HEROES2W.res"
        w.build([resource_output, "build/link/HEROES2W.resources.json"], "link_resources",
                inputs=["build/orig/HEROES2W.EXE",
                        "scripts/homm2/build/extract_resources.py"])
        link_outputs = ["build/link/HEROES2W.EXE", "build/link/HEROES2W.map",
                        "build/link/HEROES2W.link.json",
                        "build/link/HEROES2W.missing-data.tsv"]
        w.build(link_outputs, "link_exe",
                inputs=["build/link/objects.rsp"] + import_outputs + [resource_output],
                implicit=objs + ["build/orig/HEROES2W.EXE",
                                 "config/required_initialized_storage.tsv",
                                 "scripts/homm2/build/build_libcmt_gfy.py",
                                 "scripts/homm2/build/link_exe.py"],
                variables={"exe": "build/link/HEROES2W.EXE"})
        w.build("link", "phony", inputs="build/link/HEROES2W.EXE")
        w.build("link-order", "phony", inputs="build/link/objects.rsp")
        w.build("link-imports", "phony", inputs=import_outputs)
        w.build("link-resources", "phony", inputs=resource_output)
        w.build("link-map", "phony",
                inputs=["build/link/HEROES2W.map", "build/link/HEROES2W.link.json"])
        w.default("all")

    od = REPO / "build/objdiff"; od.mkdir(parents=True, exist_ok=True)
    # minimal VALID empty i386 COFF (.text, no symbols) for units the delinker emits
    # no target for (data-only TUs e.g. X_GLOBAL; editor-only TUs e.g. mapcell).
    import struct
    dummy = (struct.pack("<HHIIIHH", 0x14C, 1, 0, 20 + 40, 0, 0, 0)       # header (symtab @ 60)
             + struct.pack("<8sIIIIIIHHI", b".text\0\0\0", 0, 0, 0, 0, 0, 0, 0, 0, 0x60000020)
             + struct.pack("<I", 4))                                       # empty string table
    (od / "dummy.obj").write_bytes(dummy)
    delink = REPO / "build/delink"
    reviewed_units = set()
    reviewed = REPO / "config/required_initialized_storage.tsv"
    if reviewed.exists():
        with reviewed.open() as stream:
            for row in csv.DictReader(
                    (line for line in stream if not line.lstrip().startswith("#")),
                    delimiter="\t"):
                reviewed_units.add(row["unit"])
    units_j = []
    for u in units:
        tgt = delink / f"{u['unit']}.c.obj"
        units_j.append({
            "name": u["unit"],
            "base_path": f"./base/{u['unit']}.obj",
            "target_path": (f"../delink/{u['unit']}.c.obj"
                            if tgt.exists() or u["unit"] in reviewed_units else "./dummy.obj"),
            "scratch": {"platform": build.get("platform", "win32"),
                        "compiler": build.get("compiler", "msvc4.2")},
        })
    (od / "objdiff.json").write_text(json.dumps({
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "build_base": False, "build_target": False,
        "options": {"functionRelocDiffs": "data_value"},
        "watch_patterns": ["*.obj"], "units": units_j,
    }, indent=2) + "\n")
    print(f"configure: {len(units)} units -> build.ninja + build/objdiff/objdiff.json")


if __name__ == "__main__":
    main()
