/*
FlipIconToBitmapYModify, retail RVA 0x000d9ce0, size 0x58d.

This file records the bounded structure-first campaign run on 2026-07-27.
It is evidence and example source, not a compiled translation unit.

Initial audit
-------------

The starting source had the correct 59/59-block flow graph, but only 48 exact
blocks and 11 size-only blocks.  Its clean score was 89.155495%, size 1410,
with 142 candidate versus 144 retail relocations.  A complete 50-state target
insertion census reached only 89.206436%.  The corresponding top-of-TU census
reproduced the retained 92.506700% island at trial 2: size 1423, 144/144
relocations, 52 exact blocks plus seven size-only blocks.

Completed Cartesian matrices
----------------------------

1. Row-visibility boundary, three structures x (clean + 50 top states):
   153/153 compiled.

     inline IconRowVisible helper             92.506700%
     three direct predicates, current order   92.238610%
     direct predicates, mirrored lower bound  92.238610%

   Both direct spellings retained 52 exact plus seven size-only blocks.  This
   explicitly tests deinlining; it opens a distinct but lower island.

2. Setup shear lifetime x decoder read advancement:
   3 x 2 x 51 = 306/306 compiled.

     direct shear subscript
     promoted block-scope shear value
     promoted function-scope shear value

   crossed with:

     postincrement reads
     split read then pointer advance

   All six authored structures were byte-identical in every corresponding
   state.  Each reproduced 92.506700% at the same top states.

3. Literal-copy structures.

   The current structured spelling reached 92.506700%.  A no-goto expression
   quadrant with a for loop formed a lower 90.978550% island, size 1396,
   144/144 relocation count, with 46 exact plus 13 size-only blocks.

   The first historical-goto transcription was invalid diagnostic coverage:
   its goto crossed the initialization of rightDst and all 51 compiles failed
   with C2362.  It was corrected by preserving the right-quadrant block scope,
   then rerun as a complete clean-plus-50 matrix.  The corrected structure
   improved clean source to 89.544235%, and top states 10, 12, 19, 24, 31,
   and 47 reached a new 93.592490% island: size 1420, exact 144/144 relocation
   count, and 52 exact plus seven size-only blocks.

4. Fill control/inline boundary, three structures x 51 states:
   153/153 compiled.

     natural fallthrough fill body       92.506700%
     explicit shared do_fill goto        92.506700%
     separately authored inline helper   92.252014%

   The explicit goto and fallthrough are byte-neutral per state.  The helper
   is a real but lower island.

Retained structural change
--------------------------

The corrected shared literal join below is the only source change retained.
It is the historically recovered mid-90s decoder structure, preserves
semantics, improves the clean object, restores the full relocation count in
the best island, and advances MAX from the old source hash's 92.5067% to
93.5925% for the new effective-source hash.
*/

#if 0
if (gFYRun != 0) {
    if (IconRowVisible(shear, clipY)) {
        i32 left = (gFYX - gFYRun) + 1;
        i32 pendingSkip;
        if (left <= gFYClipR && clipX <= gFYX) {
            if (gFYX <= gFYClipR) {
                gFYDst = gFYRow + gFYX;
                if (clipX <= left) {
                    gFYSkip = 0;
                    gFYDimLen = gFYRun;
                    goto copy_literal;
                }
                gFYDimLen = (gFYX - clipX) + 1;
                pendingSkip = gFYRun - gFYDimLen;
                goto publish_literal_skip;
            } else {
                gFYSrc = gFYSrc + (gFYX - gFYClipR);
                u8* rightDst = gFYRow + gFYClipR;
                if (clipX <= (gFYX - gFYRun)) {
                    gFYDst = rightDst;
                    gFYSkip = 0;
                    gFYDimLen = (gFYRun - gFYX) + gFYClipR;
                    goto copy_literal;
                }
                gFYDst = rightDst;
                pendingSkip = ((gFYRun - gFYX) - clipWidth) + gFYClipR;
                gFYDimLen = clipWidth;
                goto publish_literal_skip;
            }
        publish_literal_skip:
            gFYSkip = pendingSkip;
        copy_literal:
            gFYDimIdx = 0;
            if (0 < gFYDimLen) {
                do {
                    *gFYDst = *gFYSrc;
                    gFYSrc = gFYSrc + 1;
                    gFYDst = gFYDst - 1;
                    gFYDimIdx = gFYDimIdx + 1;
                } while (gFYDimIdx < gFYDimLen);
            }
            gFYSrc = gFYSrc + gFYSkip;
            goto literal_advance_done;
        }
    }
    gFYSrc = gFYSrc + gFYRun;
literal_advance_done:
    gFYX = gFYX - gFYRun;
    continue;
}
#endif

/*
Official replay
---------------

The source-hash epoch was generated by `homm2 status update`, then trial 10
was replayed with `tu_state_noise.py --trials 50 --only-trial 10
--insertion top --families forest --record-max --retain-best`.  The tool
restored the authored source and raised the generated baseline row to
93.5925% for hash 61356725352b.aa0f82f3995a.  No probe declaration or
generated source was retained.

The remaining clue is narrow but not exact: the best object is one byte short,
has the correct relocation count but not complete ordered-relocation identity,
and still has seven size-only blocks.  Continue from the setup shear/clip-width
register ownership and those seven blocks; do not repeat the complete matrices
above.
*/
