"""homm2 match queue generator -> config/match-queue.md.

Reads the CodeView-derived build/gen/symbol_names.csv (authoritative names / sizes /
tiers — no Ghidra), drops functions already reconstructed in src/, and writes a
size-ordered worklist for the orchestrator. Run in a build shell:

    python3 -m homm2.match.gen_queue
"""
import csv, os, re, subprocess, sys
from pathlib import Path

REPO = Path(os.environ.get("HOMM2_DIR", Path(__file__).resolve().parents[3]))
CSV = REPO / "build/gen/symbol_names.csv"
OUT = REPO / "config/match-queue.md"
TIERS = ("BASE", "SOURCE", "EDITOR")


def reconstructed_rvas():
    """RVAs with a REAL body in src/ — not the carcass placeholders, which are an
    `VA(...)` line followed only by a `// signature;` comment. A function counts as
    reconstructed only if its block (RVA up to the next RVA / EOF) has a real `{`."""
    s = set()
    pat = re.compile(r"VA\((0x[0-9a-fA-F]{1,8})")
    for p in (REPO / "src").rglob("*.cpp"):
        lines = p.read_text(errors="replace").splitlines()
        marks = [(i, int(m.group(1), 16)) for i, l in enumerate(lines)
                 if (m := pat.search(l))]
        for k, (i, rva) in enumerate(marks):
            end = marks[k + 1][0] if k + 1 < len(marks) else len(lines)
            if any("{" in l and not l.lstrip().startswith("//") for l in lines[i + 1:end]):
                s.add(rva)
    return s


def demangle(names):
    """best-effort MSVC undecorate via llvm-undname; fall back to the mangled name."""
    try:
        out = subprocess.run(["llvm-undname"], input="\n".join(names),
                             capture_output=True, text=True)
        if out.returncode == 0:
            lines = out.stdout.splitlines()
            if len(lines) == len(names):
                return [l.strip() for l in lines]
    except FileNotFoundError:
        pass
    return names


def main():
    if not CSV.exists():
        sys.exit(f"missing {CSV} — run `homm2 init` first")
    done = reconstructed_rvas()
    funcs = []
    for r in csv.DictReader(open(CSV)):
        if r["kind"] != "func":
            continue
        unit = r["unit"]
        if unit.split("/")[0] not in TIERS:
            continue
        rva = int(r["rva"], 16); size = int(r["size"], 16)
        if rva in done or size == 0:
            continue
        funcs.append((rva, r["name"], unit, size))
    dem = demangle([f[1] for f in funcs])
    rows = [(rva, name, dem[i], unit, size) for i, (rva, name, unit, size) in enumerate(funcs)]
    band = sorted((x for x in rows if 64 <= x[4] <= 512), key=lambda x: x[4])
    rest = sorted((x for x in rows if not (64 <= x[4] <= 512)), key=lambda x: x[4])

    def tbl(rs):
        out = ["| rva | name | unit | size | status |", "|---|---|---|---|---|"]
        for rva, _mang, name, unit, size in rs:
            out.append(f"| 0x{rva:08x} | {name} | {unit} | {size} | ready |")
        return out

    lines = [
        "# Match queue (auto-generated by scripts/homm2/match/gen_queue.py — re-run to refill)", "",
        f"Totals: {len(rows)} unmatched reconstruction-tier functions · "
        f"{len(done)} RVAs already reconstructed in src/.", "",
        "Order: middle-small (64–512 B) first, then by size. Match top-down. "
        "Names / sizes / tiers are CodeView ground truth — no guessing.", "",
        f"## READY — middle-small (64–512 B): {len(band)}", "", *tbl(band), "",
        f"## READY — other sizes: {len(rest)}", "", *tbl(rest), "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)}: {len(band)} mid-small + {len(rest)} other "
          f"= {len(rows)} candidates ({len(done)} already reconstructed)")


if __name__ == "__main__":
    main()
