"""homm2 match queue generator -> config/match-queue.md.

Reads the CodeView-derived build/gen/symbol_names.csv (authoritative names / sizes /
tiers — no Ghidra), drops functions already reconstructed in src/, and writes a
size-ordered worklist for the orchestrator. Run in a build shell:

    python3 -m homm2.match.gen_queue
"""
import csv, os, re, subprocess, sys
from collections import defaultdict
from pathlib import Path

REPO = Path(os.environ.get("HOMM2_DIR", Path(__file__).resolve().parents[3]))
CSV = REPO / "build/gen/symbol_names.csv"
UNITS = REPO / "config/units.toml"
OUT = REPO / "config/match-queue.md"
TIERS = ("BASE", "SOURCE", "EDITOR")
IMAGE_BASE = 0x400000  # src VA() macros carry absolute VAs; the CSV is RVA-relative


def reconstructed_rvas():
    """RVAs with a REAL body in src/ — not the carcass placeholders, which are an
    `VA(...)` line followed only by a `// signature;` comment. A function counts as
    reconstructed only if its block (RVA up to the next RVA / EOF) has a real `{`.

    src `VA()` macros carry ABSOLUTE VAs (RVA + IMAGE_BASE); the CSV this set is
    matched against is RVA-relative, so normalise back to RVA-space here."""
    s = set()
    pat = re.compile(r"VA\((0x[0-9a-fA-F]{1,8})")
    for p in (REPO / "src").rglob("*.cpp"):
        lines = p.read_text(errors="replace").splitlines()
        marks = [(i, int(m.group(1), 16)) for i, l in enumerate(lines)
                 if (m := pat.search(l))]
        for k, (i, va) in enumerate(marks):
            end = marks[k + 1][0] if k + 1 < len(marks) else len(lines)
            if any("{" in l and not l.lstrip().startswith("//") for l in lines[i + 1:end]):
                s.add(va - IMAGE_BASE if va >= IMAGE_BASE else va)
    return s


def unit_flags():
    """unit -> 'base' (/Od, simple/literal) | 'o2' (/O2, hard/FPO), from units.toml."""
    flags, cur = {}, None
    for line in UNITS.read_text().splitlines():
        if (m := re.match(r'\s*unit\s*=\s*"([^"]+)"', line)):
            cur = m.group(1)
        elif (m := re.match(r'\s*flags\s*=\s*"([^"]+)"', line)) and cur:
            flags[cur] = m.group(1); cur = None
    return flags


def demangle(names):
    """best-effort MSVC undecorate via llvm-undname; fall back to the mangled name."""
    try:
        out = subprocess.run(["llvm-undname"], input="\n".join(names),
                             capture_output=True, text=True)
        if out.returncode == 0:
            lines = out.stdout.splitlines()
            if len(lines) == len(names):
                return [l.strip() for l in lines]
    except FileNotFoundError:
        pass
    return names


def main():
    if not CSV.exists():
        sys.exit(f"missing {CSV} — run `homm2 init` first")
    done = reconstructed_rvas()
    flags = unit_flags()
    funcs = []
    for r in csv.DictReader(open(CSV)):
        if r["kind"] != "func":
            continue
        unit = r["unit"]
        if unit.split("/")[0] not in TIERS:
            continue
        rva = int(r["rva"], 16); size = int(r["size"], 16)
        if rva in done or size == 0:
            continue
        funcs.append((rva, r["name"], unit, size))
    dem = demangle([f[1] for f in funcs])
    rows = [(rva, name, dem[i], unit, size) for i, (rva, name, unit, size) in enumerate(funcs)]

    # WHOLE-TU, simple-first. Group by TU; order /Od ("base") TUs before /O2 ("o2"),
    # then by remaining bytes ascending (small/simple TUs first). Within a TU, keep
    # retail-RVA (define) order so a lane fills its placeholders top-down.
    by_unit = defaultdict(list)
    for row in rows:
        by_unit[row[3]].append(row)
    units = sorted(by_unit, key=lambda u: (flags.get(u, "base") == "o2",
                                           sum(x[4] for x in by_unit[u]), u))
    base_units = [u for u in units if flags.get(u, "base") != "o2"]
    o2_units   = [u for u in units if flags.get(u, "base") == "o2"]

    def tu(u):
        fns = sorted(by_unit[u], key=lambda x: x[0])  # retail-RVA order
        out = [f"### {u} — {len(fns)} funcs · {sum(x[4] for x in fns)} B  [{flags.get(u, 'base')}]",
               "", "| rva | name | size |", "|---|---|---|"]
        out += [f"| 0x{rva:08x} | {name} | {size} |" for rva, _m, name, _u, size in fns]
        return out + [""]

    lines = [
        "# Match queue (auto-generated by scripts/homm2/match/gen_queue.py — re-run to refill)", "",
        f"Totals: {len(rows)} unmatched reconstruction-tier functions in {len(by_unit)} TUs · "
        f"{len(done)} RVAs already reconstructed in src/.", "",
        "**Strategy: WHOLE-TU, simple-first.** Dispatch a whole TU — or a 20+ function "
        "chunk of one — per matcher lane, and finish that TU before moving to the next. "
        "TUs are ordered simple→hard: /Od (\"base\", literal lowering) TUs first, then "
        "/O2 (\"o2\", FPO + regalloc) TUs; within a tier by remaining bytes ascending. "
        "Within a TU, functions are in retail-RVA (define) order. Names / sizes / tiers "
        "are CodeView ground truth — no guessing.", "",
        f"## /Od (simple, literal lowering) — {len(base_units)} TUs — match these FIRST", "",
    ]
    for u in base_units:
        lines += tu(u)
    lines += [f"## /O2 (hard, FPO + regalloc) — {len(o2_units)} TUs — match these LAST", ""]
    for u in o2_units:
        lines += tu(u)

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)}: {len(rows)} funcs across {len(by_unit)} TUs "
          f"({len(base_units)} /Od + {len(o2_units)} /O2; {len(done)} already reconstructed)")


if __name__ == "__main__":
    main()
