"""homm2 status - run objdiff over the base<->target objs and report match %.

  homm2 status                 print per-unit + overall match %
  homm2 status --write-readme  refresh the <!-- match-score --> block in README.md
"""
import json, os, subprocess, sys
from pathlib import Path
REPO = Path(os.environ.get("HOMM2_DIR", Path(__file__).resolve().parents[3]))
RM_START, RM_END = "<!-- match-score:start -->", "<!-- match-score:end -->"


def _i(v): return int(v) if v not in (None, "") else 0


def load_report():
    od = REPO / "build/objdiff"; rep = od / "report.json"
    subprocess.run(["objdiff-cli", "report", "generate", "-p", str(od), "-o", str(rep)],
                   cwd=REPO, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return json.loads(rep.read_text()) if rep.exists() else None


def unit_pct(u):
    return float((u.get("measures", {}) or {}).get("matched_code_percent", 0) or 0)


def readme_block(data):
    """gruntz-style per-tier match table (Module = BASE/SOURCE/EDITOR tier)."""
    tiers = {}
    for u in data.get("units", []):
        tier = u.get("name", "?").split("/")[0]
        m = u.get("measures", {}) or {}
        t = tiers.setdefault(tier, {"units": 0, "fe": 0, "ft": 0, "mc": 0, "tc": 0})
        t["units"] += 1
        t["fe"] += _i(m.get("matched_functions")); t["ft"] += _i(m.get("total_functions"))
        t["mc"] += _i(m.get("matched_code"));      t["tc"] += _i(m.get("total_code"))
    rows = []
    TE = TT = MC = TC = 0
    for tier in sorted(tiers, key=lambda k: -tiers[k]["ft"]):
        d = tiers[tier]
        if d["ft"] == 0:  # data-only tier, no functions to match
            continue
        TE += d["fe"]; TT += d["ft"]; MC += d["mc"]; TC += d["tc"]
        fp = 100 * d["fe"] / d["ft"]; cp = 100 * d["mc"] / d["tc"] if d["tc"] else 0
        rows.append(f"| `{tier}` | {d['units']} | {d['fe']} / {d['ft']} ({fp:.1f}%) | {cp:.1f}% |")
    overall_f = 100 * TE / TT if TT else 0
    overall_c = 100 * MC / TC if TC else 0
    out = [RM_START, "## Match status", "",
           "_Auto-generated by `homm2 status --write-readme` (refreshed by `homm2 build`); do not hand-edit._", "",
           f"**Overall: {TE} / {TT} functions exact ({overall_f:.2f}%) &middot; {overall_c:.2f}% of code bytes.**", "",
           "| Module | Units | Functions exact | Code |",
           "| :----- | ----: | --------------: | ---: |",
           *rows, "", RM_END]
    return "\n".join(out)


def main(argv=None):
    argv = list(argv or [])
    data = load_report()
    if data is None:
        print("[status] no report (run 'homm2 build' first)"); return 1
    if "--write-readme" in argv:
        block = readme_block(data); rm = REPO / "README.md"
        text = rm.read_text() if rm.exists() else "# homm2-decomp\n\n" + RM_START + "\n" + RM_END + "\n"
        if RM_START in text and RM_END in text:
            pre = text[:text.index(RM_START)]; post = text[text.index(RM_END) + len(RM_END):]
            rm.write_text(pre + block + post)
        else:
            rm.write_text(text.rstrip() + "\n\n" + block + "\n")
        print("[status] refreshed README.md match block")
        return 0
    started = sorted((u for u in data["units"] if unit_pct(u) > 0 and
                      _i((u.get("measures", {}) or {}).get("total_functions"))), key=unit_pct, reverse=True)
    for u in started[:25]:
        print(f"  {unit_pct(u):6.2f}%  {u.get('name')}")
    overall = float((data.get("measures", {}) or {}).get("matched_code_percent", 0) or 0)
    print(f"[status] units: {len(data['units'])}  with-progress: {len(started)}  overall: {overall:.2f}%")
    return 0
