"""homm2 status - run objdiff over the base<->target objs and report match %.

  homm2 status                 print per-unit + overall match %
  homm2 status --write-readme  refresh the <!-- match-score --> block in README.md
"""
import json, os, subprocess, sys
from pathlib import Path
REPO = Path(os.environ.get("HOMM2_DIR", Path(__file__).resolve().parents[3]))
RM_START, RM_END = "<!-- match-score:start -->", "<!-- match-score:end -->"


def _i(v): return int(v) if v not in (None, "") else 0


def load_report():
    od = REPO / "build/objdiff"; rep = od / "report.json"
    subprocess.run(["objdiff-cli", "report", "generate", "-p", str(od), "-o", str(rep)],
                   cwd=REPO, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return json.loads(rep.read_text()) if rep.exists() else None


def unit_pct(u):
    return float((u.get("measures", {}) or {}).get("matched_code_percent", 0) or 0)


def _md_table(headers, aligns, rows):
    """GitHub markdown table with pipes padded to column widths so the raw source
    reads cleanly in an editor. `aligns`: one char/col, 'l' left or 'r' right."""
    widths = [len(h) for h in headers]
    for r in rows:
        for i, c in enumerate(r):
            widths[i] = max(widths[i], len(c))

    def cell(text, i):
        return text.rjust(widths[i]) if aligns[i] == "r" else text.ljust(widths[i])

    def row(cells):
        return "| " + " | ".join(cell(c, i) for i, c in enumerate(cells)) + " |"

    sep = ["-" * (w - 1) + ":" if a == "r" else ":" + "-" * (w - 1)
           for w, a in zip(widths, aligns)]
    return [row(headers), "| " + " | ".join(sep) + " |", *(row(r) for r in rows)]


def readme_block(data):
    """per-tier match table (Module = BASE/SOURCE/EDITOR tier)."""
    tiers = {}
    for u in data.get("units", []):
        tier = u.get("name", "?").split("/")[0]
        m = u.get("measures", {}) or {}
        t = tiers.setdefault(tier, {"units": 0, "fe": 0, "ft": 0, "mc": 0, "tc": 0,
                                    "fz": 0.0, "fzt": 0})
        t["units"] += 1
        t["fe"] += _i(m.get("matched_functions")); t["ft"] += _i(m.get("total_functions"))
        t["mc"] += _i(m.get("matched_code"));      t["tc"] += _i(m.get("total_code"))
        # fuzzy (size-weighted instruction match) from per-function data, so partial
        # functions show progress instead of counting as 0 like the exact "Code" column.
        for f in u.get("functions", []) or []:
            sz = _i(f.get("size")); fz = f.get("fuzzy_match_percent") or 0.0
            t["fz"] += sz * fz / 100.0; t["fzt"] += sz
    rows = []
    TE = TT = 0; FZ = 0.0; FZT = 0
    for tier in sorted(tiers, key=lambda k: -tiers[k]["ft"]):
        d = tiers[tier]
        if d["ft"] == 0:  # data-only tier, no functions to match
            continue
        TE += d["fe"]; TT += d["ft"]; FZ += d["fz"]; FZT += d["fzt"]
        fp = 100 * d["fe"] / d["ft"]
        zp = 100 * d["fz"] / d["fzt"] if d["fzt"] else 0
        rows.append([f"`{tier}`", str(d["units"]),
                     f"{d['fe']} / {d['ft']} ({fp:.1f}%)", f"{zp:.1f}%"])
    overall_f = 100 * TE / TT if TT else 0
    overall_z = 100 * FZ / FZT if FZT else 0
    out = [RM_START, "## Match status", "",
           "_Auto-generated by `homm2 status --write-readme` (refreshed by `homm2 build`); do not hand-edit._", "",
           f"**Overall: {TE} / {TT} functions exact ({overall_f:.2f}%) &middot; {overall_z:.2f}% fuzzy.**", "",
           "_**Functions exact** = byte-identical. **Fuzzy** = size-weighted instruction match "
           "(the progress signal; hard functions sit < 100% exact until late)._", "",
           *_md_table(["Module", "Units", "Functions exact", "Fuzzy"], "lrrr", rows),
           "", RM_END]
    return "\n".join(out)


BASELINE = REPO / "config/match_baseline.tsv"


def _fn_fuzzy(data):
    """{(unit, function): fuzzy_match_percent} from the objdiff report."""
    out = {}
    for u in data.get("units", []):
        un = u.get("name", "?")
        for f in u.get("functions", []) or []:
            out[(un, f.get("name", "?"))] = float(f.get("fuzzy_match_percent") or 0.0)
    return out


def load_baseline():
    base = {}
    if BASELINE.exists():
        for line in BASELINE.read_text().splitlines():
            if not line or line.startswith("#"):
                continue
            p = line.split("\t")
            if len(p) >= 3:
                base[(p[0], p[1])] = float(p[2])
    return base


def write_baseline(best):
    lines = ["# homm2 match baseline - best fuzzy% per function.",
             "# Generated by `homm2 status update`; do not hand-edit.  unit<TAB>function<TAB>best_fuzzy"]
    for (un, fn), b in sorted(best.items()):
        lines.append(f"{un}\t{fn}\t{b:.4f}")
    BASELINE.write_text("\n".join(lines) + "\n")


def cmd_update(data, accept_regressions):
    cur = _fn_fuzzy(data); base = load_baseline()
    best = {k: (v if accept_regressions else max(base.get(k, 0.0), v)) for k, v in cur.items()}
    write_baseline(best)
    print(f"[status] baseline updated: {len(best)} functions -> {BASELINE.relative_to(REPO)}")
    return 0


def cmd_check(data, eps=0.05):
    cur = _fn_fuzzy(data); base = load_baseline()
    if not base:
        print("[status] no baseline yet - seed it: homm2 status update"); return 0
    regr = [(k, base[k], cur.get(k, 0.0)) for k in base if cur.get(k, 0.0) + eps < base[k]]
    if regr:
        print(f"[status] {len(regr)} REGRESSION(S) vs baseline:")
        for (un, fn), b, c in sorted(regr)[:30]:
            print(f"   {c:6.2f}% < {b:6.2f}%  {un}::{fn}")
        print("  bless if intended (rename/trivial drift): homm2 status update --accept-regressions")
        return 1
    print("[status] no regressions vs baseline."); return 0


def main(argv=None):
    argv = list(argv or [])
    data = load_report()
    if data is None:
        print("[status] no report (run 'homm2 build' first)"); return 1
    if argv and argv[0] == "update":
        return cmd_update(data, "--accept-regressions" in argv)
    if argv and argv[0] == "check":
        return cmd_check(data)
    if "--write-readme" in argv:
        block = readme_block(data); rm = REPO / "README.md"
        text = rm.read_text() if rm.exists() else "# homm2-decomp\n\n" + RM_START + "\n" + RM_END + "\n"
        if RM_START in text and RM_END in text:
            pre = text[:text.index(RM_START)]; post = text[text.index(RM_END) + len(RM_END):]
            rm.write_text(pre + block + post)
        else:
            rm.write_text(text.rstrip() + "\n\n" + block + "\n")
        print("[status] refreshed README.md match block")
        return 0
    started = sorted((u for u in data["units"] if unit_pct(u) > 0 and
                      _i((u.get("measures", {}) or {}).get("total_functions"))), key=unit_pct, reverse=True)
    for u in started[:25]:
        print(f"  {unit_pct(u):6.2f}%  {u.get('name')}")
    overall = float((data.get("measures", {}) or {}).get("matched_code_percent", 0) or 0)
    print(f"[status] units: {len(data['units'])}  with-progress: {len(started)}  overall: {overall:.2f}%")
    return 0
