"""Regenerate config/delink_relocs.tsv from the image with the delinker's sweep.

The stripped target has no base-relocation directory, so the manifest is the
only DIR32 channel. `find_relocs.py` in the vostok-delinker tree recovers those
sites from the image alone -- operands the disassembler printed, switch-table
entries, and aligned data pointers outside the literal pool -- so this is the
primary channel and `homm2.audit.reloc_donation` is now a cross-check.

The sweep is site-anchored and needs no symbol input, which is what the donation
channel could never be: donation only fires on a function whose bytes already
match, so a site arrived after exactness rather than enabling it, and the data
sections could not start at all. Measured against PoL 2.0's surviving `.reloc`
(the same program, MSVC-built, 28,801 real sites) the sweep runs at 0.9988
precision and 0.9942 recall; see docs/reloc-manifest-sweep.md.

    homm2 audit reloc-sweep              # report the yield, write nothing
    homm2 audit reloc-sweep --write      # replace config/delink_relocs.tsv

`find_relocs.py` lives in the delinker repository, not this one. Point
`VOSTOK_DELINKER` at that checkout, or pass `--find-relocs PATH`; a checkout
beside this one is found automatically.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

from homm2.core.paths import REPO

EXE = REPO / "build/orig/HMM2PL.exe"
MANIFEST = REPO / "config/delink_relocs.tsv"
SCRIPT = "scripts/find_relocs.py"

BANNER = """\
# Reviewed absolute-relocation sites for the stripped Gold 2.1 target.
# HMM2PL.exe carries no base-relocation directory (data directory 5 is 0/0), so
# the delinker cannot read DIR32 sites from the image. Every row here names the
# RVA of a 4-byte field that holds a linked target address; the delinker reads
# and classifies the target itself.
#
# Generated by `homm2 audit reloc-sweep --write` (vostok-delinker
# scripts/find_relocs.py). Do not hand-edit: regenerate instead. The rule set is
# scored against PoL 2.0's surviving .reloc directory; see
# docs/reloc-manifest-sweep.md for the measured precision per target class.
"""


def find_script(explicit: str | None) -> Path:
    """Locate find_relocs.py in the delinker source tree.

    Raises LookupError rather than exiting, so `homm2 audit` reports it as a
    failed tool instead of tripping over a non-integer exit code.
    """
    if explicit:
        path = Path(explicit)
        if not path.is_file():
            raise LookupError(f"no such file: {path}")
        return path
    roots = []
    if os.environ.get("VOSTOK_DELINKER"):
        roots.append(Path(os.environ["VOSTOK_DELINKER"]))
    roots += [REPO.parent / "vostok-delinker",
              REPO.parent.parent / "surv/vostok-delinker"]
    for root in roots:
        candidate = root / SCRIPT
        if candidate.is_file():
            return candidate
    raise LookupError(
        f"cannot find vostok-delinker's {SCRIPT}.\n"
        "  The build shell exports VOSTOK_DELINKER to the pinned delinker "
        "source; set it yourself\n"
        "  to a checkout, or pass --find-relocs PATH.\n"
        "  Looked in: " + ", ".join(str(root) for root in roots))


def read_sites(text: str) -> set[int]:
    sites = set()
    for line in text.splitlines():
        if line.startswith("#") or line.startswith("site_rva") or not line.strip():
            continue
        sites.add(int(line.split("\t")[0], 16))
    return sites


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true",
                        help="replace config/delink_relocs.tsv with the sweep")
    parser.add_argument("--find-relocs", metavar="PATH",
                        help="path to vostok-delinker's scripts/find_relocs.py")
    args = parser.parse_args(argv)

    try:
        script = find_script(args.find_relocs)
    except LookupError as missing:
        print(f"[reloc-sweep] {missing}", file=sys.stderr)
        return 1
    print(f"[reloc-sweep] {script}")
    result = subprocess.run(
        [sys.executable, str(script), str(EXE), "--report"],
        capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stderr.strip(), file=sys.stderr)
        return 1
    print(result.stderr.rstrip(), file=sys.stderr)

    swept = read_sites(result.stdout)
    existing = read_sites(MANIFEST.read_text()) if MANIFEST.is_file() else set()
    # A site the manifest holds and the sweep does not is the one result worth
    # stopping for: donation earned those rows from bytes that already matched,
    # so the sweep losing one means a rule regressed, not that the row was wrong.
    lost = existing - swept
    print(f"[reloc-sweep] {len(swept)} sites "
          f"({len(swept - existing)} new, {len(lost)} lost)")
    if lost:
        print("[reloc-sweep] sites the current manifest holds and the sweep "
              "does not: " + ", ".join(f"0x{site:x}" for site in sorted(lost)[:20]),
              file=sys.stderr)
        return 1

    if not args.write:
        print("[reloc-sweep] pass --write to replace the manifest")
        return 0

    with MANIFEST.open("w") as stream:
        stream.write(BANNER)
        print("site_rva\tkind", file=stream)
        for site in sorted(swept):
            print(f"0x{site:x}\tdir32", file=stream)
    print(f"[reloc-sweep] wrote {MANIFEST.relative_to(REPO)}; "
          "run `homm2 redelink` next")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
