#!/usr/bin/env python3
"""Every build.ninja rule declaration, in the stable emission order."""

from __future__ import annotations

PY = "python3"


def emit_rules(w, *, locale='ru', builddir='build', image=None) -> None:
    """`image` (homm2.core.paths.image_paths) selects the image every tool
    reads: its generated tree and its retail tables. The game's spelling is
    the historical one."""
    from homm2.core.paths import image_paths
    image = image or image_paths("game")
    PY = image.env + "python3"
    B, R = image.build, image.retail
    w.comment("generated by configure.py from config/units.toml - do not edit")
    w.variable("builddir", builddir)
    # depfile/deps=gcc: cc_wrap writes $out.d (repo headers this obj includes) so ninja
    # recompiles on header edits — MSVC 4.2 has no /showIncludes, so cc_wrap scans them.
    locale_flag = f' --locale {locale}' if locale != 'ru' else ''
    w.rule("cl",
           command=f"{PY} -m homm2.graph.cc --out $out --src $in{locale_flag} -- $flags",
           depfile="$out.d", deps="gcc",
           description="cl $unit")
    # DATA/DATA_COMPGEN identities come from the source manifest; the
    # normalizer changes comparison-only symbol names, never linked objects.
    w.rule("canonicalize_data_symbols",
           command=(f"{PY} -m homm2.compare.canonicalize_data_symbols "
                    "--input $in --output $out --sidecar $sidecar "
                    "--unit $unit --compgen-manifest "
                    f"{B}/gen/compiler_generated_functions.csv "
                    f"--data-manifest {B}/gen/delink_data_from_source.tsv "
                    f"--data-base-root {B}/objdiff/base"),
           description="normalize-data $unit")
    w.rule("assert_weak_external_link_set",
           command=(f"{PY} -m homm2.compare.canonicalize_data_symbols "
                    "--assert-weak-link-set $in --weak-stamp $out"),
           description="prove weak-external defaults")
    w.rule("canonicalize_relocs",
           command=(f"{PY} -m homm2.compare.canonicalize_relocs "
                    "--unit $unit --base $base --target $in --output $out "
                    f"--symbols {B}/gen/symbol_names.csv "
                    f"--rel32-aliases {R}/reloc_rel32_aliases.tsv"
                    + (f" --retail-exe {image.exe}" if image.env else "")),
           description="normalize-relocs $unit")
    w.rule("legacy_implib",
           command=(f"{PY} -m homm2.graph.legacy_import_lib "
                    "--definition $in --out $out"),
           description="legacy-implib WING32.dll")
    w.rule("native_implib",
           command=(f"{PY} -m homm2.graph.import_lib "
                    "--definition $in --dll $dll --out $out"),
           description="native-implib $dll")
    w.rule("definition_implib",
           command=(f"{PY} -m homm2.graph.regular_import_lib "
                    "--definition $in --dll $dll --out $out"),
           description="definition-implib $dll")
    w.rule("definition_vendor_implib",
           command=(f"{PY} -m homm2.graph.regular_vendor_import_lib "
                    "--definition-only --dll $dll --definition $in "
                    "--out $out $options"),
           description="definition-implib $dll")
    w.rule("archive",
           command='wine "$$MSVC_DIR/bin/LIB.EXE" @$out.rsp',
           rspfile="$out.rsp",
           rspfile_content="/NOLOGO /MACHINE:IX86 /OUT:$out $in",
           description="archive $out")
    w.rule("ml_omf",
           command=(f"{PY} -m homm2.graph.ml "
                    "--src $in --out $out"),
           description="assemble-omf $in")
    w.rule("ml_coff",
           command=(f"{PY} -m homm2.graph.ml "
                    "--coff --src $in --out $out"),
           description="assemble-coff $in")
    w.rule("link_exe",
           command=f"{PY} -m homm2.graph.link $link_mode",
           description="native LINK.EXE $out")
    w.rule("link_audit",
           command=(f"{PY} -m homm2.graph.link_exe --audit-existing "
                    "--strict --out build/link/historical/HMM2PL.exe"),
           description="link-audit HMM2PL.exe")
    w.rule("link_diff",
           command=(f"{PY} -m homm2.verify.link_diff --candidate $in "
                    "--stamp $out"),
           description="link-diff ceiling $in")
    from homm2.graph.link import PROFILES
    w.rule("link_resources",
           command=(f"{PY} -m homm2.graph.rc "
                    f"--rc {PROFILES['game'].resources} --out build/link/HMM2PL.res "
                    "--verify-exe build/orig/HMM2PL.exe "
                    "--report build/link/HMM2PL.resources.json"),
           description="rc-res HMM2PL.res")
    if image.key != "game":
        stem = PROFILES[image.key].stem
        w.rule("image_link_resources",
               command=(f"{PY} -m homm2.graph.rc "
                        f"--rc {PROFILES[image.key].resources} --out {B}/link/{stem}.res "
                        f"--verify-exe {image.exe} --icon {image.key}.ico "
                        f"--report {B}/link/{stem}.resources.json"),
               description=f"rc-res {stem}.res")
