#!/usr/bin/env python3
"""clean_source.py - derive a clean C++ tree from the matching source tree.

The matching tree carries scaffolding that exists only to prove the source
reproduces retail object code: RVA annotations (`VA`, `DATA`, `VTBL`), delinker
metadata (`DATA_COMPGEN`), codegen steering hacks (`OD_STEER`, `OR_STEER`) and
the dual-build enum machinery (`H2_ENUM_*`). None of it survives into the
compiler's view of a production build, so this performs those expansions ahead
of time and emits ordinary C++.

A translation, not a fork: the same program for the same target. The one choice
made is selecting the strict typed enum branch, which is why GENERATED_PATCHES
also carries the conversions that choice requires. See docs/clean-source.md.

Usage:
    python3 scripts/clean_source.py --out build/clean
    python3 scripts/clean_source.py --out build/clean --verify
"""

from __future__ import annotations

import argparse
import enum
import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
# How many offending sites a diagnostic lists before summarising the rest. A
# failing run usually fails the same way in many files; the first few identify
# the cause and the rest is scrollback.
MAX_REPORTED = 20
GENERATED_MARKER = ".homm2-clean-source-generated"
GENERATED_MARKER_CONTENT = "Generated by scripts/clean_source.py; safe to replace.\n"
PUBLISHED_PATHS = ("build.ninja", "imports", "include", "src", "vendor")

# Sentinel marking a construct that expanded to nothing. Line cleanup uses it to
# tell "this line went blank because we deleted an annotation" (drop the line)
# from "this line was always blank" (keep it).
DROPPED = "\x01"


# --------------------------------------------------------------------------
# Transforms: everything done to the tree, in order. Whole files (DROP_FILES,
# OVERRIDE_DIR), preprocessor (STRICT_MACRO, PROVENANCE_MACROS, `#line`), macro
# invocations (CALL_RULES and WORD_RULES, defined below next to their helpers),
# injected text (CLEAN_ALLOC_MACROS, RETAIL_FILE) and finally GENERATED_PATCHES.
# See docs/clean-source.md.
# --------------------------------------------------------------------------

# Supplied verbatim rather than derived; va.h is pure annotation machinery.
OVERRIDE_DIR = REPO / "scripts/clean_overrides"
DROP_FILES = {"include/va.h"}

# The frozen 1996 source path, and the `#line` markers that pinned MSVC 4.2's
# /Gi __LINE__ variables to retail values.
PROVENANCE_MACROS = ("RETAIL_FILE",)

class Pattern(enum.Enum):
    LITERAL = enum.auto()
    REGEX = enum.auto()


# Conversions required by the strict enum branch.
#
# Patching generated text, not the matching source: a token added there can flip
# /Od codegen parity in unrelated functions, which already cost
# advManager::DoVisions its byte-exact match once.
GENERATED_PATCHES = {
    "include/SOURCE/KB.h": [
        (
            Pattern.LITERAL, 1,
            "#include <Ints.h>",
            "#include <Ints.h>\n#include <windows.h>",
        ),
        (
            Pattern.REGEX, 4,
            r"extern void\* (hmnu(?:Adv|Cmbt|Dflt|Town));",
            r"extern HMENU \1;",
        ),
    ],
    "include/SOURCE/fileRequester.h": [
        (
            Pattern.LITERAL, 1,
            "#include <Ints.h>",
            "#include <Ints.h>\n#include <windows.h>",
        ),
        (
            Pattern.LITERAL, 1,
            "void* m_previousMenu;",
            "HMENU m_previousMenu;",
        ),
    ],
    "src/SOURCE/ARMY.cpp": [
        (
            Pattern.LITERAL, 1,
            "targetSide_8 >= 0",
            "H2EnumIndex(targetSide_8) >= 0",
        ),
    ],
    "src/SOURCE/COMMAND.cpp": [
        (
            Pattern.LITERAL, 1,
            "ExperienceValueOfStack(H2EnumIndex(OppositeCombatResult(winningSide)))",
            "ExperienceValueOfStack(static_cast<CombatSide>("
            "H2EnumIndex(OppositeCombatResult(winningSide))))",
        ),
    ],
    "src/SOURCE/dpnetwin.cpp": [
        (
            Pattern.LITERAL, 1,
            "LPDPENUMDPCALLBACK, void*",
            "LPDPENUMDPCALLBACKA, void*",
        ),
    ],
    "src/SOURCE/FLY.cpp": [
        (
            Pattern.LITERAL, 2,
            "static_cast<u32>(m_facing) < ARMY_FACING_RIGHT",
            "static_cast<u32>(m_facing) < static_cast<u32>(ARMY_FACING_RIGHT)",
        ),
    ],
    "src/SOURCE/HERO.cpp": [
        (
            Pattern.LITERAL, 1,
            "(H2EnumIndex(skillIndexValue) + 1) % HERO_SKILL_COUNT",
            "(H2EnumIndex(skillIndexValue) + 1) % H2EnumIndex(HERO_SKILL_COUNT)",
        ),
    ],
    "src/SOURCE/PHILAI.cpp": [
        (
            Pattern.LITERAL, 1,
            "best.type >= 0",
            "H2EnumIndex(best.type) >= 0",
        ),
    ],
    "src/SOURCE/KB.cpp": [
        (
            Pattern.REGEX, 4,
            r"void\* (hmnu(?:Adv|Cmbt|Dflt|Town)) = NULL;",
            r"HMENU \1 = NULL;",
        ),
    ],
    "src/SOURCE/X_CAMPGN.cpp": [
        (
            Pattern.REGEX, 52,
            r"case (MAP_[A-Z0-9_]+) \+ 1:",
            r"case static_cast<ExpansionCampaignMap>(H2EnumIndex(\1) + 1):",
        ),
    ],
}

CLEAN_IDENTIFIER_REWRITES = {
    "BitTest": "H2BitTest",
    "BitSet": "H2BitSet",
    "BitClear": "H2BitClear",
}


# --------------------------------------------------------------------------
# Rules: each maps a macro invocation to its production expansion or its strict
# typed form. Keep in step with include/va.h and include/Ints.h.
# --------------------------------------------------------------------------

def _drop(args: list[str]) -> str:
    return DROPPED


def _arg(index: int, parenthesize: bool = False):
    """Expand to one argument, as `#define M(a, b) b` would.

    `parenthesize` for expansions that are self-delimiting -- `OR_STEER(x)` is
    `(x | 0)`, so a bare argument would change precedence.
    """
    def rule(args: list[str]) -> str:
        argument = args[index].strip()
        return "(%s)" % argument if parenthesize else argument
    return rule


# The clean tree is generated in the *strict* configuration: domains become real
# `enum class` types keeping their retail width through H2EnumStorage. The
# matching tree cannot build this way -- production needs each domain to *be* an
# integer so MSVC 4.2 lowers it identically.
STRICT_MACRO = "H2_STRICT_ENUMS"


# Domains that would stay plain integers. Empty on purpose: demoting a domain
# was measured at 68 of 95 translation units against 93 for GENERATED_PATCHES,
# because it takes the type away from every site rather than the few that need it.
INTEGER_DOMAINS: set[str] = set()


def _plain_enum_open(args: list[str]) -> str:
    return "typedef enum %s {" % args[0].strip()


def _plain_enum_close(args: list[str]) -> str:
    return "} %s;" % args[0].strip()


def _enum_class_open(storage_index: int | None = None):
    def rule(args: list[str]) -> str:
        if args[0].strip() in INTEGER_DOMAINS:
            return "enum {"

        storage = args[storage_index].strip() if storage_index is not None else "i32"
        return "enum class %s : %s {" % (args[0].strip(), storage)
    return rule


# Flag domains also accumulated with `+=` / `-=`. Integer domains got these
# operators for free, so only the compound arithmetic is missing.
COMPOUND_ARITHMETIC_OPERATORS = """\
inline {name}& operator+=({name}& a, {name} b) {{
    return a = static_cast<{name}>(static_cast<i32>(a) + static_cast<i32>(b));
}}
inline {name}& operator-=({name}& a, {name} b) {{
    return a = static_cast<{name}>(static_cast<i32>(a) - static_cast<i32>(b));
}}"""

# Now covered by the flag operator set above; kept empty because a domain may
# yet need compound arithmetic without being a flag domain.
COMPOUND_ARITHMETIC_DOMAINS: set[str] = set()


def _enum_class_close(args: list[str]) -> str:
    # `using enum` re-exports the enumerators into the enclosing scope, which is
    # what lets the game keep spelling them unqualified.
    name = args[0].strip()
    if name in INTEGER_DOMAINS:
        return "};\ntypedef i32 %s;" % name
    closed = "};\nusing enum %s;" % name
    if name in COMPOUND_ARITHMETIC_DOMAINS:
        closed += "\n" + COMPOUND_ARITHMETIC_OPERATORS.format(name=name)
    return closed


def _enum_class_forward(storage_index: int | None = None):
    def rule(args: list[str]) -> str:
        if args[0].strip() in INTEGER_DOMAINS:
            return "typedef i32 %s" % args[0].strip()

        storage = args[storage_index].strip() if storage_index is not None else "i32"
        return "enum class %s : %s" % (args[0].strip(), storage)
    return rule


def _enum_storage(template: str):
    """A field that keeps its retail width but presents the domain type."""
    def rule(args: list[str]) -> str:
        return "%s<%s, %s>" % (template, args[0].strip(), args[1].strip())
    return rule


def _enum_index(args: list[str]) -> str:
    return "H2EnumIndex(%s)" % args[0].strip()


def _has(args: list[str]) -> str:
    return "(H2EnumIndex((%s) & (%s)))" % (args[0].strip(), args[1].strip())


def _bit(args: list[str]) -> str:
    return "(1 << H2EnumIndex(%s))" % args[0].strip()


def _assign_chain(args: list[str]) -> str:
    targets = [a.strip() for a in args[:-1]]
    value = args[-1].strip()
    return "(%s = %s)" % (" = ".join(targets), value)


# Operator sets for enum domains the game does arithmetic on. In the matching
# tree these expand to nothing, because the domains are integers there and the
# built-in operators already apply. With named enums they have to be real, and
# these are the same operators the repository's strict audit build defines.
STEPPED_OPERATORS = """\
inline constexpr {name} operator+({name} a, i32 amount) {{
    return static_cast<{name}>(static_cast<i32>(a) + amount);
}}
inline constexpr {name} operator-({name} a, i32 amount) {{
    return static_cast<{name}>(static_cast<i32>(a) - amount);
}}
inline constexpr i32 operator-({name} a, {name} b) {{
    return static_cast<i32>(a) - static_cast<i32>(b);
}}
inline constexpr {name} operator%({name} a, i32 modulus) {{
    return static_cast<{name}>(static_cast<i32>(a) % modulus);
}}
inline constexpr {name} operator%({name} a, {name} modulus) {{
    return static_cast<{name}>(static_cast<i32>(a) % static_cast<i32>(modulus));
}}
inline constexpr {name} operator&({name} a, i32 mask) {{
    return static_cast<{name}>(static_cast<i32>(a) & mask);
}}
inline {name}& operator+=({name}& a, i32 amount) {{ return a = a + amount; }}
inline {name}& operator-=({name}& a, i32 amount) {{ return a = a - amount; }}
inline {name}& operator+=({name}& a, {name} b) {{ return a = a + static_cast<i32>(b); }}
inline {name}& operator-=({name}& a, {name} b) {{ return a = a - static_cast<i32>(b); }}
inline {name}& operator%=({name}& a, i32 modulus) {{ return a = a % modulus; }}
inline {name}& operator%=({name}& a, {name} modulus) {{ return a = a % modulus; }}
inline {name}& operator++({name}& a) {{ return a = a + 1; }}
inline {name} operator++({name}& a, int) {{ {name} old = a; a = a + 1; return old; }}
inline {name}& operator--({name}& a) {{ return a = a - 1; }}
inline {name} operator--({name}& a, int) {{ {name} old = a; a = a - 1; return old; }}"""

FLAG_OPERATORS = """\
inline constexpr {name} operator|({name} a, {name} b) {{
    return static_cast<{name}>(static_cast<i32>(a) | static_cast<i32>(b));
}}
inline constexpr {name} operator&({name} a, {name} b) {{
    return static_cast<{name}>(static_cast<i32>(a) & static_cast<i32>(b));
}}
inline constexpr {name} operator^({name} a, {name} b) {{
    return static_cast<{name}>(static_cast<i32>(a) ^ static_cast<i32>(b));
}}
inline constexpr {name} operator~({name} a) {{
    return static_cast<{name}>(~static_cast<i32>(a));
}}
inline constexpr bool operator!({name} a) {{ return !static_cast<i32>(a); }}
inline {name}& operator|=({name}& a, {name} b) {{ return a = a | b; }}
inline {name}& operator&=({name}& a, {name} b) {{ return a = a & b; }}
inline {name}& operator^=({name}& a, {name} b) {{ return a = a ^ b; }}
// Flag sets are also accumulated and cleared arithmetically.
inline constexpr {name} operator+({name} a, {name} b) {{
    return static_cast<{name}>(static_cast<i32>(a) + static_cast<i32>(b));
}}
inline constexpr {name} operator-({name} a, {name} b) {{
    return static_cast<{name}>(static_cast<i32>(a) - static_cast<i32>(b));
}}
inline {name}& operator+=({name}& a, {name} b) {{ return a = a + b; }}
inline {name}& operator-=({name}& a, {name} b) {{ return a = a - b; }}
// Flag domains are also combined with plain masks held in integer fields.
inline constexpr {name} operator&({name} a, i32 mask) {{
    return static_cast<{name}>(static_cast<i32>(a) & mask);
}}
inline constexpr {name} operator&(i32 mask, {name} a) {{ return a & mask; }}
inline constexpr {name} operator|({name} a, i32 mask) {{
    return static_cast<{name}>(static_cast<i32>(a) | mask);
}}
inline constexpr {name} operator|(i32 mask, {name} a) {{ return a | mask; }}
inline {name}& operator&=({name}& a, i32 mask) {{ return a = a & mask; }}
inline {name}& operator|=({name}& a, i32 mask) {{ return a = a | mask; }}"""


def _operators(template: str):
    def rule(args: list[str]) -> str:
        # An integer domain already has every built-in operator; defining more
        # for it would be redefinition, or illegal on a builtin type.
        if args[0].strip() in INTEGER_DOMAINS:
            return DROPPED
        return template.format(name=args[0].strip())
    return rule


def _assign_chain_typed(args: list[str]) -> str:
    """Fan one value out to several fields that may differ in storage width."""
    value = args[-1].strip()
    assignments = "\n".join(
        "        (%s) = static_cast<decltype(%s)>(%s);" % (t.strip(), t.strip(), value)
        for t in reversed(args[:-1])
    )
    return "do {\n%s\n    } while (0)" % assignments


def _decode_masked(args: list[str]) -> str:
    domain, target, raw, mask = (arg.strip() for arg in args)
    return (
        "do {\n"
        f"        ({target}) = static_cast<{domain}>(({raw}) & ({mask}));\n"
        "    } while (0)"
    )


def _clear_flag(args: list[str]) -> str:
    flags, bit = (arg.strip() for arg in args)
    return f"(({flags}) &= ~({bit}))"


def _alloc(name: str):
    """Collapse the file/line-carrying allocation wrappers to their plain form.

    The leak tracking stays; the compiler supplies __FILE__/__LINE__ instead of
    the frozen retail operands, which drops them from ~270 call sites.
    """
    def rule(args: list[str]) -> str:
        return "%s(%s)" % (name, args[0].strip())
    return rule


def _declspec(args: list[str]) -> str:
    """Drop dllexport linkage metadata; keep `naked`, which the asm blitters need."""
    return DROPPED if args[0].strip() == "dllexport" else "__declspec(%s)" % args[0]


CALL_RULES = {
    # Retail-address annotations: audit metadata, no expansion at all.
    "VA": _drop,
    "VA_COMPGEN": _drop,
    "DATA": _drop,
    "DATA_COMPGEN_GUARD": _drop,
    "VTBL": _drop,
    "VTBL2": _drop,

    # Delinker naming for compiler-generated data: expands to the value itself.
    "DATA_COMPGEN": _arg(2),

    # Codegen steering hacks. `0[&(x)]` and `(x | 0)` exist purely to nudge
    # MSVC 4.2 register allocation; they mean `x`.
    "OD_STEER": _arg(0, parenthesize=True),
    "OR_STEER": _arg(0, parenthesize=True),

    # Enum ergonomics.
    "IDX": _enum_index,
    "HAS": _has,
    "BIT": _bit,

    # Enum domain declarations.
    "H2_ENUM_BEGIN": _plain_enum_open,
    "H2_ENUM_END": _plain_enum_close,
    "H2_ENUM_CLASS_BEGIN": _enum_class_open(),
    "H2_ENUM_CLASS_END": _enum_class_close,
    "H2_ENUM_CLASS_BEGIN_T": _enum_class_open(1),
    "H2_ENUM_CLASS_END_T": _enum_class_close,
    "H2_ENUM_CLASS_BEGIN_SPLIT": _enum_class_open(1),
    "H2_ENUM_CLASS_END_SPLIT": _enum_class_close,
    "H2_ENUM_CLASS_FORWARD": _enum_class_forward(),
    "H2_ENUM_CLASS_FORWARD_SPLIT": _enum_class_forward(1),

    # Allocation and assertion wrappers, shorn of their frozen file/line
    # operands. The clean definitions in Misc.h use __FILE__/__LINE__ instead.
    "H2_ALLOC": _alloc("H2_ALLOC"),
    "H2_ALLOC_AT": _alloc("H2_ALLOC"),
    "H2_FREE": _alloc("H2_FREE"),
    "H2_FREE_AT": _alloc("H2_FREE"),
    "H2_ASSERT": _alloc("H2_ASSERT"),

    # Parameters and returns carry the domain type outright.
    "H2_ENUM_PARAM": _arg(0),
    "H2_ENUM_BITFIELD": _arg(0),
    "H2_ENUM_RETURN": _arg(0),

    # Fields keep their retail width -- struct layout is load-bearing, because
    # the game reads these structures straight out of .AGG archives and save
    # files -- while presenting the domain type to expressions.
    "H2_ENUM_STORAGE": _enum_storage("H2EnumStorage"),
    "H2_ENUM_STORAGE_STEPPED": _enum_storage("H2SteppedEnumStorage"),

    # Operator sets for domains used as counters or bit flags.
    "H2_ENUM_STEPPED": _operators(STEPPED_OPERATORS),
    "H2_ENUM_FLAGS": _operators(FLAG_OPERATORS),
    "H2_ENUM_ASSIGN_CHAIN_5": _assign_chain_typed,
    "H2_ENUM_DECODE_MASKED": _decode_masked,
    "H2_ENUM_CLEAR_FLAG": _clear_flag,

    "SIZE": _drop,

    "__declspec": _declspec,
}

# Bare identifiers, no call syntax.
WORD_RULES = {
    "OVERRIDE": "override",

    "__cdecl": "__cdecl",
    "__stdcall": "__stdcall",
    "__fastcall": "__fastcall",
    "__pascal": "",


    # MSVC 4.2 honoured `register`; C++17 removed the storage class.
    "register": "",
}

# `va.h` supplies the annotation macros and, transitively, the integer aliases.
# With the annotations gone only the aliases are still needed.
INCLUDE_REWRITES = {
    "<va.h>": "<Ints.h>",
    '"va.h"': '"Ints.h"',
}


# --------------------------------------------------------------------------
# Lexer-aware rewriting
# --------------------------------------------------------------------------

def _literal_end(text: str, i: int) -> int | None:
    """If a comment or literal starts at `i`, return the index just past it.

    Rewriting must never reach inside these: DATA_COMPGEN values are often
    format strings full of commas and parentheses.
    """
    two = text[i:i + 2]
    if two == "//":
        end = text.find("\n", i)
        return len(text) if end < 0 else end
    if two == "/*":
        end = text.find("*/", i + 2)
        return len(text) if end < 0 else end + 2
    if text[i] in "\"'":
        quote = text[i]
        j = i + 1
        while j < len(text):
            if text[j] == "\\":
                j += 2
                continue
            if text[j] == quote:
                return j + 1
            if text[j] == "\n":  # unterminated; bail out rather than run away
                return j
            j += 1
        return len(text)
    return None


def _is_ident_start(ch: str) -> bool:
    return ch.isalpha() or ch == "_"


def _is_ident_char(ch: str) -> bool:
    return ch.isalnum() or ch == "_"


def _split_args(text: str) -> list[str]:
    """Split a macro argument list on top-level commas."""
    args, depth, start, i = [], 0, 0, 0
    while i < len(text):
        end = _literal_end(text, i)
        if end is not None:
            i = end
            continue
        ch = text[i]
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        elif ch == "," and depth == 0:
            args.append(text[start:i])
            start = i + 1
        i += 1
    args.append(text[start:])
    return args


def _match_call(text: str, open_paren: int) -> tuple[int, list[str]] | None:
    """Given the index of `(`, return (index past `)`, argument list)."""
    depth, i = 0, open_paren
    while i < len(text):
        end = _literal_end(text, i)
        if end is not None:
            i = end
            continue
        ch = text[i]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return i + 1, _split_args(text[open_paren + 1:i])
        i += 1
    return None


def rewrite(text: str) -> str:
    """Apply every rule, innermost first, outside of literals and comments."""
    out, i, n = [], 0, len(text)
    while i < n:
        end = _literal_end(text, i)
        if end is not None:
            out.append(text[i:end])
            i = end
            continue

        if not _is_ident_start(text[i]):
            out.append(text[i])
            i += 1
            continue

        j = i
        while j < n and _is_ident_char(text[j]):
            j += 1
        word = text[i:j]

        if word in CALL_RULES:
            k = j
            while k < n and text[k] in " \t\n\r":
                k += 1
            if k < n and text[k] == "(":
                matched = _match_call(text, k)
                if matched is not None:
                    close, args = matched
                    # Recurse first so nested macros (IDX inside HAS, and so on)
                    # are already expanded when the outer rule runs.
                    out.append(CALL_RULES[word]([rewrite(a) for a in args]))
                    i = close
                    continue

        if word in WORD_RULES:
            out.append(WORD_RULES[word])
            i = j
            continue

        out.append(word)
        i = j
    return "".join(out)


def strip_comments(text: str) -> str:
    """Remove comments without joining adjacent tokens."""
    out, i, n = [], 0, len(text)
    while i < n:
        two = text[i:i + 2]
        if two == "//":
            end = text.find("\n", i + 2)
            i = n if end < 0 else end
            continue
        if two == "/*":
            end = text.find("*/", i + 2)
            end = n if end < 0 else end + 2
            out.append(" " + "\n" * text[i:end].count("\n"))
            i = end
            continue
        end = _literal_end(text, i)
        if end is not None:
            out.append(text[i:end])
            i = end
            continue
        out.append(text[i])
        i += 1
    return "".join(out)


def tidy(text: str) -> str:
    """Remove the holes left by dropped annotations."""
    lines = []
    for line in text.split("\n"):
        if DROPPED in line:
            # Statement-position annotations -- `VTBL(palette, 0x004eba7c);` --
            # carry a terminator that belongs to the annotation, not to any
            # surrounding declaration, so it goes with them.
            if line.replace(DROPPED, "").replace(";", "").strip() == "":
                continue  # the line held nothing but annotations
            # `DATA(0x...) i32 gValue = 0;` -> `i32 gValue = 0;`
            line = line.replace(DROPPED + " ", "").replace(DROPPED, "")
        lines.append(line.rstrip())

    # Collapse runs of blank lines left where annotation blocks used to sit.
    tidied, blanks = [], 0
    for line in lines:
        blanks = blanks + 1 if line == "" else 0
        if blanks <= 2:
            tidied.append(line)
    return "\n".join(tidied)


# Preprocessor definitions that exist only to reproduce retail's debug-heap
# bookkeeping. Their definitions are deleted and, in the header that owned them,
# replaced by CLEAN_ALLOC_MACROS below.
ALLOC_MACRO_NAMES = ("H2_ALLOC_AT", "H2_FREE_AT", "H2_ALLOC", "H2_FREE", "H2_ASSERT")

CLEAN_ALLOC_MACROS = """\
// Allocation and assertion wrappers. The compiler supplies the call site, so
// nothing has to thread a source path and line number through by hand.
//
// Only the file's base name is passed. The leak tracker copies this into
// MemEntry::file, a fixed 61-byte field sized for retail's own spellings
// ("I:\\Projects\\Heroes\\Prog\\BASE\\PALETTE.CPP"); a modern absolute
// __FILE__ overruns it on the first allocation.
constexpr const char* H2SourceName(const char* path) {
    const char* name = path;
    for (const char* cursor = path; *cursor != '\\0'; ++cursor) {
        if (*cursor == '/' || *cursor == '\\\\') {
            name = cursor + 1;
        }
    }
    return name;
}

#define H2_ALLOC(size) BaseAlloc(size, const_cast<char*>(H2SourceName(__FILE__)), __LINE__)
#define H2_FREE(ptr) BaseFree(ptr, const_cast<char*>(H2SourceName(__FILE__)), __LINE__)
#define H2_ASSERT(condition)                                                                       \\
    ProcessAssert(condition, const_cast<char*>(H2SourceName(__FILE__)), __LINE__)"""


def _directive(line: str) -> tuple[str, str] | None:
    """Classify a preprocessor line as (directive, first token), if it is one."""
    stripped = line.lstrip()
    if not stripped.startswith("#"):
        return None
    parts = stripped[1:].lstrip().split(None, 2)
    if not parts:
        return None
    return parts[0], (parts[1].split("(")[0] if len(parts) > 1 else "")


def _strict_condition(line: str) -> bool | None:
    """Branch taken for an #if controlled solely by the strict-types macro.

    None when it is about something else and must pass through untouched.
    """
    stripped = line.lstrip()
    if not stripped.startswith("#"):
        return None
    body = stripped[1:].lstrip()
    for prefix, taken in (("ifdef", True), ("ifndef", False)):
        if body.startswith(prefix):
            rest = body[len(prefix):].strip()
            if rest.split("//")[0].strip() == STRICT_MACRO:
                return taken
    if body.startswith("if "):
        condition = body[3:].split("//")[0].strip()
        if condition in (STRICT_MACRO, "defined(%s)" % STRICT_MACRO):
            return True
        if condition in ("!%s" % STRICT_MACRO, "!defined(%s)" % STRICT_MACRO):
            return False
    return None


def resolve_strict_conditionals(text: str) -> str:
    """Collapse `#ifdef HOMM2_STRICT_ENUM_TYPES` to its typed branch.

    Every other `#if` is copied verbatim, with nesting tracked so its
    `#else`/`#endif` are still matched correctly.
    """
    lines = text.split("\n")
    out: list[str] = []
    # Stack of frames for conditionals we are resolving. Each is
    # [keeping_now, seen_taken_branch]; unrelated conditionals push None.
    stack: list[list[bool] | None] = []
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.lstrip()
        emitting = all(frame is None or frame[0] for frame in stack)

        if stripped.startswith("#"):
            body = stripped[1:].lstrip()
            taken = _strict_condition(line)

            if body.startswith(("if", "ifdef", "ifndef")) and not body.startswith("include"):
                stack.append([taken, taken] if taken is not None else None)
                if taken is not None:
                    i += 1
                    continue

            elif body.startswith(("else", "elif")) and stack:
                frame = stack[-1]
                if frame is not None:
                    # Once the strict branch has been taken, every later arm is
                    # dead; #else takes over only if it was not.
                    frame[0] = (not frame[1]) if body.startswith("else") else False
                    i += 1
                    continue

            elif body.startswith("endif") and stack:
                frame = stack.pop()
                if frame is not None:
                    i += 1
                    continue

        if emitting:
            out.append(line)
        i += 1

    return "\n".join(out)


def rewrite_directives(text: str) -> str:
    lines = text.split("\n")
    out: list[str] = []
    injected = False
    i = 0

    while i < len(lines):
        line = lines[i]
        directive = _directive(line)

        if directive is not None:
            name, target = directive

            # `#line 28` pinned retail's /Gi line variables. Nothing downstream
            # of the matching build wants it.
            if name == "line":
                i += 1
                continue

            # Definitions and undefs of scaffolding that no longer exists --
            # including `#undef DATA`, which only guarded against a collision
            # with the Windows headers.
            if (name in ("define", "undef")
                    and (target in PROVENANCE_MACROS
                         or (target in CALL_RULES and target not in INTENTIONALLY_KEPT)
                         or target in WORD_RULES)):
                while i < len(lines) and lines[i].rstrip().endswith("\\"):
                    i += 1
                i += 1
                continue

            if name == "define" and target in ALLOC_MACRO_NAMES:
                while i < len(lines) and lines[i].rstrip().endswith("\\"):
                    i += 1
                i += 1
                if not injected:
                    out.append(CLEAN_ALLOC_MACROS)
                    injected = True
                continue

            if name == "include":
                for old, new in INCLUDE_REWRITES.items():
                    if old in line:
                        line = line.replace(old, new)

        out.append(line)
        i += 1

    return "\n".join(out)


def drop_integer_domain_operators(text: str) -> str:
    """Remove operator definitions written for a domain that stays an integer.

    Once the domain is a plain integer typedef, a header's own
    `operator^=(CombatSide&, i32)` redefines built-in behaviour and is
    ill-formed. Only reachable when INTEGER_DOMAINS is non-empty.
    """
    lines = text.split("\n")
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        starts_definition = line.startswith("inline") and "operator" in line
        names_integer_domain = any(domain in line for domain in INTEGER_DOMAINS)
        if not (starts_definition and names_integer_domain):
            out.append(line)
            i += 1
            continue

        # Skip to the end of the definition by brace balance. A one-line body
        # opens and closes on the same line.
        depth = 0
        seen_brace = False
        while i < len(lines):
            depth += lines[i].count("{") - lines[i].count("}")
            seen_brace = seen_brace or "{" in lines[i]
            i += 1
            if seen_brace and depth <= 0:
                break
    return "\n".join(out)


def apply_patches(relative: str, text: str) -> str:
    for kind, sites, pattern, replacement in GENERATED_PATCHES.get(relative, []):
        if kind is Pattern.REGEX:
            text, count = re.subn(pattern, replacement, text)
        else:
            count = text.count(pattern)
            text = text.replace(pattern, replacement)
        if count != sites:
            raise SystemExit(
                "generated patch hit %d site(s) in %s, expected %d: %r\n"
                "  The source moved. Re-check the patch, then update its count."
                % (count, relative, sites, pattern)
            )
    return text


def _replace_word(text: str, word: str, replacement: str) -> str:
    """Replace a bare identifier outside comments and literals."""
    out, i, n = [], 0, len(text)
    while i < n:
        end = _literal_end(text, i)
        if end is not None:
            out.append(text[i:end])
            i = end
            continue
        if _is_ident_start(text[i]):
            j = i
            while j < n and _is_ident_char(text[j]):
                j += 1
            out.append(replacement if text[i:j] == word else text[i:j])
            i = j
            continue
        out.append(text[i])
        i += 1
    return "".join(out)


def clean(text: str, relative: str = "") -> str:
    text = resolve_strict_conditionals(text)
    text = rewrite_directives(text)

    # The base name, not __FILE__: several units store this in fixed-size char
    # arrays (40 bytes in Blur.cpp) that an absolute path always overruns. Must
    # run after the directive pass, or it rewrites the `#define RETAIL_FILE`
    # line into `#define "Blur.cpp"`.
    name = relative.rsplit("/", 1)[-1] if relative else "unknown.cpp"
    text = _replace_word(text, "RETAIL_FILE", '"%s"' % name)

    text = drop_integer_domain_operators(tidy(strip_comments(rewrite(text))))
    for old, new in CLEAN_IDENTIFIER_REWRITES.items():
        text = _replace_word(text, old, new)
    return text.rstrip("\n") + "\n"


# --------------------------------------------------------------------------
# Tree generation
# --------------------------------------------------------------------------


def validate_out_root(requested: Path) -> Path:
    """Resolve an output root and fail closed before any recursive deletion.

    Repository-owned output belongs below build/. Existing destinations are
    accepted only when a marker proves this generator created them. Never
    replace a Git worktree or a broad ancestor of this repository.
    """
    if requested.is_symlink():
        raise SystemExit("refusing symlink output root: %s" % requested)

    out_root = requested.resolve()
    repo = REPO.resolve()
    build_root = (repo / "build").resolve()

    if out_root == Path(out_root.anchor) or out_root == repo or repo.is_relative_to(out_root):
        raise SystemExit("refusing broad output root: %s" % out_root)

    inside_repo = out_root.is_relative_to(repo)
    inside_build = out_root.is_relative_to(build_root) and out_root != build_root
    if inside_repo and not inside_build:
        raise SystemExit("repository output must be below build/: %s" % out_root)

    if out_root.exists():
        if not out_root.is_dir():
            raise SystemExit("output root exists and is not a directory: %s" % out_root)
        if (out_root / ".git").exists():
            raise SystemExit("refusing to replace a Git worktree: %s" % out_root)
        marker = out_root / GENERATED_MARKER
        marked = (
            marker.is_file()
            and not marker.is_symlink()
            and marker.read_text() == GENERATED_MARKER_CONTENT
        )
        if not marked:
            raise SystemExit(
                "refusing to replace unmarked output directory: %s" % out_root
            )

    return out_root


def write_ninja(out_root: Path) -> None:
    sources = sorted((out_root / "src").rglob("*.cpp"))
    include_flags = [
        "-Iinclude",
        "-Ivendor/miles-3.6",
        "-Ivendor/smacker-3.0g",
        "-Ivendor/wing-1.0",
    ]
    flags = [
        "--target=i686-w64-windows-gnu",
        "-std=gnu++20",
        "-fms-extensions",
        "-fsjlj-exceptions",
        "-w",
        "-D_X86_",
        "-DWIN32",
        "-D_WINDOWS",
        "-D_MT",
        "-Dregister=",
        "-Wno-write-strings",
        "-Wno-narrowing",
        "-Wno-deprecated-enum-enum-conversion",
        "-Wno-deprecated-enum-float-conversion",
        *include_flags,
    ]
    lines = [
        "ninja_required_version = 1.10",
        "builddir = build",
        "cxx = clang++",
        "dlltool = llvm-dlltool",
        "cxxflags = " + " ".join(flags),
        "ldflags = --target=i686-w64-windows-gnu -fuse-ld=lld -mwindows "
        "-fsjlj-exceptions -static -static-libgcc -static-libstdc++",
        "system_libs = -lkernel32 -luser32 -lgdi32 -lwinmm -lws2_32 "
        "-lddraw -ldplayx -ladvapi32 -lole32 -luuid -lcomdlg32 "
        "-lshell32 -lnetapi32",
        "runtime_libs = -Wl,--start-group -lstdc++ -lgcc_eh -lgcc "
        "-lmcfgthread -lntdll -Wl,--end-group",
        "",
        "rule mkdir",
        "  command = mkdir -p $out",
        "  restat = 1",
        "",
        "rule cxx",
        "  command = $cxx $cxxflags -MMD -MF $out.d -c $in -o $out",
        "  depfile = $out.d",
        "  deps = gcc",
        "  description = CXX $in",
        "",
        "rule implib",
        "  command = $dlltool -m i386 -d $in -l $out",
        "  description = IMPLIB $in",
        "",
        "rule link",
        "  command = $cxx $ldflags -o $out $in $system_libs $runtime_libs",
        "  description = LINK $out",
        "",
        "build $builddir/obj: mkdir",
        "build $builddir/imports: mkdir",
    ]
    objects = []
    for source in sources:
        relative = source.relative_to(out_root).as_posix()
        name = relative.removeprefix("src/").removesuffix(".cpp").replace("/", "_")
        obj = f"$builddir/obj/{name}.o"
        lines.append(f"build {obj}: cxx {relative} || $builddir/obj")
        objects.append(obj)
    import_libraries = []
    for dll in ("MSS32", "SMACKW32", "WING32"):
        library = f"$builddir/imports/{dll}.a"
        lines.append(
            f"build {library}: implib imports/{dll}.def || $builddir/imports"
        )
        import_libraries.append(library)
    lines += [
        "",
        "build objects: phony " + " ".join(objects),
        "build $builddir/HEROES2W.EXE: link "
        + " ".join(objects + import_libraries),
        "build game: phony $builddir/HEROES2W.EXE",
        "default game",
        "",
    ]
    (out_root / "build.ninja").write_text("\n".join(lines))


MSS_IMPORTS = (
    "_AIL_set_sample_loop_count@8",
    "_AIL_set_sample_playback_rate@8",
    "_AIL_start_sample@4",
    "_AIL_set_sample_type@12",
    "_AIL_sample_volume@4",
    "_AIL_set_sample_volume@8",
    "_AIL_midiOutOpen@12",
    "_AIL_startup@0",
    "_AIL_set_preference@8",
    "_AIL_waveOutOpen@16",
    "_AIL_last_error@0",
    "_AIL_redbook_tracks@4",
    "_AIL_redbook_track_info@16",
    "_AIL_redbook_close@4",
    "_AIL_redbook_open@4",
    "_AIL_init_sample@4",
    "_AIL_serve@0",
    "_AIL_stop_sequence@4",
    "_AIL_midiOutClose@4",
    "_AIL_release_sequence_handle@4",
    "_AIL_set_sequence_loop_count@8",
    "_AIL_sequence_status@4",
    "_AIL_resume_sequence@4",
    "_AIL_init_sequence@12",
    "_AIL_start_sequence@4",
    "_AIL_set_XMIDI_master_volume@8",
    "_AIL_shutdown@0",
    "_AIL_allocate_sequence_handle@4",
    "_AIL_allocate_sample_handle@4",
    "_AIL_sample_status@4",
    "_AIL_end_sample@4",
    "_AIL_set_sample_address@12",
    "_AIL_get_preference@4",
)

SMACK_IMPORTS = (
    ("_SmackSoundUseDirectSound@4", 38),
    ("_SmackSoundUseMSS@4", 33),
    ("_SmackNextFrame@4", 21),
    ("_SmackToBufferRect@8", 28),
    ("_SmackDoFrame@4", 19),
    ("_SmackToBuffer@28", 23),
    ("_SmackClose@4", 18),
    ("_SmackOpen@12", 14),
    ("_SmackWait@4", 32),
    ("_SmackSummary@8", 20),
)

WING_IMPORTS = (
    ("_WinGCreateDC@0", "WinGCreateDC"),
    ("_WinGCreateBitmap@12", "WinGCreateBitmap"),
    ("_WinGRecommendDIBFormat@4", "WinGRecommendDIBFormat"),
    ("_WinGSetDIBColorTable@16", "WinGSetDIBColorTable"),
    ("_WinGStretchBlt@40", "WinGStretchBlt"),
    ("_WinGBitBlt@32", "WinGBitBlt"),
)


def write_import_defs(out_root: Path) -> None:
    imports = out_root / "imports"
    imports.mkdir()

    mss = ["LIBRARY mss32.dll", "EXPORTS"]
    mss += [f"  {symbol[1:]} = {symbol}" for symbol in MSS_IMPORTS]
    (imports / "MSS32.def").write_text("\n".join(mss) + "\n")

    smack = ["LIBRARY smackw32.DLL", "EXPORTS"]
    smack += [
        f"  {symbol[1:]} @{ordinal} NONAME"
        for symbol, ordinal in SMACK_IMPORTS
    ]
    (imports / "SMACKW32.def").write_text("\n".join(smack) + "\n")

    wing = ["LIBRARY WING32.dll", "EXPORTS"]
    wing += [
        f"  {symbol[1:]} = {lookup}"
        for symbol, lookup in WING_IMPORTS
    ]
    (imports / "WING32.def").write_text("\n".join(wing) + "\n")


def generate(out_root: Path) -> tuple[int, int, list[str]]:
    out_root = validate_out_root(out_root)
    if out_root.exists():
        shutil.rmtree(out_root)
    out_root.mkdir(parents=True)
    (out_root / GENERATED_MARKER).write_text(GENERATED_MARKER_CONTENT)

    debris: list[str] = []
    patched_files: set[str] = set()
    sources = 0
    for tier in ("include", "src", "vendor"):
        for path in sorted((REPO / tier).rglob("*")):
            if not path.is_file() or path.suffix not in (".h", ".cpp"):
                continue
            relative = path.relative_to(REPO)
            if str(relative).replace("\\", "/") in DROP_FILES:
                continue
            target = out_root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            source_text = path.read_text()
            relative_text = str(relative).replace("\\", "/")
            if tier == "vendor":
                cleaned_text = tidy(strip_comments(source_text)).rstrip("\n") + "\n"
            else:
                cleaned_text = apply_patches(
                    relative_text,
                    clean(source_text, relative_text),
                )
            patched_files.add(relative_text)
            target.write_text(cleaned_text)
            for number, line in stranded(source_text, cleaned_text):
                debris.append(f"{relative}:{number}: {line}")
            sources += 1

    overrides = 0
    if OVERRIDE_DIR.is_dir():
        for path in sorted(OVERRIDE_DIR.rglob("*")):
            if path.is_file():
                target = out_root / path.relative_to(OVERRIDE_DIR)
                target.parent.mkdir(parents=True, exist_ok=True)
                text = tidy(strip_comments(path.read_text())).rstrip("\n") + "\n"
                target.write_text(text)
                overrides += 1

    write_import_defs(out_root)
    write_ninja(out_root)

    # A patch key that no file matched means the source moved and the patch is
    # now silently doing nothing.
    for key in GENERATED_PATCHES:
        if key not in patched_files:
            raise SystemExit("generated patch names a file that was not generated: %s" % key)

    return sources, overrides, debris


# Macros the clean tree keeps on purpose: the allocation wrappers survive in
# their argument-free form, and `__declspec` still carries `naked`.
INTENTIONALLY_KEPT = {
    "H2_ALLOC",
    "H2_FREE",
    "H2_ASSERT",
    "__declspec",
    "__cdecl",
    "__fastcall",
    "__stdcall",
}
MARKER_PREFIXES = ("H2_ENUM_",)
MARKER_NAMES = {STRICT_MACRO, "RETAIL_FILE"}


def residue(out_root: Path) -> dict[str, int]:
    """Count scaffolding that survived, as a self-check.

    Scans with the same lexer used for rewriting, so occurrences inside string
    literals (".\\DATA\\HEROES2.AGG") and comments are not miscounted.
    """
    names = ((set(CALL_RULES) | set(WORD_RULES)) - INTENTIONALLY_KEPT) | MARKER_NAMES
    found: dict[str, int] = {}
    for path in sorted(out_root.rglob("*")):
        if not path.is_file() or path.suffix not in (".h", ".cpp"):
            continue
        text = path.read_text()
        i, n = 0, len(text)
        while i < n:
            if text[i:i + 2] in ("//", "/*"):
                found["comment"] = found.get("comment", 0) + 1
                end = _literal_end(text, i)
                i = n if end is None else end
                continue
            end = _literal_end(text, i)
            if end is not None:
                i = end
                continue
            if _is_ident_start(text[i]):
                j = i
                while j < n and _is_ident_char(text[j]):
                    j += 1
                word = text[i:j]
                if word in names or word.startswith(MARKER_PREFIXES):
                    found[word] = found.get(word, 0) + 1
                i = j
                continue
            i += 1
    return found


def publish(out_root: Path, branch: str) -> int:
    """Publish the generated tree onto a branch, one commit per source commit.

    The clean tree is a pure function of the matching tree, so it is never
    edited by hand: as matching advances toward byte-exactness, this is re-run
    and the improvements flow through to the branch consumers build against.
    """
    import subprocess
    import tempfile

    def git(*argv: str, cwd: Path = REPO, **kwargs) -> str:
        return subprocess.run(("git", *argv), cwd=cwd, text=True,
                              capture_output=True, check=True, **kwargs).stdout.strip()

    out_root = validate_out_root(out_root)
    source_commit = git("rev-parse", "HEAD")
    source_branch = git("rev-parse", "--abbrev-ref", "HEAD")
    if git("status", "--porcelain"):
        raise SystemExit("refusing to publish from a dirty source worktree")

    subprocess.run(
        ("git", "check-ref-format", "--branch", branch),
        cwd=REPO,
        check=True,
        capture_output=True,
    )
    branch_ref = "refs/heads/%s" % branch
    # The exit status is the answer here, so it is read rather than raised on.
    exists = subprocess.run(
        ("git", "show-ref", "--verify", "--quiet", branch_ref),
        cwd=REPO,
        capture_output=True,
        check=False,
    ).returncode == 0
    if exists:
        message = git("log", "-1", "--format=%B", branch_ref)
        if "Generated by scripts/clean_source.py." not in message:
            raise SystemExit(
                "refusing to replace non-generated branch %s" % branch
            )

    # A branch can only be checked out in one worktree. If the user already has
    # one open on `branch` -- handy for browsing the generated tree -- publish
    # into it rather than fighting over the checkout.
    existing, current = None, None
    for line in git("worktree", "list", "--porcelain").split("\n"):
        if line.startswith("worktree "):
            current = Path(line.split(" ", 1)[1])
        elif line == "branch %s" % branch_ref:
            existing = current

    temporary = existing is None
    worktree = existing

    if temporary:
        # Best effort: clears stale entries if any, and is fine if there are none.
        subprocess.run(("git", "worktree", "prune"), cwd=REPO, capture_output=True,
                       check=False)
        worktree = Path(tempfile.mkdtemp(
            prefix=".clean-worktree-",
            dir=out_root.parent,
        ))
        worktree.rmdir()
        if exists:
            git("worktree", "add", str(worktree), branch)
        else:
            git("worktree", "add", "--detach", str(worktree))
            subprocess.run(("git", "checkout", "--orphan", branch),
                           cwd=worktree, check=True, capture_output=True)
            # Empties the index the orphan inherited. Fails harmlessly when the
            # checkout it was branched from was itself empty.
            subprocess.run(("git", "rm", "-rf", "--quiet", "."),
                           cwd=worktree, capture_output=True, check=False)

    try:
        assert worktree is not None
        if git("status", "--porcelain", cwd=worktree):
            raise SystemExit(
                "refusing to replace dirty generated worktree at %s" % worktree
            )

        for stale in PUBLISHED_PATHS:
            path = worktree / stale
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink(missing_ok=True)
        for relative in PUBLISHED_PATHS:
            source = out_root / relative
            target = worktree / relative
            if source.is_dir():
                shutil.copytree(source, target)
            elif source.is_file():
                shutil.copyfile(source, target)

        stage_paths = [
            relative for relative in PUBLISHED_PATHS
            if (worktree / relative).exists()
            or git("ls-files", "--", relative, cwd=worktree)
        ]
        subprocess.run(
            ("git", "add", "-A", "--", *stage_paths),
            cwd=worktree,
            check=True,
            capture_output=True,
        )
        # --quiet exits non-zero precisely when there is a difference.
        unchanged = not subprocess.run(
            ("git", "diff", "--cached", "--quiet", "--", *stage_paths),
            cwd=worktree,
            capture_output=True,
            check=False,
        ).returncode

        message = (
            f"source: regenerate from {source_branch} {source_commit[:9]}\n\n"
            f"Generated by scripts/clean_source.py. Do not edit this branch by "
            f"hand -- it is a pure function of the matching tree, and every "
            f"change belongs upstream in the generator or the matching source.\n\n"
            f"Source-Commit: {source_commit}\n"
        )
        recorded = git("log", "-1", "--format=%B", cwd=worktree) if exists else ""
        if unchanged and source_commit in recorded:
            print(f"[clean] {branch} already matches {source_commit[:9]}")
        else:
            commit_args = ["git", "commit", "--quiet"]
            if unchanged:
                commit_args.append("--allow-empty")
            commit_args += ["-m", message]
            subprocess.run(
                tuple(commit_args), cwd=worktree, check=True, capture_output=True
            )
            print(f"[clean] committed to {branch} from "
                  f"{source_branch} {source_commit[:9]}")
    finally:
        if temporary:
            # Cleanup on the way out of a failure must not mask the failure.
            subprocess.run(
                ("git", "worktree", "remove", "--force", str(worktree)),
                cwd=REPO,
                capture_output=True,
                check=False,
            )
        else:
            print(f"[clean] checkout at {worktree}")
    return 0


def _punctuation_only(text: str) -> list[tuple[int, str]]:
    lines = []
    for number, line in enumerate(text.split("\n"), 1):
        stripped = line.strip()
        if stripped and not stripped.strip(";,"):
            lines.append((number, stripped))
    return lines


def stranded(source: str, cleaned: str) -> list[tuple[int, str]]:
    """Structural debris a dropped construct left behind.

    Expanding a macro to nothing can strand the punctuation that belonged to it
    -- a lone `;` where `VTBL(palette, 0x004eba7c);` used to be. That still
    compiles, so nothing else would catch it.

    Reported as a delta against the input, because a bare `;` is also a
    legitimate empty statement: the game really does write `if (easy) ;` to
    leave a branch of an if/else chain empty.
    """
    introduced = (
        len(_punctuation_only(cleaned))
        - len(_punctuation_only(strip_comments(source)))
    )
    return _punctuation_only(cleaned)[-introduced:] if introduced > 0 else []


def verify(out_root: Path) -> int:
    """Build the generated Windows executable with Ninja."""
    import subprocess

    result = subprocess.run(
        ("ninja", "-C", str(out_root), "game"),
        check=False,
    )
    if result.returncode == 0:
        print("[clean] verify: built build/HEROES2W.EXE")
    return result.returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="build/clean", help="output tree root")
    parser.add_argument("--verify", action="store_true",
                        help="build the generated Windows executable with Ninja")
    parser.add_argument("--publish", metavar="BRANCH", nargs="?", const="clean",
                        help="commit the generated tree onto BRANCH (default: clean)")
    args = parser.parse_args(argv)
    requested = (REPO / args.out) if not Path(args.out).is_absolute() else Path(args.out)
    out_root = validate_out_root(requested)
    sources, overrides, debris = generate(out_root)
    print(f"[clean] wrote {sources} transformed files "
          f"({overrides} supplied overrides) to {out_root}")

    left = residue(out_root)
    if left:
        print("[clean] WARNING: scaffolding survived the transform:", file=sys.stderr)
        for name, count in sorted(left.items(), key=lambda kv: -kv[1]):
            print(f"          {name:<32} {count}", file=sys.stderr)
        return 1

    if debris:
        print("[clean] WARNING: stranded punctuation from dropped constructs:",
              file=sys.stderr)
        for site in debris[:MAX_REPORTED]:
            print(f"          {site}", file=sys.stderr)
        if len(debris) > MAX_REPORTED:
            print(f"          ... and {len(debris) - MAX_REPORTED} more", file=sys.stderr)
        return 1

    print("[clean] no comments, scaffolding macros, or stranded punctuation remain")

    status = 0
    if args.verify:
        status = verify(out_root)

    if args.publish:
        return publish(out_root, args.publish) or status
    return status


if __name__ == "__main__":
    raise SystemExit(main())
