#ifndef HOMM2_ADVMGR_H
#define HOMM2_ADVMGR_H
#include <va.h>
// Declarations of the free functions DEFINED in ADVMGR.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
class mapCell;
struct tag_message;

typedef enum AdventureScreenConstant {
    ADVMGR_SCREEN_WIDTH = 640,
    ADVMGR_SCREEN_HEIGHT = 480,
    ADVMGR_SCROLL_BORDER = 16,
    ADVMGR_VIEW_EDGE_MARGIN = 8,
    ADVMGR_RADAR_LEFT = 480,
    ADVMGR_RADAR_RIGHT = 624,
    ADVMGR_RADAR_TOP = 16,
    ADVMGR_RADAR_BOTTOM = 160,
    ADVMGR_PUZZLE_TILE_SIZE = 32,
    ADVMGR_PUZZLE_X_TRIM = 12
} AdventureScreenConstant;

typedef enum AdventureScrollDirection {
    ADVMGR_SCROLL_NORTH = 0,
    ADVMGR_SCROLL_NORTH_EAST = 1,
    ADVMGR_SCROLL_EAST = 2,
    ADVMGR_SCROLL_SOUTH_EAST = 3,
    ADVMGR_SCROLL_SOUTH = 4,
    ADVMGR_SCROLL_SOUTH_WEST = 5,
    ADVMGR_SCROLL_WEST = 6,
    ADVMGR_SCROLL_NORTH_WEST = 7
} AdventureScrollDirection;

typedef enum AdventureScrollConstant {
    ADVMGR_SCROLL_MIN_ORIGIN = 1 - ADVMGR_VIEW_EDGE_MARGIN,
    ADVMGR_VIEW_CENTER_OFFSET = ADVMGR_VIEW_EDGE_MARGIN - 1,
    ADVMGR_SCROLL_TICK_INTERVAL = 70
} AdventureScrollConstant;

typedef enum AdventureButtonConstant {
    ADVMGR_BUTTON_MESSAGE = 0x200,
    ADVMGR_BUTTON_ENABLE = 5,
    ADVMGR_BUTTON_DISABLE = 6,
    ADVMGR_BUTTON_FIRST = 1,
    ADVMGR_BUTTON_LAST = 6,
    ADVMGR_BUTTON_TARGET = 2,
    ADVMGR_BUTTON_SLOT_1 = 1,
    ADVMGR_BUTTON_SLOT_2 = 2,
    ADVMGR_BUTTON_SLOT_3 = 3,
    ADVMGR_BUTTON_SLOT_4 = 4,
    ADVMGR_BUTTON_SLOT_5 = 5,
    ADVMGR_BUTTON_SLOT_6 = 6,
    ADVMGR_BUTTON_BROADCAST_ARG = 1,
    ADVMGR_BUTTON_BROADCAST_FLAGS = 0x4008
} AdventureButtonConstant;

typedef enum AdventureTriggerConstant {
    ADVMGR_TRIGGER_TYPE_MASK = 0x7f,
    ADVMGR_TRIGGER_ACTION_FLAG = 0x80,
    ADVMGR_SPECIAL_TRIGGER = 0x7a,
    ADVMGR_SPECIAL_TRIGGER_MASK = 0x3f,
    ADVMGR_TRIGGER_EVENT_5 = 5,
    ADVMGR_TRIGGER_EVENT_6 = 6
} AdventureTriggerConstant;

typedef enum AdventureHoverObject {
    ADVMGR_HOVER_MONSTER = 0x18,
    ADVMGR_HOVER_COAST = 0x1c,
    ADVMGR_HOVER_SHIPWRECK = 0x20,
    ADVMGR_HOVER_TOWN = 0x23,
    ADVMGR_HOVER_HERO = 0x2a,
    ADVMGR_HOVER_BOAT = 0x2b,
    ADVMGR_HOVER_SHIPWRECK_TRIGGER =
        ADVMGR_HOVER_SHIPWRECK | ADVMGR_TRIGGER_ACTION_FLAG
} AdventureHoverObject;

typedef enum AdventureHoverConstant {
    ADVMGR_HOVER_VIEW_CELLS = 15,
    ADVMGR_HOVER_MAX_CELL = ADVMGR_HOVER_VIEW_CELLS - 1,
    ADVMGR_HOVER_OBJECT_BLOCKED = 0x08,
    ADVMGR_HOVER_UNREACHABLE = 0x80,
    ADVMGR_HOVER_ROUTE_DAY_LIMIT = 3,
    ADVMGR_HOVER_ROUTE_FRAMES_PER_DAY = 6,
    ADVMGR_HOVER_SCROLL_FRAME_FIRST = 32,
    ADVMGR_HOVER_SCROLL_FRAME_END = 40
} AdventureHoverConstant;

typedef enum AdventurePointerFrame {
    ADVMGR_POINTER_DEFAULT = 0,
    ADVMGR_POINTER_HERO = 2,
    ADVMGR_POINTER_TOWN = 3,
    ADVMGR_POINTER_MOVE = 4,
    ADVMGR_POINTER_ATTACK = 5,
    ADVMGR_POINTER_SAIL = 6,
    ADVMGR_POINTER_DISEMBARK = 7,
    ADVMGR_POINTER_SELECT_HERO = 8,
    ADVMGR_POINTER_ACTION = 9,
    ADVMGR_POINTER_WATER_ACTION = 28
} AdventurePointerFrame;

typedef enum AdventureFrameConstant {
    ADVMGR_MOBILITY_SCALE = 22,
    ADVMGR_MOBILITY_DIVISOR = 1500,
    ADVMGR_MANA_DIVISOR = 5,
    ADVMGR_MANA_MIN_VISIBLE = 3,
    ADVMGR_MOBILITY_TOP_THRESHOLD = 30,
    ADVMGR_MOBILITY_HIGH_THRESHOLD = 26,
    ADVMGR_MOBILITY_MID_THRESHOLD = 23,
    ADVMGR_MANA_TOP_THRESHOLD = 33,
    ADVMGR_MANA_HIGH_THRESHOLD = 28,
    ADVMGR_MANA_MID_THRESHOLD = 23,
    ADVMGR_FRAME_TOP = 25,
    ADVMGR_FRAME_HIGH = 24,
    ADVMGR_FRAME_MID = 23
} AdventureFrameConstant;

typedef enum AdventureStateConstant {
    ADVMGR_INVALID_CELL = -1,
    ADVMGR_INVALID_HERO = -1,
    ADVMGR_LOOPING_SOUND_LIMIT = 4,
    ADVMGR_OBJECT_ICON_COUNT = 64,
    ADVMGR_HERO_ICON_COUNT = 8,
    ADVMGR_PLAYER_COLOR_COUNT = 6,
    ADVMGR_LOOPING_SAMPLE_COUNT = 28,
    ADVMGR_CURSOR_SAMPLE_COUNT = 9,
    ADVMGR_SOUND_CELL_COUNT = 4,
    ADVMGR_HIGH_MEMORY_BUFFER_DIVISOR = 100,
    ADVMGR_XLARGE_MAP_SIZE = 144,
    ADVMGR_CURSOR_SAMPLE_VOLUME = 64,
    ADVMGR_CURSOR_SAMPLE_CHANNEL = 2,
    ADVMGR_QUICK_VIEW_NONE = -99,
    ADVMGR_DEFAULT_POINTER_FRAME = -999,
    ADVMGR_UNUSED_OBJECT_ICON_1 = 21,
    ADVMGR_UNUSED_OBJECT_ICON_2 = 38
} AdventureStateConstant;

typedef enum AdventureRemoteConstant {
    ADVMGR_REMOTE_DATA_REQUEST = 1,
    ADVMGR_REMOTE_PACKET_TYPE_GAME = 2,
    ADVMGR_REMOTE_PACKET_TYPE_ALT = 3,
    ADVMGR_REMOTE_COMMAND_SAVE_GAME = 1,
    ADVMGR_REMOTE_COMMAND_POP_NET_BOX = 11,
    ADVMGR_REMOTE_COMMAND_COMBAT = 21,
    ADVMGR_REMOTE_COMMAND_PLAYER_EXIT = 31,
    ADVMGR_REMOTE_COMMAND_HOST_PLAYER_EXIT = 33,
    ADVMGR_REMOTE_COMMAND_GROUP_MAP_CHANGE = 41,
    ADVMGR_REMOTE_LOAD_MAP_CHANGE = 11
} AdventureRemoteConstant;

typedef enum AdventureRemoteWaitConstant {
    ADVMGR_REMOTE_WAIT_COMMAND_MESSAGE = 1,
    ADVMGR_REMOTE_WAIT_MOUSE_MESSAGE = 4,
    ADVMGR_REMOTE_WAIT_EXIT_COMMAND = 16,
    ADVMGR_REMOTE_WAIT_POP_NET_BOX_COMMAND = 60,
    ADVMGR_REMOTE_WAIT_EXIT_MODIFIER_MASK = 0x0c,
    ADVMGR_REMOTE_WAIT_EXIT_MESSAGE = 0x4000,
    ADVMGR_REMOTE_WAIT_EXIT_RESULT = 2
} AdventureRemoteWaitConstant;

#pragma pack(push, 1)
struct AdventureRemotePacket {
    signed char sender;
    char unknown1[4];
    signed char type;
    signed char command;
    char unknown7[2];
    union {
        char payload[16];
        struct {
            int saveDataSize;
            int saveCrc;
            int saveTransmitCrc;
            int savePlayerExited;
        };
    };
};
#pragma pack(pop)

typedef enum AdventureEnvironmentSoundConstant {
    ADVMGR_ENVIRONMENT_SOUND_NONE = -1,
    ADVMGR_ENVIRONMENT_SOUND_LOG_UNUSED = -999,
    ADVMGR_ENVIRONMENT_SOUND_PAN = 100,
    ADVMGR_ENVIRONMENT_SOUND_DEFAULT_VOLUME = 127,
    ADVMGR_ENVIRONMENT_SOUND_MAX_DISTANCE = 5,
    ADVMGR_ENVIRONMENT_SOUND_FIRST_LAYER = 1,
    ADVMGR_ENVIRONMENT_SOUND_LAYER_COUNT = 2,
    ADVMGR_ENVIRONMENT_SOUND_CHANNEL_TYPE = 3
} AdventureEnvironmentSoundConstant;

typedef enum AdventureEnvironmentSoundId {
    ADVMGR_SOUND_BUOY = 0,
    ADVMGR_SOUND_SHIPWRECK = 1,
    ADVMGR_SOUND_COAST = 2,
    ADVMGR_SOUND_ORACLE = 3,
    ADVMGR_SOUND_STONE_LITHS = 4,
    ADVMGR_SOUND_SMALL_VOLCANO = 5,
    ADVMGR_SOUND_LAVA_POOL = 6,
    ADVMGR_SOUND_ALCHEMIST_LAB = 7,
    ADVMGR_SOUND_ALCHEMIST_LAB_ACTION = 8,
    ADVMGR_SOUND_WATER_WHEEL = 9,
    ADVMGR_SOUND_CAMPFIRE = 10,
    ADVMGR_SOUND_WINDMILL = 11,
    ADVMGR_SOUND_FOUNTAIN = 12,
    ADVMGR_SOUND_WATERING_HOLE = 13,
    ADVMGR_SOUND_STREAM = 14,
    ADVMGR_SOUND_MINE = 15,
    ADVMGR_SOUND_SAWMILL = 16,
    ADVMGR_SOUND_DAEMON_CAVE = 17,
    ADVMGR_SOUND_SHRINE = 18,
    ADVMGR_SOUND_SEAGULLS = 19,
    ADVMGR_SOUND_COASTLINE = 20,
    ADVMGR_SOUND_TAR_PIT = 21,
    ADVMGR_SOUND_TRADING_POST = 22,
    ADVMGR_SOUND_DERELICT_SHIP = 23,
    ADVMGR_SOUND_RUINS = 24,
    ADVMGR_SOUND_DWELLING = 25,
    ADVMGR_SOUND_ABANDONED_MINE = 26,
    ADVMGR_SOUND_LARGE_VOLCANO = 27
} AdventureEnvironmentSoundId;

typedef enum AdventureTeleportConstant {
    ADVMGR_TELEPORT_MAP_CHANGE = 9,
    ADVMGR_TELEPORT_MAP_CHANGE_VALUE = -999,
    ADVMGR_TELEPORT_CELL_OBJECT_FLAG = 0x40,
    ADVMGR_TELEPORT_RESTORE_MODE = 99,
    ADVMGR_TELEPORT_VIEW_CENTER = 7,
    ADVMGR_TELEPORT_DELAY = 90,
    ADVMGR_TELEPORT_TELESCOPE_ARTIFACT = 0x40,
    ADVMGR_TELEPORT_FIZZLE_TIME = 128,
    ADVMGR_TELEPORT_REMOTE_FIZZLE_ADJUSTMENT = 64
} AdventureTeleportConstant;

typedef enum AdventureTravelSpellConstant {
    ADVMGR_TRAVEL_DIALOG_ACCEPT = 1,
    ADVMGR_TRAVEL_MUSIC = 1,
    ADVMGR_DIMENSION_DOOR_SPELL = 0x38,
    ADVMGR_TOWN_PORTAL_SPELL = 0x3a,
    ADVMGR_TOWN_PORTAL_WINDOW_X = 159,
    ADVMGR_TOWN_PORTAL_WINDOW_Y = 65,
    ADVMGR_TOWN_PORTAL_DISTANCE_LIMIT = 1000
} AdventureTravelSpellConstant;

typedef enum AdventureTownPortalMessage {
    ADVMGR_TOWN_PORTAL_MESSAGE = 0x200,
    ADVMGR_TOWN_PORTAL_COMMAND_SELECT = 13,
    ADVMGR_TOWN_PORTAL_COMMAND_TEXT = 3,
    ADVMGR_TOWN_PORTAL_COMMAND_ADD_TOWN = 56,
    ADVMGR_TOWN_PORTAL_COMMAND_FINISH = 54,
    ADVMGR_TOWN_PORTAL_COMMAND_CHOICE = 55,
    ADVMGR_TOWN_PORTAL_TITLE_WIDGET = 1,
    ADVMGR_TOWN_PORTAL_CHOICE_WIDGET = 100,
    ADVMGR_TOWN_PORTAL_CLOSE_COMMAND = 10,
    ADVMGR_TOWN_PORTAL_FIRST_CHOICE = 0x7801,
    ADVMGR_TOWN_PORTAL_LAST_CHOICE = 0x7802,
    ADVMGR_TOWN_PORTAL_UNHANDLED = 1,
    ADVMGR_TOWN_PORTAL_HANDLED = 2
} AdventureTownPortalMessage;

typedef enum AdventureSoundObject {
    ADVMGR_SOUND_OBJECT_ALCHEMIST_LAB = 0x01,
    ADVMGR_SOUND_OBJECT_BUOY = 0x03,
    ADVMGR_SOUND_OBJECT_DAEMON_CAVE = 0x05,
    ADVMGR_SOUND_OBJECT_CAMPFIRE = 0x08,
    ADVMGR_SOUND_OBJECT_FOUNTAIN = 0x09,
    ADVMGR_SOUND_OBJECT_ARCHER_HOUSE = 0x0d,
    ADVMGR_SOUND_OBJECT_DWARF_COTTAGE = 0x0f,
    ADVMGR_SOUND_OBJECT_PEASANT_HUT = 0x10,
    ADVMGR_SOUND_OBJECT_LOG_CABIN = 0x11,
    ADVMGR_SOUND_OBJECT_WATER_WHEEL = 0x16,
    ADVMGR_SOUND_OBJECT_MINE = 0x17,
    ADVMGR_SOUND_OBJECT_SAWMILL = 0x1d,
    ADVMGR_SOUND_OBJECT_ORACLE = 0x1e,
    ADVMGR_SOUND_OBJECT_SHRINE_FIRST = 0x1f,
    ADVMGR_SOUND_OBJECT_SHIPWRECK = 0x20,
    ADVMGR_SOUND_OBJECT_STONE_LITHS = 0x24,
    ADVMGR_SOUND_OBJECT_WHIRLPOOL = 0x27,
    ADVMGR_SOUND_OBJECT_WINDMILL = 0x28,
    ADVMGR_SOUND_OBJECT_RUINS = 0x3d,
    ADVMGR_SOUND_OBJECT_TRADING_POST = 0x3f,
    ADVMGR_SOUND_OBJECT_ABANDONED_MINE = 0x40,
    ADVMGR_SOUND_OBJECT_SIRENS = 0x41,
    ADVMGR_SOUND_OBJECT_SHRINE_SECOND = 0x4a,
    ADVMGR_SOUND_OBJECT_SHRINE_THIRD = 0x4b,
    ADVMGR_SOUND_OBJECT_TAR_PIT = 0x51,
    ADVMGR_SOUND_OBJECT_ARTESIAN_SPRING = 0x52,
    ADVMGR_SOUND_OBJECT_WATERING_HOLE = 0x54,
    ADVMGR_SOUND_OBJECT_DERELICT_SHIP = 0x5b,
    ADVMGR_SOUND_OBJECT_VOLCANO = 0x65,
    ADVMGR_SOUND_OBJECT_WATER_LAKE = 0x68,
    ADVMGR_SOUND_OBJECT_LAVA_POOL = 0x70
} AdventureSoundObject;

typedef enum AdventureSoundTilesetConstant {
    ADVMGR_SOUND_GROUND_SHAPE_MASK = 0x0f,
    ADVMGR_SOUND_TILESET_WATER = 0x28,
    ADVMGR_SOUND_TILESET_STREAM = 0x2d,
    ADVMGR_SOUND_TILESET_WATER_LAKE_UNUSED = 0x34,
    ADVMGR_SOUND_TILESET_SMALL_VOLCANO = 0x3a,
    ADVMGR_SOUND_TILESET_LARGE_VOLCANO = 0x3c,
    ADVMGR_SOUND_SEAGULL_FRAME_FIRST = 0xb6,
    ADVMGR_SOUND_SEAGULL_FRAME_LAST = 0xb7,
    ADVMGR_SOUND_ALCHEMIST_FRAME_FIRST = 0x27,
    ADVMGR_SOUND_ALCHEMIST_FRAME_LAST = 0x2c
} AdventureSoundTilesetConstant;

typedef enum AdventureOpenConstant {
    ADVMGR_SCROLL_Y = 195,
    ADVMGR_SCROLL_LEFT_X = 540,
    ADVMGR_SCROLL_RIGHT_X = 612,
    ADVMGR_SCROLL_WIDTH = 8,
    ADVMGR_SCROLL_HEIGHT = 17,
    ADVMGR_SCROLL_LEFT_FRAME = 26,
    ADVMGR_SCROLL_RIGHT_FRAME = 27,
    ADVMGR_SCROLL_HOTKEY = 16,
    ADVMGR_TIMER_DELAY = 120,
    ADVMGR_MANAGER_MESSAGE = 0x400
} AdventureOpenConstant;

typedef enum AdventureInterfaceConstant {
    ADVMGR_INTERFACE_AUTO = 0,
    ADVMGR_INTERFACE_GOOD = 1,
    ADVMGR_INTERFACE_EVIL = 2,
    ADVMGR_INTERFACE_TRANSLATION_COUNT = 37,
    ADVMGR_INTERFACE_MESSAGE = 0x200,
    ADVMGR_INTERFACE_REPLACE_RESOURCE = 0x3c
} AdventureInterfaceConstant;

typedef enum AdventureSystemOptionsMessage {
    ADVMGR_SYSTEM_OPTIONS_MESSAGE = 0x200,
    ADVMGR_SYSTEM_OPTIONS_ACTIVATE = 12,
    ADVMGR_SYSTEM_OPTIONS_ACCEPT = 13,
    ADVMGR_SYSTEM_OPTIONS_HOVER = 14,
    ADVMGR_SYSTEM_OPTIONS_CONTEXT_FLAG = 0x200,
    ADVMGR_SYSTEM_OPTIONS_DIALOG_ACCEPT = 0x7800,
    ADVMGR_SYSTEM_OPTIONS_UNHANDLED = 1,
    ADVMGR_SYSTEM_OPTIONS_HANDLED = 2
} AdventureSystemOptionsMessage;

typedef enum AdventureSystemOption {
    ADVMGR_SYSTEM_OPTION_MUSIC_VOLUME = 10,
    ADVMGR_SYSTEM_OPTION_SOUND_VOLUME = 11,
    ADVMGR_SYSTEM_OPTION_HERO_SPEED = 12,
    ADVMGR_SYSTEM_OPTION_MUSIC_SOURCE = 13,
    ADVMGR_SYSTEM_OPTION_SHOW_ROUTE = 14,
    ADVMGR_SYSTEM_OPTION_COMPUTER_SPEED = 15,
    ADVMGR_SYSTEM_OPTION_INTERFACE = 16,
    ADVMGR_SYSTEM_OPTION_VIDEO = 17,
    ADVMGR_SYSTEM_OPTION_COLOR_CURSOR = 18,
    ADVMGR_SYSTEM_OPTION_FIRST = ADVMGR_SYSTEM_OPTION_MUSIC_VOLUME,
    ADVMGR_SYSTEM_OPTION_LAST = ADVMGR_SYSTEM_OPTION_COLOR_CURSOR,
    ADVMGR_SYSTEM_OPTION_COUNT = ADVMGR_SYSTEM_OPTION_LAST - ADVMGR_SYSTEM_OPTION_FIRST + 1
} AdventureSystemOption;

typedef enum AdventureSystemOptionConstant {
    ADVMGR_OPTION_VOLUME_LEVELS = 11,
    ADVMGR_OPTION_HERO_SPEED_LEVELS = 5,
    ADVMGR_OPTION_COMPUTER_SPEED_MAX = 4,
    ADVMGR_OPTION_COMPUTER_SPEED_DEFAULT = 2,
    ADVMGR_OPTION_INTERFACE_COUNT = 3,
    ADVMGR_OPTION_MUSIC_MIDI = 0,
    ADVMGR_OPTION_MUSIC_CD = 1,
    ADVMGR_OPTION_DIALOG_MESSAGE = 1,
    ADVMGR_OPTION_DIALOG_HELP = 4,
    ADVMGR_OPTION_DIALOG_NONE = -1
} AdventureSystemOptionConstant;

typedef enum AdventureSummonBoatConstant {
    ADVMGR_SUMMON_CENTER_OFFSET = 7,
    ADVMGR_SUMMON_DIRECTION_COUNT = 8,
    ADVMGR_SUMMON_BOAT_COUNT = 48,
    ADVMGR_SUMMON_OCCUPIED_FLAG = 0x80,
    ADVMGR_SUMMON_MIN_DISTANCE = 2,
    ADVMGR_SUMMON_RESTORE_MODE = 5,
    ADVMGR_SUMMON_SCREEN_MARGIN = 16,
    ADVMGR_SUMMON_SCREEN_LIMIT = 464,
    ADVMGR_SUMMON_FIZZLE_X_OFFSET = 48,
    ADVMGR_SUMMON_FIZZLE_WIDTH = 112,
    ADVMGR_SUMMON_FIZZLE_HEIGHT = 80,
    ADVMGR_SUMMON_TARGET_X = 154,
    ADVMGR_SUMMON_TARGET_Y = 152,
    ADVMGR_SUMMON_TARGET_WIDTH = 150,
    ADVMGR_SUMMON_TARGET_HEIGHT = 136,
    ADVMGR_SUMMON_BOAT_TRIGGER = 0xab
} AdventureSummonBoatConstant;

typedef enum AdventureRouteConstant {
    ADVMGR_ROUTE_PATH_COST_LIMIT = 59999,
    ADVMGR_ROUTE_TERRAIN_COST_INFINITY = 999999999,
    ADVMGR_ROUTE_DAY_MASK = 0x100,
    ADVMGR_ROUTE_ARROW_FRAME_STRIDE = 24,
    ADVMGR_ROUTE_ARROW_FRAME_OFFSET = 2,
    ADVMGR_ROUTE_STRAIGHT_COST_0 = 75,
    ADVMGR_ROUTE_STRAIGHT_COST_1 = 100,
    ADVMGR_ROUTE_STRAIGHT_COST_2 = 125,
    ADVMGR_ROUTE_STRAIGHT_COST_3 = 150,
    ADVMGR_ROUTE_STRAIGHT_COST_4 = 175,
    ADVMGR_ROUTE_STRAIGHT_COST_5 = 200,
    ADVMGR_ROUTE_DIAGONAL_COST_0 = 112,
    ADVMGR_ROUTE_DIAGONAL_COST_1 = 150,
    ADVMGR_ROUTE_DIAGONAL_COST_2 = 187,
    ADVMGR_ROUTE_DIAGONAL_COST_3 = 225,
    ADVMGR_ROUTE_DIAGONAL_COST_4 = 262,
    ADVMGR_ROUTE_DIAGONAL_COST_5 = 300
} AdventureRouteConstant;

typedef enum AdventureCommand {
    ADVMGR_COMMAND_NONE = -1,
    ADVMGR_COMMAND_MOVE_TO = 1,
    ADVMGR_COMMAND_HERO_VIEW = 2,
    ADVMGR_COMMAND_TOWN_VIEW = 3,
    ADVMGR_COMMAND_SELECT_HERO = 4,
    ADVMGR_COMMAND_SELECT_TOWN = 5,
    ADVMGR_COMMAND_OCCUPIED_TOWN_VIEW = 6,
    ADVMGR_COMMAND_CONTINUE_ROUTE = 7
} AdventureCommand;

typedef enum AdventureInputEvent {
    ADVMGR_INPUT_MOUSE_DOWN = 1,
    ADVMGR_INPUT_MOUSE_UP = 8,
    ADVMGR_INPUT_KEY_DOWN = 0x20,
    ADVMGR_INPUT_COMMAND = 0x200
} AdventureInputEvent;

typedef enum AdventureSearchConstant {
    ADVMGR_ARTIFACT_CAPACITY = 14,
    ADVMGR_CLEAR_GROUND_TILESET = 47,
    ADVMGR_DIG_HOLE_TILESET = 56,
    ADVMGR_DIG_HOLE_FRAME = 140,
    ADVMGR_ULTIMATE_ARTIFACT_NONE = -1,
    ADVMGR_SPHERE_OF_NEGATION = 98,
    ADVMGR_ULTIMATE_ARTIFACT_MUSIC = 41
} AdventureSearchConstant;

typedef enum AdventureDrawMask {
    ADVMGR_DRAW_GROUND = 0x01,
    ADVMGR_DRAW_OBJECT = 0x02,
    ADVMGR_DRAW_OVERLAY = 0x04,
    ADVMGR_DRAW_HERO = 0x08,
    ADVMGR_DRAW_CLOUD = 0x20,
    ADVMGR_DRAW_OVERLAY_TOP = 0x40,
    ADVMGR_DRAW_HERO_SHADOW = 0x80
} AdventureDrawMask;

typedef enum AdventureDrawConstant {
    ADVMGR_CELL_PIXELS = 32,
    ADVMGR_DRAW_VIEW_CELLS = 15,
    ADVMGR_DRAW_LAST_CELL = ADVMGR_DRAW_VIEW_CELLS - 1,
    ADVMGR_DRAW_FORWARD_DIRECTION_MAX = 4,
    ADVMGR_DRAW_CLIP_WIDTH = 480,
    ADVMGR_DRAW_CLIP_HEIGHT = 480,
    ADVMGR_CLOUD_VARIANTS = 4,
    ADVMGR_HERO_TYPE_BOAT = 6,
    ADVMGR_HERO_SHADOW_FRAME_END = 36,
    ADVMGR_MINE_GUARDIAN_ICON_SLOT = 10,
    ADVMGR_TILESET_MONSTER = 20,
    ADVMGR_TILESET_MINE = 12,
    ADVMGR_TILESET_BOAT = 39,
    ADVMGR_MONSTER_TRIGGER = 0x97,
    ADVMGR_HERO_TRIGGER = 0xaa,
    ADVMGR_BOAT_TRIGGER = 0xab
} AdventureDrawConstant;

typedef enum AdventureComboDrawConstant {
    ADVMGR_COMBO_VIEW_CELLS = 15,
    ADVMGR_COMBO_GRID_CELLS = 18,
    ADVMGR_COMBO_CLEAR_BYTES = 256,
    ADVMGR_COMBO_CLOUD_MARK = 10,
    ADVMGR_COMBO_FRAME_LIMIT = 12,
    ADVMGR_COMBO_HERO_PANEL_LEFT = 5,
    ADVMGR_COMBO_HERO_PANEL_RIGHT = 10,
    ADVMGR_COMBO_HERO_PANEL_TOP = 6,
    ADVMGR_COMBO_HERO_PANEL_BOTTOM = 9,
    ADVMGR_COMBO_UPDATE_MIN = 16,
    ADVMGR_COMBO_UPDATE_MAX = 463,
    ADVMGR_MONSTER_GHOST = 0x3b,
    ADVMGR_CURSOR_ROUTE = 6
} AdventureComboDrawConstant;

typedef enum AdventureUpdateScreenConstant {
    ADVMGR_UPDATE_NONE = -1,
    ADVMGR_UPDATE_VIEWPORT_ORIGIN = 16,
    ADVMGR_UPDATE_VIEWPORT_SIZE = 448,
    ADVMGR_UPDATE_ANIMATION_PHASES = 6,
    ADVMGR_UPDATE_FRAME_CYCLE = 18
} AdventureUpdateScreenConstant;

typedef enum AdventureRadarConstant {
    ADVMGR_RADAR_SIZE = 144,
    ADVMGR_RADAR_SCREEN_PITCH = 640,
    ADVMGR_RADAR_ROW_GROUPS = 5,
    ADVMGR_RADAR_GROUP_BYTES = 128,
    ADVMGR_RADAR_MAP_SMALL = 36,
    ADVMGR_RADAR_MAP_MEDIUM = 72,
    ADVMGR_RADAR_MAP_LARGE = 108,
    ADVMGR_RADAR_MAP_XLARGE = 144,
    ADVMGR_RADAR_UNSEEN_COLOR = 0x24,
    ADVMGR_RADAR_NEUTRAL_OWNER = 6,
    ADVMGR_RADAR_TERRAIN_SHADE = 3,
    ADVMGR_RADAR_PARTIAL_MARGIN = 2,
    ADVMGR_RADAR_PARTIAL_SPAN = 16,
    ADVMGR_RADAR_CURRENT_CELL = 7,
    ADVMGR_RADAR_TOWN_RADIUS = 2,
    ADVMGR_RADAR_TOWN_TRIGGER = 0x2a,
    ADVMGR_RADAR_TOWN_TILESET_1 = 0x23,
    ADVMGR_RADAR_TOWN_TILESET_2 = 0x24,
    ADVMGR_RADAR_SPECIAL_TILESET = 0x3e,
    ADVMGR_RADAR_REEFS_TRIGGER = 0x67,
    ADVMGR_RADAR_NEIGHBOR_TRIGGER = 0xa3
} AdventureRadarConstant;

typedef enum AdventureArmySizeThreshold {
    ADVMGR_ARMY_FEW_LIMIT = 5,
    ADVMGR_ARMY_SEVERAL_LIMIT = 10,
    ADVMGR_ARMY_PACK_LIMIT = 20,
    ADVMGR_ARMY_LOTS_LIMIT = 50,
    ADVMGR_ARMY_HORDE_LIMIT = 100,
    ADVMGR_ARMY_THRONG_LIMIT = 250,
    ADVMGR_ARMY_SWARM_LIMIT = 500,
    ADVMGR_ARMY_ZOUNDS_LIMIT = 1000
} AdventureArmySizeThreshold;

typedef enum AdventureBottomHeroViewConstant {
    ADVMGR_BOTTOM_HERO_VIEW_ID = 3,
    ADVMGR_BOTTOM_HERO_ARMY_SLOTS = 5,
    ADVMGR_BOTTOM_HERO_EMPTY_SLOT = -1,
    ADVMGR_BOTTOM_HERO_LABEL_BYTES = 6,
    ADVMGR_BOTTOM_HERO_MAX_FULL_COUNT = 1999,
    ADVMGR_BOTTOM_HERO_COUNT_DIVISOR = 1000,
    ADVMGR_BOTTOM_HERO_PANEL_X = 480,
    ADVMGR_BOTTOM_HERO_PANEL_Y = 392,
    ADVMGR_BOTTOM_HERO_PANEL_WIDTH = 143,
    ADVMGR_BOTTOM_HERO_PANEL_HEIGHT = 71,
    ADVMGR_BOTTOM_HERO_ICON_WIDTH = 32,
    ADVMGR_BOTTOM_HERO_ICON_HEIGHT = 28,
    ADVMGR_BOTTOM_HERO_LABEL_HEIGHT = 12,
    ADVMGR_BOTTOM_HERO_LABEL_Y_OFFSET = 25,
    ADVMGR_BOTTOM_HERO_TOP_LABEL_SHIFT = 2,
    ADVMGR_BOTTOM_HERO_TOP_MIN_HEIGHT = 35,
    ADVMGR_BOTTOM_HERO_LOWER_MIN_HEIGHT = 37,
    ADVMGR_BOTTOM_HERO_GROUP_WIDTH = 45,
    ADVMGR_BOTTOM_HERO_CHARACTER_WIDTH = 5,
    ADVMGR_BOTTOM_HERO_FIRST_ICON_ID = 2002,
    ADVMGR_BOTTOM_HERO_FIRST_TEXT_ID = 2101,
    ADVMGR_BOTTOM_HERO_WIDGET_FLAGS = 16,
    ADVMGR_BOTTOM_HERO_TEXT_ALIGNMENT = 0x200
} AdventureBottomHeroViewConstant;

typedef enum AdventureVisionsConstant {
    ADVMGR_VISIONS_RADIUS = 3,
    ADVMGR_VISIONS_MONSTER_TRIGGER = 0x98,
    ADVMGR_VISIONS_NO_MONSTER_DISTANCE = 100,
    ADVMGR_VISIONS_MESSAGE_BUFFER_SIZE = 200
} AdventureVisionsConstant;

typedef enum AdventureEnemyTurnViewConstant {
    ADVMGR_ENEMY_TURN_VIEW_ID = 4,
    ADVMGR_ENEMY_TURN_BACKGROUND_X = 480,
    ADVMGR_ENEMY_TURN_BACKGROUND_Y = 392,
    ADVMGR_ENEMY_TURN_BACKGROUND_WIDTH = 143,
    ADVMGR_ENEMY_TURN_BACKGROUND_HEIGHT = 71,
    ADVMGR_ENEMY_TURN_HOURGLASS_X = 493,
    ADVMGR_ENEMY_TURN_HOURGLASS_Y = 403,
    ADVMGR_ENEMY_TURN_HOURGLASS_WIDTH = 118,
    ADVMGR_ENEMY_TURN_HOURGLASS_HEIGHT = 51,
    ADVMGR_ENEMY_TURN_CREST_X = 495,
    ADVMGR_ENEMY_TURN_ANIMATION_X = 559,
    ADVMGR_ENEMY_TURN_ANIMATION_Y = 405,
    ADVMGR_ENEMY_TURN_ANIMATION_WIDTH = 50,
    ADVMGR_ENEMY_TURN_ANIMATION_HEIGHT = 47,
    ADVMGR_ENEMY_TURN_BACKGROUND_ID = 2000,
    ADVMGR_ENEMY_TURN_HOURGLASS_ID = 2001,
    ADVMGR_ENEMY_TURN_CREST_ID = 2002,
    ADVMGR_ENEMY_TURN_SAND_ID = 2003,
    ADVMGR_ENEMY_TURN_PHASE_ID = 2004,
    ADVMGR_ENEMY_TURN_BACKGROUND_Z = 1000,
    ADVMGR_ENEMY_TURN_HOURGLASS_Z = 1010,
    ADVMGR_ENEMY_TURN_SAND_Z = 1020,
    ADVMGR_ENEMY_TURN_CREST_Z = 1030,
    ADVMGR_ENEMY_TURN_PHASE_Z = 1040,
    ADVMGR_ENEMY_TURN_WIDGET_FLAGS = 16,
    ADVMGR_ENEMY_TURN_SAND_FRAME_OFFSET = 11,
    ADVMGR_ENEMY_TURN_SAND_FRAME_LIMIT = 20,
    ADVMGR_ENEMY_TURN_SAND_RESTART_FRAME = 16,
    ADVMGR_ENEMY_TURN_PHASE_FRAME_OFFSET = 1,
    ADVMGR_ENEMY_TURN_ANIMATION_DELAY = 300,
    ADVMGR_ENEMY_TURN_PHASE_DELAY = 700,
    ADVMGR_ENEMY_TURN_MESSAGE_TYPE = 0x200,
    ADVMGR_ENEMY_TURN_MESSAGE_SET_FRAME = 4
} AdventureEnemyTurnViewConstant;

typedef enum AdventureCloudNeighbor {
    ADVMGR_CLOUD_NORTH = 0x01,
    ADVMGR_CLOUD_EAST = 0x02,
    ADVMGR_CLOUD_SOUTH = 0x04,
    ADVMGR_CLOUD_WEST = 0x08,
    ADVMGR_CLOUD_NORTH_EAST = 0x10,
    ADVMGR_CLOUD_SOUTH_EAST = 0x20,
    ADVMGR_CLOUD_SOUTH_WEST = 0x40,
    ADVMGR_CLOUD_NORTH_WEST = 0x80,
    ADVMGR_CLOUD_LEFT_EDGE = 0xc8,
    ADVMGR_CLOUD_RIGHT_EDGE = 0x32,
    ADVMGR_CLOUD_TOP_EDGE = 0x91,
    ADVMGR_CLOUD_BOTTOM_EDGE = 0x64
} AdventureCloudNeighbor;

typedef enum AdventureQuickInfoObject {
    ADVMGR_OBELISK_INDEX_BASE = 1,
    ADVMGR_RESOURCE_FRAME_PAIR_MASK = ~1,
    ADVMGR_OBJECT_NONE = 0,
    ADVMGR_OBJECT_FORT = 3,
    ADVMGR_OBJECT_STANDING_STONES = 7,
    ADVMGR_OBJECT_GAZEBO = 9,
    ADVMGR_OBJECT_GAZEBO_VISIT = 10,
    ADVMGR_OBJECT_MINE = 0x17,
    ADVMGR_OBJECT_MONSTER = 0x18,
    ADVMGR_OBJECT_OBELISK = 0x19,
    ADVMGR_OBJECT_MERCENARY_CAMP = 0x1a,
    ADVMGR_OBJECT_RESOURCE = 0x1b,
    ADVMGR_OBJECT_ARTIFACT = 0x29,
    ADVMGR_OBJECT_FORT_VISIT = 0x3e,
    ADVMGR_OBJECT_GUARDED = 0x40,
    ADVMGR_OBJECT_STANDING_STONE_ALT = 0x42,
    ADVMGR_OBJECT_XANADU = 0x43,
    ADVMGR_OBJECT_TREE_ALT = 0x44,
    ADVMGR_OBJECT_WITCH_DOCTOR_VISIT = 0x45,
    ADVMGR_OBJECT_WITCH_DOCTOR_ALT = 0x46,
    ADVMGR_OBJECT_MERCENARY_VISIT = 0x49,
    ADVMGR_OBJECT_EVENT_SITE = 0x54,
    ADVMGR_OBJECT_XANADU_ALT = 0x56,
    ADVMGR_OBJECT_EVENT_SITE_ALT = 0x5e,
    ADVMGR_OBJECT_REEFS = 0x67,
    ADVMGR_OBJECT_BARRIER = 0x77,
    ADVMGR_OBJECT_TENT = 0x78,
    ADVMGR_OBJECT_RECRUITMENT_SITE = 0x79,
    ADVMGR_OBJECT_GENERIC_SITE = 0x7a
} AdventureQuickInfoObject;

typedef enum AdventureVisitMask {
    ADVMGR_VISIT_FORT = 2,
    ADVMGR_VISIT_GAZEBO = 4,
    ADVMGR_VISIT_MERCENARY_CAMP = 8,
    ADVMGR_VISIT_STANDING_STONES = 0x10,
    ADVMGR_VISIT_WITCH_DOCTOR = 0x100,
    ADVMGR_VISIT_EVENT_SITE = 0x200,
    ADVMGR_VISIT_XANADU = 0x1000,
    ADVMGR_VISIT_TREE_OF_KNOWLEDGE = 0x2000,
    ADVMGR_VISIT_GENERIC_TOWER = 0x100000,
    ADVMGR_VISIT_GENERIC_SPRING = 0x200000,
    ADVMGR_VISIT_GENERIC_HUT = 0x400000,
    ADVMGR_VISIT_GENERIC_ALTAR = 0x800000
} AdventureVisitMask;

typedef enum AdventureSiteConstant {
    ADVMGR_SITE_TILESET_1 = 0x3d,
    ADVMGR_SITE_TILESET_2 = 0x3e,
    ADVMGR_SITE_TILESET_3 = 0x3f,
    ADVMGR_GENERIC_SITE_1_END = 4,
    ADVMGR_GENERIC_SITE_2_END = 0x48,
    ADVMGR_GENERIC_ALTAR_END = 5,
    ADVMGR_GENERIC_UNUSED_END = 10,
    ADVMGR_GENERIC_TOWER_END = 0x2f,
    ADVMGR_GENERIC_SPRING_END = 0x6f,
    ADVMGR_GENERIC_SITE_3_SPLIT = 0x20,
    ADVMGR_GENERIC_SITE_3_END = 0x3b,
    ADVMGR_RECRUITMENT_START = 0x48,
    ADVMGR_RECRUITMENT_1_END = 0x4e,
    ADVMGR_RECRUITMENT_2_END = 0x70,
    ADVMGR_RECRUITMENT_3_END = 0x78,
    ADVMGR_RECRUITMENT_4_END = 0x81,
    ADVMGR_RECRUITMENT_5_END = 0x89
} AdventureSiteConstant;

typedef enum AdventurePanelCommand {
    ADVMGR_PANEL_NEXT_HERO = 1,
    ADVMGR_PANEL_CONTINUE_ROUTE = 2,
    ADVMGR_PANEL_OVERVIEW = 3,
    ADVMGR_PANEL_END_TURN = 4,
    ADVMGR_PANEL_ADVENTURE_OPTIONS = 5,
    ADVMGR_PANEL_CONTROL_OPTIONS = 6,
    ADVMGR_PANEL_SYSTEM_OPTIONS = 7,
    ADVMGR_PANEL_CAST_SPELL = 8,
    ADVMGR_PANEL_HERO_PAGE_PREVIOUS = 20,
    ADVMGR_PANEL_HERO_PAGE_NEXT = 21,
    ADVMGR_PANEL_TOWN_PAGE_PREVIOUS = 23,
    ADVMGR_PANEL_TOWN_PAGE_NEXT = 24,
    ADVMGR_OVERVIEW_HERO = 1,
    ADVMGR_OVERVIEW_TOWN = 2,
    ADVMGR_DIALOG_OK = 0x7806,
    ADVMGR_BOTTOM_VIEW_FIRST_MESSAGE = 2000,
    ADVMGR_BOTTOM_VIEW_LAST_MESSAGE = 2200,
    ADVMGR_BOTTOM_VIEW_DURATION = 3000,
    ADVMGR_LOCATORS_PER_PAGE = 5,
    ADVMGR_LOCATOR_PAGE_STEP = 4
} AdventurePanelCommand;

int SaveGame(void);
int DimensionDoorHandler(struct tag_message &);
int TownPortalHandler(struct tag_message &);
void ComputeAdvNetControl(void);
int MapExtraPosAndAdjacentsSet(int, int, unsigned char);
int APanelHandler(struct tag_message &);
int CPanelHandler(struct tag_message &);
void UpdateSystemOptions(int);
int SystemOptionsHandler(struct tag_message &);
int GetMobilityFrame(int);
int GetManaFrame(int);
unsigned char StopOnTrigger(class mapCell *);


// ---- globals (declarations, RVA order) ----
extern float fFirstWeekTownFV;
extern int iVepCacheHits;
extern int iTotalVepHits;
extern int giShowComputerRoute;
extern long glLastStartTick;
extern long glCurTicks;
extern long glTotalTicks;
extern float gfAttackHumanBonus;
extern float gfAttackComputerBonus;
extern int bSVSearchArrayInUse;
extern int bEvaluatingTravelGates;
extern int gbReduceByBerserk;
extern float fBerserkFactor;
extern int giMaxHeroesForThisPlayer;
extern float fReduceFactor;
extern unsigned char giCurPlayerBit;
extern int giBestShipyardDist;
extern short gaiHeroLiveChance[54];
extern int giHumanTownConquered;
extern int costTemp[7];
extern int gbPossibleShipyardFound;
extern int iCurPlaceToVisit;
extern int giBestShipyardId;
extern int gbActualBoatFound;
extern unsigned char giCurWatchPlayerBit;
extern float gfHeroInteractionBonus[54];
extern int gbBerserk;
extern int giCurAIHeroMorale;
extern int iPlacesVisited[30][2];
extern int gbTroopReload;
extern int giCurAIHeroLuck;
extern int gbActualShipyardFound;

#endif // HOMM2_ADVMGR_H
