#ifndef HOMM2_ADVMGR_H
#define HOMM2_ADVMGR_H
#include <va.h>
// Declarations of the free functions DEFINED in ADVMGR.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
class mapCell;
struct tag_message;

typedef enum AdventureScreenConstant {
    ADVMGR_SCREEN_WIDTH = 640,
    ADVMGR_SCREEN_HEIGHT = 480,
    ADVMGR_SCROLL_BORDER = 16,
    ADVMGR_VIEW_EDGE_MARGIN = 8,
    ADVMGR_RADAR_LEFT = 480,
    ADVMGR_RADAR_RIGHT = 624,
    ADVMGR_RADAR_TOP = 16,
    ADVMGR_RADAR_BOTTOM = 160,
    ADVMGR_PUZZLE_TILE_SIZE = 32,
    ADVMGR_PUZZLE_X_TRIM = 12
} AdventureScreenConstant;

typedef enum AdventureButtonConstant {
    ADVMGR_BUTTON_MESSAGE = 0x200,
    ADVMGR_BUTTON_ENABLE = 5,
    ADVMGR_BUTTON_DISABLE = 6,
    ADVMGR_BUTTON_FIRST = 1,
    ADVMGR_BUTTON_LAST = 6,
    ADVMGR_BUTTON_TARGET = 2,
    ADVMGR_BUTTON_SLOT_1 = 1,
    ADVMGR_BUTTON_SLOT_2 = 2,
    ADVMGR_BUTTON_SLOT_3 = 3,
    ADVMGR_BUTTON_SLOT_4 = 4,
    ADVMGR_BUTTON_SLOT_5 = 5,
    ADVMGR_BUTTON_SLOT_6 = 6,
    ADVMGR_BUTTON_BROADCAST_ARG = 1,
    ADVMGR_BUTTON_BROADCAST_FLAGS = 0x4008
} AdventureButtonConstant;

typedef enum AdventureTriggerConstant {
    ADVMGR_TRIGGER_TYPE_MASK = 0x7f,
    ADVMGR_SPECIAL_TRIGGER = 0x7a,
    ADVMGR_SPECIAL_TRIGGER_MASK = 0x3f,
    ADVMGR_TRIGGER_EVENT_5 = 5,
    ADVMGR_TRIGGER_EVENT_6 = 6
} AdventureTriggerConstant;

typedef enum AdventureFrameConstant {
    ADVMGR_MOBILITY_SCALE = 22,
    ADVMGR_MOBILITY_DIVISOR = 1500,
    ADVMGR_MANA_DIVISOR = 5,
    ADVMGR_MANA_MIN_VISIBLE = 3,
    ADVMGR_MOBILITY_TOP_THRESHOLD = 30,
    ADVMGR_MOBILITY_HIGH_THRESHOLD = 26,
    ADVMGR_MOBILITY_MID_THRESHOLD = 23,
    ADVMGR_MANA_TOP_THRESHOLD = 33,
    ADVMGR_MANA_HIGH_THRESHOLD = 28,
    ADVMGR_MANA_MID_THRESHOLD = 23,
    ADVMGR_FRAME_TOP = 25,
    ADVMGR_FRAME_HIGH = 24,
    ADVMGR_FRAME_MID = 23
} AdventureFrameConstant;

typedef enum AdventureStateConstant {
    ADVMGR_INVALID_CELL = -1,
    ADVMGR_INVALID_HERO = -1,
    ADVMGR_LOOPING_SOUND_LIMIT = 4,
    ADVMGR_OBJECT_ICON_COUNT = 64,
    ADVMGR_HERO_ICON_COUNT = 8,
    ADVMGR_PLAYER_COLOR_COUNT = 6,
    ADVMGR_LOOPING_SAMPLE_COUNT = 28,
    ADVMGR_CURSOR_SAMPLE_COUNT = 9,
    ADVMGR_SOUND_CELL_COUNT = 4,
    ADVMGR_CURSOR_SAMPLE_VOLUME = 64,
    ADVMGR_CURSOR_SAMPLE_CHANNEL = 2,
    ADVMGR_QUICK_VIEW_NONE = -99,
    ADVMGR_DEFAULT_POINTER_FRAME = -999,
    ADVMGR_UNUSED_OBJECT_ICON_1 = 21,
    ADVMGR_UNUSED_OBJECT_ICON_2 = 38
} AdventureStateConstant;

typedef enum AdventureOpenConstant {
    ADVMGR_SCROLL_Y = 195,
    ADVMGR_SCROLL_LEFT_X = 540,
    ADVMGR_SCROLL_RIGHT_X = 612,
    ADVMGR_SCROLL_WIDTH = 8,
    ADVMGR_SCROLL_HEIGHT = 17,
    ADVMGR_SCROLL_LEFT_FRAME = 26,
    ADVMGR_SCROLL_RIGHT_FRAME = 27,
    ADVMGR_SCROLL_HOTKEY = 16,
    ADVMGR_TIMER_DELAY = 120,
    ADVMGR_MANAGER_MESSAGE = 0x400
} AdventureOpenConstant;

typedef enum AdventureInterfaceConstant {
    ADVMGR_INTERFACE_AUTO = 0,
    ADVMGR_INTERFACE_GOOD = 1,
    ADVMGR_INTERFACE_EVIL = 2,
    ADVMGR_INTERFACE_TRANSLATION_COUNT = 37,
    ADVMGR_INTERFACE_MESSAGE = 0x200,
    ADVMGR_INTERFACE_REPLACE_RESOURCE = 0x3c
} AdventureInterfaceConstant;

typedef enum AdventureCommand {
    ADVMGR_COMMAND_NONE = -1,
    ADVMGR_COMMAND_MOVE_TO = 1,
    ADVMGR_COMMAND_HERO_VIEW = 2,
    ADVMGR_COMMAND_TOWN_VIEW = 3,
    ADVMGR_COMMAND_SELECT_HERO = 4,
    ADVMGR_COMMAND_SELECT_TOWN = 5,
    ADVMGR_COMMAND_OCCUPIED_TOWN_VIEW = 6,
    ADVMGR_COMMAND_CONTINUE_ROUTE = 7
} AdventureCommand;

typedef enum AdventureInputEvent {
    ADVMGR_INPUT_MOUSE_DOWN = 1,
    ADVMGR_INPUT_MOUSE_UP = 8,
    ADVMGR_INPUT_KEY_DOWN = 0x20,
    ADVMGR_INPUT_COMMAND = 0x200
} AdventureInputEvent;

typedef enum AdventureSearchConstant {
    ADVMGR_ARTIFACT_CAPACITY = 14,
    ADVMGR_CLEAR_GROUND_TILESET = 47,
    ADVMGR_DIG_HOLE_TILESET = 56,
    ADVMGR_DIG_HOLE_FRAME = 140,
    ADVMGR_ULTIMATE_ARTIFACT_NONE = -1,
    ADVMGR_SPHERE_OF_NEGATION = 98,
    ADVMGR_ULTIMATE_ARTIFACT_MUSIC = 41
} AdventureSearchConstant;

typedef enum AdventureDrawMask {
    ADVMGR_DRAW_GROUND = 0x01,
    ADVMGR_DRAW_OBJECT = 0x02,
    ADVMGR_DRAW_OVERLAY = 0x04,
    ADVMGR_DRAW_HERO = 0x08,
    ADVMGR_DRAW_CLOUD = 0x20,
    ADVMGR_DRAW_OVERLAY_TOP = 0x40,
    ADVMGR_DRAW_HERO_SHADOW = 0x80
} AdventureDrawMask;

typedef enum AdventureDrawConstant {
    ADVMGR_CELL_PIXELS = 32,
    ADVMGR_DRAW_CLIP_WIDTH = 480,
    ADVMGR_DRAW_CLIP_HEIGHT = 480,
    ADVMGR_CLOUD_VARIANTS = 4,
    ADVMGR_HERO_TYPE_BOAT = 6,
    ADVMGR_HERO_SHADOW_FRAME_END = 36,
    ADVMGR_MINE_GUARDIAN_ICON_SLOT = 10,
    ADVMGR_TILESET_MONSTER = 20,
    ADVMGR_TILESET_MINE = 12,
    ADVMGR_TILESET_BOAT = 39,
    ADVMGR_MONSTER_TRIGGER = 0x97,
    ADVMGR_HERO_TRIGGER = 0xaa,
    ADVMGR_BOAT_TRIGGER = 0xab
} AdventureDrawConstant;

typedef enum AdventureComboDrawConstant {
    ADVMGR_COMBO_VIEW_CELLS = 15,
    ADVMGR_COMBO_GRID_CELLS = 18,
    ADVMGR_COMBO_CLEAR_BYTES = 256,
    ADVMGR_COMBO_CLOUD_MARK = 10,
    ADVMGR_COMBO_FRAME_LIMIT = 12,
    ADVMGR_COMBO_HERO_PANEL_LEFT = 5,
    ADVMGR_COMBO_HERO_PANEL_RIGHT = 10,
    ADVMGR_COMBO_HERO_PANEL_TOP = 6,
    ADVMGR_COMBO_HERO_PANEL_BOTTOM = 9,
    ADVMGR_COMBO_UPDATE_MIN = 16,
    ADVMGR_COMBO_UPDATE_MAX = 463,
    ADVMGR_MONSTER_GHOST = 0x3b,
    ADVMGR_CURSOR_ROUTE = 6
} AdventureComboDrawConstant;

typedef enum AdventureRadarConstant {
    ADVMGR_RADAR_SIZE = 144,
    ADVMGR_RADAR_SCREEN_PITCH = 640,
    ADVMGR_RADAR_ROW_GROUPS = 5,
    ADVMGR_RADAR_GROUP_BYTES = 128,
    ADVMGR_RADAR_MAP_SMALL = 36,
    ADVMGR_RADAR_MAP_MEDIUM = 72,
    ADVMGR_RADAR_MAP_LARGE = 108,
    ADVMGR_RADAR_MAP_XLARGE = 144,
    ADVMGR_RADAR_UNSEEN_COLOR = 0x24,
    ADVMGR_RADAR_NEUTRAL_OWNER = 6,
    ADVMGR_RADAR_TERRAIN_SHADE = 3,
    ADVMGR_RADAR_PARTIAL_MARGIN = 2,
    ADVMGR_RADAR_PARTIAL_SPAN = 16,
    ADVMGR_RADAR_CURRENT_CELL = 7,
    ADVMGR_RADAR_TOWN_RADIUS = 2,
    ADVMGR_RADAR_TOWN_TRIGGER = 0x2a,
    ADVMGR_RADAR_TOWN_TILESET_1 = 0x23,
    ADVMGR_RADAR_TOWN_TILESET_2 = 0x24,
    ADVMGR_RADAR_SPECIAL_TILESET = 0x3e,
    ADVMGR_RADAR_REEFS_TRIGGER = 0x67,
    ADVMGR_RADAR_NEIGHBOR_TRIGGER = 0xa3
} AdventureRadarConstant;

typedef enum AdventureArmySizeThreshold {
    ADVMGR_ARMY_FEW_LIMIT = 5,
    ADVMGR_ARMY_SEVERAL_LIMIT = 10,
    ADVMGR_ARMY_PACK_LIMIT = 20,
    ADVMGR_ARMY_LOTS_LIMIT = 50,
    ADVMGR_ARMY_HORDE_LIMIT = 100,
    ADVMGR_ARMY_THRONG_LIMIT = 250,
    ADVMGR_ARMY_SWARM_LIMIT = 500,
    ADVMGR_ARMY_ZOUNDS_LIMIT = 1000
} AdventureArmySizeThreshold;

typedef enum AdventureCloudNeighbor {
    ADVMGR_CLOUD_NORTH = 0x01,
    ADVMGR_CLOUD_EAST = 0x02,
    ADVMGR_CLOUD_SOUTH = 0x04,
    ADVMGR_CLOUD_WEST = 0x08,
    ADVMGR_CLOUD_NORTH_EAST = 0x10,
    ADVMGR_CLOUD_SOUTH_EAST = 0x20,
    ADVMGR_CLOUD_SOUTH_WEST = 0x40,
    ADVMGR_CLOUD_NORTH_WEST = 0x80,
    ADVMGR_CLOUD_LEFT_EDGE = 0xc8,
    ADVMGR_CLOUD_RIGHT_EDGE = 0x32,
    ADVMGR_CLOUD_TOP_EDGE = 0x91,
    ADVMGR_CLOUD_BOTTOM_EDGE = 0x64
} AdventureCloudNeighbor;

typedef enum AdventureQuickInfoObject {
    ADVMGR_OBELISK_INDEX_BASE = 1,
    ADVMGR_RESOURCE_FRAME_PAIR_MASK = ~1,
    ADVMGR_OBJECT_NONE = 0,
    ADVMGR_OBJECT_FORT = 3,
    ADVMGR_OBJECT_STANDING_STONES = 7,
    ADVMGR_OBJECT_GAZEBO = 9,
    ADVMGR_OBJECT_GAZEBO_VISIT = 10,
    ADVMGR_OBJECT_MINE = 0x17,
    ADVMGR_OBJECT_MONSTER = 0x18,
    ADVMGR_OBJECT_OBELISK = 0x19,
    ADVMGR_OBJECT_MERCENARY_CAMP = 0x1a,
    ADVMGR_OBJECT_RESOURCE = 0x1b,
    ADVMGR_OBJECT_ARTIFACT = 0x29,
    ADVMGR_OBJECT_FORT_VISIT = 0x3e,
    ADVMGR_OBJECT_GUARDED = 0x40,
    ADVMGR_OBJECT_STANDING_STONE_ALT = 0x42,
    ADVMGR_OBJECT_XANADU = 0x43,
    ADVMGR_OBJECT_TREE_ALT = 0x44,
    ADVMGR_OBJECT_WITCH_DOCTOR_VISIT = 0x45,
    ADVMGR_OBJECT_WITCH_DOCTOR_ALT = 0x46,
    ADVMGR_OBJECT_MERCENARY_VISIT = 0x49,
    ADVMGR_OBJECT_EVENT_SITE = 0x54,
    ADVMGR_OBJECT_XANADU_ALT = 0x56,
    ADVMGR_OBJECT_EVENT_SITE_ALT = 0x5e,
    ADVMGR_OBJECT_REEFS = 0x67,
    ADVMGR_OBJECT_BARRIER = 0x77,
    ADVMGR_OBJECT_TENT = 0x78,
    ADVMGR_OBJECT_RECRUITMENT_SITE = 0x79,
    ADVMGR_OBJECT_GENERIC_SITE = 0x7a
} AdventureQuickInfoObject;

typedef enum AdventureVisitMask {
    ADVMGR_VISIT_FORT = 2,
    ADVMGR_VISIT_GAZEBO = 4,
    ADVMGR_VISIT_MERCENARY_CAMP = 8,
    ADVMGR_VISIT_STANDING_STONES = 0x10,
    ADVMGR_VISIT_WITCH_DOCTOR = 0x100,
    ADVMGR_VISIT_EVENT_SITE = 0x200,
    ADVMGR_VISIT_XANADU = 0x1000,
    ADVMGR_VISIT_TREE_OF_KNOWLEDGE = 0x2000,
    ADVMGR_VISIT_GENERIC_TOWER = 0x100000,
    ADVMGR_VISIT_GENERIC_SPRING = 0x200000,
    ADVMGR_VISIT_GENERIC_HUT = 0x400000,
    ADVMGR_VISIT_GENERIC_ALTAR = 0x800000
} AdventureVisitMask;

typedef enum AdventureSiteConstant {
    ADVMGR_SITE_TILESET_1 = 0x3d,
    ADVMGR_SITE_TILESET_2 = 0x3e,
    ADVMGR_SITE_TILESET_3 = 0x3f,
    ADVMGR_GENERIC_SITE_1_END = 4,
    ADVMGR_GENERIC_SITE_2_END = 0x48,
    ADVMGR_GENERIC_ALTAR_END = 5,
    ADVMGR_GENERIC_UNUSED_END = 10,
    ADVMGR_GENERIC_TOWER_END = 0x2f,
    ADVMGR_GENERIC_SPRING_END = 0x6f,
    ADVMGR_GENERIC_SITE_3_SPLIT = 0x20,
    ADVMGR_GENERIC_SITE_3_END = 0x3b,
    ADVMGR_RECRUITMENT_START = 0x48,
    ADVMGR_RECRUITMENT_1_END = 0x4e,
    ADVMGR_RECRUITMENT_2_END = 0x70,
    ADVMGR_RECRUITMENT_3_END = 0x78,
    ADVMGR_RECRUITMENT_4_END = 0x81,
    ADVMGR_RECRUITMENT_5_END = 0x89
} AdventureSiteConstant;

typedef enum AdventurePanelCommand {
    ADVMGR_PANEL_NEXT_HERO = 1,
    ADVMGR_PANEL_CONTINUE_ROUTE = 2,
    ADVMGR_PANEL_OVERVIEW = 3,
    ADVMGR_PANEL_END_TURN = 4,
    ADVMGR_PANEL_ADVENTURE_OPTIONS = 5,
    ADVMGR_PANEL_CONTROL_OPTIONS = 6,
    ADVMGR_PANEL_SYSTEM_OPTIONS = 7,
    ADVMGR_PANEL_CAST_SPELL = 8,
    ADVMGR_PANEL_HERO_PAGE_PREVIOUS = 20,
    ADVMGR_PANEL_HERO_PAGE_NEXT = 21,
    ADVMGR_PANEL_TOWN_PAGE_PREVIOUS = 23,
    ADVMGR_PANEL_TOWN_PAGE_NEXT = 24,
    ADVMGR_OVERVIEW_HERO = 1,
    ADVMGR_OVERVIEW_TOWN = 2,
    ADVMGR_DIALOG_OK = 0x7806,
    ADVMGR_BOTTOM_VIEW_FIRST_MESSAGE = 2000,
    ADVMGR_BOTTOM_VIEW_LAST_MESSAGE = 2200,
    ADVMGR_BOTTOM_VIEW_DURATION = 3000,
    ADVMGR_LOCATORS_PER_PAGE = 5,
    ADVMGR_LOCATOR_PAGE_STEP = 4
} AdventurePanelCommand;

int SaveGame(void);
int DimensionDoorHandler(struct tag_message &);
int TownPortalHandler(struct tag_message &);
void ComputeAdvNetControl(void);
int MapExtraPosAndAdjacentsSet(int, int, unsigned char);
int APanelHandler(struct tag_message &);
int CPanelHandler(struct tag_message &);
void UpdateSystemOptions(int);
int SystemOptionsHandler(struct tag_message &);
int GetMobilityFrame(int);
int GetManaFrame(int);
unsigned char StopOnTrigger(class mapCell *);


// --- globals owned by this TU (moved from _globals.h; CodeView-attributed) ---
extern int iCurHourGlassPhase;

// ---- globals (declarations, RVA order) ----
extern float fFirstWeekTownFV;
extern int iVepCacheHits;
extern int iTotalVepHits;
extern int giShowComputerRoute;
extern long glLastStartTick;
extern long glCurTicks;
extern long glTotalTicks;
extern float gfAttackHumanBonus;
extern float gfAttackComputerBonus;
extern int bSVSearchArrayInUse;
extern int bEvaluatingTravelGates;
extern int gbReduceByBerserk;
extern float fBerserkFactor;
extern int giMaxHeroesForThisPlayer;
extern float fReduceFactor;
extern unsigned char giCurPlayerBit;
extern int giBestShipyardDist;
extern short gaiHeroLiveChance[54];
extern int giHumanTownConquered;
extern int *costTemp;
extern int gbPossibleShipyardFound;
extern int iCurPlaceToVisit;
extern int giBestShipyardId;
extern int gbActualBoatFound;
extern unsigned char giCurWatchPlayerBit;
extern float gfHeroInteractionBonus[54];
extern int gbBerserk;
extern int giCurAIHeroMorale;
extern int iPlacesVisited[30][2];
extern int gbTroopReload;
extern int giCurAIHeroLuck;
extern int gbActualShipyardFound;

#endif // HOMM2_ADVMGR_H
