#ifndef HOMM2_SOURCE_ADVMANAGER_H
#define HOMM2_SOURCE_ADVMANAGER_H
// Reconstructed class (SOURCE) from CodeView NB09 of HEROES2W.EXE — NOT original source.
// 139 methods, 3 own-virtual, 0 static data.
#include "../_macros.h"
#include "../BASE/baseManager.h"
// forward declarations:
class armyGroup;
class hero;
class mapCell;
class town;
struct SAMPLE2;
struct SMapChange;
struct tag_message;

class advManager : public baseManager {
public:
    // --- constructors ---
    advManager(void);
    // --- virtual methods (vtable order) ---
    virtual int Open(int) OVERRIDE;
    virtual void Close(void) OVERRIDE;
    virtual int Main(struct tag_message &) OVERRIDE;
    // --- methods ---
    void StartCursor(int);
    void StopCursor(int);
    void DrawCursor(void);
    void DrawCursorShadow(void);
    int GetCursorBaseFrame(int);
    void TurnTo(int);
    int GetMoveShowIt(class hero *, int);
    class mapCell * MoveHero(int, int, int *, int *, int *, int, int *, int);
    void CheckAdjacentMon(int *);
    int ValidMoveWithEvent(class hero *, int);
    int ValidMove(int, int);
    void MoveOrigin(int, int);
    void ProcessMapChange(struct SMapChange);
    void ProcessIncomingSingleMapChange(struct SMapChange *);
    void ProcessIncomingGroupMapChange(char *);
    void PurgeMapChangeQueue(void);
    void UnwindMapChangeQueue(int, int);
    void ViewWorld(int, int, int);
    void VWCleanup(void);
    void VWInit(int, int);
    void VWCompleteDraw(void);
    void GetCursorSampleSet(int);
    class mapCell * DoAdvCommand(void);
    void CheckSetEvilInterface(int, int);
    void Reseed(int, int);
    int ProcessSelect(struct tag_message *, class mapCell * *);
    int ProcessDeSelect(struct tag_message *, int *, class mapCell * *);
    int ProcessSearch(int, int);
    int ProcessHover(int, int);
    void UpdateScreen(int, int);
    void CompleteDraw(int, int, int, int);
    void CompleteDraw(int);
    int GetCloudLookup(int, int);
    void DrawCell(int, int, int, int, int, int);
    class mapCell * GetCell(int, int);
    void UpdateRadar(int, int);
    void QuickInfo(int, int);
    void UpdateHeroLocator(int, int, int);
    void UpdateHeroLocators(int, int);
    void UpdateTownLocators(int, int);
    void UpdBottomView(int, int, int);
    void ClearBottomView(void);
    int UpdBottomViewEnemyTurn(void);
    int UpdBottomViewNewTurn(void);
    int UpdBottomViewResMsg(void);
    int UpdBottomViewKingdom(void);
    int UpdBottomViewHero(void);
    void HeroQuickView(int, int, int, int);
    char * GetArmySizeName(int, int);
    void TownQuickView(int, int, int, int);
    void RedrawAdvScreen(int, int);
    void DeactivateCurrTown(void);
    void DeactivateCurrHero(void);
    void MobilizeCurrHero(int);
    void DemobilizeCurrHero(void);
    void SetTownContext(int);
    void SetHeroContext(int, int);
    void DoHeroKnob(void);
    void DoTownKnob(void);
    void CastSpell(int);
    void CheckCastSpell(void);
    int ComboDraw(int, int, int);
    int ComboDraw(int);
    void SetEnvironmentOrigin(int, int, int);
    void CheckLoadSample(int);
    int GetSoundId(int, int);
    void InsertSound(int, int, int, int);
    void TeleportTo(class hero *, int, int, int, int);
    void DimensionDoor(void);
    void TownGate(int);
    void SummonBoat(void);
    void ShowRoute(int, int, int);
    void HideRoute(int, int, int);
    void CheckDimHero(void);
    void CheckDimNextHeroBut(void);
    void SeedTo(int, int);
    void ForceNewHover(void);
    void ScreenScroll(int, int);
    void CheckScreenScroll(void);
    int MouseInScrollZone(void);
    void SetInitialMapOrigin(void);
    void LoadRemote(void);
    char * CheckHandleNet(void);
    int CheckHandleNetPlayerWait(struct tag_message &, int);
    void TrimLoopingSounds(int);
    void DisableButtons(void);
    void EnableButtons(void);
    void SaveAdventureBorder(void);
    void DrawAdventureBorder(void);
    int FindAdjacentMonster(int, int, int *, int *, int, int);
    void ViewPuzzle(void);
    void PuzzleDraw(int, int, int, int);
    void AdvPanel(void);
    int ControlPanel(void);
    void SystemOptions(void);
    int DoVisions(class hero *);
    int IsCrystalBallInEffect(int, int, int);
    void DoEvent(class mapCell *, int, int);
    void EraseObj(class mapCell *, int, int);
    void HeroSwap(class hero *, class hero *);
    int BarrierEvent(class mapCell *, class hero *);
    void PasswordEvent(class mapCell *, class hero *);
    void GenericSiteEvent(class mapCell *, class hero *);
    void RecruitSiteEvent(class mapCell *, class hero *);
    void ExpansionRecruitEvent(class hero *, int, short int *);
    void JailEvent(class mapCell *, class hero *, int, int);
    void TownEvent(class mapCell *, int, int);
    void EventSound(int, int, struct SAMPLE2 *);
    void EventWindow(int, int, char *, int, int, int, int, int);
    int GiveRandomArtifact(class hero *);
    int GiveExperience(class hero *, int, int);
    void GiveResource(class hero *, int, int);
    void RecruitEvent(class hero *, int, class mapCell *);
    int SkeletonEvent(class hero *, class mapCell *, char *, int, int);
    int ZombieEvent(class hero *, class mapCell *, char *, int, int);
    int GhostEvent(class hero *, class mapCell *, char *, int, int);
    void HouseEvent(class hero *, class mapCell *);
    int CombatMonsterEvent(class hero *, int, int, class mapCell *, int, int, int, int, int, int, int, int, int, int, int);
    void TransferArtifacts(class hero *, class hero *);
    void HeroLoses(class hero *);
    void DoWhirlpool(class hero *);
    void FizzleCenter(int);
    void DoAIEvent(class mapCell *, class hero *, int, int);
    int BarrierAIEvent(class mapCell *, class hero *);
    void PasswordAIEvent(class mapCell *, class hero *);
    void GenericSiteAIEvent(class mapCell *, class hero *);
    void RecruitSiteAIEvent(class mapCell *, class hero *);
    void JailAIEvent(class mapCell *, class hero *, int, int);
    void PlayerMonsterInteract(class mapCell *, class mapCell *, class hero *, int *, int, int, int, int, int);
    void ComputerMonsterInteract(class mapCell *, class hero *, int *);
    int DoNetCombat(char *);
    int DoCombat(int, int, class hero *, class armyGroup *, class town *, class hero *, class armyGroup *, int, int, int, int);
    void SendHeroTownData(int, int, class hero *, class armyGroup *, class town *, class hero *, class armyGroup *, int, int, int, int, int, int, int);
    void ReceiveHeroTownData(char *, int *, int *, int *, class hero * *, class armyGroup * *, class town * *, class hero * *, class armyGroup * *, int *, int *, int *, signed char *, signed char *, signed char *);
    int AutoResolveCombat(int, int, class hero *, class armyGroup *, class town *, class hero *, class armyGroup *, int, int, int, int);
};
#endif // HOMM2_SOURCE_ADVMANAGER_H
