#ifndef HOMM2_ARMY_H
#define HOMM2_ARMY_H

#include <Ints.h>
#include <SOURCE/KB_TYPES.h>
// Declarations of the free functions DEFINED in ARMY.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):

HOMM2_ENUM_BEGIN(ArmyAnimationSequence)
    ARMY_ANIMATION_WALK = 6,
    ARMY_ANIMATION_STAND = 7,
    ARMY_ANIMATION_STANDING_FIRST = 8,
    ARMY_ANIMATION_STANDING_END = 13,
    ARMY_ANIMATION_DEATH = 13,
    ARMY_ANIMATION_WINCE = 14,
    ARMY_ANIMATION_WINCE_RETURN = 15,
    ARMY_ANIMATION_SHOOT_UP = 28,
    ARMY_ANIMATION_SHOOT_FORWARD = 30,
    ARMY_ANIMATION_SHOOT_DOWN = 32
HOMM2_ENUM_END(ArmyAnimationSequence)

HOMM2_ENUM_BEGIN(ArmySampleType)
    ARMY_SAMPLE_MOVE,
    ARMY_SAMPLE_ATTACK,
    ARMY_SAMPLE_WINCE,
    ARMY_SAMPLE_SHOT,
    ARMY_SAMPLE_KILL,
    ARMY_SAMPLE_EXTRA_ONE,
    ARMY_SAMPLE_EXTRA_TWO,
    ARMY_SAMPLE_COUNT
HOMM2_ENUM_END(ArmySampleType)

HOMM2_ENUM_VALUES_BEGIN(ArmyCombatConstant)
    ARMY_SAMPLE_VOLUME = 64,
    ARMY_SAMPLE_CHANNEL = 3,
    ARMY_PRIMARY_SAMPLE_COUNT = ARMY_SAMPLE_KILL + 1,
    ARMY_QUANTITY_TEXT_SIZE = 12,
    ARMY_SPELL_INFLUENCE_COUNT = 15,
    ARMY_SPELL_EFFECT_ANIMATION_DURATION = 275,
    ARMY_HEX_COLUMNS = 13,
    ARMY_COMBAT_WIDTH = 640,
    ARMY_COMBAT_HEIGHT = 443,
    ARMY_PROJECTILE_CLIP_HEIGHT = 480,
    ARMY_COMBAT_MAX_X = ARMY_COMBAT_WIDTH - 1,
    ARMY_COMBAT_MAX_Y = ARMY_COMBAT_HEIGHT - 1,
    ARMY_COMBAT_FRAME_DELAY = 75,
    ARMY_MAGE_BOLT_DELAY = 115,
    ARMY_POW_EFFECT_DELAY = 120,
    ARMY_LICH_EXPLOSION_EFFECT = 20,
    ARMY_ARCHMAGE_DISPEL_CHANCE = 20,
    ARMY_PERCENT_MAX = 100
HOMM2_ENUM_VALUES_END(ArmyCombatConstant)

HOMM2_ENUM_BEGIN(ArmySpellInfluence)
    ARMY_SPELL_INFLUENCE_HASTE = 0,
    ARMY_SPELL_INFLUENCE_SLOW = 1,
    ARMY_SPELL_INFLUENCE_BLIND = 2,
    ARMY_SPELL_INFLUENCE_BLESS = 3,
    ARMY_SPELL_INFLUENCE_CURSE = 4,
    ARMY_SPELL_INFLUENCE_BERSERK = 5,
    ARMY_SPELL_INFLUENCE_PARALYZE = 6,
    ARMY_SPELL_INFLUENCE_HYPNOTIZE = 7,
    ARMY_SPELL_INFLUENCE_DRAGON_SLAYER = 8,
    ARMY_SPELL_INFLUENCE_BLOODLUST = 9,
    ARMY_SPELL_INFLUENCE_SHIELD = 10,
    ARMY_SPELL_INFLUENCE_PETRIFIED = 11,
    ARMY_SPELL_INFLUENCE_ANTI_MAGIC = 12,
    ARMY_SPELL_INFLUENCE_STONESKIN = 13,
    ARMY_SPELL_INFLUENCE_STEELSKIN = 14
HOMM2_ENUM_END(ArmySpellInfluence)

HOMM2_ENUM_BEGIN(ArmySpellCancelType)
    ARMY_CANCEL_SPELLS_AFTER_MOVE = 0,
    ARMY_CANCEL_SPELLS_AFTER_ATTACK = 1,
    ARMY_CANCEL_SPELLS_AFTER_DAMAGE = 2,
    ARMY_CANCEL_SPELLS_UNUSED = 3
HOMM2_ENUM_END(ArmySpellCancelType)

HOMM2_ENUM_VALUES_BEGIN(ArmyAttackConstant)
    ARMY_COMBAT_TEXT_SIZE = 200,
    ARMY_COMBAT_SIDE_COUNT = 2,
    ARMY_COMBAT_DIRECTION_COUNT = 8,
    ARMY_ADJACENT_DIRECTION_COUNT = 6,
    ARMY_MOAT_CELL_COUNT = 9,
    ARMY_MOAT_GATE_INDEX = 4,
    ARMY_LUCK_ROLL_MAX = 24,
    ARMY_ATTACK_EFFECT_CHANCE = 20,
    ARMY_ROYAL_MUMMY_EFFECT_CHANCE = 30,
    ARMY_ATTACK_DELAY_SHORT = 16,
    ARMY_ATTACK_DELAY_NORMAL = 20,
    ARMY_ATTACK_DELAY_LONG = 24,
    ARMY_BREATH_ATTACK_DELAY_BONUS = 2,
    ARMY_ALL_ATTACK_DIRECTIONS = 0xFF,
    ARMY_NEAREST_DISTANCE_LIMIT = 999999,
    ARMY_DAMAGE_PENALTY_HALF = 2,
    ARMY_RETALIATION_DELAY = 150,
    ARMY_SECOND_ATTACK_DELAY = 100,
    ARMY_BAD_LUCK_EFFECT = 10,
    ARMY_BAD_LUCK_EFFECT_DELAY = 180,
    ARMY_ASCII_CASE_OFFSET = 32,
    ARMY_DAMAGE_STAT_LIMIT = 20,
    ARMY_MOAT_ATTACK_BONUS = 3,
    ARMY_DRAGON_SLAYER_BONUS = 5,
    ARMY_GENIE_HALF_ROLL_MAX = 5,
    ARMY_GENIE_HALF_ROLL = 2,
    ARMY_PATH_BLOCKED = 3
HOMM2_ENUM_VALUES_END(ArmyAttackConstant)

HOMM2_ENUM_BEGIN(ArmyCombatDirection)
    ARMY_DIRECTION_LEFT = 1,
    ARMY_DIRECTION_RIGHT = 4
HOMM2_ENUM_END(ArmyCombatDirection)

HOMM2_ENUM_VALUES_BEGIN(ArmyFlightConstant)
    ARMY_ALL_ADJACENT_DIRECTIONS = 0x3f,
    ARMY_FLIGHT_SOUND_FRAME = 1,
    ARMY_VAMPIRE_FLIGHT_SOUND_DELAY = 100
HOMM2_ENUM_VALUES_END(ArmyFlightConstant)

#define ARMY_VAMPIRE_FLIGHT_DURATION_SCALE 1.3

HOMM2_ENUM_VALUES_BEGIN(ArmySpellStatConstant)
    ARMY_HASTE_SPEED_BONUS = 2,
    ARMY_BLOODLUST_ATTACK_BONUS = 3,
    ARMY_STONESKIN_DEFENSE_BONUS = 3,
    ARMY_STEELSKIN_DEFENSE_BONUS = 5
HOMM2_ENUM_VALUES_END(ArmySpellStatConstant)

#define ARMY_HASTE_WALK_DURATION_SCALE 0.65
#define ARMY_SLOW_WALK_DURATION_SCALE 1.5

#define ARMY_PROJECTILE_PI 3.14159
#define ARMY_SHOOT_UP_MIN_ANGLE 25.0f
#define ARMY_SHOOT_FORWARD_MIN_ANGLE -25.0f

HOMM2_ENUM_VALUES_BEGIN(ArmyDeathConstant)
    ARMY_CORPSE_LIMIT = 14,
    ARMY_DEATH_RANDOM_MAX = 100,
    ARMY_DEATH_PRIMARY_CHANCE = 60,
    ARMY_DEATH_SECONDARY_CHANCE = 80
HOMM2_ENUM_VALUES_END(ArmyDeathConstant)

HOMM2_ENUM_VALUES_BEGIN(ArmySpellEffectConstant)
    ARMY_NO_EFFECT = -1,
    ARMY_EFFECT_MINIMUM_Y = 999,
    ARMY_DELAYED_MEDUSA_EFFECT = 101
HOMM2_ENUM_VALUES_END(ArmySpellEffectConstant)

HOMM2_ENUM_VALUES_BEGIN(ArmyFrameConstant)
    ARMY_MISSILE_OFFSET_COUNT = 3,
    ARMY_PROJECTILE_ANGLE_COUNT = 12,
    ARMY_ANIMATION_SEQUENCE_COUNT = 34,
    ARMY_ANIMATION_FRAME_COUNT = 16
HOMM2_ENUM_VALUES_END(ArmyFrameConstant)

HOMM2_ENUM_BEGIN(ArmyWalkSegment)
    ARMY_WALK_SEGMENT_BEGIN = 0,
    ARMY_WALK_SEGMENT_BEGIN_STANDING = 1,
    ARMY_WALK_SEGMENT_MIDDLE = 2,
    ARMY_WALK_SEGMENT_END = 3,
    ARMY_WALK_SEGMENT_END_STANDING = 4,
    ARMY_WALK_SEGMENT_STAND = 5,
    ARMY_WALK_SEGMENT_COUNT = 6
HOMM2_ENUM_END(ArmyWalkSegment)

HOMM2_ENUM_VALUES_BEGIN(ArmySpellChanceConstant)
    ARMY_RANDOM_SPELL_ROLL_MAX = 99,
    ARMY_RESURRECT_POWER_PER_SPELL_POWER = 50,
    ARMY_HYPNOTIZE_HIT_POINTS_PER_POWER = 25,
    ARMY_ARTIFACT_POWER_MULTIPLIER = 2,
    ARMY_CURE_HIT_POINTS_PER_POWER = 5,
    ARMY_WIDE_CREATURE_HALF_WIDTH = 22,
    ARMY_CONTROL_EFFECT_Y_OFFSET = 5
HOMM2_ENUM_VALUES_END(ArmySpellChanceConstant)

#define ARMY_SPELL_CHANCE_NONE 0.0f
#define ARMY_SPELL_CHANCE_DWARF 0.75f
#define ARMY_SPELL_CHANCE_ALWAYS 1.0f
#define ARMY_SPELL_CHANCE_PERCENT 100.0f

#define ARMY_RANGER_ATTACK_DURATION_SCALE 0.78
#define ARMY_DURATION_BASE_SCALE 1.0
#define ARMY_ATTACK_DURATION_SPEED_SCALE 0.08
#define ARMY_WALK_DURATION_SPEED_SCALE 0.12

#pragma pack(push, 1)
struct SMonFrameInfo {
    struct MissileOffset {
        i16 x;
        i16 y;
    };
    char unknown00;
    i16 spellEffectX;                                                               // +0x01
    i16 spellEffectY;                                                               // +0x03
    i8 animationXOffsets[IDX(ARMY_WALK_SEGMENT_COUNT)][ARMY_ANIMATION_FRAME_COUNT]; // +0x05
    i8 walkXOffsets[ARMY_ANIMATION_FRAME_COUNT];                                    // +0x65
    i8 standingAnimationCount;                                                      // +0x75
    float standingAnimationChances[10];                                             // +0x76
    i32 standStillDelay;                                                            // +0x9e
    i32 walkDuration;                                                               // +0xa2
    i32 attackDuration;                                                             // +0xa6
    i32 flightSpeed;                                                                // +0xaa
    struct MissileOffset missileOffsets[ARMY_MISSILE_OFFSET_COUNT];                 // +0xae
    u8 projectileDirectionCount;                                                    // +0xba
    float projectileAngles[ARMY_PROJECTILE_ANGLE_COUNT];                            // +0xbb
    i32 quantityX[2];                                                               // +0xeb
    i8 animationFrameCount[ARMY_ANIMATION_SEQUENCE_COUNT];                          // +0xf3
    i8 animationFrames[ARMY_ANIMATION_SEQUENCE_COUNT][ARMY_ANIMATION_FRAME_COUNT];  // +0x115
};
SIZE(SMonFrameInfo, 0x335);
#pragma pack(pop)
extern SMonFrameInfo sViewArmyMonFrameInfo;

void BuildTempWalkSeq(struct SMonFrameInfo*, i32, i32);
void ModifyFrameInfo(struct SMonFrameInfo*, CreatureType);

#endif // HOMM2_ARMY_H
