#ifndef HOMM2_CAMPAIGN_H
#define HOMM2_CAMPAIGN_H

#include <Ints.h>
#include <SOURCE/KB.h>

struct tag_message;

H2_ENUM_CLASS_BEGIN(CampaignAward)
    CAMPAIGN_AWARD_DWARVEN_ALLIANCE           = 0,
    CAMPAIGN_AWARD_SORCERESS_GUILD            = 1,
    CAMPAIGN_AWARD_ROLAND_STRENGTHENED        = 2,
    CAMPAIGN_AWARD_ROLAND_CARRYOVER_FORCES    = 3,
    CAMPAIGN_AWARD_CORLAGON_DEFEATED          = 4,
    CAMPAIGN_AWARD_ROLAND_ULTIMATE_CROWN      = 5,
    CAMPAIGN_AWARD_NECROMANCER_GUILD          = 6,
    CAMPAIGN_AWARD_DWARFBANE                  = 7,
    CAMPAIGN_AWARD_OGRE_ALLIANCE              = 8,
    CAMPAIGN_AWARD_DRAGON_ALLIANCE            = 9,
    CAMPAIGN_AWARD_ARCHIBALD_ULTIMATE_CROWN   = 10,
    CAMPAIGN_AWARD_ARCHIBALD_CARRYOVER_FORCES = 11
H2_ENUM_CLASS_END(CampaignAward)

H2_ENUM_BEGIN(CampaignMessageConstant)
    CAMPAIGN_CLOSE_COMMAND               = 10,
    CAMPAIGN_HANDLER_CLOSE               = 2,
    CAMPAIGN_HANDLER_CONTINUE            = 1,
    CAMPAIGN_DIALOG_CANCEL               = 0x7801,
    CAMPAIGN_DIALOG_ACCEPT               = 0x7802,
    CAMPAIGN_DIALOG_RESTART              = 0x385,
    CAMPAIGN_DIALOG_REPLAY               = 0x386,
    CAMPAIGN_TRACK_WIDGET_0              = 0x352,
    CAMPAIGN_TRACK_WIDGET_1              = 0x353,
    CAMPAIGN_TRACK_WIDGET_2              = 0x354,
    CAMPAIGN_TRACK_WIDGET_3              = 0x355,
    CAMPAIGN_TRACK_WIDGET_4              = 0x356,
    CAMPAIGN_TRACK_WIDGET_5              = 0x357,
    CAMPAIGN_TRACK_WIDGET_6              = 0x358,
    CAMPAIGN_TRACK_WIDGET_7              = 0x359,
    CAMPAIGN_TRACK_WIDGET_8              = 0x35a,
    CAMPAIGN_TRACK_WIDGET_9              = 0x35b,
    CAMPAIGN_TRACK_WIDGET_10             = 0x35c,
    CAMPAIGN_TRACK_WIDGET_11             = 0x35d,
    CAMPAIGN_TRACK_WIDGET_FIRST          = CAMPAIGN_TRACK_WIDGET_0,
    CAMPAIGN_TRACK_WIDGET_LAST           = CAMPAIGN_TRACK_WIDGET_11,
    CAMPAIGN_BONUS_WIDGET_0              = 0x32a,
    CAMPAIGN_BONUS_WIDGET_1              = 0x32b,
    CAMPAIGN_BONUS_WIDGET_2              = 0x32c,
    CAMPAIGN_BONUS_WIDGET_FIRST          = CAMPAIGN_BONUS_WIDGET_0,
    CAMPAIGN_BONUS_WIDGET_LAST           = CAMPAIGN_BONUS_WIDGET_2,
    CAMPAIGN_TRACK_ICON_WIDGET           = 0x329,
    CAMPAIGN_SCENARIO_NUMBER_WIDGET      = 0x321,
    CAMPAIGN_SCENARIO_NAME_WIDGET        = 0x322,
    CAMPAIGN_SCENARIO_DESCRIPTION_WIDGET = 0x323,
    CAMPAIGN_SCENARIO_BONUS_WIDGET       = 0x324,
    CAMPAIGN_AWARDS_WIDGET               = 0x325,
    CAMPAIGN_BONUS_TEXT_WIDGET_FIRST     = 0x326,
    CAMPAIGN_WIDGET_ENABLE_FRAME         = 8,
    CAMPAIGN_WIDGET_DISABLE_FRAME        = 9,
    CAMPAIGN_WIDGET_REFRESH_FRAME        = 4
H2_ENUM_END(CampaignMessageConstant)

H2_ENUM_BEGIN(CampaignDisplayConstant)
    CAMPAIGN_TRACK_ICON_SIZE       = 41,
    CAMPAIGN_TRACK_ICON_OFFSET     = 2,
    CAMPAIGN_TRACK_ICON_FRAME      = 10,
    CAMPAIGN_TRACK_ICON_COLOR      = 0x10,
    CAMPAIGN_TRACK_FRAME_COMPLETE  = 11,
    CAMPAIGN_TRACK_FRAME_AVAILABLE = 10,
    CAMPAIGN_TRACK_FRAME_LOCKED    = 12,
    CAMPAIGN_RESTART_CONFIRM       = 2,
    CAMPAIGN_DIALOG_NO_RESOURCE    = -1,
    CAMPAIGN_DIALOG_FADE_STEPS     = 8,
    CAMPAIGN_GOOD_MUSIC            = 24,
    CAMPAIGN_EVIL_MUSIC            = 22
H2_ENUM_END(CampaignDisplayConstant)

H2_ENUM_CLASS_BEGIN(CampaignHeroPortrait)
    CAMPAIGN_HERO_ROLAND    = 54,
    CAMPAIGN_HERO_CORLAGON  = 55,
    CAMPAIGN_HERO_ARCHIBALD = 57,
    CAMPAIGN_HERO_HALTON    = 58
H2_ENUM_CLASS_END(CampaignHeroPortrait)

i32 CampaignHandler(struct tag_message&);

#endif
