#ifndef HOMM2_CAMPAIGN_H
#define HOMM2_CAMPAIGN_H
// Declarations of the free functions DEFINED in Campaign.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

typedef enum CampaignSide {
    CAMPAIGN_ROLAND = 0,
    CAMPAIGN_ARCHIBALD = 1,
    CAMPAIGN_SIDE_COUNT = 2
} CampaignSide;

typedef enum CampaignChoiceType {
    CAMPAIGN_CHOICE_RESOURCE = 0,
    CAMPAIGN_CHOICE_ARTIFACT = 1,
    CAMPAIGN_CHOICE_SPELL = 2,
    CAMPAIGN_CHOICE_SECONDARY_SKILL = 3,
    CAMPAIGN_CHOICE_CREATURES = 4,
    CAMPAIGN_CHOICE_PUZZLE_PIECES = 5,
    CAMPAIGN_CHOICE_EXPERIENCE = 6,
    CAMPAIGN_CHOICE_NONE = 7,
    CAMPAIGN_CHOICE_ALIGNMENT = 8
} CampaignChoiceType;

typedef enum CampaignConstant {
    CAMPAIGN_MAP_COUNT = 12,
    CAMPAIGN_REGULAR_MAP_COUNT = 11,
    CAMPAIGN_TRACK_POINT_COUNT = 13,
    CAMPAIGN_BONUS_CHOICE_COUNT = 3,
    CAMPAIGN_AWARD_COUNT = 12,
    CAMPAIGN_SWITCHING_MAP = 11,
    CAMPAIGN_SWITCHING_SCENARIO = 4,
    CAMPAIGN_NO_SCENARIO = -1,
    CAMPAIGN_ROLAND_FINAL_SCENARIO = 9,
    CAMPAIGN_ARCHIBALD_FINAL_SCENARIO = 10,
    CAMPAIGN_STATE_RESET_SIZE = 0x147,
    CAMPAIGN_SETUP_RESET_SIZE = 0x41,
    CAMPAIGN_ARMY_NAME_BUFFER_SIZE = 52,
    CAMPAIGN_ARMY_SLOT_COUNT = 5,
    CAMPAIGN_CARRYOVER_PLAYER = 3,
    CAMPAIGN_TRIPLE_ARMY_MULTIPLIER = 3,
    CAMPAIGN_EASY_SCENARIO_LIMIT = 2,
    CAMPAIGN_NORMAL_SCENARIO_LIMIT = 5,
    CAMPAIGN_HERO_COUNT = 54,
    CAMPAIGN_HERO_PRIORITY_HIGH = 100,
    CAMPAIGN_HERO_PRIORITY_NORMAL = 90,
    CAMPAIGN_EXPERIENCE_BONUS = 5000,
    CAMPAIGN_SUMMON_EARTH_SPELL = 43,
    CAMPAIGN_SWITCH_VICTORY_VALUE = 99,
    CAMPAIGN_ROLAND_TIME_LIMIT = 90
} CampaignConstant;

typedef enum CampaignAward {
    CAMPAIGN_AWARD_DWARF_ALLIANCE = 0,
    CAMPAIGN_AWARD_BATTLE_GARB = 1,
    CAMPAIGN_AWARD_TRIPLE_ARMY = 2,
    CAMPAIGN_AWARD_CARRYOVER_ARMY = 3,
    CAMPAIGN_AWARD_DEFEAT_CORLAGON = 4,
    CAMPAIGN_AWARD_DRAGON_SLAYER = 5,
    CAMPAIGN_AWARD_DWARFBANE = 6,
    CAMPAIGN_AWARD_OGRE_ALLIANCE = 7,
    CAMPAIGN_AWARD_DRAGON_ALLIANCE = 8,
    CAMPAIGN_AWARD_DEFEAT_ARCHIBALD = 9,
    CAMPAIGN_AWARD_ULTIMATE_CROWN = 10,
    CAMPAIGN_AWARD_ULTIMATE_CROWN_ALT = 11
} CampaignAward;

typedef enum CampaignScenarioArmyCount {
    CAMPAIGN_BARBARIAN_ORC_CHIEF_COUNT = 12,
    CAMPAIGN_BARBARIAN_OGRE_COUNT = 18,
    CAMPAIGN_BARBARIAN_GOBLIN_COUNT = 40,
    CAMPAIGN_WARLOCK_CENTAUR_COUNT = 40,
    CAMPAIGN_WARLOCK_GARGOYLE_COUNT = 24,
    CAMPAIGN_WARLOCK_GRIFFIN_COUNT = 18,
    CAMPAIGN_NECROMANCER_SKELETON_COUNT = 50,
    CAMPAIGN_NECROMANCER_MUMMY_COUNT = 18,
    CAMPAIGN_NECROMANCER_VAMPIRE_COUNT = 8
} CampaignScenarioArmyCount;

typedef enum CampaignMessageConstant {
    CAMPAIGN_MESSAGE_WIDGET = 0x200,
    CAMPAIGN_MESSAGE_SET_TEXT = 3,
    CAMPAIGN_MESSAGE_SET_FRAME = 4,
    CAMPAIGN_MESSAGE_SELECT = 5,
    CAMPAIGN_MESSAGE_DESELECT = 6,
    CAMPAIGN_MESSAGE_SET_ICON = 9,
    CAMPAIGN_MESSAGE_HOVER = 12,
    CAMPAIGN_MESSAGE_ACTIVATE = 13,
    CAMPAIGN_MESSAGE_HELP = 14,
    CAMPAIGN_CLOSE_COMMAND = 10,
    CAMPAIGN_HANDLER_CLOSE = 2,
    CAMPAIGN_HANDLER_CONTINUE = 1,
    CAMPAIGN_DIALOG_CANCEL = 0x7801,
    CAMPAIGN_DIALOG_ACCEPT = 0x7802,
    CAMPAIGN_DIALOG_RESTART = 0x385,
    CAMPAIGN_DIALOG_REPLAY = 0x386,
    CAMPAIGN_TRACK_WIDGET_FIRST = 0x352,
    CAMPAIGN_TRACK_WIDGET_LAST = 0x35d,
    CAMPAIGN_BONUS_WIDGET_FIRST = 0x32a,
    CAMPAIGN_BONUS_WIDGET_LAST = 0x32c,
    CAMPAIGN_TRACK_ICON_WIDGET = 0x329,
    CAMPAIGN_SCENARIO_NUMBER_WIDGET = 0x321,
    CAMPAIGN_SCENARIO_NAME_WIDGET = 0x322,
    CAMPAIGN_SCENARIO_DESCRIPTION_WIDGET = 0x323,
    CAMPAIGN_SCENARIO_BONUS_WIDGET = 0x324,
    CAMPAIGN_AWARDS_WIDGET = 0x325,
    CAMPAIGN_BONUS_TEXT_WIDGET_FIRST = 0x326,
    CAMPAIGN_WIDGET_ENABLE_FRAME = 8,
    CAMPAIGN_WIDGET_DISABLE_FRAME = 9,
    CAMPAIGN_WIDGET_REFRESH_FRAME = 4
} CampaignMessageConstant;

typedef enum CampaignDisplayConstant {
    CAMPAIGN_TRACK_ICON_SIZE = 41,
    CAMPAIGN_TRACK_ICON_OFFSET = 2,
    CAMPAIGN_TRACK_ICON_FRAME = 10,
    CAMPAIGN_TRACK_ICON_COLOR = 0x10,
    CAMPAIGN_TRACK_FRAME_COMPLETE = 11,
    CAMPAIGN_TRACK_FRAME_AVAILABLE = 10,
    CAMPAIGN_TRACK_FRAME_LOCKED = 12,
    CAMPAIGN_RESTART_CONFIRM = 2,
    CAMPAIGN_DIALOG_NO_RESOURCE = -1,
    CAMPAIGN_DIALOG_FADE_STEPS = 8,
    CAMPAIGN_POINTER_HIDDEN_HOTSPOT = -999,
    CAMPAIGN_GOOD_MUSIC = 24,
    CAMPAIGN_EVIL_MUSIC = 22
} CampaignDisplayConstant;

typedef enum CampaignSmacker {
    CAMPAIGN_SMACKER_ROLAND_INTRO = 5,
    CAMPAIGN_SMACKER_ROLAND_1 = 6,
    CAMPAIGN_SMACKER_ROLAND_2 = 7,
    CAMPAIGN_SMACKER_ROLAND_3A = 8,
    CAMPAIGN_SMACKER_ROLAND_3B = 9,
    CAMPAIGN_SMACKER_ROLAND_4 = 10,
    CAMPAIGN_SMACKER_ROLAND_5A = 11,
    CAMPAIGN_SMACKER_ROLAND_5B = 12,
    CAMPAIGN_SMACKER_ROLAND_6 = 13,
    CAMPAIGN_SMACKER_ROLAND_7 = 14,
    CAMPAIGN_SMACKER_ROLAND_8 = 15,
    CAMPAIGN_SMACKER_ROLAND_9 = 16,
    CAMPAIGN_SMACKER_ARCHIBALD_INTRO = 19,
    CAMPAIGN_SMACKER_ARCHIBALD_1 = 20,
    CAMPAIGN_SMACKER_ARCHIBALD_2 = 21,
    CAMPAIGN_SMACKER_ARCHIBALD_3 = 22,
    CAMPAIGN_SMACKER_ARCHIBALD_4A = 23,
    CAMPAIGN_SMACKER_ARCHIBALD_4B = 24,
    CAMPAIGN_SMACKER_ARCHIBALD_4_END = 25,
    CAMPAIGN_SMACKER_ARCHIBALD_5A = 26,
    CAMPAIGN_SMACKER_ARCHIBALD_5B = 27,
    CAMPAIGN_SMACKER_ARCHIBALD_6 = 28,
    CAMPAIGN_SMACKER_ARCHIBALD_7A = 29,
    CAMPAIGN_SMACKER_ARCHIBALD_7B = 30,
    CAMPAIGN_SMACKER_ARCHIBALD_8 = 31,
    CAMPAIGN_SMACKER_ARCHIBALD_9 = 32,
    CAMPAIGN_SMACKER_ARCHIBALD_10 = 33,
    CAMPAIGN_SMACKER_ARCHIBALD_END = 34
} CampaignSmacker;

typedef enum CampaignHeroPortrait {
    CAMPAIGN_HERO_ROLAND = 54,
    CAMPAIGN_HERO_CORLAGON = 55,
    CAMPAIGN_HERO_ARCHIBALD = 57,
    CAMPAIGN_HERO_HALTON = 58
} CampaignHeroPortrait;

typedef enum CampaignMapDifficulty {
    CAMPAIGN_DIFFICULTY_EASY = 0,
    CAMPAIGN_DIFFICULTY_NORMAL = 1,
    CAMPAIGN_DIFFICULTY_HARD = 2
} CampaignMapDifficulty;

#pragma pack(push, 1)
struct SCampaignChoice {
    unsigned char type;
    short value;
    short amount;
};
#pragma pack(pop)
SIZE(SCampaignChoice, 5);

extern struct SCampaignChoice campaignChoices[CAMPAIGN_SIDE_COUNT]
                                              [CAMPAIGN_MAP_COUNT]
                                              [CAMPAIGN_BONUS_CHOICE_COUNT];

int CampaignHandler(struct tag_message &);

#endif // HOMM2_CAMPAIGN_H
