#ifndef HOMM2_CASTLE_H
#define HOMM2_CASTLE_H

#include <Ints.h>
// Declarations of the free functions DEFINED in Castle.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
class heroWindow;
struct tag_message;

typedef enum CastleBuildingConstant {
    CASTLE_SLOT_COUNT = 18,
    CASTLE_UPGRADE_OFFSET = 5
} CastleBuildingConstant;

typedef enum CastleControl {
    CASTLE_CONTROL_BUILDING_OVERLAY_FIRST = 400,
    CASTLE_CONTROL_STATUS_FIRST = 500,
    CASTLE_CONTROL_BUILDING_NAME_FIRST = 600,
    CASTLE_CONTROL_BUILDING_ICON_FIRST = 700,
    CASTLE_CONTROL_BUILDING_BUTTON_FIRST = 800,
    CASTLE_CONTROL_HERO_FIRST = 900,
    CASTLE_CONTROL_RECRUIT_FIRST = 902,
    CASTLE_CONTROL_CAPTAIN_ICON = 1100,
    CASTLE_CONTROL_CAPTAIN_OVERLAY = 1101,
    CASTLE_CONTROL_CAPTAIN_BUTTON = 1102,
    CASTLE_CONTROL_CAPTAIN_STATS = 1104,
    CASTLE_CONTROL_CAPTAIN_VALUES = 1105,
    CASTLE_CONTROL_CAPTAIN_FLAG = 1106,
    CASTLE_CONTROL_CAPTAIN_FORMATION_SPREAD_INACTIVE = 213,
    CASTLE_CONTROL_CAPTAIN_FORMATION_SPREAD = 214,
    CASTLE_CONTROL_CAPTAIN_FORMATION_GROUPED_INACTIVE = 215,
    CASTLE_CONTROL_CAPTAIN_FORMATION_GROUPED = 216,
    CASTLE_CONTROL_STATUS_TEXT = 502,
    CASTLE_CONTROL_CLOSE = 0x7800
} CastleControl;

typedef enum CastleWidgetCommand {
    CASTLE_WIDGET_TEXT = 3,
    CASTLE_WIDGET_FRAME = 4,
    CASTLE_WIDGET_ENABLE = 5,
    CASTLE_WIDGET_DISABLE = 6,
    CASTLE_WIDGET_ICON_FILE = 9
} CastleWidgetCommand;

typedef enum CastleWidgetFrame {
    CASTLE_FRAME_AVAILABLE = 1,
    CASTLE_FRAME_UNAVAILABLE = 2,
    CASTLE_FRAME_BUILT = 11,
    CASTLE_FRAME_CANNOT_BUILD = 12,
    CASTLE_FRAME_CANNOT_AFFORD = 13
} CastleWidgetFrame;

typedef enum CastleInfoText {
    CASTLE_INFO_ALREADY_BUILT = 4,
    CASTLE_INFO_CANNOT_BUILD = 5,
    CASTLE_INFO_CANNOT_AFFORD = 6,
    CASTLE_INFO_BUILD = 7,
    CASTLE_INFO_CANNOT_AFFORD_HERO = 8,
    CASTLE_INFO_TOO_MANY_HEROES = 9,
    CASTLE_INFO_TOWN_OCCUPIED = 10,
    CASTLE_INFO_RECRUIT_HERO = 11,
    CASTLE_INFO_EXIT = 12,
    CASTLE_INFO_OPTIONS = 13,
    CASTLE_INFO_GROUPED_FORMATION = 14,
    CASTLE_INFO_SPREAD_FORMATION = 15
} CastleInfoText;

typedef enum CastleConstant {
    CASTLE_QUICK_VIEW_MODIFIER = 2,
    CASTLE_EXIT_COMMAND = 10,
    CASTLE_MAGE_GUILD = 0,
    CASTLE_CAPTAIN = 15,
    CASTLE_MAGE_GUILD_MAX_LEVEL = 5,
    CASTLE_CAPTAIN_BUILDING_MASK = 0x8000,
    CASTLE_HERO_COUNT_LIMIT = 8,
    CASTLE_PRIMARY_STAT_COUNT = 4,
    CASTLE_INTERFACE_X = 18,
    CASTLE_INTERFACE_Y = 463,
    CASTLE_INTERFACE_WIDTH = 604,
    CASTLE_INTERFACE_HEIGHT = 16,
    CASTLE_BACKGROUND_LEFT = 458,
    CASTLE_BACKGROUND_TOP = 0,
    CASTLE_TERRAIN_ICON_COLUMNS = 5,
    CASTLE_TERRAIN_ICON_FRAMES = 2,
    CASTLE_RACE_ICON_FRAMES = 32
} CastleConstant;

i32 CastleHandler(struct tag_message&);

extern u8 castleSlotsBase[CASTLE_SLOT_COUNT];
extern class heroWindow* casWin;
extern u8 castleSlotsUse[CASTLE_SLOT_COUNT];

#endif // HOMM2_CASTLE_H
