#ifndef HOMM2_CMBTMGR_H
#define HOMM2_CMBTMGR_H

#include <Ints.h>
// Declarations of the free functions DEFINED in CMBTMGR.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

struct CombatTowerOrigin {
    u16 x;
    u16 y;
};

typedef enum CombatSystemOptionWidget {
    COMBAT_SYSTEM_OPTION_SPEED_BUTTON = 10,
    COMBAT_SYSTEM_OPTION_ARMY_INFO_BUTTON = 11,
    COMBAT_SYSTEM_OPTION_AUTO_SPELL_BUTTON = 12,
    COMBAT_SYSTEM_OPTION_GRID_BUTTON = 13,
    COMBAT_SYSTEM_OPTION_SHADE_BUTTON = 14,
    COMBAT_SYSTEM_OPTION_MOUSE_HEX_BUTTON = 15,
    COMBAT_SYSTEM_OPTION_SPEED_TEXT = 20,
    COMBAT_SYSTEM_OPTION_ARMY_INFO_TEXT = 21,
    COMBAT_SYSTEM_OPTION_AUTO_SPELL_TEXT = 22,
    COMBAT_SYSTEM_OPTION_GRID_TEXT = 23,
    COMBAT_SYSTEM_OPTION_SHADE_TEXT = 24,
    COMBAT_SYSTEM_OPTION_MOUSE_HEX_TEXT = 25,
    COMBAT_SYSTEM_OPTION_CLOSE_BUTTON = 0x7800
} CombatSystemOptionWidget;

enum {
    COMBAT_SYSTEM_OPTION_EVENT = 0x200,
    COMBAT_SYSTEM_OPTION_TEXT_MESSAGE = 3,
    COMBAT_SYSTEM_OPTION_BUTTON_MESSAGE = 4,
    COMBAT_SYSTEM_OPTION_BUTTON_EVENT = 12,
    COMBAT_SYSTEM_OPTION_CLOSE_EVENT = 13,
    COMBAT_SYSTEM_OPTION_HOVER_EVENT = 14,
    COMBAT_SYSTEM_OPTION_RIGHT_BUTTON = 0x200,
    COMBAT_SYSTEM_OPTION_CYCLE_COUNT = 3,
    COMBAT_SYSTEM_OPTION_HELP_DIALOG = 4,
    COMBAT_SYSTEM_OPTION_HANDLER_CONTINUE = 1,
    COMBAT_SYSTEM_OPTION_HANDLER_CLOSE = 2,
    COMBAT_SYSTEM_OPTION_STATE_OFFSET_STEP = 2,
    COMBAT_SYSTEM_OPTION_SPEED_STATE_OFFSET = 0,
    COMBAT_SYSTEM_OPTION_ARMY_INFO_STATE_OFFSET = 3,
    COMBAT_SYSTEM_OPTION_AUTO_SPELL_STATE_OFFSET = 6,
    COMBAT_SYSTEM_OPTION_GRID_STATE_OFFSET = 8,
    COMBAT_SYSTEM_OPTION_SHADE_STATE_OFFSET = 10,
    COMBAT_SYSTEM_OPTION_MOUSE_HEX_STATE_OFFSET = 12,
    COMBAT_SYSTEM_OPTION_DRAW_MASK = 0x7fff
};

i32 ValidHex(i32);
void UpdateCombatSystemOptions(i32);
i32 CombatSystemOptionsHandler(struct tag_message&);

#endif // HOMM2_CMBTMGR_H
