#ifndef HOMM2_SOURCE_COMBATTYPES_H
#define HOMM2_SOURCE_COMBATTYPES_H

#include <va.h>

H2_ENUM_BEGIN(ArmyDrawState)
    ARMY_DRAW_BEHIND      = 0,
    ARMY_DRAW_NORMAL      = 1,
    ARMY_DRAW_EFFECT      = 2,
    ARMY_DRAW_IN_FRONT    = 3,
    ARMY_DRAW_PHASE_COUNT = 4,
    ARMY_DRAW_ALL         = 100
H2_ENUM_END(ArmyDrawState)

H2_ENUM_BEGIN(CombatHexDirection)
    COMBAT_DIRECTION_INVALID         = -1,
    COMBAT_DIRECTION_NORTHEAST       = 0,
    COMBAT_DIRECTION_EAST            = 1,
    COMBAT_DIRECTION_SOUTHEAST       = 2,
    COMBAT_DIRECTION_SOUTHWEST       = 3,
    COMBAT_DIRECTION_WEST            = 4,
    COMBAT_DIRECTION_NORTHWEST       = 5,
    COMBAT_DIRECTION_WIDE_WEST       = 6,
    COMBAT_DIRECTION_WIDE_EAST       = 7,
    COMBAT_DIRECTION_OPPOSITE_OFFSET = 3,
    COMBAT_DIRECTION_ADJACENT_COUNT  = 6,
    COMBAT_DIRECTION_COUNT           = 8
H2_ENUM_END(CombatHexDirection)
H2_ENUM_STEPPED(CombatHexDirection)

#endif
