#ifndef HOMM2_COMMAND_H
#define HOMM2_COMMAND_H

#include <Ints.h>
// Declarations of the free functions DEFINED in COMMAND.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

H2_ENUM_CLASS_BEGIN(CombatMainResult)
    COMBAT_MAIN_CONTINUE = 1,
    COMBAT_MAIN_FINISHED = 2
H2_ENUM_CLASS_END(CombatMainResult)

H2_ENUM_CLASS_BEGIN(CombatKeyCommand)
    COMBAT_KEY_MOUSE_COORDS = 2,
    COMBAT_KEY_VIEW_ARMY = 0x14,
    COMBAT_KEY_VIEW_GENERAL = 0x23,
    COMBAT_KEY_CAST_SPELL = 0x2e,
    COMBAT_KEY_WAIT = 0x39,
    COMBAT_KEY_CLOSE_NETWORK_BOX = 0x3c,
    COMBAT_KEY_REDRAW_SCREEN = 0x3d,
    COMBAT_KEY_CYCLE_ARMY_VIEW = 0x3f,
    COMBAT_KEY_TOGGLE_GRID = 0x40,
    COMBAT_KEY_TOGGLE_MOUSE_HEX = 0x41,
    COMBAT_KEY_CYCLE_SHADE = 0x42,
    COMBAT_KEY_CYCLE_SPELL_EFFECT = 0x43,
    COMBAT_KEY_DEBUG_CREATURE_EFFECT = 0x57
H2_ENUM_CLASS_END(CombatKeyCommand)

H2_ENUM_CLASS_BEGIN(CombatWindowCommand)
    COMBAT_WINDOW_HOVER = 12,
    COMBAT_WINDOW_CLICK = 13,
    COMBAT_WINDOW_HELP = 14,
    COMBAT_WINDOW_MAIN_BUTTON = 0x40,
    COMBAT_WINDOW_HELP_FLAG = 0x200
H2_ENUM_CLASS_END(CombatWindowCommand)

H2_ENUM_BEGIN(CombatWinLoseConstant)
    COMBAT_WIN_LOSE_WIDGET_COUNT = 25,
    COMBAT_WIN_LOSE_NEXT_CONTROL = 0x7800,
    COMBAT_WIN_LOSE_TEXT_COMMAND = 3,
    COMBAT_WIN_LOSE_ANIMATION_COMMAND = 4,
    COMBAT_WIN_LOSE_RESOURCE_COMMAND = 9,
    COMBAT_WIN_LOSE_CLOSE_COMMAND = 10,
    COMBAT_WIN_LOSE_TEXT_ID = 101,
    COMBAT_WIN_LOSE_RESOURCE_LOAD_ID = 200,
    COMBAT_WIN_LOSE_RESOURCE_DRAW_ID = 201,
    COMBAT_WIN_LOSE_DRAW_DEPTH = 0x7fff,
    COMBAT_WIN_LOSE_ANIMATION_CYCLE_FIRST = 1,
    COMBAT_WIN_LOSE_ANIMATION_LOSS = 2,
    COMBAT_WIN_LOSE_ANIMATION_FLEE = 3,
    COMBAT_WIN_LOSE_ANIMATION_CYCLE_SECOND = 4,
    COMBAT_WIN_LOSE_FIRST_ANIMATION_FRAME = 1,
    COMBAT_WIN_LOSE_LOOP_FRAME_COUNT = 20,
    COMBAT_WIN_LOSE_FLEE_SECOND_RESOURCE_FRAME = 43,
    COMBAT_WIN_LOSE_FLEE_THIRD_RESOURCE_FRAME = 69,
    COMBAT_WIN_LOSE_FLEE_LAST_FRAME = 25,
    COMBAT_WIN_LOSE_LOSS_SECOND_RESOURCE_FRAME = 30,
    COMBAT_WIN_LOSE_LOSS_THIRD_RESOURCE_FRAME = 59,
    COMBAT_WIN_LOSE_LOSS_RESET_FRAME = 80,
    COMBAT_WIN_LOSE_INITIAL_DELAY = 90,
    COMBAT_WIN_LOSE_LOOP_DELAY = 99,
    COMBAT_WIN_LOSE_FLEE_DELAY = 40,
    COMBAT_WIN_LOSE_LOSS_DELAY = 50,
    COMBAT_WIN_LOSE_LOSS_FINAL_DELAY = 100,
    COMBAT_WIN_LOSE_ARTIFACT_ICON_ID = 2001,
    COMBAT_WIN_LOSE_ARTIFACT_IMAGE_ID = 2002,
    COMBAT_WIN_LOSE_ARTIFACT_TEXT_ID = 2101,
    COMBAT_WIN_LOSE_SKELETON_ICON_ID = 900,
    COMBAT_WIN_LOSE_SKELETON_TEXT_ID = 901,
    COMBAT_WIN_LOSE_EAGLE_BACKGROUND_ID = 902,
    COMBAT_WIN_LOSE_EAGLE_SPELL_ID = 903,
    COMBAT_WIN_LOSE_EAGLE_TEXT_ID = 904,
    COMBAT_WIN_LOSE_ICON_FLAGS = 16,
    COMBAT_WIN_LOSE_SPELL_ICON_FLAGS = 17,
    COMBAT_WIN_LOSE_TEXT_FLAGS = 512
H2_ENUM_END(CombatWinLoseConstant)

H2_ENUM_CLASS_BEGIN(CombatBattleResultText)
    COMBAT_RESULT_TEXT_ENEMY_SURRENDERED = 0,
    COMBAT_RESULT_TEXT_ENEMY_FLED = 1,
    COMBAT_RESULT_TEXT_VICTORY = 2,
    COMBAT_RESULT_TEXT_EXPERIENCE = 3,
    COMBAT_RESULT_TEXT_HERO_SURRENDER = 4,
    COMBAT_RESULT_TEXT_HERO_FLEE = 5,
    COMBAT_RESULT_TEXT_HERO_DEFEAT = 6,
    COMBAT_RESULT_TEXT_FORCES_SURRENDER = 7,
    COMBAT_RESULT_TEXT_FORCES_FLEE = 8,
    COMBAT_RESULT_TEXT_FORCES_DEFEAT = 9,
    COMBAT_RESULT_TEXT_NETWORK_EXPERIENCE = 10
H2_ENUM_CLASS_END(CombatBattleResultText)

H2_ENUM_CLASS_BEGIN(CombatControlId)
    COMBAT_CONTROL_ATTACK = 1,
    COMBAT_CONTROL_WAIT = 2,
    COMBAT_CONTROL_DISABLE_SELECTION = 3,
    COMBAT_CONTROL_SYSTEM_OPTIONS = 4,
    COMBAT_CONTROL_HELP_FIRST = 10,
    COMBAT_CONTROL_HELP_SECOND = 11,
    COMBAT_CONTROL_HELP_THIRD = 12,
    COMBAT_CONTROL_HELP_FOURTH = 13
H2_ENUM_CLASS_END(CombatControlId)

H2_ENUM_BEGIN(CombatRemoteConstant)
    COMBAT_REMOTE_PACKET_TYPE = 1,
    COMBAT_REMOTE_CATEGORY_ACTION = 2,
    COMBAT_REMOTE_COMMAND_MESSAGE = 11,
    COMBAT_REMOTE_COMMAND_ACTION = 23
H2_ENUM_END(CombatRemoteConstant)

H2_ENUM_CLASS_BEGIN(CombatAction)
    COMBAT_ACTION_NONE = 0,
    COMBAT_ACTION_CAST_SPELL = 1,
    COMBAT_ACTION_MOVE = 2,
    COMBAT_ACTION_WAIT = 3,
    COMBAT_ACTION_RETREAT = 4,
    COMBAT_ACTION_SURRENDER = 5,
    COMBAT_ACTION_ATTACK = 6,
    COMBAT_ACTION_DEFEND = 7
H2_ENUM_CLASS_END(CombatAction)

H2_ENUM_CLASS_BEGIN(CombatActionDataIndex)
    COMBAT_ACTION_DATA_ACTION = 0,
    COMBAT_ACTION_DATA_EXTRA = 1,
    COMBAT_ACTION_DATA_GRID = 2,
    COMBAT_ACTION_DATA_SECOND_GRID = 3,
    COMBAT_ACTION_DATA_COUNT = 4
H2_ENUM_CLASS_END(CombatActionDataIndex)

H2_ENUM_BEGIN(CombatDirectionConstant)
    COMBAT_DIRECTION_COUNT = 8,
    COMBAT_ADJACENT_DIRECTION_COUNT = 6,
    COMBAT_DIRECTION_SPECIAL_FIRST = 6,
    COMBAT_DIRECTION_SPECIAL_SECOND = 7,
    COMBAT_DIRECTION_SECTOR_COUNT = 24,
    COMBAT_DIRECTION_SECTOR_QUARTER = 6,
    COMBAT_DIRECTION_SECTOR_HALF = 12,
    COMBAT_DIRECTION_SECTOR_THREE_QUARTERS = 18,
    COMBAT_DIRECTION_PENDING_OFFSET = 10,
    COMBAT_DIRECTION_SECTORS_PER_ADJACENT = 4,
    COMBAT_DIRECTION_SPECIAL_FIRST_SECTOR_START = 11,
    COMBAT_DIRECTION_SPECIAL_FIRST_SECTOR_CENTER = 12,
    COMBAT_DIRECTION_SPECIAL_FIRST_SECTOR_END = 13,
    COMBAT_DIRECTION_SPECIAL_SECOND_SECTOR_PREVIOUS = 23,
    COMBAT_DIRECTION_SPECIAL_SECOND_SECTOR_CENTER = 0,
    COMBAT_DIRECTION_SPECIAL_SECOND_SECTOR_NEXT = 1
H2_ENUM_END(CombatDirectionConstant)

H2_ENUM_BEGIN(CombatCommandConstant)
    COMBAT_POINTER_DEFAULT = 6,
    COMBAT_POINTER_VIEW = 5,
    COMBAT_POINTER_ATTACK_OFFSET = 7,
    COMBAT_INVALID_ARMY_INDEX = -1,
    COMBAT_INVALID_HEX = -1,
    COMBAT_PLAYER_NONE = -1,
    COMBAT_SMALL_VIEW_SIDE_NONE = -1,
    COMBAT_SMALL_VIEW_POSITION_NONE = -1,
    COMBAT_IGNORED_HEX = -2,
    COMBAT_INVALID_COMMAND = -99,
    COMBAT_CASTLE_GATE_HEX = 59
H2_ENUM_END(CombatCommandConstant)

H2_ENUM_BEGIN(CombatRoundConstant)
    COMBAT_ROUND_INITIAL_SPEED = 15,
    COMBAT_ROUND_ABILITY_FLAGS = 0xff1f,
    COMBAT_RESULT_DRAW = -1,
    COMBAT_WIN_MESSAGE = 0x4000
H2_ENUM_END(CombatRoundConstant)

H2_ENUM_BEGIN(CombatCommandGeometry)
    COMBAT_CONTROL_RIGHT_MIN_X = 590,
    COMBAT_CONTROL_LEFT_MAX_X = 50,
    COMBAT_CONTROL_SYSTEM_OPTIONS_MIN_Y = 460,
    COMBAT_SCREEN_HEIGHT = 480,
    COMBAT_SCREEN_MAX_X = 639,
    COMBAT_SCREEN_MAX_Y = 479,
    COMBAT_ARMY_VIEW_LEVEL_COUNT = 3,
    COMBAT_SPELL_EFFECT_TYPE_COUNT = 3,
    COMBAT_COMMAND_FRAME_DELAY = 75,
    COMBAT_DEBUG_VAPORIZE_MASK = 0x3,
    COMBAT_DEBUG_DOUBLE_RIPPLE_MASK = 0xc
H2_ENUM_END(CombatCommandGeometry)

H2_ENUM_BEGIN(CombatCasualtyConstant)
    COMBAT_CASUALTY_QUANTITY_STORAGE_COUNT = 42,
    COMBAT_CASUALTY_DISPLAY_LIMIT = 7,
    COMBAT_CASUALTY_WIDGETS_PER_SIDE = 7,
    COMBAT_CASUALTY_WINDOW_WIDTH = 320,
    COMBAT_CASUALTY_WINDOW_BOTTOM = 458
H2_ENUM_END(CombatCasualtyConstant)

H2_ENUM_BEGIN(CombatCycleConstant)
    COMBAT_CREATURE_CYCLE_SEQUENCE_FIRST = 8,
    COMBAT_CREATURE_CYCLE_SEQUENCE_LAST = 12,
    COMBAT_HERO_ANIMATION_STAND = 0,
    COMBAT_HERO_ANIMATION_DEATH_FIRST = 1,
    COMBAT_HERO_ANIMATION_DEATH_SECOND = 2,
    COMBAT_HERO_ANIMATION_IDLE_FIRST = 9,
    COMBAT_HERO_ANIMATION_IDLE_SECOND = 10,
    COMBAT_HERO_ANIMATION_IDLE_LAST = 11,
    COMBAT_HERO_IDLE_DELAY = 4500,
    COMBAT_STAND_DELAY_RANDOM_THRESHOLD = 51,
    COMBAT_STAND_DELAY_RANDOM_MIN = 50,
    COMBAT_IDLE_ROLL_MIN = 1,
    COMBAT_IDLE_ROLL_MAX = 100,
    COMBAT_IDLE_REPEAT_CHANCE = 8
H2_ENUM_END(CombatCycleConstant)

H2_ENUM_BEGIN(CombatVictoryConstant)
    COMBAT_VICTORY_NECROMANCY_STACK_LIMIT = 5,
    COMBAT_VICTORY_FADE_STEPS = 8,
    COMBAT_VICTORY_WATER_FADE_STEPS = 5,
    COMBAT_VICTORY_WATER_TERRAIN = 7,
    COMBAT_VICTORY_FADE_DELAY = 60,
    COMBAT_VICTORY_MUSIC = 29,
    COMBAT_LOSS_MUSIC = 30
H2_ENUM_END(CombatVictoryConstant)

H2_ENUM_BEGIN(CombatSurrenderDialogConstant)
    COMBAT_SURRENDER_DIALOG_TYPE = 1,
    COMBAT_SURRENDER_DIALOG_ACCEPT_RESULT = 2,
    COMBAT_SURRENDER_TEXT_WIDTH = 30,
    COMBAT_SURRENDER_PORTRAIT_RESOURCE_ID = 1,
    COMBAT_SURRENDER_CAPTAIN_PORTRAIT_COMMAND = 5,
    COMBAT_SURRENDER_HERO_PORTRAIT_COMMAND = 6,
    COMBAT_SURRENDER_PORTRAIT_WIDGET_ID = 30,
    COMBAT_SURRENDER_PORTRAIT_DEFAULT_COLOR = 4,
    COMBAT_SURRENDER_CAPTAIN_OVERLAY_COMMAND = 4,
    COMBAT_SURRENDER_CAPTAIN_NEUTRAL_COLOR = 6,
    COMBAT_SURRENDER_TEXT_ID = 2
H2_ENUM_END(CombatSurrenderDialogConstant)

#define COMBAT_NECROMANCY_LEVEL_FACTOR 0.1
#define COMBAT_SURRENDER_QUILL_FACTOR 0.1
#define COMBAT_SURRENDER_BASE_FACTOR 0.5
#define COMBAT_SURRENDER_DIPLOMACY_FACTOR 0.2
#define COMBAT_IDLE_ROLL_DIVISOR 100.0f
#define COMBAT_STAND_DELAY_BASE_FACTOR 0.25
#define COMBAT_STAND_DELAY_RANDOM_FACTOR 0.5
#define COMBAT_CYCLE_TIMER_FACTOR 150.0f

H2_ENUM_CLASS_BEGIN(CombatHelpTextIndex)
    COMBAT_HELP_SKIP_UNIT = 1,
    COMBAT_HELP_AUTO_COMBAT = 2,
    COMBAT_HELP_SYSTEM_OPTIONS = 3,
    COMBAT_HELP_OTHER_CONTROL = 4
H2_ENUM_CLASS_END(CombatHelpTextIndex)

#define COMBAT_SOUND_POLL_DELAY 75.0f
#define COMBAT_DIRECTION_SLOPE_STEEPEST 3.73
#define COMBAT_DIRECTION_SLOPE_STEEP 1.73
#define COMBAT_DIRECTION_SLOPE_DIAGONAL 1.0f
#define COMBAT_DIRECTION_SLOPE_SHALLOW 0.58
#define COMBAT_DIRECTION_SLOPE_SHALLOWEST 0.27

#pragma pack(push, 1)
struct CombatRemotePacket {
    i8 messageLength;
    char reserved1[4];
    i8 category;
    i8 command;
    char reserved7[2];
    i32 nextAction;
    i32 nextActionExtra;
    i32 nextActionGridIndex;
    i32 nextActionGridIndex2;
};
#pragma pack(pop)
SIZE(CombatRemotePacket, 0x19);

i32 WinCombatHandler(struct tag_message&);
i32 InCombatArea(i32, i32);

#endif // HOMM2_COMMAND_H
