#ifndef HOMM2_COMMAND_H
#define HOMM2_COMMAND_H
// Declarations of the free functions DEFINED in COMMAND.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

typedef enum CombatMainResult {
    COMBAT_MAIN_CONTINUE = 1,
    COMBAT_MAIN_FINISHED = 2
} CombatMainResult;

typedef enum CombatInputEvent {
    COMBAT_EVENT_NONE = 0,
    COMBAT_EVENT_KEY = 1,
    COMBAT_EVENT_MOUSE_MOVE = 4,
    COMBAT_EVENT_MOUSE_BUTTON = 8,
    COMBAT_EVENT_MOUSE_OTHER = 0x20,
    COMBAT_EVENT_WINDOW = 0x200
} CombatInputEvent;

typedef enum CombatKeyCommand {
    COMBAT_KEY_MOUSE_COORDS = 2,
    COMBAT_KEY_VIEW_ARMY = 0x14,
    COMBAT_KEY_VIEW_GENERAL = 0x23,
    COMBAT_KEY_CAST_SPELL = 0x2e,
    COMBAT_KEY_WAIT = 0x39,
    COMBAT_KEY_CLOSE_NETWORK_BOX = 0x3c,
    COMBAT_KEY_REDRAW_SCREEN = 0x3d,
    COMBAT_KEY_CYCLE_ARMY_VIEW = 0x3f,
    COMBAT_KEY_TOGGLE_GRID = 0x40,
    COMBAT_KEY_TOGGLE_MOUSE_HEX = 0x41,
    COMBAT_KEY_CYCLE_SHADE = 0x42,
    COMBAT_KEY_CYCLE_SPELL_EFFECT = 0x43,
    COMBAT_KEY_DEBUG_CREATURE_EFFECT = 0x57
} CombatKeyCommand;

typedef enum CombatWindowCommand {
    COMBAT_WINDOW_HOVER = 12,
    COMBAT_WINDOW_CLICK = 13,
    COMBAT_WINDOW_HELP = 14,
    COMBAT_WINDOW_MAIN_BUTTON = 0x40,
    COMBAT_WINDOW_HELP_FLAG = 0x200
} CombatWindowCommand;

typedef enum CombatControlId {
    COMBAT_CONTROL_ATTACK = 1,
    COMBAT_CONTROL_WAIT = 2,
    COMBAT_CONTROL_DISABLE_SELECTION = 3,
    COMBAT_CONTROL_SYSTEM_OPTIONS = 4,
    COMBAT_CONTROL_HELP_FIRST = 10,
    COMBAT_CONTROL_HELP_SECOND = 11,
    COMBAT_CONTROL_HELP_THIRD = 12,
    COMBAT_CONTROL_HELP_FOURTH = 13
} CombatControlId;

typedef enum CombatRemoteConstant {
    COMBAT_REMOTE_PACKET_TYPE = 1,
    COMBAT_REMOTE_CATEGORY_ACTION = 2,
    COMBAT_REMOTE_COMMAND_MESSAGE = 11,
    COMBAT_REMOTE_COMMAND_ACTION = 23
} CombatRemoteConstant;

typedef enum CombatDirectionConstant {
    COMBAT_DIRECTION_COUNT = 8,
    COMBAT_ADJACENT_DIRECTION_COUNT = 6,
    COMBAT_DIRECTION_SPECIAL_FIRST = 6,
    COMBAT_DIRECTION_SPECIAL_SECOND = 7,
    COMBAT_DIRECTION_SECTOR_COUNT = 24,
    COMBAT_DIRECTION_SECTOR_QUARTER = 6,
    COMBAT_DIRECTION_SECTOR_HALF = 12,
    COMBAT_DIRECTION_SECTOR_THREE_QUARTERS = 18,
    COMBAT_DIRECTION_PENDING_OFFSET = 10,
    COMBAT_DIRECTION_SECTORS_PER_ADJACENT = 4,
    COMBAT_DIRECTION_SPECIAL_FIRST_SECTOR_START = 11,
    COMBAT_DIRECTION_SPECIAL_FIRST_SECTOR_CENTER = 12,
    COMBAT_DIRECTION_SPECIAL_FIRST_SECTOR_END = 13,
    COMBAT_DIRECTION_SPECIAL_SECOND_SECTOR_PREVIOUS = 23,
    COMBAT_DIRECTION_SPECIAL_SECOND_SECTOR_CENTER = 0,
    COMBAT_DIRECTION_SPECIAL_SECOND_SECTOR_NEXT = 1
} CombatDirectionConstant;

typedef enum CombatCommandConstant {
    COMBAT_POINTER_DEFAULT = 6,
    COMBAT_POINTER_VIEW = 5,
    COMBAT_POINTER_ATTACK_OFFSET = 7,
    COMBAT_INVALID_HEX = -1,
    COMBAT_IGNORED_HEX = -2,
    COMBAT_INVALID_COMMAND = -99,
    COMBAT_CASTLE_GATE_HEX = 59
} CombatCommandConstant;

typedef enum CombatCommandGeometry {
    COMBAT_CONTROL_RIGHT_MIN_X = 590,
    COMBAT_CONTROL_LEFT_MAX_X = 50,
    COMBAT_CONTROL_SYSTEM_OPTIONS_MIN_Y = 460,
    COMBAT_SCREEN_HEIGHT = 480,
    COMBAT_ARMY_VIEW_LEVEL_COUNT = 3,
    COMBAT_SPELL_EFFECT_TYPE_COUNT = 3,
    COMBAT_COMMAND_FRAME_DELAY = 75,
    COMBAT_DEBUG_VAPORIZE_MASK = 0x3,
    COMBAT_DEBUG_DOUBLE_RIPPLE_MASK = 0xc
} CombatCommandGeometry;

typedef enum CombatHelpTextIndex {
    COMBAT_HELP_SKIP_UNIT = 1,
    COMBAT_HELP_AUTO_COMBAT = 2,
    COMBAT_HELP_SYSTEM_OPTIONS = 3,
    COMBAT_HELP_OTHER_CONTROL = 4
} CombatHelpTextIndex;

#define COMBAT_SOUND_POLL_DELAY 75.0f
#define COMBAT_DIRECTION_SLOPE_STEEPEST 3.73
#define COMBAT_DIRECTION_SLOPE_STEEP 1.73
#define COMBAT_DIRECTION_SLOPE_DIAGONAL 1.0f
#define COMBAT_DIRECTION_SLOPE_SHALLOW 0.58
#define COMBAT_DIRECTION_SLOPE_SHALLOWEST 0.27

#pragma pack(push, 1)
struct CombatRemotePacket {
    signed char messageLength;
    char reserved1[4];
    signed char category;
    signed char command;
    char reserved7[2];
    int nextAction;
    int nextActionExtra;
    int nextActionGridIndex;
    int nextActionGridIndex2;
};
#pragma pack(pop)
SIZE(CombatRemotePacket, 0x19);

int WinCombatHandler(struct tag_message &);
int InCombatArea(int, int);

#endif // HOMM2_COMMAND_H
