#ifndef HOMM2_CURSOR_H
#define HOMM2_CURSOR_H
// Declarations of the free functions DEFINED in CURSOR.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).

typedef enum CursorConstant {
    CURSOR_HERO_TYPE_BOAT = 6,
    CURSOR_BOAT_WAKE_TYPE = 7,
    CURSOR_DIRECTION_COUNT = 8,
    CURSOR_TURN_FRAME_COUNT = 16,
    CURSOR_FRAMES_PER_DIRECTION = 9,
    CURSOR_LAST_FRAME_COUNT = 8,
    CURSOR_FLIP_FLAG = 0x80,
    CURSOR_FRAME_MASK = 0x7f,
    CURSOR_BOAT_BASE_FRAME_5 = 0x9b,
    CURSOR_BOAT_BASE_FRAME_6 = 0x92,
    CURSOR_BOAT_BASE_FRAME_7 = 0x89,
    CURSOR_MAP_DRAW_OFFSET = 7,
    CURSOR_DRAW_X = 0xe0,
    CURSOR_FLIPPED_DRAW_X = 0x100,
    CURSOR_DRAW_Y = 0xff,
    CURSOR_BOAT_DRAW_Y = 0xf5,
    CURSOR_CLIP_SIZE = 0x1e0,
    CURSOR_FLAG_FRAME_BASE = 0x38,
    CURSOR_HORSE_SHADOW_OFFSET = 0x32,
    CURSOR_BOAT_SHADOW_OFFSET = 0x24,
    CURSOR_SHADOW_ANIM_FIRST = 9,
    CURSOR_SHADOW_ANIM_END = 0x24,
    CURSOR_SLOW_TURN_MULTIPLIER = 3,
    CURSOR_MAP_VISIBLE_FLAG = 0x40,
    CURSOR_CELL_UNCOVERED_FLAG = 0x04,
    CURSOR_BOAT_COUNT = 48,
    CURSOR_MOVE_HALF_TILE_PIXELS = 16,
    CURSOR_ARTIFACT_CAPACITY = 14,
    CURSOR_RESOURCE_DIALOG_PENALTY = 100000,
    CURSOR_VISIBILITY_ARTIFACT = 64,
    CURSOR_FIZZLE_X = 0xc0,
    CURSOR_FIZZLE_Y = 0xc0,
    CURSOR_FIZZLE_WIDTH = 0x60,
    CURSOR_FIZZLE_HEIGHT = 0x60,
    CURSOR_FIZZLE_COMPUTER_TYPE = 50,
    CURSOR_INVALID_POSITION = -1
} CursorConstant;

void SendMapChange(int, signed char, unsigned char, unsigned char, int, unsigned char, unsigned char);

#endif // HOMM2_CURSOR_H
