#ifndef HOMM2_SOURCE_DIMPALETTE_H
#define HOMM2_SOURCE_DIMPALETTE_H

#include <Ints.h>
#include <BASE/display.h>

H2_ENUM_BEGIN(DimPaletteConstant)
    DIM_PALETTE_SET_COUNT   = 3,
    DIM_PALETTE_LEVEL_COUNT = 4,
H2_ENUM_END(DimPaletteConstant)

extern u8 uDimPal[DIM_PALETTE_SET_COUNT][DIM_PALETTE_LEVEL_COUNT][PALETTE_COLOR_COUNT];

#endif
