#ifndef HOMM2_EVENTS_H
#define HOMM2_EVENTS_H
// Declarations of the free functions DEFINED in EVENTS.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
class hero;

enum {
    COMBAT_REMOTE_BUFFER_SIZE = 0xff,
    COMBAT_REMOTE_HEADER_SIZE = 0x9b,
    COMBAT_REMOTE_HERO_FIRST_SIZE = 200,
    COMBAT_REMOTE_HERO_SECOND_SIZE = 50,
    COMBAT_REMOTE_HERO_SECOND_SPELL_INDEX = 52,
    COMBAT_REMOTE_PACKET_HEADER_SIZE = 9,
    COMBAT_REMOTE_FRAGMENT_TYPE = 1,
    COMBAT_REMOTE_TIMEOUT = 90000
};

typedef enum CombatRemoteCommand {
    COMBAT_REMOTE_COMMAND = 0x15,
    COMBAT_REMOTE_CONFIRM_COMMAND = 0x16
} CombatRemoteCommand;

typedef enum CombatRemoteFragment {
    COMBAT_REMOTE_FIRST_HERO_FIRST = 1,
    COMBAT_REMOTE_FIRST_HERO_SECOND = 2,
    COMBAT_REMOTE_SECOND_HERO_FIRST = 3,
    COMBAT_REMOTE_SECOND_HERO_SECOND = 4
} CombatRemoteFragment;

#pragma pack(push, 1)
struct mapEventExtra {
    unsigned char active;
    int resources[7];
    short artifact;
    unsigned char answerCount;
    char answers[8][13];
    char riddle[1];
};
struct signEventExtra {
    char pad[9];
    char text[1];
};
struct rumourEventExtra {
    char pad[8];
    char text[1];
};
struct timeEventExtra {
    char unknown00;
    int resources[7];
    char unknown1d[2];
    unsigned char appliesToComputer;
    char unknown20;
    unsigned short firstDay;
    unsigned short repeatInterval;
    char unknown25[5];
    unsigned char appliesToHuman;
    unsigned char players[6];
    char message[1];
};
struct mapHeroExtra {
    signed char owner;
    unsigned char hasCustomArmy;
    signed char troopTypes[5];
    unsigned short troopCounts[5];
    unsigned char hasCustomHero;
    signed char heroId;
    signed char artifacts[3];
    char unknown16;
    int experience;
    unsigned char hasCustomSkills;
    signed char skillTypes[8];
    signed char skillLevels[8];
    char unknown2c;
    unsigned char hasCustomName;
    char name[13];
    unsigned char hasPatrol;
    union {
        signed char patrolRadius;
        signed char heroClass;
    };
    signed char hasAssignedHero;
};
struct mapTownExtra {
    signed char color;
    unsigned char hasCustomBuildings;
    unsigned int buildings;
    signed char mageGuildLevel;
    signed char hasCustomArmy;
    signed char troopTypes[5];
    unsigned short troopCounts[5];
    unsigned char hasShrine;
    char unused18;
    char name[15];
    signed char unknown28;
};
#pragma pack(pop)

typedef enum MapEventType {
    MAP_EVENT_ALCHEMIST_LAB = 1,
    MAP_EVENT_SIGN = 2,
    MAP_EVENT_BUOY = 3,
    MAP_EVENT_SKELETON = 4,
    MAP_EVENT_DAEMON_CAVE = 5,
    MAP_EVENT_TREASURE_CHEST = 6,
    MAP_EVENT_FAERIE_RING = 7,
    MAP_EVENT_CAMPFIRE = 8,
    MAP_EVENT_FOUNTAIN = 9,
    MAP_EVENT_GAZEBO = 10,
    MAP_EVENT_ANCIENT_LAMP = 11,
    MAP_EVENT_GRAVEYARD = 12,
    MAP_EVENT_ARCHER_HOUSE = 13,
    MAP_EVENT_GOBLIN_HUT = 14,
    MAP_EVENT_DWARF_COTTAGE = 15,
    MAP_EVENT_PEASANT_HUT = 16,
    MAP_EVENT_LOG_CABIN = 17,
    MAP_EVENT_ALCHEMIST_TOWER = 18,
    MAP_EVENT_MAP_EVENT = 19,
    MAP_EVENT_DRAGON_CITY = 20,
    MAP_EVENT_LIGHTHOUSE = 21,
    MAP_EVENT_WATER_WHEEL = 22,
    MAP_EVENT_MINE = 23,
    MAP_EVENT_MONSTER = 24,
    MAP_EVENT_OBELISK = 25,
    MAP_EVENT_OASIS = 26,
    MAP_EVENT_RESOURCE = 27,
    MAP_EVENT_COAST = 28,
    MAP_EVENT_SAWMILL = 29,
    MAP_EVENT_ORACLE = 30,
    MAP_EVENT_SHRINE_FIRST_CIRCLE = 31,
    MAP_EVENT_SHIPWRECK = 32,
    MAP_EVENT_SEA_CHEST = 33,
    MAP_EVENT_DESERT_TENT = 34,
    MAP_EVENT_CASTLE = 35,
    MAP_EVENT_STONE_LITHS = 36,
    MAP_EVENT_WAGON_CAMP = 37,
    MAP_EVENT_HUT_OF_MAGI = 38,
    MAP_EVENT_WHIRLPOOL = 39,
    MAP_EVENT_WINDMILL = 40,
    MAP_EVENT_ARTIFACT = 41,
    MAP_EVENT_MERMAID = 42,
    MAP_EVENT_HERO_INTERACTION = MAP_EVENT_MERMAID,
    MAP_EVENT_BOAT = 43,
    MAP_EVENT_RANDOM_ULTIMATE_ARTIFACT = 44,
    MAP_EVENT_RANDOM_ARTIFACT = 45,
    MAP_EVENT_RANDOM_RESOURCE = 46,
    MAP_EVENT_RANDOM_MONSTER = 47,
    MAP_EVENT_RANDOM_TOWN = 48,
    MAP_EVENT_RANDOM_CASTLE = 49,
    MAP_EVENT_EYE_OF_MAGI = 50,
    MAP_EVENT_RANDOM_MONSTER_WEAK = 51,
    MAP_EVENT_RANDOM_MONSTER_MEDIUM = 52,
    MAP_EVENT_RANDOM_MONSTER_STRONG = 53,
    MAP_EVENT_RANDOM_MONSTER_VERY_STRONG = 54,
    MAP_EVENT_HERO = 55,
    MAP_EVENT_NOTHING_SPECIAL = 56,
    MAP_EVENT_MOSSY_ROCK = 57,
    MAP_EVENT_WATCH_TOWER = 58,
    MAP_EVENT_TREE_HOUSE = 59,
    MAP_EVENT_TREE_CITY = 60,
    MAP_EVENT_RUINS = 61,
    MAP_EVENT_FORT = 62,
    MAP_EVENT_TRADING_POST = 63,
    MAP_EVENT_ABANDONED_MINE = 64,
    MAP_EVENT_SIRENS = 65,
    MAP_EVENT_STANDING_STONES = 66,
    MAP_EVENT_IDOL = 67,
    MAP_EVENT_TREE_OF_KNOWLEDGE = 68,
    MAP_EVENT_WITCH_DOCTOR_HUT = 69,
    MAP_EVENT_TEMPLE = 70,
    MAP_EVENT_HILL_FORT = 71,
    MAP_EVENT_HALFLING_HOLE = 72,
    MAP_EVENT_MERCENARY_CAMP = 73,
    MAP_EVENT_SHRINE_SECOND_CIRCLE = 74,
    MAP_EVENT_SHRINE_THIRD_CIRCLE = 75,
    MAP_EVENT_PYRAMID = 76,
    MAP_EVENT_CITY_OF_DEAD = 77,
    MAP_EVENT_EXCAVATION = 78,
    MAP_EVENT_SPHINX = 79,
    MAP_EVENT_WAGON = 80,
    MAP_EVENT_TAR_PIT = 81,
    MAP_EVENT_ARTESIAN_SPRING = 82,
    MAP_EVENT_TROLL_BRIDGE = 83,
    MAP_EVENT_WATERING_HOLE = 84,
    MAP_EVENT_WITCH_HUT = 85,
    MAP_EVENT_XANADU = 86,
    MAP_EVENT_CAVE = 87,
    MAP_EVENT_LEAN_TO = 88,
    MAP_EVENT_MAGELLAN_MAPS = 89,
    MAP_EVENT_FLOTSAM = 90,
    MAP_EVENT_DERELICT_SHIP = 91,
    MAP_EVENT_SHIPWRECK_SURVIVOR = 92,
    MAP_EVENT_BOTTLE = 93,
    MAP_EVENT_MAGIC_WELL = 94,
    MAP_EVENT_MAGIC_GARDEN = 95,
    MAP_EVENT_OBSERVATION_TOWER = 96,
    MAP_EVENT_FREEMANS_FOUNDRY = 97,
    MAP_EVENT_REEFS = 98,
    MAP_EVENT_TREES = 99,
    MAP_EVENT_MOUNTAINS = 100,
    MAP_EVENT_VOLCANO = 101,
    MAP_EVENT_FLOWERS = 102,
    MAP_EVENT_ROCK = 103,
    MAP_EVENT_WATER_LAKE = 104,
    MAP_EVENT_MANDRAKE = 105,
    MAP_EVENT_DEAD_TREE = 106,
    MAP_EVENT_STUMP = 107,
    MAP_EVENT_CRATER = 108,
    MAP_EVENT_CACTUS = 109,
    MAP_EVENT_MOUND = 110,
    MAP_EVENT_DUNE = 111,
    MAP_EVENT_LAVA_POOL = 112,
    MAP_EVENT_SHRUB = 113,
    MAP_EVENT_ARENA = 114,
    MAP_EVENT_BARROW_MOUNDS = 115,
    MAP_EVENT_RANDOM_TREASURE_ARTIFACT = 116,
    MAP_EVENT_RANDOM_MINOR_ARTIFACT = 117,
    MAP_EVENT_RANDOM_MAJOR_ARTIFACT = 118,
    MAP_EVENT_BARRIER = 119,
    MAP_EVENT_TRAVELER_TENT = 120,
    MAP_EVENT_EXPANSION_DWELLING = 121,
    MAP_EVENT_EXPANSION_OBJECT = 122,
    MAP_EVENT_JAIL = 123
} MapEventType;

typedef enum MapEventConstant {
    MAP_EVENT_ACTION_FLAG = 0x80,
    MAP_EVENT_TYPE_MASK = 0x7f,
    MAP_EVENT_DATA_EMPTY = 0,
    MAP_EVENT_DATA_SHIFT = 3,
    MAP_EVENT_RESOURCE_OFFSET = 1,
    MAP_EVENT_RESOURCE_AMOUNT = 5,
    MAP_EVENT_GOLD_AMOUNT = 500,
    CAMPFIRE_RESOURCE_MASK = 0xf,
    CAMPFIRE_AMOUNT_SHIFT = 4,
    CAMPFIRE_GOLD_MULTIPLIER = 100,
    OASIS_MOBILITY_BONUS = 800,
    EVENT_ARTIFACT_CAPACITY = 14,
    SKELETON_EMPTY = 1,
    SKELETON_ARTIFACT_OFFSET = 2,
    SKELETON_GOLD = 1000,
    CHEST_ARTIFACT_FLAG = 0x100,
    CHEST_ARTIFACT_MASK = 0xff,
    CHEST_GOLD_ONLY = 2,
    CHEST_GOLD_MULTIPLIER = 500,
    CHEST_EXPERIENCE_MULTIPLIER = 125,
    DAEMON_CAVE_EMPTY = 1,
    DAEMON_REWARD_EXPERIENCE = 2,
    DAEMON_REWARD_ARTIFACT = 3,
    DAEMON_REWARD_EXPERIENCE_GOLD = 4,
    DAEMON_REWARD_RANSOM = 5,
    DAEMON_SERVANT_BASE = 0x3e,
    DAEMON_SERVANT_COUNT = 8,
    DAEMON_REWARD_MASK = 0xf,
    DAEMON_SERVANT_MASK = 0xf0,
    DAEMON_SERVANT_SHIFT = 4,
    DAEMON_EXPERIENCE = 1000,
    DAEMON_GOLD = 2500,
    EVENT_RANDOM_ARTIFACT_ANY = 14,
    EVENT_RANDOM_ARTIFACT_GOLD = 1000,
    GAZEBO_EXPERIENCE = 1000,
    MINE_GOLD_INCOME = 1000,
    MINE_ORE_INCOME = 2,
    MINE_RESOURCE_ICON_OFFSET = 59,
    WINDMILL_RESOURCE_AMOUNT = 2,
    WINDMILL_EMPTY = 99,
    SEA_CHEST_GOLD = 1500,
    SEA_CHEST_ARTIFACT_GOLD = 1000,
    MAGELLAN_MAP_COST = 1000,
    WATERING_HOLE_MOBILITY_BONUS = 400,
    HERO_SECONDARY_SKILL_LIMIT = 8,
    XANADU_ADMISSION_LEVEL = 10,
    TREE_KNOWLEDGE_MODE_SHIFT = 6,
    TREE_KNOWLEDGE_FREE = 1,
    TREE_KNOWLEDGE_GOLD = 2,
    TREE_KNOWLEDGE_GEMS = 3,
    TREE_KNOWLEDGE_GOLD_COST = 2000,
    TREE_KNOWLEDGE_GEM_COST = 10,
    DWELLING_GUARDED_FLAG = 0x100,
    DRAGON_CITY_GREEN_DRAGON = 35,
    DRAGON_CITY_RED_DRAGON = 36,
    DRAGON_CITY_BLACK_DRAGON = 37,
    DRAGON_CITY_RECRUIT = 36,
    CITY_DEAD_PRIMARY = 53,
    CITY_DEAD_SECONDARY = 48,
    CITY_DEAD_TERTIARY = 55,
    CITY_DEAD_RECRUIT = 55,
    TROLL_BRIDGE_TROLL = 17,
    TROLL_BRIDGE_WAR_TROLL = 18,
    PYRAMID_PRIMARY_MONSTER = 51,
    PYRAMID_SECONDARY_MONSTER = 53,
    PYRAMID_GUARD_COUNT = 50,
    PYRAMID_SPELLBOOK_ARTIFACT = 0x51,
    PYRAMID_WISDOM_REQUIRED = 3,
    SHRINE_WISDOM_BONUS = 2,
    EVENT_TEXT_BUFFER_SIZE = 500,
    EVENT_TEXT_GRAVEYARD_PROMPT = 20,
    EVENT_TEXT_GRAVEYARD_EMPTY = 21,
    EVENT_TEXT_GRAVEYARD_REWARD = 22,
    EVENT_TEXT_FOLLOWERS = 66,
    EVENT_TEXT_MONSTER_REFUSAL = 67,
    EVENT_TEXT_RESOURCE_PICKUP = 72,
    EVENT_TEXT_SKELETON_EMPTY = 93,
    EVENT_TEXT_SKELETON_REWARD = 94,
    EVENT_TEXT_COUNT = 95,
    WAGON_ARTIFACT_FLAG = 0x80,
    WAGON_ARTIFACT_MASK = 0x7f,
    ARTIFACT_GUARDED_FLAG = 0x100,
    ARTIFACT_MONSTER_MASK = 0x7f,
    ARTIFACT_MODE_MASK = 0xf,
    ARTIFACT_RESOURCE_MASK = 0xf0,
    ARTIFACT_RESOURCE_SHIFT = 4,
    ARTIFACT_MODE_PICKUP = 1,
    ARTIFACT_MODE_GOLD = 3,
    ARTIFACT_MODE_WISDOM = 4,
    ARTIFACT_MODE_LEADERSHIP = 5,
    ARTIFACT_MODE_RESOURCE_3 = 6,
    ARTIFACT_MODE_RESOURCE_5 = 7,
    ARTIFACT_GOLD_COST = 2000,
    ARTIFACT_RESOURCE_3_GOLD_COST = 2500,
    ARTIFACT_RESOURCE_5_GOLD_COST = 3000,
    ARTIFACT_RESOURCE_3_AMOUNT = 3,
    ARTIFACT_RESOURCE_5_AMOUNT = 5,
    ARTIFACT_SPELL_SCROLL = 0x56,
    ARTIFACT_ROGUE_GUARD = 0x39,
    ARTIFACT_ROGUE_COUNT = 50,
    ABANDONED_MINE_X_MIN = -2,
    ABANDONED_MINE_X_MAX = 1,
    ABANDONED_MINE_Y_TOP = -1,
    ABANDONED_MINE_TILESET_TOP_A = 56,
    ABANDONED_MINE_TILESET_TOP_B = 51,
    ABANDONED_MINE_TILESET_BOTTOM_A = 26,
    ABANDONED_MINE_TILESET_BOTTOM_B = 32,
    ABANDONED_MINE_TILESET_CENTER = 29,
    ABANDONED_MINE_EVENT = 23,
    ABANDONED_MINE_OBJECT = 64,
    MAP_EVENT_REWARD_NONE = -1,
    MAP_EVENT_REWARD_ARTIFACT = 7,
    SPHINX_ANSWER_BUFFER_SIZE = 52,
    SPHINX_INPUT_LENGTH = 12,
    SPHINX_RESOURCE_COUNT = 7,
    OBSERVATION_TOWER_RADIUS = 20,
    ORACLE_WINDOW_TEXT_ID = 14,
    ORACLE_THIEVES_GUILD_RANK = 99,
    ORACLE_MESSAGE_TYPE = 0x200,
    ORACLE_MESSAGE_COMMAND = 3,
    TELEPORT_TRIGGER_FLAG = 0x80,
    STONE_LITHS_MIN_DISTANCE = 1,
    WHIRLPOOL_MIN_DISTANCE = 3,
    HERO_TOWN_LOCATION = 0xa3,
    BOAT_CURSOR_TYPE = 6,
    BOAT_RESTORE_MODE = 2,
    COAST_FIZZLE_X = 192,
    COAST_FIZZLE_Y = 192,
    COAST_FIZZLE_WIDTH = 96,
    COAST_FIZZLE_HEIGHT = 96
} MapEventConstant;

typedef enum UndeadEventLevel {
    UNDEAD_EVENT_LEVEL_SMALL = 2,
    UNDEAD_EVENT_LEVEL_MEDIUM = 3,
    UNDEAD_EVENT_LEVEL_LARGE = 4
} UndeadEventLevel;

typedef enum UndeadEventConstant {
    SKELETON_EVENT_SMALL_COUNT = 25,
    SKELETON_EVENT_MEDIUM_COUNT = 50,
    SKELETON_EVENT_LARGE_COUNT = 100,
    SKELETON_EVENT_HUGE_COUNT = 200,
    SKELETON_EVENT_SMALL_GOLD = 500,
    SKELETON_EVENT_MEDIUM_GOLD = 1000,
    SKELETON_EVENT_LARGE_GOLD = 2000,
    SKELETON_EVENT_HUGE_GOLD = 5000,
    ZOMBIE_EVENT_SMALL_COUNT = 6,
    ZOMBIE_EVENT_SMALL_SUPPORT_COUNT = 4,
    ZOMBIE_EVENT_MEDIUM_COUNT = 15,
    ZOMBIE_EVENT_MEDIUM_SUPPORT_COUNT = 10,
    ZOMBIE_EVENT_LARGE_COUNT = 30,
    ZOMBIE_EVENT_LARGE_SUPPORT_COUNT = 20,
    ZOMBIE_EVENT_HUGE_COUNT = 60,
    ZOMBIE_EVENT_HUGE_SUPPORT_COUNT = 40,
    ZOMBIE_EVENT_SUPPORT_STACKS = 2,
    ZOMBIE_EVENT_SMALL_GOLD = 500,
    ZOMBIE_EVENT_MEDIUM_GOLD = 1000,
    ZOMBIE_EVENT_LARGE_GOLD = 3000,
    ZOMBIE_EVENT_HUGE_GOLD = 1000,
    GHOST_EVENT_SMALL_COUNT = 10,
    GHOST_EVENT_MEDIUM_COUNT = 15,
    GHOST_EVENT_LARGE_COUNT = 25,
    GHOST_EVENT_HUGE_COUNT = 50,
    GHOST_EVENT_SMALL_GOLD = 1000,
    GHOST_EVENT_MEDIUM_GOLD = 2000,
    GHOST_EVENT_LARGE_GOLD = 5000,
    GHOST_EVENT_HUGE_GOLD = 2000
} UndeadEventConstant;

typedef enum AIEventConstant {
    AI_EVENT_RESOURCE_COUNT = 7,
    AI_EVENT_ARMY_STACK_COUNT = 5,
    AI_EVENT_NO_OWNER = -1,
    AI_EVENT_NO_CREATURE = -1,
    AI_EVENT_ARTIFACT_LIMIT = 14,
    AI_EVENT_MAGIC_BOOK = 0x51,
    AI_EVENT_SPELL_SCROLL = 0x56,
    AI_EVENT_ROGUE_GUARD = 0x39,
    AI_EVENT_ROGUE_COUNT = 50,
    AI_EVENT_GUARD_COUNT_MAX = 255,
    AI_EVENT_MINE_SPELL_FIRST = 61,
    AI_EVENT_MINE_SPELL_LAST = 64,
    AI_EVENT_MINE_SPELL_LOOP_END = 999,
    AI_EVENT_MINE_SPELL_POWER_MAX = 51,
    AI_EVENT_MINE_SPELL_COUNT_SCALE = 5,
    AI_EVENT_DAEMON_GOLD = 2500,
    AI_EVENT_SEA_CHEST_GOLD = 1500,
    AI_EVENT_SEA_CHEST_ARTIFACT_GOLD = 1000,
    AI_EVENT_TREE_GOLD = 2000,
    AI_EVENT_TREE_GEMS = 10,
    AI_EVENT_ARTIFACT_GOLD = 2000,
    AI_EVENT_ARTIFACT_RESOURCE_3_GOLD = 2500,
    AI_EVENT_ARTIFACT_RESOURCE_5_GOLD = 3000,
    AI_EVENT_ARTIFACT_RESOURCE_3 = 3,
    AI_EVENT_ARTIFACT_RESOURCE_5 = 5,
    AI_EVENT_TELEPORT_STONE_DISTANCE = 1,
    AI_EVENT_TELEPORT_WHIRLPOOL_DISTANCE = 3,
    AI_EVENT_ABANDONED_MINE_ARMY_DIVISOR = 5,
    AI_EVENT_OBSERVATION_RADIUS = 20,
    AI_EVENT_WINDMILL_EMPTY = 99,
    AI_EVENT_RANDOM_EVENT_SUCCESS = 40,
    AI_EVENT_RANDOM_PERCENT_MAX = 100,
    AI_EVENT_HERO_TOWN_LOCATION = 0xa3,
    AI_EVENT_BOAT_CURSOR = 6,
    AI_EVENT_BOAT_RESTORE_MODE = 3,
    AI_EVENT_SITE_TYPE_MASK = 0x3f,
    AI_EVENT_SITE_LEVEL_SHIFT = 6,
    AI_EVENT_BARRIER_COLOR_MASK = 7,
    AI_EVENT_RECRUIT_TYPE_MASK = 7,
    AI_EVENT_RECRUIT_COUNT_SHIFT = 3,
    AI_EVENT_CURSED_ARTIFACT_COST = 750,
    AI_EVENT_CURSED_ARTIFACT_GOLD_THRESHOLD = 1500,
    AI_EVENT_GRAVEYARD_ARMY_REMAINDER = 1,
    AI_EVENT_CREATURE_UPGRADE_FROM = 7,
    AI_EVENT_CREATURE_UPGRADE_TO = 8,
    AI_EVENT_CREATURE_UPGRADE_MOBILITY = 400,
    AI_EVENT_HERO_LIMIT = 8,
    AI_EVENT_JAILED_HERO = 0x41,
    AI_EVENT_HERO_DIRECTION = 2,
    AI_EVENT_HERO_MAP_CHANGE = 3,
    AI_EVENT_HERO_MAP_CHANGE_VALUE = -999
} AIEventConstant;

typedef enum BarrierEventConstant {
    BARRIER_COLOR_MASK = 7,
    BARRIER_PASSWORD_SHIFT = 3,
    BARRIER_INPUT_LENGTH = 14,
    BARRIER_INPUT_BUFFER_SIZE = 16
} BarrierEventConstant;

typedef enum GenericSiteType {
    GENERIC_SITE_ALCHEMIST_TOWER = 0,
    GENERIC_SITE_ARENA = 1,
    GENERIC_SITE_HUT_OF_MAGI = 2,
    GENERIC_SITE_EYE_OF_MAGI = 3,
    GENERIC_SITE_STABLES = 4,
    GENERIC_SITE_MERMAIDS = 5,
    GENERIC_SITE_SIRENS = 6
} GenericSiteType;

typedef enum GenericSiteConstant {
    GENERIC_SITE_TYPE_MASK = 0x3f,
    GENERIC_SITE_LEVEL_SHIFT = 6,
    GENERIC_SITE_ARTIFACT_SLOT_COUNT = 14,
    GENERIC_SITE_ARMY_SLOT_COUNT = 5,
    GENERIC_SITE_ALCHEMIST_COST = 750,
    GENERIC_SITE_VISIBILITY_RADIUS = 10,
    GENERIC_SITE_HUT_COLOR = 3,
    GENERIC_SITE_STABLE_MOBILITY = 400,
    GENERIC_SITE_STABLE_CREATURE = 7,
    GENERIC_SITE_STABLE_UPGRADE = 8,
    GENERIC_SITE_STABLE_REWARD_TYPE = 18,
    GENERIC_SITE_STABLE_REWARD_VALUE = 8,
    GENERIC_SITE_MERMAID_WINDOW_ICON = 10,
    GENERIC_SITE_STRING_LIMIT = 10
} GenericSiteConstant;

#define GENERIC_SITE_SIREN_ARMY_REMAINDER 0.7

typedef enum FoundryCreatureType {
    FOUNDRY_PIKEMAN = 3,
    FOUNDRY_VETERAN_PIKEMAN = 4,
    FOUNDRY_SWORDSMAN = 5,
    FOUNDRY_MASTER_SWORDSMAN = 6,
    FOUNDRY_IRON_GOLEM = 40,
    FOUNDRY_STEEL_GOLEM = 41,
    FOUNDRY_DIALOG_CREATURE = 18
} FoundryCreatureType;

typedef enum HillFortCreatureType {
    HILL_FORT_ORC = 12,
    HILL_FORT_ORC_CHIEF = 13,
    HILL_FORT_OGRE = 15,
    HILL_FORT_OGRE_LORD = 16,
    HILL_FORT_DWARF = 21,
    HILL_FORT_BATTLE_DWARF = 22
} HillFortCreatureType;

typedef enum EventRecruitCreature {
    EVENT_RECRUIT_SPRITE = 20,
    EVENT_RECRUIT_ROGUE = 57,
    EVENT_RECRUIT_NOMAD = 58,
    EVENT_RECRUIT_GENIE = 60,
    EVENT_RECRUIT_MEDUSA = 61
} EventRecruitCreature;

typedef enum RecruitSiteType {
    RECRUIT_SITE_GENIE = 0,
    RECRUIT_SITE_EARTH_ELEMENTAL = 1,
    RECRUIT_SITE_AIR_ELEMENTAL = 2,
    RECRUIT_SITE_FIRE_ELEMENTAL = 3,
    RECRUIT_SITE_WATER_ELEMENTAL = 4
} RecruitSiteType;

typedef enum HouseRecruitmentSite {
    HOUSE_RECRUIT_ARCHER = 0,
    HOUSE_RECRUIT_GOBLIN = 1,
    HOUSE_RECRUIT_PEASANT = 2,
    HOUSE_RECRUIT_DWARF = 3,
    HOUSE_RECRUIT_LOG_CABIN = 4,
    HOUSE_RECRUIT_TREE_HOUSE = 5,
    HOUSE_RECRUIT_HALFLING = 6,
    HOUSE_RECRUIT_WATCH_TOWER = 7,
    HOUSE_RECRUIT_CAVE = 8,
    HOUSE_RECRUIT_EXCAVATION = 9,
    HOUSE_RECRUIT_SITE_COUNT = 10
} HouseRecruitmentSite;

typedef enum HouseEventConstant {
    HOUSE_EVENT_RECRUIT_DIALOG_BASE = 23,
    HOUSE_EVENT_ARMY_FULL_DIALOG_BASE = 24,
    HOUSE_EVENT_EMPTY_DIALOG_BASE = 25
} HouseEventConstant;

typedef enum EventSoundConstant {
    EVENT_SOUND_NONE = -1,
    EVENT_SOUND_TRACK_1 = 1,
    EVENT_SOUND_TREASURE = 19,
    EVENT_SOUND_EXPERIENCE = 22,
    EVENT_SOUND_TRACK_31 = 31,
    EVENT_SOUND_TRACK_32 = 32,
    EVENT_SOUND_TRACK_33 = 33,
    EVENT_SOUND_TRACK_34 = 34,
    EVENT_SOUND_TRACK_35 = 35,
    EVENT_SOUND_TRACK_36 = 36,
    EVENT_SOUND_TRACK_37 = 37,
    EVENT_SOUND_TRACK_38 = 38,
    EVENT_SOUND_TRACK_39 = 39,
    EVENT_SOUND_TRACK_40 = 40,
    EVENT_SOUND_MORALE = 100,
    EVENT_SOUND_LUCK = 101,
    EVENT_SOUND_PICKUP = 102,
    EVENT_SOUND_MINE = 103,
    EVENT_SOUND_FILENAME_LENGTH = 32,
    EVENT_SOUND_SAMPLE_NAME_EMPTY_LIMIT = 1
} EventSoundConstant;

typedef enum EventSoundVariant {
    EVENT_SOUND_VARIANT_0 = 0,
    EVENT_SOUND_VARIANT_1 = 1,
    EVENT_SOUND_VARIANT_2 = 2,
    EVENT_SOUND_VARIANT_3 = 3,
    EVENT_SOUND_VARIANT_4 = 4,
    EVENT_SOUND_VARIANT_5 = 5,
    EVENT_SOUND_VARIANT_6 = 6
} EventSoundVariant;

typedef enum EraseObjectConstant {
    ERASE_NEIGHBOR_COUNT = 4,
    ERASE_CELL_COUNT = 5,
    ERASE_NO_FRAME = -1,
    ERASE_EMPTY_INDEX = 0xff,
    ERASE_CLEARED_TILESET = 47,
    ERASE_MAP_CHANGE_OBJECT = 5,
    ERASE_MAP_CHANGE_VALUE = -999,
    ERASE_ENVIRONMENT_BORDER = 7
} EraseObjectConstant;

typedef enum EraseObjectTileset {
    ERASE_TILESET_11 = 11,
    ERASE_TILESET_46 = 46,
    ERASE_TILESET_50 = 50,
    ERASE_TILESET_55 = 55,
    ERASE_TILESET_59 = 59,
    ERASE_TILESET_62 = 62,
    ERASE_TILESET_63 = 63
} EraseObjectTileset;

typedef enum MonsterInteractionConstant {
    MONSTER_JOIN_FORCED = 0x1000,
    MONSTER_COUNT_MASK = 0xfff,
    MONSTER_DIPLOMACY_NONE = 0,
    MONSTER_DIPLOMACY_BASIC = 1,
    MONSTER_DIPLOMACY_ADVANCED = 2,
    MONSTER_DIPLOMACY_EXPERT = 3,
    MONSTER_NO_JOIN_ARTIFACT = 0x46,
    MONSTER_DIALOG_YES = 0x7805,
    MONSTER_DIALOG_NO = 0x7806,
    MONSTER_OFFER_BUFFER_SIZE = 300
} MonsterInteractionConstant;

#define MONSTER_STRENGTH_JOIN 2.0
#define MONSTER_STRENGTH_FLEE 5.0

typedef enum MonsterInteractionType {
    MONSTER_OGRE = 0x0f,
    MONSTER_OGRE_LORD = 0x10,
    MONSTER_DWARF = 0x15,
    MONSTER_BATTLE_DWARF = 0x16,
    MONSTER_ELF = 0x17,
    MONSTER_GRAND_ELF = 0x18,
    MONSTER_GREEN_DRAGON = 0x23,
    MONSTER_RED_DRAGON = 0x24,
    MONSTER_BLACK_DRAGON = 0x25,
    MONSTER_TITAN = 0x2e,
    MONSTER_SKELETON = 0x2f,
    MONSTER_GENIE = 0x3b,
    MONSTER_EARTH_ELEMENTAL = 0x3e,
    MONSTER_AIR_ELEMENTAL = 0x3f,
    MONSTER_FIRE_ELEMENTAL = 0x40,
    MONSTER_WATER_ELEMENTAL = 0x41
} MonsterInteractionType;

#define MONSTER_NECROMANCY_FRACTION 0.1
#define MONSTER_AI_JOIN_COST_FRACTION 0.75

typedef enum CombatMonsterEventConstant {
    COMBAT_MONSTER_ARMY_SLOTS = 5,
    COMBAT_MONSTER_INVALID_TYPE = -1,
    COMBAT_MONSTER_RANDOM_MAX = 100,
    COMBAT_MONSTER_REDUCED_STACK_CHANCE = 25,
    COMBAT_MONSTER_FOUR_STACK_THRESHOLD = 50,
    COMBAT_MONSTER_UPGRADE_CHANCE = 50
} CombatMonsterEventConstant;

typedef enum EventArtifactType {
    EVENT_ARTIFACT_ULTIMATE_BOOK = 0,
    EVENT_ARTIFACT_ULTIMATE_SWORD = 1,
    EVENT_ARTIFACT_ULTIMATE_CLOAK = 2,
    EVENT_ARTIFACT_ULTIMATE_WAND = 3,
    EVENT_ARTIFACT_ULTIMATE_SHIELD = 4,
    EVENT_ARTIFACT_ULTIMATE_STAFF = 5,
    EVENT_ARTIFACT_ULTIMATE_CROWN = 6,
    EVENT_ARTIFACT_GOLDEN_GOOSE = 7,
    EVENT_ARTIFACT_ARCANE_NECKLACE = 8,
    EVENT_ARTIFACT_CASTER_BRACELET = 9,
    EVENT_ARTIFACT_MAGE_RING = 10,
    EVENT_ARTIFACT_WITCHES_BROACH = 11,
    EVENT_ARTIFACT_MEDAL_VALOR = 12,
    EVENT_ARTIFACT_MEDAL_COURAGE = 13,
    EVENT_ARTIFACT_MEDAL_HONOR = 14,
    EVENT_ARTIFACT_MEDAL_DISTINCTION = 15,
    EVENT_ARTIFACT_FIZBIN_MISFORTUNE = 16,
    EVENT_ARTIFACT_THUNDER_MACE = 17,
    EVENT_ARTIFACT_ARMORED_GAUNTLETS = 18,
    EVENT_ARTIFACT_DEFENDER_HELM = 19,
    EVENT_ARTIFACT_GIANT_FLAIL = 20,
    EVENT_ARTIFACT_BALLISTA = 21,
    EVENT_ARTIFACT_STEALTH_SHIELD = 22,
    EVENT_ARTIFACT_DRAGON_SWORD = 23,
    EVENT_ARTIFACT_POWER_AXE = 24,
    EVENT_ARTIFACT_DIVINE_BREASTPLATE = 25,
    EVENT_ARTIFACT_MINOR_SCROLL = 26,
    EVENT_ARTIFACT_MAJOR_SCROLL = 27,
    EVENT_ARTIFACT_SUPERIOR_SCROLL = 28,
    EVENT_ARTIFACT_FOREMOST_SCROLL = 29,
    EVENT_ARTIFACT_ENDLESS_SACK_GOLD = 30,
    EVENT_ARTIFACT_ENDLESS_BAG_GOLD = 31,
    EVENT_ARTIFACT_ENDLESS_PURSE_GOLD = 32,
    EVENT_ARTIFACT_NOMAD_BOOTS = 33,
    EVENT_ARTIFACT_TRAVELER_BOOTS = 34,
    EVENT_ARTIFACT_RABBIT_FOOT = 35,
    EVENT_ARTIFACT_GOLDEN_HORSESHOE = 36,
    EVENT_ARTIFACT_GAMBLERS_COIN = 37,
    EVENT_ARTIFACT_FOUR_LEAF_CLOVER = 38,
    EVENT_ARTIFACT_TRUE_COMPASS = 39,
    EVENT_ARTIFACT_SAILORS_ASTROLABE = 40,
    EVENT_ARTIFACT_EVIL_EYE = 41,
    EVENT_ARTIFACT_ENCHANTED_HOURGLASS = 42,
    EVENT_ARTIFACT_GOLD_WATCH = 43,
    EVENT_ARTIFACT_SKULLCAP = 44,
    EVENT_ARTIFACT_ICE_CLOAK = 45,
    EVENT_ARTIFACT_FIRE_CLOAK = 46,
    EVENT_ARTIFACT_LIGHTNING_HELM = 47,
    EVENT_ARTIFACT_EVERCOLD_ICICLE = 48,
    EVENT_ARTIFACT_EVERHOT_LAVA_ROCK = 49,
    EVENT_ARTIFACT_LIGHTNING_ROD = 50,
    EVENT_ARTIFACT_SNAKE_RING = 51,
    EVENT_ARTIFACT_ANKH = 52,
    EVENT_ARTIFACT_BOOK_ELEMENTS = 53,
    EVENT_ARTIFACT_ELEMENTAL_RING = 54,
    EVENT_ARTIFACT_HOLY_PENDANT = 55,
    EVENT_ARTIFACT_PENDANT_FREE_WILL = 56,
    EVENT_ARTIFACT_PENDANT_LIFE = 57,
    EVENT_ARTIFACT_SERENITY_PENDANT = 58,
    EVENT_ARTIFACT_SEEING_EYE_PENDANT = 59,
    EVENT_ARTIFACT_KINETIC_PENDANT = 60,
    EVENT_ARTIFACT_PENDANT_DEATH = 61,
    EVENT_ARTIFACT_WAND_NEGATION = 62,
    EVENT_ARTIFACT_GOLDEN_BOW = 63,
    EVENT_ARTIFACT_TELESCOPE = 64,
    EVENT_ARTIFACT_STATESMAN_QUILL = 65,
    EVENT_ARTIFACT_WIZARD_HAT = 66,
    EVENT_ARTIFACT_POWER_RING = 67,
    EVENT_ARTIFACT_AMMO_CART = 68,
    EVENT_ARTIFACT_TAX_LIEN = 69,
    EVENT_ARTIFACT_HIDEOUS_MASK = 70,
    EVENT_ARTIFACT_ENDLESS_POUCH_SULFUR = 71,
    EVENT_ARTIFACT_ENDLESS_VIAL_MERCURY = 72,
    EVENT_ARTIFACT_ENDLESS_POUCH_GEMS = 73,
    EVENT_ARTIFACT_ENDLESS_CORD_WOOD = 74,
    EVENT_ARTIFACT_ENDLESS_CART_ORE = 75,
    EVENT_ARTIFACT_ENDLESS_POUCH_CRYSTAL = 76,
    EVENT_ARTIFACT_SPIKED_HELM = 77,
    EVENT_ARTIFACT_SPIKED_SHIELD = 78,
    EVENT_ARTIFACT_WHITE_PEARL = 79,
    EVENT_ARTIFACT_BLACK_PEARL = 80,
    EVENT_ARTIFACT_MAGIC_BOOK = 81,
    EVENT_ARTIFACT_EDITOR_ANY_ULTIMATE = 82,
    EVENT_ARTIFACT_EDITOR_UNUSED_84 = 83,
    EVENT_ARTIFACT_EDITOR_UNUSED_85 = 84,
    EVENT_ARTIFACT_EDITOR_UNUSED_86 = 85,
    EVENT_ARTIFACT_SPELL_SCROLL = 86,
    EVENT_ARTIFACT_ARM_OF_MARTYR = 87,
    EVENT_ARTIFACT_BREASTPLATE_ANDURAN = 88,
    EVENT_ARTIFACT_BROACH_SHIELDING = 89,
    EVENT_ARTIFACT_BATTLE_GARB = 90,
    EVENT_ARTIFACT_CRYSTAL_BALL = 91,
    EVENT_ARTIFACT_HEART_FIRE = 92,
    EVENT_ARTIFACT_HEART_ICE = 93,
    EVENT_ARTIFACT_HELMET_ANDURAN = 94,
    EVENT_ARTIFACT_HOLY_HAMMER = 95,
    EVENT_ARTIFACT_LEGENDARY_SCEPTER = 96,
    EVENT_ARTIFACT_MASTHEAD = 97,
    EVENT_ARTIFACT_SPHERE_NEGATION = 98,
    EVENT_ARTIFACT_STAFF_WIZARDRY = 99,
    EVENT_ARTIFACT_SWORD_BREAKER = 100,
    EVENT_ARTIFACT_SWORD_ANDURAN = 101,
    EVENT_ARTIFACT_SPADE_NECROMANCY = 102,
    EVENT_ARTIFACT_COUNT = 103
} EventArtifactType;

typedef enum EventArtifactStatConstant {
    EVENT_ARTIFACT_PRIMARY_STAT_COUNT = 4,
    EVENT_ARTIFACT_SLOT_COUNT = 14,
    EVENT_ARTIFACT_NONE = -1,
    EVENT_ARTIFACT_NON_TRANSFERABLE_LAST = EVENT_ARTIFACT_ULTIMATE_WAND,
    EVENT_ARTIFACT_TAKE = 1,
    EVENT_ARTIFACT_SPELL_POINT_MULTIPLIER = 10
} EventArtifactStatConstant;

typedef enum EventEffectConstant {
    EVENT_WHIRLPOOL_TRIGGER_ROLL = 1,
    EVENT_WHIRLPOOL_TRIGGER_MAX = 3,
    EVENT_WHIRLPOOL_ARMY_VALUE_LIMIT = 99999999,
    EVENT_FIZZLE_HERO_LOSS = 0,
    EVENT_FIZZLE_ARTIFACT = 1,
    EVENT_FIZZLE_X = 168,
    EVENT_FIZZLE_Y = 160,
    EVENT_FIZZLE_WIDTH = 132,
    EVENT_FIZZLE_HEIGHT = 132,
    EVENT_FIZZLE_STEPS = 65
} EventEffectConstant;

signed char StrEqNoCase(char *, char *);
int GiveArtifact(class hero *, int, int, signed char);
void GiveTakeArtifactStat(class hero *, int, int);
int RiddleStringsEqual(char *, char *);

#endif // HOMM2_EVENTS_H
