#ifndef HOMM2_EVENTS_H
#define HOMM2_EVENTS_H
// Declarations of the free functions DEFINED in EVENTS.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
class hero;

typedef enum MapEventType {
    MAP_EVENT_BUOY = 3,
    MAP_EVENT_SKELETON = 4,
    MAP_EVENT_DAEMON_CAVE = 5,
    MAP_EVENT_TREASURE_CHEST = 6,
    MAP_EVENT_FAERIE_RING = 7,
    MAP_EVENT_CAMPFIRE = 8,
    MAP_EVENT_FOUNTAIN = 9,
    MAP_EVENT_GAZEBO = 10,
    MAP_EVENT_ANCIENT_LAMP = 11,
    MAP_EVENT_GRAVEYARD = 12,
    MAP_EVENT_ARCHER_HOUSE = 13,
    MAP_EVENT_GOBLIN_HUT = 14,
    MAP_EVENT_DWARF_COTTAGE = 15,
    MAP_EVENT_PEASANT_HUT = 16,
    MAP_EVENT_LOG_CABIN = 17,
    MAP_EVENT_MAP_EVENT = 18,
    MAP_EVENT_DRAGON_CITY = 19,
    MAP_EVENT_LIGHTHOUSE = 20,
    MAP_EVENT_WATER_WHEEL = 21,
    MAP_EVENT_MINE = 22,
    MAP_EVENT_MONSTER = 23,
    MAP_EVENT_OBELISK = 24,
    MAP_EVENT_OASIS = 25,
    MAP_EVENT_RESOURCE = 26,
    MAP_EVENT_SAWMILL = 27,
    MAP_EVENT_ORACLE = 28,
    MAP_EVENT_SHRINE_FIRST_CIRCLE = 29,
    MAP_EVENT_SHIPWRECK = 30,
    MAP_EVENT_SEA_CHEST = 31,
    MAP_EVENT_DESERT_TENT = 32,
    MAP_EVENT_CASTLE = 33,
    MAP_EVENT_STONE_LITHS = 34,
    MAP_EVENT_WAGON_CAMP = 35,
    MAP_EVENT_HUT_OF_MAGI = 36,
    MAP_EVENT_WHIRLPOOL = 37,
    MAP_EVENT_WINDMILL = 38,
    MAP_EVENT_ARTIFACT = 39,
    MAP_EVENT_MERMAID = 40,
    MAP_EVENT_BOAT = 41,
    MAP_EVENT_RANDOM_ULTIMATE_ARTIFACT = 42,
    MAP_EVENT_RANDOM_ARTIFACT = 43,
    MAP_EVENT_RANDOM_RESOURCE = 44,
    MAP_EVENT_RANDOM_MONSTER = 45,
    MAP_EVENT_RANDOM_TOWN = 46,
    MAP_EVENT_RANDOM_CASTLE = 47,
    MAP_EVENT_EYE_OF_MAGI = 48,
    MAP_EVENT_RANDOM_MONSTER_WEAK = 49,
    MAP_EVENT_RANDOM_MONSTER_MEDIUM = 50,
    MAP_EVENT_RANDOM_MONSTER_STRONG = 51,
    MAP_EVENT_RANDOM_MONSTER_VERY_STRONG = 52,
    MAP_EVENT_HERO = 53,
    MAP_EVENT_NOTHING_SPECIAL = 54,
    MAP_EVENT_MOSSY_ROCK = 55,
    MAP_EVENT_WATCH_TOWER = 56,
    MAP_EVENT_TREE_HOUSE = 57,
    MAP_EVENT_TREE_CITY = 58,
    MAP_EVENT_RUINS = 59,
    MAP_EVENT_FORT = 60,
    MAP_EVENT_TRADING_POST = 61,
    MAP_EVENT_ABANDONED_MINE = 62,
    MAP_EVENT_SIRENS = 63,
    MAP_EVENT_STANDING_STONES = 64,
    MAP_EVENT_IDOL = 65,
    MAP_EVENT_TREE_OF_KNOWLEDGE = 66,
    MAP_EVENT_WITCH_DOCTOR_HUT = 67,
    MAP_EVENT_TEMPLE = 68,
    MAP_EVENT_HILL_FORT = 69,
    MAP_EVENT_HALFLING_HOLE = 70,
    MAP_EVENT_MERCENARY_CAMP = 71,
    MAP_EVENT_SHRINE_SECOND_CIRCLE = 72,
    MAP_EVENT_SHRINE_THIRD_CIRCLE = 73,
    MAP_EVENT_PYRAMID = 74,
    MAP_EVENT_CITY_OF_DEAD = 75,
    MAP_EVENT_EXCAVATION = 76,
    MAP_EVENT_SPHINX = 77,
    MAP_EVENT_WAGON = 78,
    MAP_EVENT_TAR_PIT = 79,
    MAP_EVENT_ARTESIAN_SPRING = 80,
    MAP_EVENT_TROLL_BRIDGE = 81,
    MAP_EVENT_WATERING_HOLE = 82,
    MAP_EVENT_WITCH_HUT = 83,
    MAP_EVENT_XANADU = 84,
    MAP_EVENT_CAVE = 85,
    MAP_EVENT_LEAN_TO = 86,
    MAP_EVENT_MAGELLAN_MAPS = 87,
    MAP_EVENT_FLOTSAM = 88,
    MAP_EVENT_DERELICT_SHIP = 89,
    MAP_EVENT_SHIPWRECK_SURVIVOR = 90,
    MAP_EVENT_BOTTLE = 91,
    MAP_EVENT_MAGIC_WELL = 92,
    MAP_EVENT_MAGIC_GARDEN = 93,
    MAP_EVENT_OBSERVATION_TOWER = 94,
    MAP_EVENT_FREEMANS_FOUNDRY = 95,
    MAP_EVENT_REEFS = 96,
    MAP_EVENT_TREES = 97,
    MAP_EVENT_MOUNTAINS = 98,
    MAP_EVENT_VOLCANO = 99,
    MAP_EVENT_FLOWERS = 100,
    MAP_EVENT_ROCK = 101,
    MAP_EVENT_WATER_LAKE = 102,
    MAP_EVENT_MANDRAKE = 103,
    MAP_EVENT_DEAD_TREE = 104,
    MAP_EVENT_STUMP = 105,
    MAP_EVENT_CRATER = 106,
    MAP_EVENT_CACTUS = 107,
    MAP_EVENT_MOUND = 108,
    MAP_EVENT_DUNE = 109,
    MAP_EVENT_LAVA_POOL = 110,
    MAP_EVENT_SHRUB = 111,
    MAP_EVENT_ARENA = 112,
    MAP_EVENT_BARROW_MOUNDS = 113,
    MAP_EVENT_RANDOM_TREASURE_ARTIFACT = 114,
    MAP_EVENT_RANDOM_MINOR_ARTIFACT = 115,
    MAP_EVENT_RANDOM_MAJOR_ARTIFACT = 116,
    MAP_EVENT_BARRIER = 117,
    MAP_EVENT_TRAVELER_TENT = 118,
    MAP_EVENT_EXPANSION_DWELLING = 119,
    MAP_EVENT_EXPANSION_OBJECT = 120,
    MAP_EVENT_JAIL = 121,
    MAP_EVENT_EXPANSION_ALTAR = 122,
    MAP_EVENT_EXPANSION_SITE = 123
} MapEventType;

typedef enum EventSoundConstant {
    EVENT_SOUND_NONE = -1,
    EVENT_SOUND_TRACK_1 = 1,
    EVENT_SOUND_TREASURE = 19,
    EVENT_SOUND_EXPERIENCE = 22,
    EVENT_SOUND_TRACK_31 = 31,
    EVENT_SOUND_TRACK_32 = 32,
    EVENT_SOUND_TRACK_33 = 33,
    EVENT_SOUND_TRACK_34 = 34,
    EVENT_SOUND_TRACK_35 = 35,
    EVENT_SOUND_TRACK_36 = 36,
    EVENT_SOUND_TRACK_37 = 37,
    EVENT_SOUND_TRACK_38 = 38,
    EVENT_SOUND_TRACK_39 = 39,
    EVENT_SOUND_TRACK_40 = 40,
    EVENT_SOUND_MORALE = 100,
    EVENT_SOUND_LUCK = 101,
    EVENT_SOUND_PICKUP = 102,
    EVENT_SOUND_MINE = 103,
    EVENT_SOUND_FILENAME_LENGTH = 32,
    EVENT_SOUND_SAMPLE_NAME_EMPTY_LIMIT = 1
} EventSoundConstant;

typedef enum EventSoundVariant {
    EVENT_SOUND_VARIANT_0 = 0,
    EVENT_SOUND_VARIANT_1 = 1,
    EVENT_SOUND_VARIANT_2 = 2,
    EVENT_SOUND_VARIANT_3 = 3,
    EVENT_SOUND_VARIANT_4 = 4,
    EVENT_SOUND_VARIANT_5 = 5,
    EVENT_SOUND_VARIANT_6 = 6
} EventSoundVariant;

typedef enum EraseObjectConstant {
    ERASE_NEIGHBOR_COUNT = 4,
    ERASE_CELL_COUNT = 5,
    ERASE_NO_FRAME = -1,
    ERASE_EMPTY_INDEX = 0xff,
    ERASE_CLEARED_TILESET = 47,
    ERASE_MAP_CHANGE_OBJECT = 5,
    ERASE_MAP_CHANGE_VALUE = -999,
    ERASE_ENVIRONMENT_BORDER = 7
} EraseObjectConstant;

typedef enum EraseObjectTileset {
    ERASE_TILESET_11 = 11,
    ERASE_TILESET_46 = 46,
    ERASE_TILESET_50 = 50,
    ERASE_TILESET_55 = 55,
    ERASE_TILESET_59 = 59,
    ERASE_TILESET_62 = 62,
    ERASE_TILESET_63 = 63
} EraseObjectTileset;

typedef enum MonsterInteractionConstant {
    MONSTER_JOIN_FORCED = 0x1000,
    MONSTER_COUNT_MASK = 0xfff,
    MONSTER_DIPLOMACY_NONE = 0,
    MONSTER_DIPLOMACY_BASIC = 1,
    MONSTER_DIPLOMACY_ADVANCED = 2,
    MONSTER_DIPLOMACY_EXPERT = 3,
    MONSTER_NO_JOIN_ARTIFACT = 0x46,
    MONSTER_DIALOG_YES = 0x7805,
    MONSTER_OFFER_BUFFER_SIZE = 300
} MonsterInteractionConstant;

#define MONSTER_STRENGTH_JOIN 2.0
#define MONSTER_STRENGTH_FLEE 5.0

typedef enum MonsterInteractionType {
    MONSTER_OGRE = 0x0f,
    MONSTER_OGRE_LORD = 0x10,
    MONSTER_DWARF = 0x15,
    MONSTER_BATTLE_DWARF = 0x16,
    MONSTER_ELF = 0x17,
    MONSTER_GRAND_ELF = 0x18,
    MONSTER_GREEN_DRAGON = 0x23,
    MONSTER_RED_DRAGON = 0x24,
    MONSTER_BLACK_DRAGON = 0x25,
    MONSTER_GENIE = 0x3b,
    MONSTER_EARTH_ELEMENTAL = 0x3e,
    MONSTER_AIR_ELEMENTAL = 0x3f,
    MONSTER_FIRE_ELEMENTAL = 0x40,
    MONSTER_WATER_ELEMENTAL = 0x41
} MonsterInteractionType;

signed char StrEqNoCase(char *, char *);
int GiveArtifact(class hero *, int, int, signed char);
void GiveTakeArtifactStat(class hero *, int, int);
int RiddleStringsEqual(char *, char *);

#endif // HOMM2_EVENTS_H
