#ifndef HOMM2_SOURCE_EXPCAMPAIGN_H
#define HOMM2_SOURCE_EXPCAMPAIGN_H
// Reconstructed class (SOURCE) from CodeView NB09 of HEROES2W.EXE — NOT original source.
// 36 methods, 0 own-virtual, 0 static data.
#include <va.h>
#include <SOURCE/Campaign.h>
// forward declarations:
class heroWindow;
struct tag_message;

typedef enum ExpansionCampaignId {
    EXPANSION_CAMPAIGN_PRICE_OF_LOYALTY = 0,
    EXPANSION_CAMPAIGN_DESCENDANTS = 1,
    EXPANSION_CAMPAIGN_WIZARDS_ISLE = 2,
    EXPANSION_CAMPAIGN_VOYAGE_HOME = 3,
    EXPANSION_CAMPAIGN_COUNT = 4
} ExpansionCampaignId;

typedef enum ExpansionCampaignConstant {
    EXPANSION_CAMPAIGN_MAX_MAP_COUNT = 8,
    EXPANSION_CAMPAIGN_BONUS_CHOICE_COUNT = 3,
    EXPANSION_CAMPAIGN_AWARD_COUNT = 11,
    EXPANSION_CAMPAIGN_PLAYER_SETUP_RESET_SIZE = 0x41,
    EXPANSION_CAMPAIGN_ARMY_NAME_BUFFER_SIZE = 52,
    EXPANSION_CAMPAIGN_HERO_COUNT = 54,
    EXPANSION_CAMPAIGN_TRACK_ICON_SIZE = 41,
    EXPANSION_CAMPAIGN_TRACK_ICON_COLOR = 0x10,
    EXPANSION_CAMPAIGN_MAP_FILENAME_SIZE = 13,
    EXPANSION_CAMPAIGN_SCROLL_ARTIFACT = 0x56,
    EXPANSION_CAMPAIGN_SET_GUARDIAN_SPELL = 0x3d,
    EXPANSION_CAMPAIGN_SPECIAL_SKILL_LEVEL = 1,
    EXPANSION_CAMPAIGN_SPECIAL_SKILL = 12,
    EXPANSION_CAMPAIGN_SPECIAL_SKILL_ALT_LEVEL = 2,
    EXPANSION_CAMPAIGN_SPECIAL_SKILL_ALT = 2,
    EXPANSION_CAMPAIGN_NON_SCROLL_SPELL_FIRST = 0x22,
    EXPANSION_CAMPAIGN_NON_SCROLL_SPELL_SECOND = 0x27,
    EXPANSION_CAMPAIGN_ICON_FRAME_BASE = 15,
    EXPANSION_CAMPAIGN_MUSIC = 24,
    EXPANSION_CAMPAIGN_DAYS_PER_WEEK = 7,
    EXPANSION_CAMPAIGN_DAYS_PER_MONTH = 28,
    EXPANSION_CAMPAIGN_FIRST_ALTERNATE_NAME_MAP = 4,
    EXPANSION_CAMPAIGN_IVAN_NAME_OFFSET = 6,
    EXPANSION_CAMPAIGN_MAIN_PLAYER = 0,
    EXPANSION_CAMPAIGN_GOLDEN_BOW_EVENT_X = 5,
    EXPANSION_CAMPAIGN_GOLDEN_BOW_EVENT_Y = 0
} ExpansionCampaignConstant;

typedef enum ExpansionCampaignHeroPortrait {
    EXPANSION_HERO_DAINWIN = 0x3d,
    EXPANSION_HERO_GALLAVANT = 0x41,
    EXPANSION_HERO_CEALLACH = 0x43
} ExpansionCampaignHeroPortrait;

typedef enum ExpansionCampaignAward {
    EXPANSION_AWARD_ELVEN_ALLIANCE = 0,
    EXPANSION_AWARD_BREASTPLATE_ANDURAN = 1,
    EXPANSION_AWARD_WOOD_BONUS = 2,
    EXPANSION_AWARD_HELMET_ANDURAN = 3,
    EXPANSION_AWARD_DEFEAT_KRAEGER = 4,
    EXPANSION_AWARD_BATTLE_GARB = 5,
    EXPANSION_AWARD_WAYWARD_SON = 6,
    EXPANSION_AWARD_UNCLE_IVAN = 7,
    EXPANSION_AWARD_LEGENDARY_SCEPTER = 8,
    EXPANSION_AWARD_SET_GUARDIAN = 9,
    EXPANSION_AWARD_SPHERE_NEGATION = 10
} ExpansionCampaignAward;

typedef enum ExpansionCampaignMap {
    EXPANSION_MAP_NONE = -1,
    EXPANSION_MAP_POL_UPRISING = 0,
    EXPANSION_MAP_POL_ISLAND_OF_CHAOS = 1,
    EXPANSION_MAP_POL_ARROWS_FLIGHT = 2,
    EXPANSION_MAP_POL_ABYSS = 3,
    EXPANSION_MAP_POL_GIANTS_PASS = 4,
    EXPANSION_MAP_POL_AURORA_BOREALIS = 5,
    EXPANSION_MAP_POL_BETRAYALS_END = 6,
    EXPANSION_MAP_POL_CORRUPTIONS_HEART = 7,
    EXPANSION_MAP_DES_CONQUER_AND_UNIFY = 0,
    EXPANSION_MAP_DES_BORDER_TOWNS = 1,
    EXPANSION_MAP_DES_WAYWARD_SON = 2,
    EXPANSION_MAP_DES_UNCLE_IVAN = 3,
    EXPANSION_MAP_DES_SOUTHERN_WAR = 4,
    EXPANSION_MAP_DES_IVORY_GATES = 5,
    EXPANSION_MAP_DES_ELVEN_LANDS = 6,
    EXPANSION_MAP_DES_EPIC_BATTLE = 7,
    EXPANSION_MAP_WIZ_SHROUDED_ISLES = 0,
    EXPANSION_MAP_WIZ_ETERNAL_SCROLLS = 1,
    EXPANSION_MAP_WIZ_POWERS_END = 2,
    EXPANSION_MAP_WIZ_FOUNT_OF_WIZARDRY = 3,
    EXPANSION_MAP_VOY_STRANDED = 0,
    EXPANSION_MAP_VOY_PIRATE_ISLES = 1,
    EXPANSION_MAP_VOY_KING_AND_COUNTRY = 2,
    EXPANSION_MAP_VOY_BLOOD_IS_THICKER = 3
} ExpansionCampaignMap;

typedef enum ExpansionCampaignSmacker {
    EXPANSION_SMACKER_POL_INTRO = 0x27,
    EXPANSION_SMACKER_POL_UPRISING = 0x28,
    EXPANSION_SMACKER_POL_ISLAND_OF_CHAOS = 0x29,
    EXPANSION_SMACKER_POL_ARROWS_FLIGHT = 0x2a,
    EXPANSION_SMACKER_POL_BRANCH_REUNITED = 0x2b,
    EXPANSION_SMACKER_POL_AURORA_BOREALIS = 0x2c,
    EXPANSION_SMACKER_POL_BETRAYALS_END = 0x2d,
    EXPANSION_SMACKER_POL_CORRUPTIONS_HEART = 0x2e,
    EXPANSION_SMACKER_DES_INTRO = 0x2f,
    EXPANSION_SMACKER_DES_CONQUER_AND_UNIFY = 0x30,
    EXPANSION_SMACKER_DES_BORDER_TOWNS = 0x31,
    EXPANSION_SMACKER_DES_FAMILY_REUNITED = 0x32,
    EXPANSION_SMACKER_DES_SOUTHERN_WAR = 0x33,
    EXPANSION_SMACKER_DES_BRANCH_REUNITED = 0x34,
    EXPANSION_SMACKER_DES_EPIC_BATTLE = 0x35,
    EXPANSION_SMACKER_WIZ_INTRO = 0x36,
    EXPANSION_SMACKER_WIZ_SHROUDED_ISLES = 0x37,
    EXPANSION_SMACKER_WIZ_ETERNAL_SCROLLS = 0x38,
    EXPANSION_SMACKER_WIZ_POWERS_END = 0x39,
    EXPANSION_SMACKER_WIZ_FOUNT_OF_WIZARDRY = 0x3a,
    EXPANSION_SMACKER_VOY_INTRO = 0x3b,
    EXPANSION_SMACKER_VOY_STRANDED = 0x3c,
    EXPANSION_SMACKER_VOY_PIRATE_ISLES = 0x3d,
    EXPANSION_SMACKER_VOY_KING_AND_COUNTRY = 0x3e,
    EXPANSION_SMACKER_VOY_BLOOD_IS_THICKER = 0x3f,
    EXPANSION_SMACKER_CAMPAIGN_CHOICE = 0x43
} ExpansionCampaignSmacker;

typedef enum ExpansionCampaignResource {
    EXPANSION_CAMPAIGN_RESOURCE_WOOD = 0,
    EXPANSION_CAMPAIGN_RESOURCE_MERCURY = 1,
    EXPANSION_CAMPAIGN_RESOURCE_ORE = 2,
    EXPANSION_CAMPAIGN_RESOURCE_SULFUR = 3,
    EXPANSION_CAMPAIGN_RESOURCE_CRYSTAL = 4,
    EXPANSION_CAMPAIGN_RESOURCE_GEMS = 5,
    EXPANSION_CAMPAIGN_RESOURCE_GOLD = 6
} ExpansionCampaignResource;

typedef enum ExpansionCampaignChoiceConstant {
    EXPANSION_CAMPAIGN_CHOICE_UNUSED_VALUE = -1,
    EXPANSION_CAMPAIGN_CHOICE_NO_AMOUNT = -1,
    EXPANSION_CAMPAIGN_CHOICE_ZERO_AMOUNT = 0,
    EXPANSION_CAMPAIGN_ARTIFACT_AMOUNT_ONE = 1,
    EXPANSION_CAMPAIGN_PRIMARY_BONUS_ONE = 1,
    EXPANSION_CAMPAIGN_PRIMARY_BONUS_TWO = 2,
    EXPANSION_CAMPAIGN_CRUSADER_COUNT = 3,
    EXPANSION_CAMPAIGN_MAGE_COUNT = 5,
    EXPANSION_CAMPAIGN_WOOD_FIVE = 5,
    EXPANSION_CAMPAIGN_ORE_FIVE = 5,
    EXPANSION_CAMPAIGN_WOOD_TEN = 10,
    EXPANSION_CAMPAIGN_SULFUR_TEN = 10,
    EXPANSION_CAMPAIGN_CRYSTAL_TEN = 10,
    EXPANSION_CAMPAIGN_SULFUR_FIFTEEN = 15,
    EXPANSION_CAMPAIGN_WOOD_TWENTY = 20,
    EXPANSION_CAMPAIGN_WOOD_FIFTY = 50,
    EXPANSION_CAMPAIGN_GOLD_FIVE_HUNDRED = 500,
    EXPANSION_CAMPAIGN_GOLD_ONE_THOUSAND = 1000,
    EXPANSION_CAMPAIGN_GOLD_TWO_THOUSAND = 2000,
    EXPANSION_CAMPAIGN_GOLD_THREE_THOUSAND = 3000,
    EXPANSION_CAMPAIGN_GOLD_PENALTY_ONE_THOUSAND = -1000,
    EXPANSION_CAMPAIGN_WOOD_PENALTY_TEN = -10,
    EXPANSION_CAMPAIGN_MERCURY_PENALTY_TWO = -2,
    EXPANSION_CAMPAIGN_SPELL_VIEW_HEROES = 52
} ExpansionCampaignChoiceConstant;

#pragma pack(push, 1)  // recovered layout is byte-packed
class ExpCampaign {
public:
    i32 m_campaignId;  // +0x00
    i32 m_currentMap;  // +0x04
    i32 m_mapCount;  // +0x08
    u8 m_mapChoices[EXPANSION_CAMPAIGN_MAX_MAP_COUNT];  // +0x0c
    u8 m_mapsPlayed[EXPANSION_CAMPAIGN_MAX_MAP_COUNT];  // +0x14
    i16 m_mapDays[EXPANSION_CAMPAIGN_MAX_MAP_COUNT];  // +0x1c
    u8 m_awards[EXPANSION_CAMPAIGN_AWARD_COUNT];  // +0x2c
    u8 m_bonusChoices[EXPANSION_CAMPAIGN_MAX_MAP_COUNT];  // +0x37
    char m_pad_0x3f[4];
    i32 m_viewMap;  // +0x43
    class heroWindow *m_window;  // +0x47
    i32 m_viewOnly;  // +0x4b
    char m_pad_0x4f;
    // --- constructors ---
    ExpCampaign(void);
    ~ExpCampaign();
    // --- methods ---
    void ResetMapChoices(void);
    void ResetMapsPlayed(void);
    void ResetAwards(void);
    void ResetBonusChoices(void);
    void GrantAward(i32);
    void RemoveAward(i32);
    i8 HasAward(i32);
    void SetMapWasPlayed(void);
    void InitNewCampaign(i32);
    void InitMap(void);
    void ShowInfo(i32, i32);
    void UpdateInfo(i32);
    i32 HandleVictory(void);
    void HandleVictory1(void);
    void HandleVictory2(void);
    void HandleVictory3(void);
    void HandleVictory4(void);
    void ReplaySmacker(void);
    void ReplaySmacker1(void);
    void ReplaySmacker2(void);
    void ReplaySmacker3(void);
    void ReplaySmacker4(void);
    u8 IsCompleted(void);
    i8 IsThisMapCompleted(void);
private:
    static i32 MessageHandler(struct tag_message &);   // ?...@ExpCampaign@@CIH... (private static)
public:
    void Autosave(void);
    i32 Choose(void);
    i16 Days(void);
    i32 CampaignID(void);
    char * JosephName(void);
    char * IvanName(void);
    i8 IsSpecialGoldenBow(i32, i32);
    i8 IsSpecialUA(void);
    i8 IsSpecialLossCondition(i32);
};
#pragma pack(pop)
SIZE(ExpCampaign, 0x50);

extern struct SCampaignChoice
    xCampaignChoices[EXPANSION_CAMPAIGN_COUNT]
                    [EXPANSION_CAMPAIGN_MAX_MAP_COUNT]
                    [EXPANSION_CAMPAIGN_BONUS_CHOICE_COUNT];
#endif // HOMM2_SOURCE_EXPCAMPAIGN_H
