#ifndef HOMM2_GAME_H
#define HOMM2_GAME_H
#include <va.h>
#include <SOURCE/KB_TYPES.h>
struct tag_message;

#pragma pack(push, 1)
struct EventExtra {
    u8 unknown00;
    i32 resources[7];
    i16 artifact;
    u8 applyToComputer;
    u8 cancelAfterVisit;
    char unknown21[4];
    i8 active;
    u16 x;
    u16 y;
    u8 unknown2a;
    u8 players[6];
    char message[1];
};
#pragma pack(pop)
SIZE(EventExtra, 0x32);
struct RandomHeroArmyRange {
    i16 creature;
    i16 minimum;
    i16 maximum;
};

H2_ENUM_BEGIN(GameSerializationConstant)
    GAME_SOURCE_LINE = 660,
    GAME_LOAD_SOURCE_LINE = 1103,
    GAME_SAVE_BUFFER_SIZE = 50000,
    GAME_FILE_MARKER = 1234,
    GAME_UNUSED_FILE_MARKER = 9999,
    GAME_PLAYER_COUNT = 6,
    GAME_HERO_COUNT = 54,
    GAME_TOWN_COUNT = 72,
    GAME_MINE_COUNT = 144,
    GAME_BOAT_COUNT = 48
H2_ENUM_END(GameSerializationConstant)

// Action trigger ids carried in mapCell::m_triggerType (non-action id | the
// MAP_TRIGGER_ACTION_FLAG 0x80 bit). ProcessRandomObjects converts every
// MAP_TRIGGER_RANDOM_* cell into its concrete counterpart at map load.
H2_ENUM_CLASS_BEGIN(GameMapTrigger)
    MAP_TRIGGER_TOWN_BASE = 0x23,
    MAP_TRIGGER_MONSTER = 0x98,
    MAP_TRIGGER_RESOURCE = 0x9b,
    MAP_TRIGGER_SEA_CHEST = 0xa1,
    MAP_TRIGGER_TOWN = 0xa3,
    MAP_TRIGGER_ARTIFACT = 0xa9,
    MAP_TRIGGER_HERO = 0xaa,
    MAP_TRIGGER_BOAT = 0xab,
    MAP_TRIGGER_RANDOM_ULTIMATE_ARTIFACT = 0xac,
    MAP_TRIGGER_RANDOM_ARTIFACT = 0xad,
    MAP_TRIGGER_RANDOM_RESOURCE = 0xae,
    MAP_TRIGGER_RANDOM_MONSTER = 0xaf,
    MAP_TRIGGER_RANDOM_TOWN = 0xb0,
    MAP_TRIGGER_RANDOM_CASTLE = 0xb1,
    MAP_TRIGGER_RANDOM_MINE = 0xb2,
    MAP_TRIGGER_RANDOM_MONSTER_LEVEL_1 = 0xb3,
    MAP_TRIGGER_RANDOM_MONSTER_LEVEL_2 = 0xb4,
    MAP_TRIGGER_RANDOM_MONSTER_LEVEL_3 = 0xb5,
    MAP_TRIGGER_RANDOM_MONSTER_LEVEL_4 = 0xb6,
    MAP_TRIGGER_RANDOM_ARTIFACT_LEVEL_1 = 0xf4,
    MAP_TRIGGER_RANDOM_ARTIFACT_LEVEL_2 = 0xf5,
    MAP_TRIGGER_RANDOM_ARTIFACT_LEVEL_3 = 0xf6
H2_ENUM_CLASS_END(GameMapTrigger)

// mapCell::m_objectMetadata layout for monster cells: low 12 bits carry the
// troop count, bit 0x1000 marks a placed guardian.
H2_ENUM_CLASS_BEGIN(GameMonsterMetadata)
    MAP_MONSTER_COUNT_MASK = 0xfff,
    MAP_MONSTER_GUARD_FLAG = 0x1000
H2_ENUM_CLASS_END(GameMonsterMetadata)

H2_ENUM_BEGIN(GameDifficultyConstant)
    GAME_DIFFICULTY_HARD = 2,
    GAME_DIFFICULTY_EXPERT = 3,
    GAME_DIFFICULTY_IMPOSSIBLE = 4
H2_ENUM_END(GameDifficultyConstant)

H2_ENUM_BEGIN(GameScoreConstant)
    GAME_SCORE_MAP_SMALL = 36,
    GAME_SCORE_MAP_MEDIUM = 72,
    GAME_SCORE_MAP_LARGE = 108,
    GAME_SCORE_MAP_EXTRA_LARGE = 144,
    GAME_SCORE_BASE = 200,
    GAME_SCORE_FIRST_TIER = 60,
    GAME_SCORE_SECOND_TIER = 120,
    GAME_SCORE_THIRD_TIER = 360,
    GAME_SCORE_MINIMUM = 20
H2_ENUM_END(GameScoreConstant)

#define GAME_SCORE_EXTRA_LARGE_DAY_SCALE 0.6
#define GAME_SCORE_LARGE_DAY_SCALE 0.8
#define GAME_SCORE_SMALL_DAY_SCALE 1.4
#define GAME_VIEW_ARMY_FRAME_DELAY_SCALE 1.35

H2_ENUM_BEGIN(GameJoinConstant)
    GAME_JOIN_HEADER_SIZE = 2,
    GAME_JOIN_BUFFER_SIZE = 700000,
    GAME_JOIN_LOG_UNUSED = -999
H2_ENUM_END(GameJoinConstant)

H2_ENUM_CLASS_BEGIN(GameDiffEncoding)
    DIFF_COMMAND_SHIFT = 7,
    DIFF_LEN_WORD_FLAG = 0x40,
    DIFF_LEN_BYTE_FLAG = 0x20,
    DIFF_LEN_WORD_HIGH_MASK = 0x3f,
    DIFF_LEN_HIGH_MASK = 0x2f0000,
    DIFF_LEN_LOW_MASK = 0xffff,
    DIFF_LEN_SHORT_MASK = 0x1f,
    DIFF_LEN_BYTE_MAX = 0x1f,
    DIFF_LEN_WORD_MAX = 0x1fff
H2_ENUM_CLASS_END(GameDiffEncoding)

H2_ENUM_CLASS_BEGIN(GameSaveSentinel)
    GAME_SAVED_TOWN_OFF_MAP = 0xff
H2_ENUM_CLASS_END(GameSaveSentinel)

H2_ENUM_BEGIN(GameWeeklyConstant)
    WEEKLY_WATER_WHEEL_EMPTY = 0xff,
    WEEKLY_MONSTER_POPULATION_LIMIT = 0x1fe1,
    WEEKLY_DWELLING_NO_GROWTH_FLAG = 0x80,
    WEEKLY_FIRST_DWELLING = 19,
    WEEKLY_LAST_DWELLING = 30,
    WEEKLY_GROWTH_LIMIT = 0x1feb,
    WEEKLY_DRAGON_CITY_LIMIT = 220,
    WEEKLY_MONSTER_LIMIT = 4000,
    WEEKLY_RECRUIT_TYPE_MASK = 7,
    WEEKLY_RECRUIT_COUNT_SHIFT = 3,
    WEEKLY_RECRUIT_MIN_GROWTH = 2,
    WEEKLY_RECRUIT_MAX_GROWTH = 5,
    WEEKLY_RECRUIT_LIMIT = 1000,
    WEEKLY_SITE_TYPE_MASK = 0x3f,
    WEEKLY_AVAILABLE_HERO = 64
H2_ENUM_END(GameWeeklyConstant)

H2_ENUM_BEGIN(GameMonthlyConstant)
    MONTH_TYPE_NORMAL = 0,
    MONTH_TYPE_CREATURE = 1,
    MONTH_TYPE_PLAGUE = 2,
    MONTH_ROLL_MIN = 1,
    MONTH_ROLL_MAX = 10,
    MONTH_NORMAL_ROLL_MAX = 5,
    MONTH_CREATURE_ROLL_MAX = 9,
    MONTH_NORMAL_NAME_MIN = 0,
    MONTH_NORMAL_NAME_MAX = 9,
    MONTH_CREATURE_LIST_MIN = 0,
    MONTH_CREATURE_LIST_MAX = 11,
    MONTH_WELL_BUILDING = 0x10,
    MONTH_WELL_GROWTH = 2,
    MONTH_FIRST_DWELLING_BONUS_BUILDING = 0x800,
    MONTH_FIRST_DWELLING_GROWTH = 8,
    MONTH_MONSTER_TRIGGER = 0x98,
    MONTH_MONSTER_TILESET = 12,
    MONTH_MONSTER_SPAWN_MIN = 0,
    MONTH_MONSTER_SPAWN_MAX = 360,
    MONTH_MONSTER_SPAWN_ROLL = 10,
    MONTH_MONSTER_GUARD_ROLL_MAX = 100,
    MONTH_MONSTER_GUARD_CHANCE = 20
H2_ENUM_END(GameMonthlyConstant)

H2_ENUM_BEGIN(GameRandomTownConstant)
    NEUTRAL_TOWN_CASTLE_REINFORCE_CHANCE = 80,
    NEUTRAL_TOWN_REINFORCE_CHANCE = 40,
    RANDOM_TOWN_UNOWNED_COLOR = -1,
    RANDOM_TOWN_RACE_MIN = 0,
    RANDOM_TOWN_RACE_MAX = 5,
    RANDOM_TOWN_AGE = 10,
    RANDOM_TOWN_LEFT = -5,
    RANDOM_TOWN_TOP = -3,
    RANDOM_TOWN_RIGHT = 2,
    RANDOM_TOWN_BOTTOM = 1,
    RANDOM_TOWN_OBJECT_SOURCE_FIRST = 0,
    RANDOM_TOWN_OBJECT_SOURCE_LAST = 0x1f,
    RANDOM_TOWN_OVERLAY_SOURCE_FIRST = 0x20,
    RANDOM_TOWN_OVERLAY_SOURCE_LAST = 0xFF,
    RANDOM_TOWN_RACE_FRAME_SHIFT = 5,
    RANDOM_TOWN_FIRST_TRIGGER = 0x30,
    RANDOM_TOWN_SECOND_TRIGGER = 0x31,
    RANDOM_TOWN_TRIGGER = 0x23
H2_ENUM_END(GameRandomTownConstant)

H2_ENUM_BEGIN(GameRandomArtifactConstant)
    RANDOM_ARTIFACT_BASE_TABLE_SIZE = IDX(ARTIFACT_MAGIC_BOOK) + 1,
    GAME_SPECIAL_HERO_CLASS_NONE = -1,
    RANDOM_ARTIFACT_FIRST = IDX(ARTIFACT_ULTIMATE_BOOK),
    RANDOM_ARTIFACT_BASE_LAST = IDX(ARTIFACT_MAGIC_BOOK),
    RANDOM_ARTIFACT_EXPANSION_LAST = IDX(ARTIFACT_SPADE_NECROMANCY),
    RANDOM_ARTIFACT_UNIQUE_RETRIES = 100,
    RANDOM_ARTIFACT_CURSED_ROLL_MAX = 100,
    RANDOM_ARTIFACT_CURSED_REJECT_CHANCE = 30,
    VICTORY_ARTIFACT_ID_OFFSET = 1
H2_ENUM_END(GameRandomArtifactConstant)

H2_ENUM_BEGIN(GameRandomHeroConstant)
    RANDOM_HERO_COUNT = 54,
    RANDOM_HERO_NORMAL_ARMY = 0,
    RANDOM_HERO_EXPERIENCE_MIN = 0,
    RANDOM_HERO_EXPERIENCE_MAX = 50,
    RANDOM_HERO_EXPERIENCE_BASE = 40,
    RANDOM_HERO_SEED_MIN = 1,
    RANDOM_HERO_SEED_MAX = 255,
    RANDOM_HERO_ENABLED = 1,
    RANDOM_HERO_STARTING_SPELL_KNOWN = 1,
    RANDOM_HERO_STACK_SELECTED = 1,
    RANDOM_HERO_FIRST_STACK_CHANCE = 50,
    RANDOM_HERO_FIRST_STACK_BONUS_CHANCE = 30,
    RANDOM_HERO_SECOND_STACK_CHANCE = 25,
    RANDOM_HERO_SECOND_STACK_BONUS_CHANCE = 40,
    RANDOM_HERO_PERCENT_MIN = 0,
    RANDOM_HERO_PERCENT_MAX = 99,
    RANDOM_HERO_ARMY_SLOT_COUNT = 5,
    RANDOM_HERO_ARMY_SELECTION_COUNT = 2,
    RANDOM_HERO_ARMY_OPTION_COUNT = 3,
    RANDOM_HERO_COUNT_SCALE = 10,
    RANDOM_HERO_COUNT_ROUNDING = 9,
    RANDOM_HERO_EMPTY_COUNT = -1
H2_ENUM_END(GameRandomHeroConstant)

H2_ENUM_BEGIN(GameVisibilityConstant)
    VISIBILITY_EARLY_TURN_LAST = 20,
    VISIBILITY_MIDDLE_TURN_LAST = 40,
    VISIBILITY_EARLY_AI_BONUS = 1,
    VISIBILITY_MIDDLE_AI_BONUS = 2,
    VISIBILITY_LATE_AI_BONUS = 3,
    VISIBILITY_SMALL_RADIUS_LIMIT = 5,
    VISIBILITY_SMALL_RADIUS_THRESHOLD = 2,
    VISIBILITY_LARGE_RADIUS_THRESHOLD = 3,
    VISIBILITY_RADIAL_RADIUS_LIMIT = 10
H2_ENUM_END(GameVisibilityConstant)

H2_ENUM_BEGIN(GameLuckConstant)
    LUCK_NEUTRAL = 0,
    LUCK_MINIMUM = -3,
    LUCK_MAXIMUM = 3,
    LUCK_RAINBOW_BONUS = 2
H2_ENUM_END(GameLuckConstant)

H2_ENUM_BEGIN(GameWaitConstant)
    WAIT_BOTTOM_VIEW_TIMEOUT = 9999999,
    WAIT_AMBIENT_MUSIC = 21,
    WAIT_DIALOG_TYPE = 9
H2_ENUM_END(GameWaitConstant)

H2_ENUM_BEGIN(GameTimeEventConstant)
    TIME_EVENT_DAYS_PER_WEEK = 7,
    TIME_EVENT_DAYS_PER_MONTH = 28,
    TIME_EVENT_RESOURCE_COUNT = 7,
    TIME_EVENT_RESOURCE_PENALTY = 100000
H2_ENUM_END(GameTimeEventConstant)

H2_ENUM_BEGIN(GameHeroPoolConstant)
    AVAILABLE_HERO_SLOTS = 2
H2_ENUM_END(GameHeroPoolConstant)

H2_ENUM_BEGIN(GameCompressionTestConstant)
    COMPRESSION_TEST_RANDOM_SIZE_MIN = 20000,
    COMPRESSION_TEST_RANDOM_SIZE_MAX = 100000,
    COMPRESSION_TEST_RANDOM_BUFFER_EXTRA = 5000,
    COMPRESSION_TEST_FILE_BUFFER_EXTRA = 2000,
    COMPRESSION_TEST_FILENAME_SIZE = 32
H2_ENUM_END(GameCompressionTestConstant)

i32 GetNumObelisks(i32 color);
void ComputeUALoc(i32);
void GenerateStandardFileName(char*, char*);
i32 ViewSpellsHandler(struct tag_message&);
i32 ViewSpecialHandler(struct tag_message&);
i32 ViewArmyHandler(struct tag_message&);
i32 IsCursedItem(ArtifactType item);
i32 CalcBaseScore(i32);
void WriteDiffHeaderInfo(u8 cmd, i32 len, u8* buf, i32* pos);
i32 GetSkipCopyLen(u8* buf, i32* pos);
void CreateDiffFile(char*, char*, char*, i32, i32);
void CreateJoinFile(char*, char*, char*);
EventExtra* GetMapEvent(i32 x, i32 y);
void CheckValidAvailableHeroes(void);
i32 CalcFileCRC(char* filename);
void CompressTest2(void);
void CompressTest(void);
void CompressTest3(void);

extern char bMapInitialized;

#endif
