#ifndef HOMM2_GAME_H
#define HOMM2_GAME_H
#include <va.h>
// Declarations of the free functions DEFINED in GAME.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

// GAME-private types.
#pragma pack(push, 1)
struct EventExtra {
    u8 unknown00;
    i32 resources[7];
    i16 artifact;
    u8 applyToComputer;
    u8 cancelAfterVisit;
    char unknown21[4];
    i8 active;
    u16 x;
    u16 y;
    u8 unknown2a;
    u8 players[6];
    char message[1];
};
#pragma pack(pop)
SIZE(EventExtra, 0x32);
struct RandomHeroArmyRange {
    i16 creature;
    i16 minimum;
    i16 maximum;
};

typedef enum GameSerializationConstant {
    GAME_SOURCE_LINE = 660,
    GAME_LOAD_SOURCE_LINE = 1103,
    GAME_SAVE_BUFFER_SIZE = 50000,
    GAME_FILE_MARKER = 1234,
    GAME_UNUSED_FILE_MARKER = 9999,
    GAME_PLAYER_COUNT = 6,
    GAME_HERO_COUNT = 54,
    GAME_TOWN_COUNT = 72,
    GAME_MINE_COUNT = 144,
    GAME_BOAT_COUNT = 48
} GameSerializationConstant;

typedef enum GameSourceLine {
    GAME_VIEW_ARMY_SOURCE_LINE_BASE = 0x0dd1,
    GAME_VIEW_ARMY_ALLOC_OFFSET = 0x93,
    GAME_VIEW_ARMY_FREE_OFFSET = 0x164,
    GAME_SETUP_TOWNS_SOURCE_LINE_BASE = 0x17f9,
    GAME_SETUP_TOWNS_FREE_OFFSET = 0xee,
    GAME_PROCESS_ON_MAP_HEROES_SOURCE_LINE_BASE = 0x18ef,
    GAME_PROCESS_ON_MAP_HEROES_FREE_OFFSET = 0xdd,
    GAME_SET_MAP_SIZE_SOURCE_LINE_BASE = 0x1d0d,
    GAME_SET_MAP_SIZE_FREE_OFFSET = 0xc,
    GAME_SET_MAP_SIZE_ALLOC_OFFSET = 0xd,
    GAME_CREATE_JOIN_FILE_SOURCE_LINE_BASE = 0x1e0f,
    GAME_CREATE_JOIN_DIFF_ALLOC_OFFSET = 0xd,
    GAME_CREATE_JOIN_BUFFER_ALLOC_OFFSET = 0x16,
    GAME_CREATE_JOIN_OLD_ALLOC_OFFSET = 0x21,
    GAME_CREATE_JOIN_OLD_FREE_OFFSET = 0x53,
    GAME_CREATE_JOIN_DIFF_FREE_OFFSET = 0x55,
    GAME_CREATE_JOIN_BUFFER_FREE_OFFSET = 0x57,
    GAME_CALC_FILE_CRC_SOURCE_LINE_BASE = 0x1f5e,
    GAME_CALC_CRC_ALLOC_OFFSET = 3,
    GAME_CALC_CRC_FREE_OFFSET = 0xe
} GameSourceLine;

typedef enum GameMapTrigger {
    MAP_TRIGGER_TOWN_BASE = 0x23,
    MAP_TRIGGER_TOWN = 0xa3,
    MAP_TRIGGER_RANDOM_ARTIFACT = 0xa9
} GameMapTrigger;

typedef enum GameDifficultyConstant {
    GAME_DIFFICULTY_HARD = 2,
    GAME_DIFFICULTY_EXPERT = 3,
    GAME_DIFFICULTY_IMPOSSIBLE = 4
} GameDifficultyConstant;

typedef enum GameScoreConstant {
    GAME_SCORE_MAP_SMALL = 36,
    GAME_SCORE_MAP_MEDIUM = 72,
    GAME_SCORE_MAP_LARGE = 108,
    GAME_SCORE_MAP_EXTRA_LARGE = 144,
    GAME_SCORE_BASE = 200,
    GAME_SCORE_FIRST_TIER = 60,
    GAME_SCORE_SECOND_TIER = 120,
    GAME_SCORE_THIRD_TIER = 360,
    GAME_SCORE_MINIMUM = 20
} GameScoreConstant;

#define GAME_SCORE_EXTRA_LARGE_DAY_SCALE 0.6
#define GAME_SCORE_LARGE_DAY_SCALE 0.8
#define GAME_SCORE_SMALL_DAY_SCALE 1.4
#define GAME_VIEW_ARMY_FRAME_DELAY_SCALE 1.35

typedef enum GameJoinConstant {
    GAME_JOIN_HEADER_SIZE = 2,
    GAME_JOIN_BUFFER_SIZE = 700000,
    GAME_JOIN_LOG_UNUSED = -999
} GameJoinConstant;

typedef enum GameDailyArtifactConstant {
    ARTIFACT_POWER_RING = 0x43,
    ARTIFACT_ENDLESS_POUCH_SULFUR = 0x47,
    ARTIFACT_ENDLESS_VIAL_MERCURY = 0x48,
    ARTIFACT_ENDLESS_POUCH_GEMS = 0x49,
    ARTIFACT_ENDLESS_CORD_WOOD = 0x4a,
    ARTIFACT_ENDLESS_CART_ORE = 0x4b,
    ARTIFACT_ENDLESS_POUCH_CRYSTAL = 0x4c
} GameDailyArtifactConstant;

typedef enum GameWeeklyConstant {
    WEEKLY_FIRST_DWELLING = 19,
    WEEKLY_LAST_DWELLING = 30,
    WEEKLY_GROWTH_LIMIT = 0x1feb,
    WEEKLY_DRAGON_CITY_LIMIT = 220,
    WEEKLY_MONSTER_LIMIT = 4000,
    WEEKLY_RECRUIT_TYPE_MASK = 7,
    WEEKLY_RECRUIT_COUNT_SHIFT = 3,
    WEEKLY_RECRUIT_MIN_GROWTH = 2,
    WEEKLY_RECRUIT_MAX_GROWTH = 5,
    WEEKLY_RECRUIT_LIMIT = 1000,
    WEEKLY_AVAILABLE_HERO = 64,
    WEEKLY_HERO_RESERVED_FLAG = 0x10000,
    WEEKLY_HERO_VISIT_FLAG = 0x800000
} GameWeeklyConstant;

typedef enum GameMonthlyConstant {
    MONTH_TYPE_NORMAL = 0,
    MONTH_TYPE_CREATURE = 1,
    MONTH_TYPE_PLAGUE = 2,
    MONTH_ROLL_MIN = 1,
    MONTH_ROLL_MAX = 10,
    MONTH_NORMAL_ROLL_MAX = 5,
    MONTH_CREATURE_ROLL_MAX = 9,
    MONTH_NORMAL_NAME_MIN = 0,
    MONTH_NORMAL_NAME_MAX = 9,
    MONTH_CREATURE_LIST_MIN = 0,
    MONTH_CREATURE_LIST_MAX = 11,
    MONTH_WELL_BUILDING = 0x10,
    MONTH_WELL_GROWTH = 2,
    MONTH_FIRST_DWELLING_BONUS_BUILDING = 0x800,
    MONTH_FIRST_DWELLING_GROWTH = 8,
    MONTH_MONSTER_TRIGGER = 0x98,
    MONTH_MONSTER_TILESET = 12,
    MONTH_MONSTER_SPAWN_MIN = 0,
    MONTH_MONSTER_SPAWN_MAX = 360,
    MONTH_MONSTER_SPAWN_ROLL = 10,
    MONTH_MONSTER_GUARD_ROLL_MAX = 100,
    MONTH_MONSTER_GUARD_CHANCE = 20,
    MONTH_MONSTER_GUARD_FLAG = 0x1000
} GameMonthlyConstant;

typedef enum GameRandomTownConstant {
    RANDOM_TOWN_UNOWNED_COLOR = -1,
    RANDOM_TOWN_RACE_MIN = 0,
    RANDOM_TOWN_RACE_MAX = 5,
    RANDOM_TOWN_AGE = 10,
    RANDOM_TOWN_LEFT = -5,
    RANDOM_TOWN_TOP = -3,
    RANDOM_TOWN_RIGHT = 2,
    RANDOM_TOWN_BOTTOM = 1,
    RANDOM_TOWN_SOURCE_TILESET = 0x26,
    RANDOM_TOWN_OBJECT_SOURCE_FIRST = 0,
    RANDOM_TOWN_OBJECT_SOURCE_LAST = 0x1f,
    RANDOM_TOWN_OVERLAY_SOURCE_FIRST = 0x20,
    RANDOM_TOWN_OVERLAY_SOURCE_LAST = 0xff,
    RANDOM_TOWN_OBJECT_TILESET = 0x23,
    RANDOM_TOWN_OVERLAY_TILESET = 0x25,
    RANDOM_TOWN_RACE_FRAME_SHIFT = 5,
    RANDOM_TOWN_FIRST_TRIGGER = 0x30,
    RANDOM_TOWN_SECOND_TRIGGER = 0x31,
    RANDOM_TOWN_TRIGGER = 0x23
} GameRandomTownConstant;

typedef enum GameRandomArtifactConstant {
    ARTIFACT_MEDAL_OF_VALOR = 0xc,
    ARTIFACT_MEDAL_OF_COURAGE = 0xd,
    ARTIFACT_MEDAL_OF_HONOR = 0xe,
    ARTIFACT_MEDAL_OF_DISTINCTION = 0xf,
    ARTIFACT_FIZBIN_OF_MISFORTUNE = 0x10,
    RANDOM_ARTIFACT_FIRST = 0,
    RANDOM_ARTIFACT_BASE_LAST = 0x51,
    RANDOM_ARTIFACT_EXPANSION_LAST = 0x66,
    ARTIFACT_EDITOR_ANY_ULTIMATE = 0x52,
    ARTIFACT_EDITOR_UNUSED_84 = 0x53,
    ARTIFACT_EDITOR_UNUSED_85 = 0x54,
    ARTIFACT_EDITOR_UNUSED_86 = 0x55,
    ARTIFACT_RANDOM_SPELL_SCROLL = 0x56,
    ARTIFACT_UNDEAD_MORALE = 0x57,
    ARTIFACT_BREASTPLATE_ANDURAN = 0x58,
    ARTIFACT_BATTLE_GARB = 0x5a,
    ARTIFACT_HELMET_ANDURAN = 0x5e,
    ARTIFACT_SPHERE_NEGATION = 0x62,
    ARTIFACT_SWORD_ANDURAN = 0x65,
    RANDOM_ARTIFACT_UNIQUE_RETRIES = 100,
    RANDOM_ARTIFACT_CURSED_ROLL_MAX = 100,
    RANDOM_ARTIFACT_CURSED_REJECT_CHANCE = 30,
    VICTORY_CONDITION_ARTIFACT = 3,
    VICTORY_ARTIFACT_ID_OFFSET = 1
} GameRandomArtifactConstant;

typedef enum GameRandomHeroConstant {
    RANDOM_HERO_COUNT = 54,
    RANDOM_HERO_NORMAL_ARMY = 0,
    RANDOM_HERO_EXPERIENCE_MIN = 0,
    RANDOM_HERO_EXPERIENCE_MAX = 50,
    RANDOM_HERO_EXPERIENCE_BASE = 40,
    RANDOM_HERO_SEED_MIN = 1,
    RANDOM_HERO_SEED_MAX = 255,
    RANDOM_HERO_ENABLED = 1,
    RANDOM_HERO_STARTING_SPELL_KNOWN = 1,
    RANDOM_HERO_STACK_SELECTED = 1,
    RANDOM_HERO_FIRST_STACK_CHANCE = 50,
    RANDOM_HERO_FIRST_STACK_BONUS_CHANCE = 30,
    RANDOM_HERO_SECOND_STACK_CHANCE = 25,
    RANDOM_HERO_SECOND_STACK_BONUS_CHANCE = 40,
    RANDOM_HERO_PERCENT_MIN = 0,
    RANDOM_HERO_PERCENT_MAX = 99,
    RANDOM_HERO_ARMY_SLOT_COUNT = 5,
    RANDOM_HERO_ARMY_SELECTION_COUNT = 2,
    RANDOM_HERO_ARMY_OPTION_COUNT = 3,
    RANDOM_HERO_COUNT_SCALE = 10,
    RANDOM_HERO_COUNT_ROUNDING = 9,
    RANDOM_HERO_EMPTY_CREATURE = -1,
    RANDOM_HERO_EMPTY_COUNT = -1,
    RANDOM_HERO_KNIGHT_FIRST = 0,
    RANDOM_HERO_KNIGHT_SECOND = 1,
    RANDOM_HERO_KNIGHT_THIRD = 3,
    RANDOM_HERO_BARBARIAN_FIRST = 11,
    RANDOM_HERO_BARBARIAN_SECOND = 12,
    RANDOM_HERO_BARBARIAN_THIRD = 14,
    RANDOM_HERO_SORCERESS_FIRST = 20,
    RANDOM_HERO_SORCERESS_SECOND = 21,
    RANDOM_HERO_SORCERESS_THIRD = 23,
    RANDOM_HERO_WARLOCK_FIRST = 29,
    RANDOM_HERO_WARLOCK_SECOND = 30,
    RANDOM_HERO_WARLOCK_THIRD = 31,
    RANDOM_HERO_WIZARD_FIRST = 38,
    RANDOM_HERO_WIZARD_SECOND = 39,
    RANDOM_HERO_WIZARD_THIRD = 40,
    RANDOM_HERO_NECROMANCER_FIRST = 47,
    RANDOM_HERO_NECROMANCER_SECOND = 48,
    RANDOM_HERO_NECROMANCER_THIRD = 50,
    RANDOM_HERO_SORCERESS_STARTING_SPELL = 14,
    RANDOM_HERO_WARLOCK_STARTING_SPELL = 18,
    RANDOM_HERO_WIZARD_STARTING_SPELL = 16,
    RANDOM_HERO_NECROMANCER_STARTING_SPELL = 9
} GameRandomHeroConstant;

typedef enum GameVisibilityConstant {
    VISIBILITY_EARLY_TURN_LAST = 20,
    VISIBILITY_MIDDLE_TURN_LAST = 40,
    VISIBILITY_EARLY_AI_BONUS = 1,
    VISIBILITY_MIDDLE_AI_BONUS = 2,
    VISIBILITY_LATE_AI_BONUS = 3,
    VISIBILITY_SMALL_RADIUS_LIMIT = 5,
    VISIBILITY_SMALL_RADIUS_THRESHOLD = 2,
    VISIBILITY_LARGE_RADIUS_THRESHOLD = 3,
    VISIBILITY_RADIAL_RADIUS_LIMIT = 10
} GameVisibilityConstant;

typedef enum GameLuckConstant {
    ARTIFACT_RABBIT_FOOT = 0x23,
    ARTIFACT_GOLDEN_HORSESHOE = 0x24,
    ARTIFACT_GAMBLERS_LUCKY_COIN = 0x25,
    ARTIFACT_FOUR_LEAF_CLOVER = 0x26,
    ARTIFACT_MASTHEAD = 0x61,
    LUCK_NEUTRAL = 0,
    LUCK_MINIMUM = -3,
    LUCK_MAXIMUM = 3,
    LUCK_RAINBOW_BONUS = 2
} GameLuckConstant;

typedef enum GameWaitConstant {
    WAIT_BOTTOM_VIEW_TIMEOUT = 9999999,
    WAIT_AMBIENT_MUSIC = 21,
    WAIT_DIALOG_TYPE = 9
} GameWaitConstant;

typedef enum GameTimeEventConstant {
    TIME_EVENT_DAYS_PER_WEEK = 7,
    TIME_EVENT_DAYS_PER_MONTH = 28,
    TIME_EVENT_RESOURCE_COUNT = 7,
    TIME_EVENT_RESOURCE_PENALTY = 100000
} GameTimeEventConstant;

typedef enum GameHeroPoolConstant {
    AVAILABLE_HERO_SLOTS = 2
} GameHeroPoolConstant;

typedef enum GameCompressionTestConstant {
    COMPRESSION_TEST_RANDOM_SIZE_MIN = 20000,
    COMPRESSION_TEST_RANDOM_SIZE_MAX = 100000,
    COMPRESSION_TEST_RANDOM_BUFFER_EXTRA = 5000,
    COMPRESSION_TEST_FILE_BUFFER_EXTRA = 2000,
    COMPRESSION_TEST_FILENAME_SIZE = 32
} GameCompressionTestConstant;

i32 GetNumObelisks(i32 color);
void ComputeUALoc(i32);
void GenerateStandardFileName(char *, char *);
i32 ViewSpellsHandler(struct tag_message &);
i32 ViewSpecialHandler(struct tag_message &);
i32 ViewArmyHandler(struct tag_message &);
i32 IsCursedItem(i32 item);
i32 CalcBaseScore(i32);
void WriteDiffHeaderInfo(u8 cmd, i32 len, u8 *buf, i32 *pos);
i32 GetSkipCopyLen(u8 *buf, i32 *pos);
void CreateDiffFile(char *, char *, char *, i32, i32);
void CreateJoinFile(char *, char *, char *);
EventExtra *GetMapEvent(i32 x, i32 y);
void CheckValidAvailableHeroes(void);
i32 CalcFileCRC(char *filename);
void CompressTest2(void);
void CompressTest(void);
void CompressTest3(void);


// --- globals owned by this TU (moved from _globals.h; CodeView-attributed) ---
extern char bMapInitialized;

#endif // HOMM2_GAME_H
