#ifndef HOMM2_HERO_H
#define HOMM2_HERO_H

#include <Ints.h>
// Declarations of the free functions DEFINED in HERO.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

H2_ENUM_BEGIN(HeroUiConstant)
    HERO_UI_STATUS_TEXT_WIDGET = 0x12f,
    HERO_UI_ARTIFACT_FIRST = 0x14,
    HERO_UI_ARTIFACT_LAST = 0x21,
    HERO_UI_PRIMARY_STAT_FIRST = 0x51,
    HERO_UI_PRIMARY_STAT_LAST = 0x54,
    HERO_UI_ADDITIONAL_STATS = 0x55,
    HERO_UI_ARMY_ICON_FIRST = 0x57,
    HERO_UI_ARMY_PORTRAIT_FIRST = 0x5c,
    HERO_UI_ARMY_COUNT_FIRST = 0x61,
    HERO_UI_ARMY_SELECTOR_FIRST = 0x66,
    HERO_UI_ARMY_SELECTOR_LAST = 0x6a,
    HERO_UI_HERO_TITLE = 2,
    HERO_UI_HERO_PORTRAIT = 0x41,
    HERO_UI_PRIMARY_STAT_VALUE_FIRST = 0x4c,
    HERO_UI_PLAYER_CREST = 0x56,
    HERO_UI_MORALE_FIRST = 0xc8,
    HERO_UI_MORALE_LAST = 0xca,
    HERO_UI_LUCK_FIRST = 0xcb,
    HERO_UI_LUCK_LAST = 0xcd,
    HERO_UI_EXPERIENCE_FIRST = 0xce,
    HERO_UI_EXPERIENCE_LAST = 0xcf,
    HERO_UI_SPELL_POINTS_FIRST = 0xd3,
    HERO_UI_SPELL_POINTS_LAST = 0xd4,
    HERO_UI_FORMATION_SPREAD = 0xd6,
    HERO_UI_FORMATION_GROUPED = 0xd8,
    HERO_UI_FORMATION_SPREAD_ICON = 0xd5,
    HERO_UI_FORMATION_GROUPED_ICON = 0xd7,
    HERO_UI_PREVIOUS_HERO = 300,
    HERO_UI_NEXT_HERO = 301,
    HERO_UI_ARMY_SELECTION_NONE = -1,
    HERO_UI_HERO_CYCLE_MIN_COUNT = 2,
    HERO_UI_SINGLE_HERO_COUNT = 1,
    HERO_UI_MODIFIER_ICON_COUNT = 3,
    HERO_UI_MIN_MODIFIER_ICONS = 1,
    HERO_UI_PREVIOUS_HERO_MASK = -2,
    HERO_UI_SECONDARY_SKILL_ROW1_FIRST = 0x190,
    HERO_UI_SECONDARY_SKILL_ROW1_LAST = 0x197,
    HERO_UI_SECONDARY_SKILL_ROW2_FIRST = 0x198,
    HERO_UI_SECONDARY_SKILL_ROW2_LAST = 0x19f,
    HERO_UI_SECONDARY_SKILL_ROW3_FIRST = 0x1a0,
    HERO_UI_SECONDARY_SKILL_ROW3_LAST = 0x1a7,
    HERO_UI_CLOSE = 0x7800,
    HERO_UI_DISMISS = 0x7803,
    HERO_UI_QUICK_VIEW_MODIFIER = 0x200,
    HERO_UI_SPLIT_MODIFIER_MASK = 3,
    HERO_UI_DIALOG_CLOSE_COMMAND = 10,
    HERO_UI_HANDLER_CONTINUE = 1,
    HERO_UI_HANDLER_CLOSE = 2,
    HERO_UI_VIEW_ARMY_X = 0x77,
    HERO_UI_VIEW_ARMY_Y = 0x14,
    HERO_UI_VIEW_SPELLS_ALL = 2,
    HERO_UI_VIEW_SPELLS_SPECIAL = 1,
    HERO_UI_CASTLE_DIALOG_ACTIVE = 1,
    HERO_UI_ARMY_EMPTY_FRAME = 2,
    HERO_UI_WIDGET_FRAME_ACTIVE = 4,
    HERO_UI_ARTIFACT_DIALOG_ICON = 0x1c,
    HERO_UI_ARMY_SLOT_COUNT = 5,
    HERO_UI_SCREEN_WIDTH = 640,
    HERO_UI_SCREEN_HEIGHT = 480,
    HERO_UI_FADE_STEPS = 8,
    HERO_UI_FADE_IN = 0,
    HERO_UI_FADE_OUT = 1,
    HERO_UI_LOOPING_SOUND_KEEP_COUNT = 4,
    HERO_UI_VIEW_CLOSED = 0,
    HERO_UI_VIEW_DISMISSED = 1,
    HERO_UI_WINDOW_TEXT_ID = 6,
    HERO_UI_BACKDROP_PALETTE = 1,
    HERO_UI_DIALOG_DISMISS = 0x7803,
    HERO_UI_DIALOG_SPLIT = 0x7802,
    HERO_UI_SPLIT_WINDOW_X = 0xb1,
    HERO_UI_SPLIT_WINDOW_Y = 0x14,
    HERO_UI_SPLIT_TEXT = 1,
    HERO_UI_SPLIT_AMOUNT = 68,
    HERO_UI_CONTROL_VALUE_DEFAULT = 6,
    HERO_UI_CONTROL_FRAME_DEFAULT = 4,
    HERO_UI_CYCLE_BUTTON_FRAME = 2,
    HERO_UI_CYCLE_BUTTON_DISABLED_FRAME = 0x1000,
    HERO_UI_LUCK_NEGATIVE_FRAME = 3,
    HERO_UI_LUCK_NEUTRAL_FRAME = 6,
    HERO_UI_LUCK_POSITIVE_FRAME = 2,
    HERO_UI_MORALE_NEGATIVE_FRAME = 5,
    HERO_UI_MORALE_NEUTRAL_FRAME = 7,
    HERO_UI_MORALE_POSITIVE_FRAME = 4,
    HERO_UI_EMPTY_SKILL_FRAME = 0,
    HERO_UI_EMPTY_ARTIFACT_FRAME = 0,
    HERO_UI_ARTIFACT_CONTROL_VALUE = 2
H2_ENUM_END(HeroUiConstant)

H2_ENUM_CLASS_BEGIN(HeroScreenText)
    HERO_TEXT_PRIMARY_STAT = 1,
    HERO_TEXT_ADDITIONAL_STATS = 2,
    HERO_TEXT_GOOD_MORALE = 3,
    HERO_TEXT_NEUTRAL_MORALE = 4,
    HERO_TEXT_BAD_MORALE = 5,
    HERO_TEXT_GOOD_LUCK = 6,
    HERO_TEXT_NEUTRAL_LUCK = 7,
    HERO_TEXT_BAD_LUCK = 8,
    HERO_TEXT_EXPERIENCE = 9,
    HERO_TEXT_SELECT_ARMY = 10,
    HERO_TEXT_EMPTY = 11,
    HERO_TEXT_MOVE_ARMY = 12,
    HERO_TEXT_EXCHANGE_ARMIES = 13,
    HERO_TEXT_VIEW_SPELLS = 14,
    HERO_TEXT_ARTIFACT = 15,
    HERO_TEXT_DISMISS = 16,
    HERO_TEXT_EXIT = 17,
    HERO_TEXT_SCREEN = 18,
    HERO_TEXT_COMBINE_ARMIES = 19,
    HERO_TEXT_SPLIT_ARMY = 20,
    HERO_TEXT_SECONDARY_SKILL = 21,
    HERO_TEXT_SPELL_POINTS = 22,
    HERO_TEXT_SPREAD_FORMATION = 23,
    HERO_TEXT_GROUPED_FORMATION = 24
H2_ENUM_CLASS_END(HeroScreenText)

void HeroMessageUpdate(char*);
void UpdateHeroScreenStatusBar(struct tag_message&);
i32 HeroHandler(struct tag_message&);
void RedrawHeroScreen(void);
i32 HeroView(i32, i32, i32);
void SetupHeroView(void);
void DoHeroSplit(i32, i32);

#endif // HOMM2_HERO_H
