#ifndef HOMM2_HERO_H
#define HOMM2_HERO_H
// Declarations of the free functions DEFINED in HERO.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

typedef enum HeroUiConstant {
    HERO_UI_KEY_DOWN = 1,
    HERO_UI_KEY_UP = 2,
    HERO_UI_HOVER = 4,
    HERO_UI_MESSAGE = 0x200,
    HERO_UI_INPUT_SELECT = 12,
    HERO_UI_INPUT_DESELECT = 13,
    HERO_UI_INPUT_ALTERNATE_SELECT = 14,
    HERO_UI_WIDGET_TEXT = 3,
    HERO_UI_WIDGET_FRAME = 4,
    HERO_UI_WIDGET_ENABLE = 5,
    HERO_UI_WIDGET_DISABLE = 6,
    HERO_UI_WIDGET_ICON_FILE = 9,
    HERO_UI_STATUS_TEXT_WIDGET = 0x12f,
    HERO_UI_ARTIFACT_FIRST = 0x14,
    HERO_UI_ARTIFACT_LAST = 0x21,
    HERO_UI_PRIMARY_STAT_FIRST = 0x51,
    HERO_UI_PRIMARY_STAT_LAST = 0x54,
    HERO_UI_ADDITIONAL_STATS = 0x55,
    HERO_UI_ARMY_ICON_FIRST = 0x57,
    HERO_UI_ARMY_PORTRAIT_FIRST = 0x5c,
    HERO_UI_ARMY_COUNT_FIRST = 0x61,
    HERO_UI_ARMY_SELECTOR_FIRST = 0x66,
    HERO_UI_ARMY_SELECTOR_LAST = 0x6a,
    HERO_UI_MORALE_FIRST = 0xc8,
    HERO_UI_MORALE_LAST = 0xca,
    HERO_UI_LUCK_FIRST = 0xcb,
    HERO_UI_LUCK_LAST = 0xcd,
    HERO_UI_EXPERIENCE_FIRST = 0xce,
    HERO_UI_EXPERIENCE_LAST = 0xcf,
    HERO_UI_SPELL_POINTS_FIRST = 0xd3,
    HERO_UI_SPELL_POINTS_LAST = 0xd4,
    HERO_UI_FORMATION_SPREAD = 0xd6,
    HERO_UI_FORMATION_GROUPED = 0xd8,
    HERO_UI_PREVIOUS_HERO = 300,
    HERO_UI_NEXT_HERO = 301,
    HERO_UI_ARMY_SELECTION_NONE = -1,
    HERO_UI_HERO_CYCLE_MIN_COUNT = 2,
    HERO_UI_PREVIOUS_HERO_MASK = -2,
    HERO_UI_SECONDARY_SKILL_ROW1_FIRST = 0x190,
    HERO_UI_SECONDARY_SKILL_ROW1_LAST = 0x197,
    HERO_UI_SECONDARY_SKILL_ROW2_FIRST = 0x198,
    HERO_UI_SECONDARY_SKILL_ROW2_LAST = 0x19f,
    HERO_UI_SECONDARY_SKILL_ROW3_FIRST = 0x1a0,
    HERO_UI_SECONDARY_SKILL_ROW3_LAST = 0x1a7,
    HERO_UI_CLOSE = 0x7800,
    HERO_UI_DISMISS = 0x7803,
    HERO_UI_SHIFT_LEFT = 0x2a,
    HERO_UI_SHIFT_RIGHT = 0x36,
    HERO_UI_QUICK_VIEW_MODIFIER = 0x200,
    HERO_UI_SPLIT_MODIFIER_MASK = 3,
    HERO_UI_DIALOG_CLOSE_COMMAND = 10,
    HERO_UI_HANDLER_CONTINUE = 1,
    HERO_UI_HANDLER_CLOSE = 2,
    HERO_UI_VIEW_ARMY_X = 0x77,
    HERO_UI_VIEW_ARMY_Y = 0x14,
    HERO_UI_VIEW_SPELLS_ALL = 2,
    HERO_UI_VIEW_SPELLS_SPECIAL = 1,
    HERO_UI_CASTLE_DIALOG_ACTIVE = 1,
    HERO_UI_ARMY_EMPTY_FRAME = 2,
    HERO_UI_WIDGET_FRAME_ACTIVE = 4,
    HERO_UI_ARTIFACT_DIALOG_ICON = 0x1c,
    HERO_UI_ARMY_SLOT_COUNT = 5
} HeroUiConstant;

typedef enum HeroScreenText {
    HERO_TEXT_PRIMARY_STAT = 1,
    HERO_TEXT_ADDITIONAL_STATS = 2,
    HERO_TEXT_GOOD_MORALE = 3,
    HERO_TEXT_NEUTRAL_MORALE = 4,
    HERO_TEXT_BAD_MORALE = 5,
    HERO_TEXT_GOOD_LUCK = 6,
    HERO_TEXT_NEUTRAL_LUCK = 7,
    HERO_TEXT_BAD_LUCK = 8,
    HERO_TEXT_EXPERIENCE = 9,
    HERO_TEXT_SELECT_ARMY = 10,
    HERO_TEXT_EMPTY = 11,
    HERO_TEXT_MOVE_ARMY = 12,
    HERO_TEXT_EXCHANGE_ARMIES = 13,
    HERO_TEXT_VIEW_SPELLS = 14,
    HERO_TEXT_ARTIFACT = 15,
    HERO_TEXT_DISMISS = 16,
    HERO_TEXT_EXIT = 17,
    HERO_TEXT_SCREEN = 18,
    HERO_TEXT_COMBINE_ARMIES = 19,
    HERO_TEXT_SPLIT_ARMY = 20,
    HERO_TEXT_SECONDARY_SKILL = 21,
    HERO_TEXT_SPELL_POINTS = 22,
    HERO_TEXT_SPREAD_FORMATION = 23,
    HERO_TEXT_GROUPED_FORMATION = 24
} HeroScreenText;

void HeroMessageUpdate(char *);
void UpdateHeroScreenStatusBar(struct tag_message &);
int HeroHandler(struct tag_message &);
void RedrawHeroScreen(void);
int HeroView(int, int, int);
void SetupHeroView(void);
void DoHeroSplit(int, int);

#endif // HOMM2_HERO_H
