#ifndef HOMM2_SOURCE_HIGHSCOREMANAGER_H
#define HOMM2_SOURCE_HIGHSCOREMANAGER_H
#include <va.h>
#include "../BASE/baseManager.h"
struct tag_message;
class heroWindow;

H2_ENUM_BEGIN(HighScoreManagerConstant)
    HIGH_SCORE_DISPLAY_ENTRY_COUNT = 10,
    HIGH_SCORE_ANIMATION_FRAME_COUNT = 18,
    HIGH_SCORE_ANIMATION_DELAY = 120,
    HIGH_SCORE_TIMER_SLOT = 0,
    HIGH_SCORE_FILENAME_LENGTH = 352,
    HIGH_SCORE_FADE_STEPS = 8,
    HIGH_SCORE_MONSTER_FRAME_STRIDE = 9,
    HIGH_SCORE_MONSTER_ACTIVE_FRAME_OFFSET = 1,
    HIGH_SCORE_TEXT_WIDGET_STRIDE = 4,
    HIGH_SCORE_STANDARD_BUTTON = 100,
    HIGH_SCORE_CAMPAIGN_BUTTON = 0x93,
    HIGH_SCORE_CLOSE_BUTTON = 0x7800,
    HIGH_SCORE_FIRST_MONSTER_WIDGET = 0xc9,
    HIGH_SCORE_FIRST_SHADOW_WIDGET = 0xdd,
    HIGH_SCORE_FIRST_TEXT_WIDGET = 0x6a,
    HIGH_SCORE_TEXT_SCENARIO_OFFSET = 1,
    HIGH_SCORE_TEXT_RATING_OFFSET = 2,
    HIGH_SCORE_TEXT_SCORE_OFFSET = 3,
    HIGH_SCORE_TITLE_WIDGET = 0x66,
    HIGH_SCORE_STANDARD_TITLE_FRAME = 6,
    HIGH_SCORE_CAMPAIGN_TITLE_FRAME = 7,
    HIGH_SCORE_WIDGET_DEFAULT_VALUE = 6,
    HIGH_SCORE_STANDARD_SCENARIO_RESIZE = 0xf1,
    HIGH_SCORE_CAMPAIGN_SCENARIO_RESIZE = 0x127,
    HIGH_SCORE_STANDARD_RATING_RESIZE = 0x190,
    HIGH_SCORE_CAMPAIGN_RATING_RESIZE = 0x1d3,
    HIGH_SCORE_PRIMARY_SELECTION_FRAME = 1,
    HIGH_SCORE_SECONDARY_SELECTION_FRAME = 2,
    HIGH_SCORE_DRAW_X = 0,
    HIGH_SCORE_DRAW_Y = 200,
    HIGH_SCORE_DRAW_HEIGHT = 230,
    HIGH_SCORE_UPDATE_X = 512,
    HIGH_SCORE_UPDATE_Y = 51,
    HIGH_SCORE_UPDATE_WIDTH = 76,
    HIGH_SCORE_UPDATE_HEIGHT = 406,
    HIGH_SCORE_INPUT_BLOCK_FLAG = 0x200,
    HIGH_SCORE_MANAGER_OPEN_OK = 0,
    HIGH_SCORE_MANAGER_CONTINUE = 1,
    HIGH_SCORE_MANAGER_CLOSE = 2
H2_ENUM_END(HighScoreManagerConstant)

#pragma pack(push, 1)
class highScoreManager : public baseManager {
public:
    i16 m_animationFrames[HIGH_SCORE_DISPLAY_ENTRY_COUNT];
    i16 m_monsterTypes[HIGH_SCORE_DISPLAY_ENTRY_COUNT];
    char m_showCampaignScores;
    heroWindow* m_window;
    highScoreManager(void);
    virtual i32 Open(i32) OVERRIDE;
    virtual void Close(void) OVERRIDE;
    virtual i32 Main(struct tag_message&) OVERRIDE;
    void Update(void);
};
#pragma pack(pop)
SIZE(highScoreManager, 0x63);
#endif
