#ifndef HOMM2_KB_H
#define HOMM2_KB_H
#include <va.h>
// Declarations of the free functions DEFINED in KB.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct SAMPLE2;
struct SSpellInfo;
struct SWinSetup;
class advManager;
class armyGroup;
class combatManager;
struct configStruct;
class executive;
class font;
class game;
class hero;
class heroWindow;
class heroWindowManager;
class icon;
class inputManager;
class mouseManager;
class palette;
class philAI;
class resourceManager;
class searchArray;
class soundManager;
struct tag_message;
struct tag_monsterInfo;
struct tag_tilePoint;
struct mapEventExtra;
class town;
class townManager;
#include <_types.h>
#include <_carcass_types.h>

// KB-private record structs (shared ones — tag_message/SAMPLE2/tag_monsterInfo/SSpellInfo/
// SWinSetup/SNetPlayerInfo — live in _types.h / _carcass_types.h).
#ifndef HOMM2_GAME_RECORD_TYPES
#define HOMM2_GAME_RECORD_TYPES
struct townSlot { char m_pad[0x64]; };
struct heroRec  { char m_pad[250]; };
#endif
struct SPlayerExit { signed char m_0, m_1, m_2, m_3, m_4, m_5, m_6; };
extern "C" void PollSound(void);
void ForcePollSound(void);
void InitMainClasses(void);
void DeleteMainClasses(void);
void EarlyShutdown(char *caption, char *text);
void SetupCDRom(void);
int EarlySetup(void);
int oldmain(void);
char toupper(char c);
int InterpretCommandLine(void);
int InitMenuHandler(struct tag_message &);
int NullHandler(struct tag_message &msg);
int RecruitHeroHandler(tag_message &msg);
char *GetBuildingInfo(int race, int building, int mode);
char *GetBuildingName(int race, int building);
void GetBuildingCost(int race, int building, int *const dest, int mageLevel);
char *GetMonsterName(int m);
void GetMonsterCost(int monster, int *const cost);
int CanBuild(town *t, int building);
int CanBuy(town *t, int type);
int GetBuildingBaseResourceValue(int race, int building, int level);
int WaitHandler(tag_message &msg);
int EventWindowHandler(struct tag_message &);
int TrueFalseDialogHandler(struct tag_message &msg);
void PlayerDead(int player);
void CheckEndGame(int, int);
void QuickViewWait(void);
void InitVars(void);
void ClearMapExtra(void);
int GetMonType(int score, int campaign);
int AddScoreToHighScore(int, int, int, int, char *);
void BVResMsg(char *s, int res, int qty);
void GOut(char *str);
int NetPosToGamePos(int netPos);
int WaitForOtherPlayer(void);
void PopNetBox(char *, int);
void AddNetBoxLine(char *str, char color);
void ShutDown(char *msg);
void FileError(char *filename);
void SmackFade(unsigned char *src, unsigned char *dst);
void ShowCongrats(int);
void CongratsWait(void);
SAMPLE2 LoadPlaySample(char *name);
void WaitEndSample(SAMPLE2 s, int waitTime);
void MemError(void);
char *GetTownName(int i);
void LoadSystemwideIcons(void);
void UnloadSystemwideIcons(void);
void EarlyShutDownSystem(void);
int GameUnsaved(void);
int HandleAppSpecificMenuCommands(int);
void UpdateSystemOptionsMenu(void);
void CleanUpMenus(void);
void UpdateAppSpecificMenus(void *hMenu);
void EarlyResizeWindow(int x, int y, int w, int h);
int InMapArea(int x, int y);
void SetupDynamicWindow(int, int, int, int, int, int, int, int *, int *, int *, int *, int *, int *, class heroWindow * *, int);
void TestDynamicWindow(int p1, int p2);
void HandleRemoteDeadPlayerExit(int pos);
void HandleRemoteSuddenExit(void);
void DropDownToOnePlayer(void);
void ReceiveHostReportsPlayerExit(int, struct SPlayerExit, int);
void ReceiveRemotePlayerExit(struct SPlayerExit);
int CheckMem(void);
int GetManaCost(int spell, hero *h);
void SetWinText(heroWindow *j, int id);
void CheckShingleUpdate(void);
void NormalDialog(char *, int, int, int, int, int, int, int, int, int);
void UpdateNormalDialog(char *text);


// --- globals owned by this TU (moved from _globals.h; CodeView-attributed) ---
extern int bDoColorCycle;
extern int gbDrawWindowBackground;
extern int bEarlySetupDone;
extern font *bigFont;
extern int bInShutDown;
extern int bShowIt;
extern int bSpecialHideCursor;
extern char *cBuildingInfoNeutral[];
extern char cNetBoxColor[];
extern char cNetBoxLine[][140];
extern char *cOutOfMemory;
extern char *gArmyNames[];
extern char *gArmyNamesPlural[];
extern int gArtifactBaseRV[100];
extern int gbAllBlack;
extern int gbCheatMenus;
extern int gbClosingApp;
extern signed char gbCombatSurrender;
extern int gbDrawSavedCursor;
extern int gbForegroundApp;
extern int gbFunctionComplete;
extern int gbGameInitialized;
extern signed char gbGamePosToNetPos[];
extern int gbHeroMoving;
extern int gbHumanPlayer[];
extern int gbLoadingMonoIcon;
extern unsigned char gColorTableYellow[];
extern unsigned char gColorTableScenWin[];
extern unsigned char gColorTableDarkGray[];
extern int gbInMemError;
extern int gbInNewGameSetup;
extern int gbInPollSound;
extern int gbNoCDRom;
extern int gbNoSound;
extern int gbPutzingWithMouseCtr;
extern int gbRemoteOn;
extern signed char gbRetreatWin;
extern int gbTextEntryEscaped;
extern int gbThisNetGotAdventureControl;
extern signed char gbThisNetHumanPlayer[];
extern unsigned char bStopOnTrigger[128];
extern char *gBuildingInfoSpecial[];
extern icon *gBuyBuildIcons;
extern char gcBottomViewText[];
extern configStruct gConfig;
extern int gDwellingBaseResourceValues[][12];
extern int gDwellingCosts[][12][7];
extern char *gDwellingNames[][12];
extern signed char gDwellingType[20][12];
extern int gGameCommand;
extern int gHeroGoldCost;
extern unsigned long gHierarchyMask[][12];
extern int giBottomViewOverride;
extern int giBottomViewOverrideEndTime;
extern int giBottomViewResource;
extern int giBottomViewResourceQty;
extern int giCycleType;
extern int giDebugLevel;
extern unsigned char giGroundToTerrain[];
extern int giHighMemBuffer;
extern int giMainVideoModeColorDepth;
extern int giNumHumanPlayers;
extern short giScoreCampaignMon[][2];
extern short giScoreMon[][2];
extern int giTCPHostStatus;
extern int giThisGamePos;
extern int giThisNetPos;
extern int giTotalHighMem;
extern int giWaitType;
extern int glTimers[];
extern int gMageBaseResourceValues[];
extern int gMageBuildingCosts[][7];
extern tag_monsterInfo gMonsterDatabase[];
extern int gNeutralBaseResourceValues[];
extern int gNeutralBuildingCosts[][7];
extern char *gNeutralBuildingNames[];
extern advManager *gpAdvManager;
extern palette *gPalette;
extern combatManager *gpCombatManager;
extern executive *gpExec;
extern game *gpGame;
extern inputManager *gpInputManager;
extern armyGroup *gpMonGroup;
extern class mouseManager *gpMouseManager;
extern philAI *gpPhilAI;
extern resourceManager *gpResourceManager;
extern searchArray *gpSearchArray;
extern soundManager *gpSoundManager;
extern townManager *gpTownManager;
extern class heroWindowManager *gpWindowManager;
extern int gResourceBaseValue[];
extern icon *gShingleAnim;
extern int gSpecialBuildingBaseResourceValues[];
extern int gSpecialBuildingCosts[][7];
extern char *gSpecialBuildingNames[];
extern SSpellInfo gsSpellInfo[];
extern icon *gSystemIcons;
extern char gText[];
extern char *gWellExtraNames[];
extern SWinSetup gWinSetup[];
extern void *hmnuAdv;
extern void *hmnuCmbt;
extern void *hmnuDflt;
extern void *hmnuTown;
extern int iCDRomErr;
extern int iMaxMapExtra;
extern int iNextShingleAnim;
extern int iShingleAnimFrame;
extern int MAP_HEIGHT;
extern int MAP_WIDTH;
extern unsigned char *mapExtra;
extern tag_tilePoint normalDirTable[];
extern SAMPLE2 NULL_SAMPLE2;
extern heroWindow *pNormalDialogWindow;
extern void **ppMapExtra;
extern short *pwSizeOfMapExtra;
extern font *smallFont;

#endif // HOMM2_KB_H
