#ifndef HOMM2_SOURCE_KB_TYPES_H
#define HOMM2_SOURCE_KB_TYPES_H
// Compatibility aggregate for shared records used by KB.cpp and its consumers. Domain
// headers are canonical where split out; MSVC mirrors remain flattened when a nested include
// boundary would perturb cumulative compiler state.
#include <va.h>
// Forward declarations for opaque pointer members.
class sample;

// Resource-type index for the game's per-resource arrays (gafAITurnCostResource, p[] amounts,
// etc.), in the standard HoMM2 order. MERCURY/ORE/CRYSTAL are confirmed by the retail's
// per-element .rdata float symbols referenced in philAI::RVConversion; the rest follow the
// canonical order.
HOMM2_ENUM_BEGIN(ResourceType)
    RES_WOOD = 0,
    RES_MERCURY = 1,
    RES_ORE = 2,
    RES_SULFUR = 3,
    RES_CRYSTAL = 4,
    RES_GEMS = 5,
    RES_GOLD = 6
HOMM2_ENUM_END(ResourceType)

HOMM2_ENUM_BEGIN(CreatureType)
    CREATURE_NONE = -1,
    CREATURE_PEASANT = 0,
    CREATURE_ARCHER = 1,
    CREATURE_RANGER = 2,
    CREATURE_PIKEMAN = 3,
    CREATURE_VETERAN_PIKEMAN = 4,
    CREATURE_SWORDSMAN = 5,
    CREATURE_MASTER_SWORDSMAN = 6,
    CREATURE_CAVALRY = 7,
    CREATURE_CHAMPION = 8,
    CREATURE_PALADIN = 9,
    CREATURE_CRUSADER = 10,
    CREATURE_GOBLIN = 11,
    CREATURE_ORC = 12,
    CREATURE_ORC_CHIEF = 13,
    CREATURE_WOLF = 14,
    CREATURE_OGRE = 15,
    CREATURE_OGRE_LORD = 16,
    CREATURE_TROLL = 17,
    CREATURE_WAR_TROLL = 18,
    CREATURE_CYCLOPS = 19,
    CREATURE_SPRITE = 20,
    CREATURE_DWARF = 21,
    CREATURE_BATTLE_DWARF = 22,
    CREATURE_ELF = 23,
    CREATURE_GRAND_ELF = 24,
    CREATURE_DRUID = 25,
    CREATURE_GREATER_DRUID = 26,
    CREATURE_UNICORN = 27,
    CREATURE_PHOENIX = 28,
    CREATURE_CENTAUR = 29,
    CREATURE_GARGOYLE = 30,
    CREATURE_GRIFFIN = 31,
    CREATURE_MINOTAUR = 32,
    CREATURE_MINOTAUR_KING = 33,
    CREATURE_HYDRA = 34,
    CREATURE_GREEN_DRAGON = 35,
    CREATURE_RED_DRAGON = 36,
    CREATURE_BLACK_DRAGON = 37,
    CREATURE_HALFLING = 38,
    CREATURE_BOAR = 39,
    CREATURE_IRON_GOLEM = 40,
    CREATURE_STEEL_GOLEM = 41,
    CREATURE_ROC = 42,
    CREATURE_MAGE = 43,
    CREATURE_ARCHMAGE = 44,
    CREATURE_GIANT = 45,
    CREATURE_TITAN = 46,
    CREATURE_SKELETON = 47,
    CREATURE_ZOMBIE = 48,
    CREATURE_MUTANT_ZOMBIE = 49,
    CREATURE_MUMMY = 50,
    CREATURE_ROYAL_MUMMY = 51,
    CREATURE_VAMPIRE = 52,
    CREATURE_VAMPIRE_LORD = 53,
    CREATURE_LICH = 54,
    CREATURE_POWER_LICH = 55,
    CREATURE_BONE_DRAGON = 56,
    CREATURE_ROGUE = 57,
    CREATURE_NOMAD = 58,
    CREATURE_GHOST = 59,
    CREATURE_GENIE = 60,
    CREATURE_MEDUSA = 61,
    CREATURE_EARTH_ELEMENTAL = 62,
    CREATURE_AIR_ELEMENTAL = 63,
    CREATURE_FIRE_ELEMENTAL = 64,
    CREATURE_WATER_ELEMENTAL = 65,
    CREATURE_COUNT = 66
HOMM2_ENUM_END(CreatureType)

HOMM2_ENUM_BEGIN(ArtifactType)
    ARTIFACT_NONE = -1,
    ARTIFACT_ULTIMATE_BOOK = 0,
    ARTIFACT_ULTIMATE_SWORD = 1,
    ARTIFACT_ULTIMATE_CLOAK = 2,
    ARTIFACT_ULTIMATE_WAND = 3,
    ARTIFACT_ULTIMATE_SHIELD = 4,
    ARTIFACT_ULTIMATE_STAFF = 5,
    ARTIFACT_ULTIMATE_CROWN = 6,
    ARTIFACT_GOLDEN_GOOSE = 7,
    ARTIFACT_ARCANE_NECKLACE = 8,
    ARTIFACT_CASTER_BRACELET = 9,
    ARTIFACT_MAGE_RING = 10,
    ARTIFACT_WITCHES_BROACH = 11,
    ARTIFACT_MEDAL_OF_VALOR = 12,
    ARTIFACT_MEDAL_OF_COURAGE = 13,
    ARTIFACT_MEDAL_OF_HONOR = 14,
    ARTIFACT_MEDAL_OF_DISTINCTION = 15,
    ARTIFACT_FIZBIN_OF_MISFORTUNE = 16,
    ARTIFACT_THUNDER_MACE = 17,
    ARTIFACT_ARMORED_GAUNTLETS = 18,
    ARTIFACT_DEFENDER_HELM = 19,
    ARTIFACT_GIANT_FLAIL = 20,
    ARTIFACT_BALLISTA = 21,
    ARTIFACT_STEALTH_SHIELD = 22,
    ARTIFACT_DRAGON_SWORD = 23,
    ARTIFACT_POWER_AXE = 24,
    ARTIFACT_DIVINE_BREASTPLATE = 25,
    ARTIFACT_MINOR_SCROLL = 26,
    ARTIFACT_MAJOR_SCROLL = 27,
    ARTIFACT_SUPERIOR_SCROLL = 28,
    ARTIFACT_FOREMOST_SCROLL = 29,
    ARTIFACT_ENDLESS_SACK_GOLD = 30,
    ARTIFACT_ENDLESS_BAG_GOLD = 31,
    ARTIFACT_ENDLESS_PURSE_GOLD = 32,
    ARTIFACT_NOMAD_BOOTS = 33,
    ARTIFACT_TRAVELER_BOOTS = 34,
    ARTIFACT_RABBIT_FOOT = 35,
    ARTIFACT_GOLDEN_HORSESHOE = 36,
    ARTIFACT_GAMBLERS_COIN = 37,
    ARTIFACT_FOUR_LEAF_CLOVER = 38,
    ARTIFACT_TRUE_COMPASS = 39,
    ARTIFACT_SAILORS_ASTROLABE = 40,
    ARTIFACT_EVIL_EYE = 41,
    ARTIFACT_ENCHANTED_HOURGLASS = 42,
    ARTIFACT_GOLD_WATCH = 43,
    ARTIFACT_SKULLCAP = 44,
    ARTIFACT_ICE_CLOAK = 45,
    ARTIFACT_FIRE_CLOAK = 46,
    ARTIFACT_LIGHTNING_HELM = 47,
    ARTIFACT_EVERCOLD_ICICLE = 48,
    ARTIFACT_EVERHOT_LAVA_ROCK = 49,
    ARTIFACT_LIGHTNING_ROD = 50,
    ARTIFACT_SNAKE_RING = 51,
    ARTIFACT_ANKH = 52,
    ARTIFACT_BOOK_ELEMENTS = 53,
    ARTIFACT_ELEMENTAL_RING = 54,
    ARTIFACT_HOLY_PENDANT = 55,
    ARTIFACT_PENDANT_FREE_WILL = 56,
    ARTIFACT_PENDANT_LIFE = 57,
    ARTIFACT_SERENITY_PENDANT = 58,
    ARTIFACT_SEEING_EYE_PENDANT = 59,
    ARTIFACT_KINETIC_PENDANT = 60,
    ARTIFACT_PENDANT_DEATH = 61,
    ARTIFACT_WAND_NEGATION = 62,
    ARTIFACT_GOLDEN_BOW = 63,
    ARTIFACT_TELESCOPE = 64,
    ARTIFACT_STATESMANS_QUILL = 65,
    ARTIFACT_WIZARD_HAT = 66,
    ARTIFACT_POWER_RING = 67,
    ARTIFACT_AMMO_CART = 68,
    ARTIFACT_TAX_LIEN = 69,
    ARTIFACT_HIDEOUS_MASK = 70,
    ARTIFACT_ENDLESS_POUCH_SULFUR = 71,
    ARTIFACT_ENDLESS_VIAL_MERCURY = 72,
    ARTIFACT_ENDLESS_POUCH_GEMS = 73,
    ARTIFACT_ENDLESS_CORD_WOOD = 74,
    ARTIFACT_ENDLESS_CART_ORE = 75,
    ARTIFACT_ENDLESS_POUCH_CRYSTAL = 76,
    ARTIFACT_SPIKED_HELM = 77,
    ARTIFACT_SPIKED_SHIELD = 78,
    ARTIFACT_WHITE_PEARL = 79,
    ARTIFACT_BLACK_PEARL = 80,
    ARTIFACT_MAGIC_BOOK = 81,
    ARTIFACT_EDITOR_ANY_ULTIMATE = 82,
    ARTIFACT_EDITOR_UNUSED_84 = 83,
    ARTIFACT_EDITOR_UNUSED_85 = 84,
    ARTIFACT_EDITOR_UNUSED_86 = 85,
    ARTIFACT_SPELL_SCROLL = 86,
    ARTIFACT_ARM_OF_MARTYR = 87,
    ARTIFACT_BREASTPLATE_ANDURAN = 88,
    ARTIFACT_BROACH_SHIELDING = 89,
    ARTIFACT_BATTLE_GARB = 90,
    ARTIFACT_CRYSTAL_BALL = 91,
    ARTIFACT_HEART_FIRE = 92,
    ARTIFACT_HEART_ICE = 93,
    ARTIFACT_HELMET_ANDURAN = 94,
    ARTIFACT_HOLY_HAMMER = 95,
    ARTIFACT_LEGENDARY_SCEPTER = 96,
    ARTIFACT_MASTHEAD = 97,
    ARTIFACT_SPHERE_NEGATION = 98,
    ARTIFACT_STAFF_WIZARDRY = 99,
    ARTIFACT_SWORD_BREAKER = 100,
    ARTIFACT_SWORD_ANDURAN = 101,
    ARTIFACT_SPADE_NECROMANCY = 102,
    ARTIFACT_COUNT = 103
HOMM2_ENUM_END(ArtifactType)

HOMM2_ENUM_BEGIN(SpellType)
    SPELL_NONE = -1,
    SPELL_FIREBALL = 0,
    SPELL_FIREBLAST = 1,
    SPELL_LIGHTNING_BOLT = 2,
    SPELL_CHAIN_LIGHTNING = 3,
    SPELL_TELEPORT = 4,
    SPELL_CURE = 5,
    SPELL_MASS_CURE = 6,
    SPELL_RESURRECT = 7,
    SPELL_TRUE_RESURRECT = 8,
    SPELL_HASTE = 9,
    SPELL_MASS_HASTE = 10,
    SPELL_SLOW = 11,
    SPELL_MASS_SLOW = 12,
    SPELL_BLIND = 13,
    SPELL_BLESS = 14,
    SPELL_MASS_BLESS = 15,
    SPELL_STONE_SKIN = 16,
    SPELL_STEEL_SKIN = 17,
    SPELL_CURSE = 18,
    SPELL_MASS_CURSE = 19,
    SPELL_HOLY_WORD = 20,
    SPELL_HOLY_SHOUT = 21,
    SPELL_ANTI_MAGIC = 22,
    SPELL_DISPEL = 23,
    SPELL_MASS_DISPEL = 24,
    SPELL_MAGIC_ARROW = 25,
    SPELL_BERSERKER = 26,
    SPELL_ARMAGEDDON = 27,
    SPELL_ELEMENTAL_STORM = 28,
    SPELL_METEOR_SHOWER = 29,
    SPELL_PARALYZE = 30,
    SPELL_HYPNOTIZE = 31,
    SPELL_COLD_RAY = 32,
    SPELL_COLD_RING = 33,
    SPELL_DISRUPTING_RAY = 34,
    SPELL_DEATH_RIPPLE = 35,
    SPELL_DEATH_WAVE = 36,
    SPELL_DRAGON_SLAYER = 37,
    SPELL_BLOOD_LUST = 38,
    SPELL_ANIMATE_DEAD = 39,
    SPELL_MIRROR_IMAGE = 40,
    SPELL_SHIELD = 41,
    SPELL_MASS_SHIELD = 42,
    SPELL_SUMMON_EARTH_ELEMENTAL = 43,
    SPELL_SUMMON_AIR_ELEMENTAL = 44,
    SPELL_SUMMON_FIRE_ELEMENTAL = 45,
    SPELL_SUMMON_WATER_ELEMENTAL = 46,
    SPELL_EARTHQUAKE = 47,
    SPELL_VIEW_MINES = 48,
    SPELL_VIEW_RESOURCES = 49,
    SPELL_VIEW_ARTIFACTS = 50,
    SPELL_VIEW_TOWNS = 51,
    SPELL_VIEW_HEROES = 52,
    SPELL_VIEW_ALL = 53,
    SPELL_IDENTIFY_HERO = 54,
    SPELL_SUMMON_BOAT = 55,
    SPELL_DIMENSION_DOOR = 56,
    SPELL_TOWN_GATE = 57,
    SPELL_TOWN_PORTAL = 58,
    SPELL_VISIONS = 59,
    SPELL_HAUNT = 60,
    SPELL_SET_EARTH_GUARDIAN = 61,
    SPELL_SET_AIR_GUARDIAN = 62,
    SPELL_SET_FIRE_GUARDIAN = 63,
    SPELL_SET_WATER_GUARDIAN = 64,
    SPELL_COUNT = 65
HOMM2_ENUM_END(SpellType)

HOMM2_ENUM_BEGIN(CreatureSpellType)
    CREATURE_SPELL_PETRIFY = 101,
    CREATURE_SPELL_DISPEL = 102
HOMM2_ENUM_END(CreatureSpellType)

HOMM2_ENUM_VALUES_BEGIN(MapObjectType)
    MAP_OBJECT_NONE = 0,
    MAP_OBJECT_ALCHEMIST_LAB = 1,
    MAP_OBJECT_SIGN = 2,
    MAP_OBJECT_BUOY = 3,
    MAP_OBJECT_SKELETON = 4,
    MAP_OBJECT_DAEMON_CAVE = 5,
    MAP_OBJECT_TREASURE_CHEST = 6,
    MAP_OBJECT_FAERIE_RING = 7,
    MAP_OBJECT_CAMPFIRE = 8,
    MAP_OBJECT_FOUNTAIN = 9,
    MAP_OBJECT_GAZEBO = 10,
    MAP_OBJECT_ANCIENT_LAMP = 11,
    MAP_OBJECT_GRAVEYARD = 12,
    MAP_OBJECT_ARCHER_HOUSE = 13,
    MAP_OBJECT_GOBLIN_HUT = 14,
    MAP_OBJECT_DWARF_COTTAGE = 15,
    MAP_OBJECT_PEASANT_HUT = 16,
    MAP_OBJECT_LOG_CABIN = 17,
    MAP_OBJECT_ALCHEMIST_TOWER = 18,
    MAP_OBJECT_MAP_EVENT = 19,
    MAP_OBJECT_DRAGON_CITY = 20,
    MAP_OBJECT_LIGHTHOUSE = 21,
    MAP_OBJECT_WATER_WHEEL = 22,
    MAP_OBJECT_MINE = 23,
    MAP_OBJECT_MONSTER = 24,
    MAP_OBJECT_OBELISK = 25,
    MAP_OBJECT_OASIS = 26,
    MAP_OBJECT_RESOURCE = 27,
    MAP_OBJECT_COAST = 28,
    MAP_OBJECT_SAWMILL = 29,
    MAP_OBJECT_ORACLE = 30,
    MAP_OBJECT_SHRINE_FIRST_CIRCLE = 31,
    MAP_OBJECT_SHIPWRECK = 32,
    MAP_OBJECT_SEA_CHEST = 33,
    MAP_OBJECT_DESERT_TENT = 34,
    MAP_OBJECT_CASTLE = 35,
    MAP_OBJECT_STONE_LITHS = 36,
    MAP_OBJECT_WAGON_CAMP = 37,
    MAP_OBJECT_HUT_OF_MAGI = 38,
    MAP_OBJECT_WHIRLPOOL = 39,
    MAP_OBJECT_WINDMILL = 40,
    MAP_OBJECT_ARTIFACT = 41,
    MAP_OBJECT_MERMAID = 42,
    MAP_OBJECT_HERO_INTERACTION = IDX(MAP_OBJECT_MERMAID),
    MAP_OBJECT_BOAT = 43,
    MAP_OBJECT_RANDOM_ULTIMATE_ARTIFACT = 44,
    MAP_OBJECT_RANDOM_ARTIFACT = 45,
    MAP_OBJECT_RANDOM_RESOURCE = 46,
    MAP_OBJECT_RANDOM_MONSTER = 47,
    MAP_OBJECT_RANDOM_TOWN = 48,
    MAP_OBJECT_RANDOM_CASTLE = 49,
    MAP_OBJECT_EYE_OF_MAGI = 50,
    MAP_OBJECT_RANDOM_MONSTER_WEAK = 51,
    MAP_OBJECT_RANDOM_MONSTER_MEDIUM = 52,
    MAP_OBJECT_RANDOM_MONSTER_STRONG = 53,
    MAP_OBJECT_RANDOM_MONSTER_VERY_STRONG = 54,
    MAP_OBJECT_HERO = 55,
    MAP_OBJECT_NOTHING_SPECIAL = 56,
    MAP_OBJECT_MOSSY_ROCK = 57,
    MAP_OBJECT_WATCH_TOWER = 58,
    MAP_OBJECT_TREE_HOUSE = 59,
    MAP_OBJECT_TREE_CITY = 60,
    MAP_OBJECT_RUINS = 61,
    MAP_OBJECT_FORT = 62,
    MAP_OBJECT_TRADING_POST = 63,
    MAP_OBJECT_ABANDONED_MINE = 64,
    MAP_OBJECT_SIRENS = 65,
    MAP_OBJECT_STANDING_STONES = 66,
    MAP_OBJECT_IDOL = 67,
    MAP_OBJECT_TREE_OF_KNOWLEDGE = 68,
    MAP_OBJECT_WITCH_DOCTOR_HUT = 69,
    MAP_OBJECT_TEMPLE = 70,
    MAP_OBJECT_HILL_FORT = 71,
    MAP_OBJECT_HALFLING_HOLE = 72,
    MAP_OBJECT_MERCENARY_CAMP = 73,
    MAP_OBJECT_SHRINE_SECOND_CIRCLE = 74,
    MAP_OBJECT_SHRINE_THIRD_CIRCLE = 75,
    MAP_OBJECT_PYRAMID = 76,
    MAP_OBJECT_CITY_OF_DEAD = 77,
    MAP_OBJECT_EXCAVATION = 78,
    MAP_OBJECT_SPHINX = 79,
    MAP_OBJECT_WAGON = 80,
    MAP_OBJECT_TAR_PIT = 81,
    MAP_OBJECT_ARTESIAN_SPRING = 82,
    MAP_OBJECT_TROLL_BRIDGE = 83,
    MAP_OBJECT_WATERING_HOLE = 84,
    MAP_OBJECT_WITCH_HUT = 85,
    MAP_OBJECT_XANADU = 86,
    MAP_OBJECT_CAVE = 87,
    MAP_OBJECT_LEAN_TO = 88,
    MAP_OBJECT_MAGELLAN_MAPS = 89,
    MAP_OBJECT_FLOTSAM = 90,
    MAP_OBJECT_DERELICT_SHIP = 91,
    MAP_OBJECT_SHIPWRECK_SURVIVOR = 92,
    MAP_OBJECT_BOTTLE = 93,
    MAP_OBJECT_MAGIC_WELL = 94,
    MAP_OBJECT_MAGIC_GARDEN = 95,
    MAP_OBJECT_OBSERVATION_TOWER = 96,
    MAP_OBJECT_FREEMANS_FOUNDRY = 97,
    MAP_OBJECT_REEFS = 98,
    MAP_OBJECT_TREES = 99,
    MAP_OBJECT_MOUNTAINS = 100,
    MAP_OBJECT_VOLCANO = 101,
    MAP_OBJECT_FLOWERS = 102,
    MAP_OBJECT_ROCK = 103,
    MAP_OBJECT_WATER_LAKE = 104,
    MAP_OBJECT_MANDRAKE = 105,
    MAP_OBJECT_DEAD_TREE = 106,
    MAP_OBJECT_STUMP = 107,
    MAP_OBJECT_CRATER = 108,
    MAP_OBJECT_CACTUS = 109,
    MAP_OBJECT_MOUND = 110,
    MAP_OBJECT_DUNE = 111,
    MAP_OBJECT_LAVA_POOL = 112,
    MAP_OBJECT_SHRUB = 113,
    MAP_OBJECT_ARENA = 114,
    MAP_OBJECT_BARROW_MOUNDS = 115,
    MAP_OBJECT_RANDOM_TREASURE_ARTIFACT = 116,
    MAP_OBJECT_RANDOM_MINOR_ARTIFACT = 117,
    MAP_OBJECT_RANDOM_MAJOR_ARTIFACT = 118,
    MAP_OBJECT_BARRIER = 119,
    MAP_OBJECT_TRAVELER_TENT = 120,
    MAP_OBJECT_EXPANSION_DWELLING = 121,
    MAP_OBJECT_EXPANSION_OBJECT = 122,
    MAP_OBJECT_JAIL = 123
HOMM2_ENUM_VALUES_END(MapObjectType)

enum {
    MAP_TRIGGER_ACTION_FLAG = 0x80,
    MAP_TRIGGER_TYPE_MASK = 0x7f
};

HOMM2_ENUM_BEGIN(FactionType)
    FACTION_KNIGHT = 0,
    FACTION_BARBARIAN = 1,
    FACTION_SORCERESS = 2,
    FACTION_WARLOCK = 3,
    FACTION_WIZARD = 4,
    FACTION_NECROMANCER = 5,
    FACTION_COUNT = 6
HOMM2_ENUM_END(FactionType)

HOMM2_ENUM_BEGIN(TerrainType)
    TERRAIN_WATER = 0,
    TERRAIN_GRASS = 1,
    TERRAIN_SNOW = 2,
    TERRAIN_SWAMP = 3,
    TERRAIN_LAVA = 4,
    TERRAIN_DESERT = 5,
    TERRAIN_DIRT = 6,
    TERRAIN_WASTELAND = 7,
    TERRAIN_BEACH = 8,
    TERRAIN_COUNT = 9
HOMM2_ENUM_END(TerrainType)

HOMM2_ENUM_BEGIN(BuildingSlotType)
    BUILDING_SLOT_MAGE_GUILD = 0,
    BUILDING_SLOT_SPECIAL_ONE = 1,
    BUILDING_SLOT_NECROMANCER_SHRINE = 2,
    BUILDING_SLOT_DOCK = 3,
    BUILDING_SLOT_SPECIAL_FOUR = 4,
    BUILDING_SLOT_UPGRADE_CASTLE = 5,
    BUILDING_SLOT_CASTLE = 6,
    BUILDING_SLOT_SPECIAL_SEVEN = 7,
    BUILDING_SLOT_WELL_EXTRA = 11,
    BUILDING_SLOT_SPECIAL = 13,
    BUILDING_SLOT_DISABLED_FIRST = 14,
    BUILDING_SLOT_NEUTRAL_LAST = 15,
    BUILDING_SLOT_DISABLED_SECOND = 16,
    BUILDING_SLOT_DISABLED_THIRD = 17,
    BUILDING_SLOT_DISABLED_FOURTH = 18,
    BUILDING_SLOT_DWELLING_FIRST = 19,
    BUILDING_SLOT_DWELLING_SECOND = 20,
    BUILDING_SLOT_DWELLING_THIRD = 21,
    BUILDING_SLOT_DWELLING_FOURTH = 22,
    BUILDING_SLOT_DWELLING_FIFTH = 23,
    BUILDING_SLOT_DWELLING_SIXTH = 24,
    BUILDING_SLOT_UPGRADE_FIRST = 25,
    BUILDING_SLOT_NECROMANCER_MAGE_PREREQUISITE = 28,
    BUILDING_SLOT_UPGRADE_LAST = 29,
    BUILDING_SLOT_DWELLING_LAST = 30,
    BUILDING_SLOT_DISABLED_LAST = 31
HOMM2_ENUM_END(BuildingSlotType)

HOMM2_ENUM_BEGIN(MonsterFlags)
    MONSTER_FLAGS_WIDE = 0x00000001,
    MONSTER_FLAGS_FLYING = 0x00000002,
    MONSTER_FLAGS_LIGHT_PALETTE = 0x00000100,
    MONSTER_FLAGS_RED_PALETTE = 0x00000200,
    MONSTER_FLAGS_DARK_BROWN_PALETTE = 0x00002000,
    MONSTER_FLAGS_GRAY_PALETTE = 0x00004000,
    MONSTER_FLAGS_SHOOTER = 0x00000004,
    MONSTER_FLAGS_BREATH_ATTACK = 0x00000008,
    MONSTER_FLAGS_DEAD = 0x00000010,
    MONSTER_FLAGS_AI_EXCLUDED = 0x00000010,
    MONSTER_FLAGS_RETALIATED = 0x00000040,
    MONSTER_FLAGS_WOKE_FROM_DAMAGE = 0x00000080,
    MONSTER_FLAGS_FULL_AI_QUANTITY = 0x00000080,
    MONSTER_FLAGS_MIRROR_IMAGE = 0x00000100,
    MONSTER_FLAGS_SUMMONED = 0x00000800,
    MONSTER_FLAGS_UNDEAD = 0x00000400,
    MONSTER_FLAGS_NO_MORALE = 0x00000400
HOMM2_ENUM_END(MonsterFlags)
HOMM2_ENUM_FLAGS(MonsterFlags)

HOMM2_ENUM_BEGIN(MonsterAbilityFlags)
    MONSTER_ABILITY_FLAG_WIDE = 0x01,
    MONSTER_ABILITY_FLAG_FLYING = 0x02,
    MONSTER_ABILITY_FLAG_SHOOTER = 0x04,
    MONSTER_ABILITY_FLAG_BREATH_ATTACK = 0x08,
    MONSTER_ABILITY_FLAG_AI_EXCLUDED = 0x10,
    MONSTER_ABILITY_FLAG_HIGH_MORALE = 0x20,
    MONSTER_ABILITY_FLAG_BAD_MORALE = 0x80,
    MONSTER_ABILITY_FLAG_FULL_AI_QUANTITY = 0x80,
    MONSTER_ABILITY_FLAG_DEFERRED_TURN = 0x1000
HOMM2_ENUM_END(MonsterAbilityFlags)
HOMM2_ENUM_FLAGS(MonsterAbilityFlags)

// Retained in the historical declaration sequence because MSVC 4.2's cumulative TU state
// changes code generation when these otherwise redundant declarations are removed.
typedef u32 UInt32;
struct MemEntry;
struct _SAMPLE; // SAMPLE2::pMem — opaque

enum {
    MENU_ENABLE_STATUS_COUNT = 70
};
#pragma pack(push, 1)
struct SMenuEnableStatus {
    u32 command;
    u8 normalEnabled;
    u8 setupEnabled;
    // All 70 retail values are zero, and the executable has no xref to this byte.
    u8 reserved;
};
#pragma pack(pop)
SIZE(SMenuEnableStatus, 7);

#include <SOURCE/CONFIG_TYPES.h>
struct tag_tilePoint {
    i8 x;
    i8 y;
    i16 frameOffset;
};
SIZE(tag_tilePoint, 4);
HOMM2_ENUM_VALUES_BEGIN(MonsterDatabaseConstant)
    MONSTER_SPRITE_NAME_SIZE = 5
HOMM2_ENUM_VALUES_END(MonsterDatabaseConstant)
HOMM2_ENUM_BEGIN(MonsterAttribute)
    MONSTER_ATTRIBUTE_WIDE = 0x01,
    MONSTER_ATTRIBUTE_FLYING = 0x02,
    MONSTER_ATTRIBUTE_RANGED = 0x04,
    MONSTER_ATTRIBUTE_TWO_HEX_ATTACKER = 0x08,
    MONSTER_ATTRIBUTE_UNDEAD = 0x0400,
    MONSTER_ATTRIBUTE_DEAD = 0x10,
    MONSTER_ATTRIBUTE_RETALIATED = 0x40,
    MONSTER_ATTRIBUTE_WOKE_FROM_DAMAGE = 0x80
HOMM2_ENUM_END(MonsterAttribute)
HOMM2_ENUM_FLAGS(MonsterAttribute)

#pragma pack(push, 1)
struct tag_monsterInfo {
    union {
        struct {
            i16 cost;
            union {
                i32 fightValue;
                i32 randomValue;
            };
        };
    };
    i8 iconIndex;
    i8 growth;
    u16 hitPoints;
    i8 race;
    i8 speed;
    i8 attack;
    i8 defense;
    i8 damageMin;
    i8 damageMax;
    i8 shots;
    char spriteName[MONSTER_SPRITE_NAME_SIZE];
    union {
        MonsterAttribute attributes;
        union {
            MonsterFlags all;
            i32 abilityFlags;
            struct {
                i8 abilities;
                i8 attributeFlags;
            } bytes;
        } flags;
    };
};
#pragma pack(pop)
SIZE(tag_monsterInfo, 0x1a);
HOMM2_ENUM_VALUES_BEGIN(CombatHeroAnimationConstant)
    COMBAT_HERO_ANIMATION_COUNT = 12,
    COMBAT_HERO_ANIMATION_FRAME_COUNT = 9
HOMM2_ENUM_VALUES_END(CombatHeroAnimationConstant)

#pragma pack(push, 1)
struct SCmbtHero {
    i16 x[2];
    i16 y[2];
    u8 idleAnimationCount;
    i8 animationFrameCount[COMBAT_HERO_ANIMATION_COUNT];
    i8 animationFrames[COMBAT_HERO_ANIMATION_COUNT][COMBAT_HERO_ANIMATION_FRAME_COUNT];
};
SIZE(SCmbtHero, 0x81);
#pragma pack(pop)
HOMM2_ENUM_BEGIN_T(SpellInfoAttribute, u8)
    SPELL_INFO_ATTRIBUTE_POWER = 0x01,
    SPELL_INFO_ATTRIBUTE_COMBAT = 0x02,
    SPELL_INFO_ATTRIBUTE_ADVENTURE = 0x04,
    SPELL_INFO_ATTRIBUTE_DURATION = 0x08
HOMM2_ENUM_END_T(SpellInfoAttribute, u8)
HOMM2_ENUM_FLAGS(SpellInfoAttribute)

struct SSpellInfo {
    char soundName[9];
    u8 level;
    u8 iconIndex;
    u8 combatEffect;
    i16 aiValue;
    u8 cost;
    u8 raceChance[6];
    SpellInfoAttribute attributes;
}; // gsSpellInfo[] (sizeof 22)
SIZE(SSpellInfo, 0x16);
struct SAMPLE2 {
    class sample* pSample;
    struct _SAMPLE* pMem;
}; // NULL_SAMPLE2

#pragma pack(push, 1)
struct SWinSetup {
    u8 windowId;
    u16 widgetId;
    char* text;
};
SIZE(SWinSetup, 7);
#pragma pack(pop)

#endif // HOMM2_SOURCE_KB_TYPES_H
