#ifndef HOMM2_NEWGAME_H
#define HOMM2_NEWGAME_H
// Declarations of the free functions DEFINED in Newgame.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
#include <SOURCE/REQUEST.h>
// forward declarations (was <_all.h>):
struct tag_message;

typedef enum NewGameConstant {
    NEW_GAME_TEXT_BUFFER_COUNT = 3,
    NEW_GAME_TEXT_BUFFER_SIZE = 0x65,
    NEW_GAME_KEY_BUFFER_SIZE = 0x69,
    NEW_GAME_MAP_PACKET_SIZE = 0x74,
    NEW_GAME_PLAYER_INFO_BUFFER_SIZE = 0x100,
    NEW_GAME_PLAYER_INFO_PACKET_SIZE = 0xcc,
    NEW_GAME_SETUP_DATA_SIZE = 0x41,
    NEW_GAME_SETUP_BUFFER_SIZE = 240,
    NEW_GAME_SETUP_PACKET_SIZE = 0x7d,
    NEW_GAME_CHAT_TEXT_LIMIT = 100,
    NEW_GAME_REMOTE_CHANNEL = 0x7f,
    NEW_GAME_REMOTE_PACKET_TYPE = 2,
    NEW_GAME_REMOTE_PACKET_TYPE_ALTERNATE = 3,
    NEW_GAME_REMOTE_CHAT = 0x0b,
    NEW_GAME_REMOTE_SETUP = 0x33,
    NEW_GAME_REMOTE_MAP_HEADER = 0x34,
    NEW_GAME_REMOTE_START = 0x35,
    NEW_GAME_REMOTE_CANCEL = 0x36,
    NEW_GAME_REMOTE_PLAYER_INFO = 0x37,
    NEW_GAME_NETWORK_PLAYER_NONE = -1,
    NEW_GAME_COMPUTER_PLAYER = 10,
    NEW_GAME_DIALOG_CLOSE_MESSAGE = 10,
    NEW_GAME_PLAYER_DEFAULT = 0,
    NEW_GAME_PLAYER_FLEXIBLE = 1,
    NEW_GAME_DEFAULT_DIFFICULTY = 1,
    NEW_GAME_MULTIPLAYER_HOTSEAT = 2,
    NEW_GAME_DIALOG_CANCEL = 0x7801,
    NEW_GAME_DIALOG_OK = 0x7802,
    NEW_GAME_MAP_OPTIONS_CONTROL = 0x36,
    NEW_GAME_WIDGET_ENABLE = 5,
    NEW_GAME_WIDGET_DISABLE = 6,
    NEW_GAME_WIDGET_ACTIVE_FRAME = 0x1000,
    NEW_GAME_WIDGET_INACTIVE_FRAME = 2,
    NEW_GAME_WIDGET_REFRESH_FRAME = 4,
    NEW_GAME_SHADOW_FRAME = 6,
    NEW_GAME_WIDGET_SET_TEXT = 3,
    NEW_GAME_WIDGET_SET_FRAME = 4,
    NEW_GAME_MESSAGE_WIDGET = 0x200,
    NEW_GAME_MESSAGE_IDLE = 0,
    NEW_GAME_MESSAGE_KEY = 1,
    NEW_GAME_EVENT_PRESS = 0x0c,
    NEW_GAME_EVENT_RELEASE = 0x0d,
    NEW_GAME_EVENT_ALTERNATE_PRESS = 0x0e,
    NEW_GAME_MOUSE_RIGHT_FLAG = 0x200,
    NEW_GAME_WINDOW_SOURCE_LINE_BASE = 635,
    NEW_GAME_SOURCE_LINE_BASE = 319,
    NEW_GAME_RANDOM_RACE = 7,
    NEW_GAME_LAST_STANDARD_RACE = 5,
    NEW_GAME_HANDICAP_COUNT = 3,
    NEW_GAME_PLAYER_CONTROL_COUNT = 6,
    NEW_GAME_DIFFICULTY_COUNT = 5,
    NEW_GAME_CHAT_LINE_COUNT = 3,
    NEW_GAME_SWAP_SEARCH_DONE = 999,
    NEW_GAME_COMPUTER_COLOR_LOCKED_FRAME = 15,
    NEW_GAME_COMPUTER_COLOR_UNLOCKED_FRAME = 3,
    NEW_GAME_HUMAN_COLOR_LOCKED_FRAME = 21,
    NEW_GAME_HUMAN_COLOR_UNLOCKED_FRAME = 9,
    NEW_GAME_MULTIPLAYER_COLOR_FRAME_OFFSET = 24,
    NEW_GAME_FIXED_RACE_FRAME_BASE = 70,
    NEW_GAME_RANDOM_RACE_FRAME_BASE = 51,
    NEW_GAME_HELP_DIFFICULTY = 0,
    NEW_GAME_HELP_HANDICAP = 1,
    NEW_GAME_HELP_PLAYER = 2,
    NEW_GAME_HELP_RACE = 3,
    NEW_GAME_HELP_MAP = 4,
    NEW_GAME_HELP_RATING = 5,
    NEW_GAME_HELP_OK = 6,
    NEW_GAME_HELP_CANCEL = 7
} NewGameConstant;

typedef enum NewGameControl {
    NEW_GAME_DIFFICULTY_HELP_FIRST = 1,
    NEW_GAME_DIFFICULTY_FIRST = 0x43,
    NEW_GAME_RACE_FIRST = 6,
    NEW_GAME_COLOR_FIRST = 0x0c,
    NEW_GAME_PLAYER_SELECT_FIRST = 0x12,
    NEW_GAME_PLAYER_NAME_FIRST = 0x18,
    NEW_GAME_RACE_ICON_FIRST = 0x1e,
    NEW_GAME_RACE_CYCLE_FIRST = 0x24,
    NEW_GAME_HANDICAP_FIRST = 0x30,
    NEW_GAME_PLAYER_HUMAN_FIRST = 0x2a,
    NEW_GAME_SCENARIO_NAME = 0x40,
    NEW_GAME_RATING = 0x42,
    NEW_GAME_MAP_SELECT = 0x48,
    NEW_GAME_SHADOW = 0x49,
    NEW_GAME_CHAT_FIRST = 0x4a,
    NEW_GAME_RACE_NAME_FIRST = 0x4e
} NewGameControl;

#pragma pack(push, 1)
struct NewGameRemotePacket {
    signed char sender;
    unsigned char reserved[4];
    signed char type;
    signed char command;
    unsigned char sequence[2];
    char payload[1];
};

#pragma pack(pop)

int NewGameHandler(struct tag_message &);

#endif // HOMM2_NEWGAME_H
