#ifndef HOMM2_OVERVIEW_H
#define HOMM2_OVERVIEW_H

#include <Ints.h>
// Declarations of the free functions DEFINED in Overview.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;
class iconWidget;
class textWidget;

H2_ENUM_CLASS_BEGIN(OverviewType)
    OVERVIEW_HEROES = 0,
    OVERVIEW_TOWNS = 1
H2_ENUM_CLASS_END(OverviewType)

H2_ENUM_BEGIN(OverviewLayoutConstant)
    OVERVIEW_VISIBLE_ROWS = 4,
    OVERVIEW_DYNAMIC_WIDGETS_PER_ROW = 70,
    OVERVIEW_ROW_HEIGHT = 86,
    OVERVIEW_ROW_ID_STRIDE = 200,
    OVERVIEW_TROOP_SLOTS = 5,
    OVERVIEW_DWELLING_SLOTS = 12,
    OVERVIEW_SECONDARY_SKILL_SLOTS = 8,
    OVERVIEW_ARTIFACT_SLOTS = 14,
    OVERVIEW_SECONDARY_SKILL_COLUMNS = 4,
    OVERVIEW_ARTIFACT_COLUMNS = 7
H2_ENUM_END(OverviewLayoutConstant)

typedef iconWidget* OverviewIconWidgetRow[OVERVIEW_DYNAMIC_WIDGETS_PER_ROW];
typedef textWidget* OverviewTextWidgetRow[OVERVIEW_DYNAMIC_WIDGETS_PER_ROW];

H2_ENUM_BEGIN(OverviewUiConstant)
    OVERVIEW_DYNAMIC_ARRAY_BYTES = 0x2bc0,
    OVERVIEW_WIDGET_SET_TEXT = 3,
    OVERVIEW_WIDGET_SET_FRAME = 4,
    OVERVIEW_HERO_TAB_WIDGET = 100,
    OVERVIEW_TOWN_TAB_WIDGET = 0x65,
    OVERVIEW_TITLE_WIDGET = 0x66,
    OVERVIEW_SCROLL_TRACK_WIDGET = 0x6e,
    OVERVIEW_SCROLL_KNOB_WIDGET = 0x6f,
    OVERVIEW_SCROLL_UP_WIDGET = 10,
    OVERVIEW_SCROLL_DOWN_WIDGET = 11,
    OVERVIEW_CLOSE_WIDGET = 14,
    OVERVIEW_TITLE_COUNT = 3,
    OVERVIEW_RESOURCE_COUNT = 7,
    OVERVIEW_RESOURCE_LAST = 6,
    OVERVIEW_RESOURCE_FIRST_WIDGET = 30,
    OVERVIEW_MINE_FIRST_WIDGET = 20,
    OVERVIEW_TOWN_TITLE_WIDGET = 20,
    OVERVIEW_HERO_TITLE_WIDGET = 35,
    OVERVIEW_DAILY_GOLD_WIDGET = 40,
    OVERVIEW_MINE_COUNT = 144,
    OVERVIEW_SAWMILL_RESOURCE = 100,
    OVERVIEW_FADE_STEPS = 8,
    OVERVIEW_SCROLL_MIN_Y = 18,
    OVERVIEW_SCROLL_RANGE = 304,
    OVERVIEW_SCROLL_KNOB_OFFSET = 9,
    OVERVIEW_SCROLL_LAST_PIXEL_ADJUST = 1,
    OVERVIEW_SCROLL_TRACK_Y = 27,
    OVERVIEW_SCROLL_SCALE = 100,
    OVERVIEW_DIALOG_CONTINUE = 1,
    OVERVIEW_DIALOG_CLOSE = 2,
    OVERVIEW_RETURN_NONE = -1,
    OVERVIEW_RETURN_HERO = 1,
    OVERVIEW_RETURN_TOWN = 2,
    OVERVIEW_ICON_ROW_BASE = 200,
    OVERVIEW_ICON_ROW_LIMIT = 1000,
    OVERVIEW_HERO_SELECT_FIRST = 100,
    OVERVIEW_HERO_SELECT_LAST = 103,
    OVERVIEW_HERO_ARMY_FIRST = 104,
    OVERVIEW_HERO_ARMY_LAST = 108,
    OVERVIEW_HERO_ARMY_ALT_FIRST = 109,
    OVERVIEW_HERO_ARMY_ALT_LAST = 113,
    OVERVIEW_HERO_ARTIFACT_FIRST = 114,
    OVERVIEW_HERO_ARTIFACT_LAST = 127,
    OVERVIEW_HERO_SKILL_FIRST = 146,
    OVERVIEW_HERO_SKILL_LAST = 153,
    OVERVIEW_HERO_STAT_FIRST = 170,
    OVERVIEW_HERO_STAT_LAST = 173,
    OVERVIEW_TOWN_SELECT_WIDGET = 4,
    OVERVIEW_TOWN_ARMY_FIRST = 5,
    OVERVIEW_TOWN_ARMY_LAST = 9,
    OVERVIEW_TOWN_ARMY_ALT_FIRST = 10,
    OVERVIEW_TOWN_ARMY_ALT_LAST = 14,
    OVERVIEW_TOWN_RECRUIT_FIRST = 15,
    OVERVIEW_TOWN_RECRUIT_LAST = 26,
    OVERVIEW_TOWN_RECRUIT_ALT_FIRST = 27,
    OVERVIEW_TOWN_RECRUIT_ALT_LAST = 38,
    OVERVIEW_TOWN_HERO_FIRST = 39,
    OVERVIEW_TOWN_HERO_LAST = 43
H2_ENUM_END(OverviewUiConstant)

i32 OverviewHandler(struct tag_message&);

#endif // HOMM2_OVERVIEW_H
