#ifndef HOMM2_PHILAI_TU_H
#define HOMM2_PHILAI_TU_H

#include <va.h>
#include <SOURCE/KB_TYPES.h>

class army;
class hero;
class playerData;
class searchArray;
class town;

H2_ENUM_CLASS_BEGIN(AIPurchaseType)
    PURCHASE_NONE     = -1,
    PURCHASE_BUILDING = 0,
    PURCHASE_HERO     = 1,
    PURCHASE_CREATURE = 2
H2_ENUM_CLASS_END(AIPurchaseType)

struct BHC {
    town* pTown;
    AIPurchaseType type;
    i32 what;
    i32 num;
};

H2_ENUM_BEGIN(AIPurchaseConstant)
    AI_PURCHASE_RESOURCE_COUNT     = IDX(RES_COUNT),
    AI_PLAYER_COUNT                = 6,
    AI_RANDOM_MINE_TYPE_COUNT      = 8,
    AI_PURCHASE_DEBUG_LEVEL        = 3,
    AI_PURCHASE_DEBUG_DELAY        = 1500,
    AI_HERO_BUILD_COORDINATE_UNSET = -99,
    AI_HERO_BUILD_DIRECTION        = 2,
    AI_HERO_BUILD_MAP_CHANGE       = 3,
    AI_HERO_BUILD_MAP_CHANGE_VALUE = -999,
    AI_HERO_AVAILABLE_FLAG         = 0x40,
    AI_PURCHASE_VALUE_DEBUG_LEVEL  = 5
H2_ENUM_END(AIPurchaseConstant)

H2_ENUM_BEGIN(AIBattleConstant)
    AI_BATTLE_NO_PLAYER              = -1,
    AI_BATTLE_EASY_DIFFICULTY        = 0,
    AI_BATTLE_ARTIFACT_SLOT_COUNT    = 14,
    AI_BATTLE_BASE_ARTIFACT_LIMIT    = 37,
    AI_BATTLE_SPECIAL_ARTIFACT_STATE = 2,
    AI_BATTLE_ATTACKER_ARTIFACT_BASE = 1400,
    AI_BATTLE_DEFENDER_ARTIFACT_BASE = 1250,
    AI_BATTLE_SPECIAL_ARTIFACT_VALUE = 50000,
    AI_BATTLE_DEBUG_LEVEL            = 9
H2_ENUM_END(AIBattleConstant)

#define AI_SECONDARY_SKILL_FIGHT_SCALE 2500.0f
#define AI_SECONDARY_SKILL_BASE_FACTOR 0.5
#define AI_SECONDARY_SKILL_NAVIGATION_FACTOR 1.3
#define AI_SECONDARY_SKILL_ARCHERY_SHARE 0.2
#define AI_SECONDARY_SKILL_ARCHERY_BASE 0.25

H2_ENUM_BEGIN(AIGenericSiteConstant)
    AI_GENERIC_SITE_CURSED_ARTIFACTS      = 0,
    AI_GENERIC_SITE_SHIPWRECK             = 1,
    AI_GENERIC_SITE_UNUSED_2              = 2,
    AI_GENERIC_SITE_UNUSED_3              = 3,
    AI_GENERIC_SITE_CREATURE_UPGRADE      = 4,
    AI_GENERIC_SITE_FAERIE_RING           = 5,
    AI_GENERIC_SITE_GRAVEYARD             = 6,
    AI_GENERIC_SITE_TYPE_MASK             = 0x3f,
    AI_GENERIC_SITE_LEVEL_SHIFT           = 6,
    AI_GENERIC_SITE_GOLD_THRESHOLD        = 1500,
    AI_GENERIC_SITE_CURSED_ARTIFACT_VALUE = 500,
    AI_GENERIC_SITE_MAX_LUCK              = 3,
    AI_GENERIC_SITE_ARMY_SLOTS            = 5,
    AI_GENERIC_SITE_WEEK_END              = 8
H2_ENUM_END(AIGenericSiteConstant)

#define AI_GENERIC_SITE_SHIPWRECK_VALUE 1000.0f
#define AI_GENERIC_SITE_FAERIE_RING_VALUE 200.0f
#define AI_GENERIC_SITE_GRAVEYARD_REMAINING 0.7
#define AI_GENERIC_SITE_DAY_VALUE 200

#define AI_MINIMUM_FIGHT_VALUE 100
#define AI_FRAME_THROTTLE_TICKS 15
#define AI_MINIMUM_TURN_MOBILITY 225
#define AI_MINIMUM_SITE_MOBILITY 75
#define AI_HERO_PURCHASE_GOLD_FLOOR 2500
#define AI_BERSERK_THRESHOLD 30000
#define AI_RELOAD_BASE 2.0f
#define AI_RELOAD_NUMERATOR 3.0f
#define AI_EASY_STRENGTH_FACTOR 1.15
#define AI_BERSERK_FACTOR 0.75
#define AI_HERO_VALUE_SCALE 0.00004
#define AI_HERO_VALUE_BASE 0.4
#define AI_ARTIFACT_POOL_DIVISOR 33.0
#define AI_BATTLE_TOWN_DEFENDER_FACTOR 1.11
#define AI_BATTLE_DIFFICULTY_STEP 0.15
#define AI_BATTLE_BASE_STRENGTH_FACTOR 0.7
#define AI_BATTLE_EASY_STRENGTH_FACTOR 1.08
#define AI_BATTLE_HUMAN_DEFENDER_FACTOR 1.14
#define AI_BATTLE_MINIMUM_STRENGTH 1.0f
#define AI_BATTLE_FULL_CHANCE 1.0f
#define AI_BATTLE_LARGE_STRENGTH 1000000.0f
#define AI_BATTLE_NORMAL_POWER 2.75f
#define AI_BATTLE_LARGE_POWER 2.0f
#define AI_BATTLE_ZERO_CHANCE 0.08
#define AI_BATTLE_LOW_CHANCE 0.12
#define AI_BATTLE_LOW_PENALTY 0.07
#define AI_BATTLE_MEDIUM_CHANCE 0.2
#define AI_BATTLE_MEDIUM_PENALTY 0.05
#define AI_BATTLE_HIGH_CHANCE 0.3
#define AI_BATTLE_HIGH_PENALTY 0.04
#define AI_BATTLE_TOP_CHANCE 0.4
#define AI_BATTLE_TOP_PENALTY 0.02
#define AI_BATTLE_LOSS_FACTOR_BASE 1.33
#define AI_BATTLE_PLAYER_FACTOR_BASE 0.66
#define AI_BATTLE_HERO_EXPERIENCE_FACTOR 0.8
#define AI_BATTLE_PERCENT_SCALE 100.0f
#define AI_QUICK_COMBAT_EXPERIENCE_DIFFICULTY_STEP 0.12
#define AI_QUICK_COMBAT_WIN_BONUS_THRESHOLD 0.6
#define AI_QUICK_COMBAT_WIN_BONUS 0.65
#define AI_QUICK_COMBAT_HIGH_WIN_CHANCE 0.8
#define AI_QUICK_COMBAT_MINIMUM_CASUALTY 0.2
#define AI_QUICK_COMBAT_CASUALTY_CAP_CHANCE 0.96
#define AI_QUICK_COMBAT_CASUALTY_DIVISOR 2.0f
#define AI_QUICK_COMBAT_DAMAGE_PENALTY_LOW 0.6
#define AI_QUICK_COMBAT_DAMAGE_PENALTY_HIGH 0.99
#define AI_QUICK_COMBAT_DAMAGE_PENALTY 0.1
#define AI_QUICK_COMBAT_DEFEAT_THRESHOLD 0.99
#define AI_QUICK_COMBAT_NECROMANCY_THRESHOLD 0.999
#define AI_QUICK_COMBAT_NECROMANCY_FACTOR 0.12
#define AI_TOWN_DEFENSE_THRESHOLD 0.7
#define AI_TOWN_ARCHER_OVERWHELMING_FACTOR 1.25
#define AI_TOWN_ARCHER_ADVANTAGE_FACTOR 0.9
#define AI_UPGRADE_EXISTING_STACK_FACTOR 1.2
#define AI_HERO_INTERACTION_ALPHA_SHARE 0.6
#define AI_HERO_INTERACTION_TARGET_SHARE 0.7f
#define AI_HERO_INTERACTION_MINIMUM_TRANSFER 0.15
#define AI_HERO_INTERACTION_VALUE_FACTOR 0.1
#define AI_PURCHASE_RANDOM_DIVISOR 100.0
#define AI_CREATURE_BALANCE_BASE 0.66
#define AI_CREATURE_VISITING_HERO_FACTOR 1.1
#define AI_CREATURE_RANGED_BASE_FACTOR 1.18
#define AI_CREATURE_RANGED_STACK_FACTOR 0.06
#define AI_CREATURE_DANGER_BASE 0.96
#define AI_CREATURE_EASY_COST_FACTOR 1.3
#define AI_CREATURE_RANDOM_BASE 90
#define AI_HERO_PURCHASE_BONUS 500.0f
#define AI_HERO_PURCHASE_FACTOR 1.3
#define AI_HERO_PURCHASE_GOLD_COST 2500
#define AI_HERO_PURCHASE_EXPERIENCE_BASE 2000
#define AI_HERO_PURCHASE_CELL_PENALTY 200.0f
#define AI_HERO_PURCHASE_RANDOM_BASE 90.0
#define AI_PURCHASE_INITIAL_VALUE -99.0f
#define AI_MINIMUM_PURCHASE_VALUE 0.02
#define AI_PLAYER_HERO_IDS_BASE 0x4a0
#define AI_DIMENSION_DOOR_SPELL_POINTS 30
#define AI_MAX_MAGE_GUILD_LEVEL 5
#define AI_TOWN_ARMY_SLOTS 5
#define AI_BUILDING_MAGE_GUILD_MASK 0x00000001
#define AI_BUILDING_SHIPYARD_MASK 0x00000008
#define AI_BUILDING_CASTLE_MASK 0x40
#define AI_BUILDING_LEFT_TURRET_MASK 0x00000100
#define AI_BUILDING_RIGHT_TURRET_MASK 0x00000200
#define AI_MAGIC_BOOK_COST 500
#define AI_MANA_PER_KNOWLEDGE 10
#define AI_EARLY_TOWN_SHARE_TURN 7
#define AI_SECOND_WEEK_END_TURN 14
#define AI_THIRD_WEEK_END_TURN 21
#define AI_MINIMUM_TOWN_SHARE_DIFFERENCE 0.08
#define AI_TOWN_SHARE_DIFFERENCE_FACTOR 0.15
#define AI_TOWN_TRANSFER_BONUS 0.04
#define AI_THIRD_WEEK_TOWN_SHARE_FACTOR 0.8
#define AI_WEAKER_ARMY_TRANSFER_FACTOR 0.25f
#define AI_STRONGER_ARMY_TRANSFER_FACTOR 0.13f
#define AI_TOWN_TRANSFER_CURVE_OFFSET 1.0f
#define AI_TOWN_TRANSFER_CURVE_CENTER 0.22
#define AI_CONQUERED_HERO_MOBILITY_LIMIT 20
#define AI_UNGUARDED_TOWN_VALUE 500
#define AI_TROOP_EMPTY_SLOT -1
#define AI_TROOP_REDISTRIBUTION_WORST_VALUE -9999
#define AI_TROOP_REDISTRIBUTION_MIN_SPEED 1
#define AI_TROOP_REDISTRIBUTION_MAX_SPEED 9
#define AI_TROOP_REDISTRIBUTION_ROUNDING 0.5
#define AI_TROOP_REDISTRIBUTION_STACK_SHARE 0.65
#define AI_TROOP_REDISTRIBUTION_REMAINDER_FACTOR 0.2
#define AI_TROOP_REDISTRIBUTION_BUDGET_FACTOR 1.2
#define AI_CREATURE_SELECTION_WORST_VALUE 1000000000.0f
#define AI_CREATURE_OFF_RACE_FACTOR 0.35
#define AI_CREATURE_SELECTION_BASE_VALUE 500.0
#define AI_DWELLING_LEVELS 12
#define AI_GOLD_RESOURCE_MULTIPLIER 100
#define AI_CAMPFIRE_RESOURCE_AMOUNT 5.0f
#define AI_CAMPFIRE_GOLD_AMOUNT 500.0f
#define AI_CAMPFIRE_AVERAGE_DIVISOR 6.0f
#define AI_OASIS_VALUE_FACTOR 350.0f
#define AI_TREASURE_CHEST_GOLD_AMOUNT 1600.0f
#define AI_BUOY_VALUE_FACTOR 400.0f
#define AI_MORALE_LUCK_SITE_VALUE_FACTOR 200.0f
#define AI_WATERING_HOLE_VALUE_FACTOR 300.0f
#define AI_GAZEBO_VALUE_FACTOR 1000.0f
#define AI_TRAINING_SITE_VALUE_FACTOR 1000.0f
#define AI_TREE_KNOWLEDGE_VALUE_FACTOR 1500.0f
#define AI_TREE_KNOWLEDGE_GOLD_COST 2000.0f
#define AI_TREE_KNOWLEDGE_GEM_COST 10.0f
#define AI_XANADU_VALUE_FACTOR 8000.0f
#define AI_TRAVEL_GATE_INITIAL_VALUE -9999
#define AI_TRAVEL_GATE_EXIT_SCALE 0.85
#define AI_TRAVEL_GATE_EXIT_RADIUS 3
#define AI_TRAVEL_GATE_EXIT_DEPTH 700
#define AI_TRAVEL_GATE_CURRENT_DEPTH 500
#define AI_TRAVEL_GATE_PENALTY 200
#define AI_POSITION_NEARBY_DELTA 1
#define AI_POSITION_DISTANCE_BASE 0.2
#define AI_POSITION_STRATEGIC_DISTANCE_BASE 1.0f
#define AI_POSITION_EMBARKED_DISTANCE_FACTOR 0.5
#define AI_POSITION_LAND_DISTANCE_1 1.0f
#define AI_POSITION_LAND_DISTANCE_2 1.5
#define AI_POSITION_LAND_DISTANCE_3 2.0f
#define AI_POSITION_LAND_DISTANCE_4 3.0f
#define AI_POSITION_LAND_DISTANCE_5 4.0f
#define AI_POSITION_LAND_DISTANCE_6 5.0f
#define AI_POSITION_LAND_FACTOR_2 1.2
#define AI_POSITION_LAND_FACTOR_3 1.4
#define AI_POSITION_LAND_FACTOR_4 1.7
#define AI_POSITION_LAND_FACTOR_5 2.0
#define AI_POSITION_LAND_FACTOR_6 2.5
#define AI_POSITION_LAND_FACTOR_FAR 3.0f
#define AI_ATTENTION_RANDOM_DIVISOR 500.0
#define AI_ATTENTION_RANDOM_BASE 0.23
#define AI_ATTENTION_WEIGHT_A_PLAYER_FACTOR 0.07
#define AI_ATTENTION_WEIGHT_B_PLAYER_FACTOR 0.15
#define AI_TOWN_CASTLE_PRIMARY_SKILL_SHARE_BASE 0.54
#define AI_TOWN_CASTLE_PRIMARY_SKILL_SHARE_STEP 0.02
#define AI_TOWN_PRIMARY_SKILL_SHARE_BASE 0.33
#define AI_TOWN_PRIMARY_SKILL_SHARE_STEP 0.01

static const float AI_TARGET_HUMAN_VALUE_FACTOR = 1.5f;
#define AI_EVENT_HUMAN_VALUE_FACTOR 1.5
static const float AI_STRATEGIC_POSITION_SCORE_FACTOR = 1.25f;
static const float AI_CREATURE_SAME_RACE_FACTOR = 1.1f;
static const float AI_FUTURE_DEFLATION_RATE = 0.15f;
static const float AI_HERO_PURCHASE_SAME_RACE_FACTOR = 0.16f;
static const float AI_ATTENTION_IDENTITY_FLOAT = 1.0f;
#define AI_HERO_PURCHASE_CLASS_DIVISOR 2.0f
#define AI_HERO_PURCHASE_IDENTITY 1.0
static const float AI_ATTENTION_IDENTITY = 1.0f;
#define AI_ATTENTION_PLAYER_CENTER 3.0
#define AI_ATTENTION_NORMALIZER 4.0
#define AI_ATTENTION_UPPER_BOUND 5.0
#define AI_MONSTER_JOIN_RATIO 2.0f
#define AI_MONSTER_OVERWHELMING_RATIO 5.0f
#define AI_MONSTER_JOIN_CHANCE_SCALE 60.0f
#define AI_MONSTER_JOIN_CHANCE_BASE 40.0f
#define AI_MONSTER_FIGHT_CHANCE_SCALE 100.0f
#define AI_MONSTER_JOIN_PURCHASE_WEIGHT 0.6
#define AI_MONSTER_JOIN_OUTCOME_WEIGHT 0.4
#define AI_EVENT_TOWN_PLAYER_FACTOR 0.25
#define AI_EVENT_VALUE_BASE_FACTOR 1.0
#define AI_TOWN_EVENT_VALUE_BASE_FACTOR 0.9
#define AI_TOWN_PRIMARY_HUMAN_VALUE_FACTOR 1.6
#define AI_TOWN_OTHER_HUMAN_VALUE_FACTOR 1.3
#define AI_EVENT_CERTAIN_ODDS 0.75
#define AI_EVENT_HIGH_ODDS 0.5
#define AI_EVENT_GOOD_ODDS 0.4
#define AI_EVENT_POOR_ODDS 0.3
#define AI_EVENT_BAD_ODDS 0.2
#define AI_EVENT_CERTAIN_CHANCE 100.0f
#define AI_EVENT_HIGH_CHANCE_SCALE 136.0f
#define AI_EVENT_GOOD_CHANCE_SCALE 130.0f
#define AI_EVENT_POOR_CHANCE_SCALE 125.0f
#define AI_EVENT_BAD_CHANCE_SCALE 113.0f

#define AI_MAX_BATTLE_STAT 40
#define AI_DAEMON_FIGHT_VALUE_FACTOR 300.0
#define AI_DAEMON_SECONDARY_FIGHT_VALUE_FACTOR 100.0
#define AI_DAEMON_GOLD_VALUE_FACTOR 2500.0f
#define AI_DAEMON_GOLD_PENALTY -750.0
#define AI_DAEMON_CAVE_GOLD_REQUIRED 2500
#define AI_MAGIC_GARDEN_GOLD_AMOUNT 500.0f
#define AI_FLOTSAM_GOLD_AMOUNT 175.0f
#define AI_FLOTSAM_WOOD_AMOUNT 5.0f
#define AI_SEA_CHEST_ARTIFACT_GOLD_AMOUNT 1000.0f
#define AI_SEA_CHEST_LARGE_GOLD_AMOUNT 1500.0f
#define AI_SEA_CHEST_SMALL_GOLD_AMOUNT 200.0f
#define AI_SEA_CHEST_MINIMUM_VALUE 150
#define AI_WATER_WHEEL_GOLD_AMOUNT 500

void ResetHeroRVs(i32, i32, i32);
void CheckDoMain(i32 a1, i32 doMain);
void ShowStatus(void);
void ValidateHero(hero* pHero);
void InitAIMapVars(void);
void CloseAIMapVars(void);
i32 OnMySide(i32);

extern i32 bHeroBuiltThisTurn;
extern float gafAITurnCostResource[AI_PURCHASE_RESOURCE_COUNT];
extern i8* gaiEnemyHeroReachable;
extern i16* gaiHeroEventStratRVOfPos;
extern i16* gaiHeroStrategicRVOfPos;
extern i16* gaiLiveChanceOfPos;
extern i8* gaiTurnValueOfMine;
extern b32 gbReduceByReload;
extern i8 giBuildBoat[AI_PLAYER_COUNT];
extern i8 giBuildBoatStuffTurn[AI_PLAYER_COUNT];
extern i8 giBuildShipyard[AI_PLAYER_COUNT];
extern i32 giCurPlayer;
extern u8 giCurPlayerBit;
extern i32 giCurTurn;
extern hero* gpCurAIHero;
extern playerData* gpCurPlayer;
extern u8 giCurWatchPlayerBit;
extern i32 iAlphaMale;
extern i32 iDummy;
extern i32 iLastFrameRateTimer;
extern searchArray SVSearchArray;

extern b32 gbGameOver;
extern i8 giMonType[];
extern i32 iViewArmyNumTroops;
extern i8* gbNGHeroType;
extern i16 giUABaseX;
extern i16 giUABaseY;
extern i32 giEndSequence;
extern b32 gbDismissArmy;
extern i8* gbNGHuman;
extern i32 iViewArmyFrame;
extern b32 gbAllowUpgrade;
extern i32 iViewArmyType;
extern class hero* viewSpellsHero;
extern b32 gbUpgradeArmy;
extern i16 RandMineQty[AI_RANDOM_MINE_TYPE_COUNT];
extern i8* gbNGDifficulty;
extern CreatureType iViewArmyUpgradeToType;
extern i32 viewArmyBaseX;
extern i32 viewArmyBaseY;
extern i8* gbNGColor;
extern i16 giUARadius;
extern i8* gbNGPlayerPos;
extern i32 viewArmyFacingWIPXMod;

#endif
