#ifndef HOMM2_SPELLS_H
#define HOMM2_SPELLS_H
// Declarations of the free functions DEFINED in SPELLS.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

typedef enum CombatSpell {
    SPELL_FIREBALL = 0,
    SPELL_FIREBLAST = 1,
    SPELL_LIGHTNING_BOLT = 2,
    SPELL_CHAIN_LIGHTNING = 3,
    SPELL_TELEPORT = 4,
    SPELL_CURE = 5,
    SPELL_MASS_CURE = 6,
    SPELL_RESURRECT = 7,
    SPELL_TRUE_RESURRECT = 8,
    SPELL_HASTE = 9,
    SPELL_MASS_HASTE = 10,
    SPELL_SLOW = 11,
    SPELL_MASS_SLOW = 12,
    SPELL_BLIND = 13,
    SPELL_BLESS = 14,
    SPELL_MASS_BLESS = 15,
    SPELL_STONE_SKIN = 16,
    SPELL_STEEL_SKIN = 17,
    SPELL_CURSE = 18,
    SPELL_MASS_CURSE = 19,
    SPELL_HOLY_WORD = 20,
    SPELL_HOLY_SHOUT = 21,
    SPELL_ANTI_MAGIC = 22,
    SPELL_DISPEL = 23,
    SPELL_MASS_DISPEL = 24,
    SPELL_MAGIC_ARROW = 25,
    SPELL_BERSERKER = 26,
    SPELL_ARMAGEDDON = 27,
    SPELL_ELEMENTAL_STORM = 28,
    SPELL_METEOR_SHOWER = 29,
    SPELL_PARALYZE = 30,
    SPELL_HYPNOTIZE = 31,
    SPELL_COLD_RAY = 32,
    SPELL_COLD_RING = 33,
    SPELL_DISRUPTING_RAY = 34,
    SPELL_DEATH_RIPPLE = 35,
    SPELL_DEATH_WAVE = 36,
    SPELL_DRAGON_SLAYER = 37,
    SPELL_BLOOD_LUST = 38,
    SPELL_ANIMATE_DEAD = 39,
    SPELL_MIRROR_IMAGE = 40,
    SPELL_SHIELD = 41,
    SPELL_MASS_SHIELD = 42,
    SPELL_SUMMON_EARTH_ELEMENTAL = 43,
    SPELL_SUMMON_AIR_ELEMENTAL = 44,
    SPELL_SUMMON_FIRE_ELEMENTAL = 45,
    SPELL_SUMMON_WATER_ELEMENTAL = 46,
    SPELL_EARTHQUAKE = 47,
    SPELL_PETRIFY = 101,
    SPELL_CREATURE_DISPEL = 102
} CombatSpell;

typedef enum CombatSpellInfluence {
    SPELL_INFLUENCE_HASTE = 0,
    SPELL_INFLUENCE_SLOW = 1,
    SPELL_INFLUENCE_BLIND = 2,
    SPELL_INFLUENCE_BLESS = 3,
    SPELL_INFLUENCE_CURSE = 4,
    SPELL_INFLUENCE_BERSERKER = 5,
    SPELL_INFLUENCE_PARALYZE = 6,
    SPELL_INFLUENCE_HYPNOTIZE = 7,
    SPELL_INFLUENCE_DRAGON_SLAYER = 8,
    SPELL_INFLUENCE_BLOOD_LUST = 9,
    SPELL_INFLUENCE_SHIELD = 10,
    SPELL_INFLUENCE_MIRROR_IMAGE = 11,
    SPELL_INFLUENCE_ANTI_MAGIC = 12,
    SPELL_INFLUENCE_STONE_SKIN = 13,
    SPELL_INFLUENCE_STEEL_SKIN = 14,
    SPELL_INFLUENCE_COUNT = 15
} CombatSpellInfluence;

typedef enum CombatSpellMonster {
    SPELL_MONSTER_IRON_GOLEM = 0x28,
    SPELL_MONSTER_STEEL_GOLEM = 0x29,
    SPELL_MONSTER_EARTH_ELEMENTAL = 0x3e,
    SPELL_MONSTER_AIR_ELEMENTAL = 0x3f,
    SPELL_MONSTER_FIRE_ELEMENTAL = 0x40,
    SPELL_MONSTER_WATER_ELEMENTAL = 0x41
} CombatSpellMonster;

typedef enum CombatSpellArtifact {
    SPELL_ARTIFACT_GOLD_WATCH = 0x2b,
    SPELL_ARTIFACT_ANKH = 0x34,
    SPELL_ARTIFACT_BOOK_ELEMENTS = 0x35,
    SPELL_ARTIFACT_HOLY_PENDANT = 0x37,
    SPELL_ARTIFACT_PENDANT_FREE_WILL = 0x38,
    SPELL_ARTIFACT_PENDANT_LIFE = 0x39,
    SPELL_ARTIFACT_SERENITY_PENDANT = 0x3a,
    SPELL_ARTIFACT_SEEING_EYE_PENDANT = 0x3b,
    SPELL_ARTIFACT_KINETIC_PENDANT = 0x3c,
    SPELL_ARTIFACT_PENDANT_DEATH = 0x3d,
    SPELL_ARTIFACT_WAND_NEGATION = 0x3e,
    SPELL_ARTIFACT_ENCHANTED_HOURGLASS = 0x2a,
    SPELL_ARTIFACT_WIZARD_HAT = 0x42,
    SPELL_ARTIFACT_SPHERE_NEGATION = 0x62
} CombatSpellArtifact;

enum {
    COMBAT_SPELL_COUNT = 65,
    SPELL_ATTRIBUTE_COMBAT = 2,
    SPELL_ATTRIBUTE_DURATION = 8,
    SPELL_DEFAULT_CREATURE_POWER = 3,
    SPELL_HOURGLASS_POWER_BONUS = 2,
    SPELL_WIZARD_HAT_POWER_BONUS = 10,
    SPELL_LIGHTNING_DAMAGE_PER_POWER = 25,
    SPELL_LIGHTNING_AIR_ELEMENTAL_DAMAGE_PER_POWER = 50,
    SPELL_MAGIC_ARROW_DAMAGE_PER_POWER = 10,
    SPELL_COLD_RAY_DAMAGE_PER_POWER = 20,
    SPELL_COLD_RAY_FIRE_ELEMENTAL_DAMAGE_PER_POWER = 40,
    SPELL_DISRUPTING_RAY_DEFENSE_REDUCTION = 3,
    SPELL_MINIMUM_DEFENSE = 1,
    SPELL_BLOOD_LUST_EFFECT = 0x200,
    SPELL_BLOOD_LUST_DURATION = 3,
    COMBAT_SIDE_COUNT = 2,
    COMBAT_HEX_EMPTY = -1,
    COMBAT_DRAW_DELAY = 75,
    COMBAT_SPELL_TARGET_Y_OFFSET = 17,
    COMBAT_HERO_CAST_LEFT_X_OFFSET = 30,
    COMBAT_HERO_CAST_RIGHT_X = 610,
    COMBAT_HERO_CAST_LEFT_Y_OFFSET = 183,
    COMBAT_HERO_CAST_RIGHT_Y_OFFSET = 148,
    COMBAT_HERO_CAST_NO_TARGET = 3,
    COMBAT_HERO_CAST_LOW = 5,
    COMBAT_HERO_CAST_HIGH = 7,
    ARMY_FLAG_WIDE = 1,
    ARMY_FACING_LEFT = 0,
    ARMY_FACING_RIGHT = 1
};

#define SPELL_COLD_RAY_DELAY 175.0f
#define SPELL_MAGIC_ARROW_DELAY 100.0f
#define SPELL_GOLEM_DAMAGE_MULTIPLIER 0.5

int CombatSpecialHandler(struct tag_message &);
int HandleCastSpell(struct tag_message &);

#endif // HOMM2_SPELLS_H
