#ifndef HOMM2_SPELLS_H
#define HOMM2_SPELLS_H

#include <Ints.h>
#include <SOURCE/KB_TYPES.h>
// Declarations of the free functions DEFINED in SPELLS.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

typedef enum CombatSpellInfluence {
    SPELL_INFLUENCE_HASTE = 0,
    SPELL_INFLUENCE_SLOW = 1,
    SPELL_INFLUENCE_BLIND = 2,
    SPELL_INFLUENCE_BLESS = 3,
    SPELL_INFLUENCE_CURSE = 4,
    SPELL_INFLUENCE_BERSERKER = 5,
    SPELL_INFLUENCE_PARALYZE = 6,
    SPELL_INFLUENCE_HYPNOTIZE = 7,
    SPELL_INFLUENCE_DRAGON_SLAYER = 8,
    SPELL_INFLUENCE_BLOOD_LUST = 9,
    SPELL_INFLUENCE_SHIELD = 10,
    SPELL_INFLUENCE_MIRROR_IMAGE = 11,
    SPELL_INFLUENCE_ANTI_MAGIC = 12,
    SPELL_INFLUENCE_STONE_SKIN = 13,
    SPELL_INFLUENCE_STEEL_SKIN = 14,
    SPELL_INFLUENCE_COUNT = 15
} CombatSpellInfluence;

typedef enum SpellRippleMode {
    SPELL_RIPPLE_MODE_WAVE = 0,
    SPELL_RIPPLE_MODE_DEATH_RIPPLE = 1,
    SPELL_RIPPLE_MODE_DEATH_WAVE = 2
} SpellRippleMode;

typedef enum SpellSourceLine {
    SPELL_VAPORIZE_SOURCE_LINE_BASE = 0x09dc,
    SPELL_VAPORIZE_ALLOC_LINE_OFFSET = 0x09,
    SPELL_VAPORIZE_FREE_LINE_OFFSET = 0x38,
    SPELL_RIPPLE_SOURCE_LINE_BASE = 0x0a1b,
    SPELL_RIPPLE_MODIFIER_ALLOC_LINE_OFFSET = 0x2c,
    SPELL_RIPPLE_WAVE_ALLOC_LINE_OFFSET = 0x2d,
    SPELL_RIPPLE_MODIFIER_FREE_LINE_OFFSET = 0x8e,
    SPELL_RIPPLE_WAVE_FREE_LINE_OFFSET = 0x8f
} SpellSourceLine;

typedef enum BoltColorMode {
    BOLT_COLOR_RED_TABLE = 257,
    BOLT_COLOR_RAINBOW_FORWARD = 300,
    BOLT_COLOR_LIGHTNING = 301,
    BOLT_COLOR_RED_BEAM = 302,
    BOLT_COLOR_RAINBOW_REVERSE = 303
} BoltColorMode;

typedef enum CombatSpellUiConstant {
    SPELL_MESSAGE_MOUSE_DOWN = 1,
    SPELL_MESSAGE_HOVER = 4,
    SPELL_MESSAGE_SELECT = 8,
    SPELL_MESSAGE_CANCEL = 0x20,
    SPELL_MESSAGE_DIALOG = 0x200,
    SPELL_COMMAND_CANCEL = 1,
    SPELL_COMMAND_CLOSE = 10,
    SPELL_CONTROL_PREVIOUS_PAGE = 2,
    SPELL_CONTROL_NEXT_PAGE = 3,
    SPELL_CONTROL_FIRST_MANA = 6,
    SPELL_CONTROL_LAST_MANA = 9,
    SPELL_CONTROL_CLOSE = 0x7800,
    SPELL_HELP_PREVIOUS_PAGE = 0,
    SPELL_HELP_NEXT_PAGE = 1,
    SPELL_HELP_CLOSE = 4,
    SPELL_HELP_MANA = 6,
    SPELL_HELP_DEFAULT = 7,
    SPELL_HANDLER_CONTINUE = 1,
    SPELL_HANDLER_CLOSE = 2,
    SPELL_ACTION_CAST = 1,
    SPELL_NO_SELECTION = -1,
    SPELL_HEX_COLUMN_COUNT = 13,
    SPELL_HEX_RIGHT_BORDER = 12,
    SPELL_ELEMENTAL_ARMY_LIMIT = 20,
    SPELL_POINTER_DEFAULT_ID = -999
} CombatSpellUiConstant;

enum {
    SPELL_ATTRIBUTE_COMBAT = 2,
    SPELL_ATTRIBUTE_DURATION = 8,
    SPELL_DEFAULT_CREATURE_POWER = 3,
    SPELL_HOURGLASS_POWER_BONUS = 2,
    SPELL_WIZARD_HAT_POWER_BONUS = 10,
    SPELL_LIGHTNING_DAMAGE_PER_POWER = 25,
    SPELL_LIGHTNING_AIR_ELEMENTAL_DAMAGE_PER_POWER = 50,
    SPELL_MAGIC_ARROW_DAMAGE_PER_POWER = 10,
    SPELL_COLD_RAY_DAMAGE_PER_POWER = 20,
    SPELL_COLD_RAY_FIRE_ELEMENTAL_DAMAGE_PER_POWER = 40,
    SPELL_FIREBALL_DAMAGE_PER_POWER = 10,
    SPELL_METEOR_DAMAGE_PER_POWER = 25,
    SPELL_ELEMENTAL_STORM_DAMAGE_PER_POWER = 25,
    SPELL_ARMAGEDDON_DAMAGE_PER_POWER = 50,
    SPELL_DISRUPTING_RAY_DEFENSE_REDUCTION = 3,
    SPELL_MINIMUM_DEFENSE = 1,
    SPELL_BLOOD_LUST_EFFECT = 0x200,
    SPELL_BLOOD_LUST_DURATION = 3,
    COMBAT_SIDE_COUNT = 2,
    COMBAT_HEX_EMPTY = -1,
    COMBAT_DRAW_DELAY = 75,
    COMBAT_SPELL_TARGET_Y_OFFSET = 17,
    COMBAT_HERO_CAST_LEFT_X_OFFSET = 30,
    COMBAT_HERO_CAST_RIGHT_X = 610,
    COMBAT_HERO_CAST_LEFT_Y_OFFSET = 183,
    COMBAT_HERO_CAST_RIGHT_Y_OFFSET = 148,
    COMBAT_HERO_CAST_NO_TARGET = 3,
    COMBAT_HERO_CAST_LOW = 5,
    COMBAT_HERO_CAST_HIGH = 7,
    SPELL_ADJACENT_DIRECTION_COUNT = 6,
    SPELL_FIREBALL_FRAME_COUNT = 12,
    SPELL_COLD_RING_FRAME_COUNT = 7,
    SPELL_FIREBALL_AFFECTED_HEX_COUNT = 19,
    SPELL_FIREBLAST_SECOND_RING_FIRST = 7,
    SPELL_FIREBLAST_AXIAL_FIRST = 13,
    SPELL_FIREBLAST_AXIAL_SECOND = 14,
    SPELL_FIREBLAST_CORNER_FIRST = 15,
    SPELL_FIREBLAST_HEX_ROW_STRIDE = 26,
    SPELL_METEOR_AFFECTED_HEX_COUNT = 7,
    SPELL_METEOR_PASS_COUNT = 2,
    SPELL_METEOR_FRAME_COUNT = 10,
    SPELL_STORM_PASS_COUNT = 6,
    SPELL_STORM_FRAME_COUNT = 10,
    SPELL_STORM_ROW_COUNT = 10,
    SPELL_STORM_COLUMN_COUNT = 12,
    SPELL_STORM_TILE_SIZE = 54,
    SPELL_STORM_FRAME_COLUMN_STEP = 3,
    SPELL_ARMAGEDDON_PALETTE_COLOR_COUNT = 256,
    SPELL_ARMAGEDDON_PALETTE_CHANNEL_COUNT = 3,
    SPELL_ARMAGEDDON_PALETTE_SIZE = 0x300,
    SPELL_ARMAGEDDON_BRIGHTEN_PASS_COUNT = 16,
    SPELL_ARMAGEDDON_SHAKE_PASS_COUNT = 4,
    SPELL_ARMAGEDDON_SHAKE_FRAME_COUNT = 15,
    SPELL_ARMAGEDDON_RESTORE_PASS_COUNT = 16,
    SPELL_ARMAGEDDON_CHANNEL_MAX = 63,
    SPELL_ARMAGEDDON_CHANNEL_STEP = 3,
    SPELL_PETRIFY_DURATION = 3,
    SPELL_FIZZLE_FRAME_DELAY = 75,
    SPELL_PETRIFY_FIZZLE_STEPS = 75,
    SPELL_BLOOD_LUST_FIZZLE_STEPS = 110,
    BOLT_RANDOM_WIDTH_LOW = 7,
    BOLT_RANDOM_WIDTH_HIGH = 12,
    BOLT_NEAR_TARGET_DISTANCE = 15,
    BOLT_FINISHED_DISTANCE = 3,
    BOLT_ANGLE_PERCENT_SCALE = 100,
    BOLT_ANGLE_AVERAGE_DIVISOR = 200,
    BOLT_RAINBOW_LAST_INDEX = 14,
    BOLT_LIGHTNING_SHADE_0 = 0x72,
    BOLT_LIGHTNING_SHADE_1 = 0x74,
    BOLT_LIGHTNING_SHADE_2 = 0x75,
    BOLT_LIGHTNING_SHADE_3 = 0xcc,
    BOLT_LIGHTNING_SHADE_4 = 0xce,
    BOLT_LIGHTNING_SHADE_5 = 0xd6,
    BOLT_MAX_COUNT = 25,
    BOLT_EXTENT_SENTINEL = 9999,
    BOLT_BRANCH_RANDOM_LOW = 50,
    BOLT_BRANCH_RANDOM_HIGH = 80,
    BOLT_BRANCH_PERCENT_LIMIT = 100,
    BOLT_PALETTE_BRIGHTEN_STEP = 16,
    BOLT_PALETTE_COMPONENT_MAX = 63,
    CHAIN_LIGHTNING_MAX_TARGETS = 4,
    CHAIN_LIGHTNING_INITIAL_DAMAGE_PER_POWER = 40,
    CHAIN_LIGHTNING_AIR_ELEMENTAL_MULTIPLIER = 2,
    CHAIN_LIGHTNING_MIN_BRANCH_DISTANCE = 8,
    CHAIN_LIGHTNING_MAX_BRANCH_DISTANCE = 30,
    CHAIN_LIGHTNING_SHORT_BRANCH_THRESHOLD = 21,
    CHAIN_LIGHTNING_DISTANCE_DIVISOR = 10,
    CHAIN_LIGHTNING_BOLT_LENGTH = 80,
    CHAIN_LIGHTNING_START_WIDTH = 9,
    CHAIN_LIGHTNING_END_WIDTH = 2,
    CHAIN_LIGHTNING_MIN_ANGLE = 10,
    CHAIN_LIGHTNING_MAX_ANGLE = 80,
    CHAIN_LIGHTNING_COLOR_MODE = BOLT_COLOR_LIGHTNING,
    SPELL_MODIFIER_ROW_COUNT = 480,
    VAPORIZE_STRIPE_WIDTH = 5,
    VAPORIZE_PHASE_COUNT = 3,
    VAPORIZE_MASKED = 0x7f,
    RIPPLE_MARGIN = 10,
    RIPPLE_PHASE_START = 10,
    RIPPLE_PHASE_END = 70,
    RIPPLE_PHASE_PERIOD = 40,
    RIPPLE_PHASE_CENTER = 20,
    RIPPLE_SKIP_CENTER_OFFSET = 10,
    RIPPLE_AMPLITUDE_INDEX_DIVISOR = 10,
    RIPPLE_MODE_ZERO_AMPLITUDE_START = 8,
    RIPPLE_MODE_ZERO_CENTER_AMPLITUDE = 5,
    RIPPLE_MODE_TWO_AMPLITUDE_START = 7,
    RIPPLE_WAVE_INDEX_OFFSET = 15,
    RIPPLE_DEATH_RIPPLE_FADE_START = 50,
    RIPPLE_DEATH_RIPPLE_FADE_BASE = 21,
    RIPPLE_DEATH_WAVE_FADE_END = 30,
    RIPPLE_DEATH_WAVE_FADE_BASE = 9,
    RIPPLE_FADE_DIVISOR = 20,
    RIPPLE_WAVE_PERIOD = 62,
    RIPPLE_WAVE_DIVISOR = 10,
    RIPPLE_SKIP_DISTANCE_0 = -3,
    RIPPLE_SKIP_DISTANCE_1 = -1,
    RIPPLE_SKIP_DISTANCE_2 = 0,
    RIPPLE_SKIP_DISTANCE_3 = 1,
    RIPPLE_SKIP_DISTANCE_4 = 3,
    MIRROR_SEARCH_MAX_DISTANCE = 9,
    MIRROR_SLIDE_FRAME_COUNT = 16,
    MIRROR_ARMY_FLAG = 0x100,
    MIRROR_MONSTER_ABILITY = 0x800,
    ELEMENTAL_SUMMON_QUANTITY_PER_POWER = 3,
    LUCK_MIN_TARGET_Y = 75,
    LUCK_TARGET_FRAME_INDEX = 0,
    LUCK_ICON_Y_PADDING = 5,
    LUCK_SHORT_BOLT_HEIGHT = 140,
    LUCK_EDGE_START_Y = 0,
    LUCK_EDGE_INSET = 150,
    LUCK_BOLT_WIDTH = 15,
    LUCK_BOLT_ANGLE = 40,
    LUCK_BOLT_DISTANCE = 10,
    LUCK_BOLT_FORCE_ANGLE = 1,
    LUCK_BOLT_FRAME_DELAY = 30,
    BLAST_COLD_RAY_FRAME_SPACING = 18,
    BLAST_DISRUPTING_RAY_FRAME_SPACING = 24,
    BLAST_FRAME_COUNT = 10,
    RESURRECT_HIT_POINTS_PER_POWER = 50,
    RESURRECT_ANIMATION_FRAME_COUNT = 22,
    RESURRECT_DEATH_REVERSE_FRAME = 18,
    RESURRECT_MONSTER_ABILITY = 0x10,
    EARTHQUAKE_SHAKE_PASS_COUNT = 3,
    EARTHQUAKE_SHAKE_FRAME_COUNT = 15,
    EARTHQUAKE_SHAKE_COORDINATE_COUNT = 2,
    EARTHQUAKE_STRUCTURE_COUNT = 4,
    EARTHQUAKE_MAX_IMPACTS = 10,
    EARTHQUAKE_WALL_HIT_CHANCE = 75,
    EARTHQUAKE_WALL_SECOND_HIT_CHANCE = 15,
    EARTHQUAKE_TOWER_HIT_CHANCE = 50,
    EARTHQUAKE_KEEP_HIT_CHANCE = 25,
    EARTHQUAKE_CLOUD_FRAME_COUNT = 13,
    EARTHQUAKE_CLOUD_VISIBLE_FRAME_COUNT = 10,
    EARTHQUAKE_APPLY_DAMAGE_FRAME = 7,
    EARTHQUAKE_CLOUD_Y_OFFSET = 25,
    EARTHQUAKE_EXTENT_MIN_X = 252,
    EARTHQUAKE_EXTENT_MAX_X = 575,
    ARMY_FLAG_WIDE = 1,
    ARMY_FACING_LEFT = 0,
    ARMY_FACING_RIGHT = 1
};

#define RIPPLE_MODE_ZERO_AMPLITUDE_BASE 0.3f
#define RIPPLE_MODE_ZERO_AMPLITUDE_STEP 0.05f
#define RIPPLE_OTHER_AMPLITUDE_BASE 0.2f
#define RIPPLE_OTHER_AMPLITUDE_STEP 0.1f
#define SPELL_VANISH_END_DELAY 500.0f
#define MIRROR_SLIDE_FRAME_DELAY 50.0f
#define BLAST_FRAME_DELAY 10.0f

#define SPELL_COLD_RAY_DELAY 175.0f
#define SPELL_MAGIC_ARROW_DELAY 100.0f
#define SPELL_AREA_ANIMATION_DELAY 75.0f
#define SPELL_METEOR_ANIMATION_DELAY 112.5
#define SPELL_ARMAGEDDON_PALETTE_DELAY 20.0f
#define SPELL_ARMAGEDDON_SHAKE_DELAY 15.0f
#define SPELL_ARMAGEDDON_SHAKE_SCALE 0.75
#define SPELL_GOLEM_DAMAGE_MULTIPLIER 0.5
#define SPELL_ARTIFACT_DAMAGE_BONUS 1.5
#define SPELL_ARTIFACT_DAMAGE_REDUCTION 0.5
#define BOLT_INITIAL_ANGLE_BIAS 2.5
#define BOLT_INITIAL_ANGLE_DIVISOR 2.0
#define BOLT_RANDOM_ANGLE_BIAS 2.0f
#define BOLT_RANDOM_ANGLE_DIVISOR 1.5
#define BOLT_ANGLE_DISTANCE_FACTOR 1.5
#define BOLT_BRANCH_COOLDOWN_FACTOR 0.75
#define BOLT_CHILD_ANGLE_SCALE 0.66
#define BOLT_CHILD_ANGLE_OFFSET 20.0
#define BOLT_CHILD_MIN_ANGLE_OFFSET -20.0
#define SPELLS_SOURCE_FILE "I:\\Projects\\Heroes\\Prog\\SOURCE\\SPELLS.CPP"

i32 CombatSpecialHandler(struct tag_message&);
i32 HandleCastSpell(struct tag_message&);

#endif // HOMM2_SPELLS_H
