#ifndef HOMM2_TOWNMGR_H
#define HOMM2_TOWNMGR_H
// Declarations of the free functions DEFINED in TOWNMGR.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).
// forward declarations (was <_all.h>):
struct tag_message;

typedef enum TownManagerMessageType {
    TOWN_MESSAGE_KEY_DOWN = 1,
    TOWN_MESSAGE_KEY_UP = 2,
    TOWN_MESSAGE_HOVER = 4,
    TOWN_MESSAGE_SELECT = 0x200,
    TOWN_MESSAGE_EXIT = 0x4000
} TownManagerMessageType;

typedef enum TownManagerInputCode {
    TOWN_INPUT_SELECT = 12,
    TOWN_INPUT_DESELECT = 13,
    TOWN_INPUT_ALTERNATE_SELECT = 14,
    TOWN_KEY_SHIFT_LEFT = 0x2a,
    TOWN_KEY_SHIFT_RIGHT = 0x36,
    TOWN_CONTROL_PREVIOUS_TOWN = 0x387,
    TOWN_CONTROL_NEXT_TOWN = 0x388,
    TOWN_CONTROL_CLOSE = 0x7800,
    TOWN_DIALOG_BUILD_BOAT = 0x7802,
    TOWN_DIALOG_BUY_SPELL_BOOK = 0x7805
} TownManagerInputCode;

typedef enum TownManagerCommand {
    TOWN_COMMAND_MAGE_GUILD = 0,
    TOWN_COMMAND_THIEVES_GUILD = 1,
    TOWN_COMMAND_TAVERN = 2,
    TOWN_COMMAND_DOCK = 3,
    TOWN_COMMAND_WELL = 4,
    TOWN_COMMAND_UPGRADE_CASTLE = 5,
    TOWN_COMMAND_CASTLE = 6,
    TOWN_COMMAND_TRADING_POST = 10,
    TOWN_COMMAND_SPECIAL_BUILDING = 13,
    TOWN_COMMAND_LAST_NEUTRAL_BUILDING = 15,
    TOWN_COMMAND_FIRST_DWELLING = 19,
    TOWN_COMMAND_NECROMANCER_MAGE_GUILD_PREREQUISITE = 28,
    TOWN_COMMAND_LAST_DWELLING = 30
} TownManagerCommand;

typedef enum TownManagerArmyCommand {
    TOWN_ARMY_COMMAND_SELECT = 0,
    TOWN_ARMY_COMMAND_VIEW = 1,
    TOWN_ARMY_COMMAND_MERGE = 2,
    TOWN_ARMY_COMMAND_SWAP = 3,
    TOWN_ARMY_COMMAND_VIEW_HERO = 4,
    TOWN_ARMY_COMMAND_SPLIT = 5
} TownManagerArmyCommand;

typedef enum TownThievesGuildCategory {
    TOWN_THIEVES_CATEGORY_TOWNS = 0,
    TOWN_THIEVES_CATEGORY_CASTLES = 1,
    TOWN_THIEVES_CATEGORY_HEROES = 2,
    TOWN_THIEVES_CATEGORY_GOLD = 3,
    TOWN_THIEVES_CATEGORY_WOOD_AND_ORE = 4,
    TOWN_THIEVES_CATEGORY_RARE_RESOURCES = 5,
    TOWN_THIEVES_CATEGORY_OBELISKS = 6,
    TOWN_THIEVES_CATEGORY_ARTIFACTS = 7,
    TOWN_THIEVES_CATEGORY_ARMY_STRENGTH = 8,
    TOWN_THIEVES_CATEGORY_INCOME = 9
} TownThievesGuildCategory;

typedef enum TownManagerConstant {
    TOWN_DEBUG_BUILD_ALL = 100,
    TOWN_BUILDING_COUNT = 32,
    TOWN_GARRISON_SLOT_FIRST = 0x75,
    TOWN_GARRISON_SLOT_LAST = 0x79,
    TOWN_HERO_SLOT_FIRST = 0x7b,
    TOWN_HERO_SLOT_LAST = 0x7f,
    TOWN_ARMY_VIEW_X = 0x77,
    TOWN_ARMY_VIEW_Y = 0x14,
    TOWN_MAX_BOATS = 48,
    TOWN_SPELL_BOOK_ARTIFACT = 0x51,
    TOWN_MAX_ARTIFACTS = 14,
    TOWN_SPELL_BOOK_COST = 500,
    TOWN_BOAT_GOLD_COST = 1000,
    TOWN_BOAT_WOOD_COST = 10,
    TOWN_QUICK_VIEW_MODIFIER = 0x200,
    TOWN_INTERFACE_BROADCAST_FLAGS = 0x4008,
    TOWN_CONTROL_STATUS_TEXT = 0x386,
    TOWN_DIALOG_CONFIRM = 0x7802,
    TOWN_RESOURCE_COUNT = 7,
    TOWN_MAGE_GUILD_MAX_LEVEL = 5,
    TOWN_MAGE_SPELLS_PER_LEVEL = 4,
    TOWN_MAGE_SPELL_UNAVAILABLE = 999,
    TOWN_MAGE_FIRST_SPELL_CONTROL = 10,
    TOWN_MAGE_FIRST_ICON_CONTROL = 0x28,
    TOWN_MAGE_FIRST_DESCRIPTION_CONTROL = 0x46,
    TOWN_MAGE_GUILD_ICON_CONTROL = 100,
    TOWN_MAGE_DESCRIPTION_CONTROL = 0x6e,
    TOWN_WIZARD_LIBRARY_BUILDING_FLAG = 0x20,
    TOWN_TAVERN_FIRST_ANIMATION_FRAME = 2,
    TOWN_TAVERN_ANIMATION_FRAME_COUNT = 20,
    TOWN_TAVERN_ANIMATION_DELAY = 0x4b,
    TOWN_TAVERN_RUMOUR_CONTROL = 0x259,
    TOWN_SPLIT_AMOUNT_CONTROL = 0x44,
    TOWN_SPLIT_INCREASE_CONTROL = 0x45,
    TOWN_SPLIT_DECREASE_CONTROL = 0x46,
    TOWN_OBJECT_BORDER_ENABLED = 2,
    TOWN_HERO_CLASS_COUNT = 6,
    TOWN_MAP_CHANGE_UNUSED = -999,
    TOWN_ARMY_SLOT_COUNT = 5,
    TOWN_REDRAW_INTERVAL = 150,
    TOWN_WELL_DWELLING_COUNT = 6,
    TOWN_WELL_FIRST_NAME_CONTROL = 7,
    TOWN_WELL_FIRST_MONSTER_ICON_CONTROL = 13,
    TOWN_WELL_FIRST_CREATURE_CONTROL = 19,
    TOWN_WELL_FIRST_DETAIL_CONTROL = 25,
    TOWN_WELL_FIRST_AVAILABLE_CONTROL = 31,
    TOWN_WELL_FIRST_AVAILABLE_COUNT_CONTROL = 37,
    TOWN_WELL_FIRST_UPGRADE_BUILDING = 24,
    TOWN_WELL_LAST_UPGRADE_BUILDING = 30,
    TOWN_WELL_FIRST_UPGRADE_OFFSET = 5,
    TOWN_WELL_FIRST_DWELLING_GROWTH_BUILDING = 11,
    TOWN_WELL_BASE_GROWTH_BONUS = 2,
    TOWN_WELL_FIRST_DWELLING_GROWTH_BONUS = 8,
    TOWN_THIEVES_PLAYER_COUNT = 6,
    TOWN_THIEVES_ORDER_BUFFER_SIZE = 8,
    TOWN_THIEVES_FIRST_RANK_CONTROL = 800,
    TOWN_THIEVES_FIRST_PLAYER_CONTROL = 900,
    TOWN_THIEVES_BASIC_CATEGORY_COUNT = 3,
    TOWN_THIEVES_PRIMARY_CATEGORY_COUNT = 5,
    TOWN_THIEVES_PERSONALITY_CATEGORY_COUNT = 7,
    TOWN_THIEVES_CREATURE_CATEGORY_COUNT = 9,
    TOWN_THIEVES_MAX_CATEGORIES = 10,
    TOWN_THIEVES_INFO_STRONGEST_HERO = 1,
    TOWN_THIEVES_INFO_PRIMARY_STATS = 2,
    TOWN_THIEVES_INFO_PERSONALITY = 3,
    TOWN_THIEVES_INFO_STRONGEST_CREATURE = 4,
    TOWN_THIEVES_INFO_ALL_CATEGORIES = 5,
    TOWN_THIEVES_PRIMARY_STAT_COUNT = 4,
    TOWN_THIEVES_DEAD_PLAYER_STAT = -1,
    TOWN_THIEVES_RANK_ICON_FRAME_BASE = 22,
    TOWN_THIEVES_SOURCE_LINE_HERO_LABELS = 0xbe,
    TOWN_THIEVES_SOURCE_LINE_HERO_STATS = 0xd8,
    TOWN_THIEVES_SOURCE_LINE_PERSONALITY = 0xf0
} TownManagerConstant;

int MageGuildHandler(struct tag_message &);
int TavernHandler(struct tag_message &);
int SplitArmyHandler(struct tag_message &);
void GetCategoryStats(int, long int * const, signed char * const);
void SortStats(long int * const, signed char * const);

#endif // HOMM2_TOWNMGR_H
