#ifndef HOMM2_VIEWWRLD_H
#define HOMM2_VIEWWRLD_H

#include <Ints.h>
struct tag_message;

H2_ENUM_CLASS_BEGIN(ViewWorldMode)
    VIEW_WORLD_MINES = 0x30,
    VIEW_WORLD_RESOURCES = 0x31,
    VIEW_WORLD_ARTIFACTS = 0x32,
    VIEW_WORLD_TOWNS = 0x33,
    VIEW_WORLD_HEROES = 0x34,
    VIEW_WORLD_ALL = 0x35
H2_ENUM_CLASS_END(ViewWorldMode)

H2_ENUM_CLASS_BEGIN(ViewWorldScale)
    VIEW_WORLD_SCALE_FAR = 4,
    VIEW_WORLD_SCALE_MIDDLE = 6,
    VIEW_WORLD_SCALE_NEAR = 12,
    VIEW_WORLD_FAR_MAX_MAP_SIZE = 108,
    VIEW_WORLD_MIDDLE_MAX_MAP_SIZE = 72,
    VIEW_WORLD_NEAR_MAX_MAP_SIZE = 36
H2_ENUM_CLASS_END(ViewWorldScale)

H2_ENUM_BEGIN(ViewWorldConstant)
    VIEW_WORLD_PALETTE_SIZE = 0x300,
    VIEW_WORLD_WINDOW_X = 0x1e0,
    VIEW_WORLD_WINDOW_Y = 0x10,
    VIEW_WORLD_ICON_WIDGET = 3,
    VIEW_WORLD_POINTER_FRAME = 0,
    VIEW_WORLD_TILESET_COUNT = 64,
    VIEW_WORLD_GROUND_SHAPE_MASK = 0x7f,
    VIEW_WORLD_TERRAIN_FRAME_STRIDE = 21,
    VIEW_WORLD_DRAW_SIZE = 0x1c0,
    VIEW_WORLD_LEFT = 0x10,
    VIEW_WORLD_TOP = 0x10,
    VIEW_WORLD_RIGHT = 0x1d0,
    VIEW_WORLD_BOTTOM = 0x1d0,
    VIEW_WORLD_SCREEN_WIDTH = 0x280,
    VIEW_WORLD_SCREEN_HEIGHT = 0x1e0,
    VIEW_WORLD_BACKGROUND_COLOR = 0x24,
    VIEW_WORLD_NO_OWNER_COLOR = 6,
    VIEW_WORLD_HIGHLIGHT_BASE = 0xd7,
    VIEW_WORLD_ARTIFACT_HIGHLIGHT = 0xd6,
    VIEW_WORLD_RESOURCE_HIGHLIGHT = 0xdd,
    VIEW_WORLD_NO_SPRITE = 0xFF,
    VIEW_WORLD_RADAR_WIDGET = 9,
    VIEW_WORLD_SCALE_CONTROL = 2,
    VIEW_WORLD_DIALOG_FIRST = 0x7800,
    VIEW_WORLD_DIALOG_EXCLUDED = 0x7804,
    VIEW_WORLD_DIALOG_LAST = 0x7806,
    VIEW_WORLD_DIALOG_CLOSE = 10,
    VIEW_WORLD_RADAR_LEFT = 0x1e0,
    VIEW_WORLD_RADAR_RIGHT = 0x270,
    VIEW_WORLD_RADAR_TOP = 0x10,
    VIEW_WORLD_RADAR_BOTTOM = 0xa0
H2_ENUM_END(ViewWorldConstant)

i32 ViewWorldDialogHandler(struct tag_message&);

#endif
