#ifndef HOMM2_X_GLOBAL_H
#define HOMM2_X_GLOBAL_H
// Globals owned by this data-only TU (from CodeView).
#include <va.h>

class ExpCampaign;

// --- globals owned by this TU (moved from _globals.h; CodeView-attributed) ---
extern signed char xIsExpansionMap;
extern unsigned char xIsPlayingExpansionCampaign;
extern class ExpCampaign xCampaign;
extern int xTheSpell;
extern char *xNecromancerShrine;
extern char *xNecromancerShrineDesc;
extern int xPasswordStringsIndex[];
extern int xShrineBuildingCost[];

// ---- globals (declarations, RVA order) ----
extern unsigned char *giGroundShape;
extern unsigned char *gColorTableTan;
extern unsigned char *gColorTableGray;
extern unsigned char *gColorTableRed;
extern unsigned char *gColorTableDarkBrown;
extern int giMainVideoModeWidth;
extern int giMainVideoModeHeight;
extern unsigned long glMilliCounter;
extern unsigned char *gMapColors;
extern unsigned char *gObjectColors;
extern unsigned char *gOwnerColors;
extern char *gTilesetFiles[64];
extern unsigned char *bPuzzleDraw;
extern unsigned char uDimPal[3][4][256];
extern unsigned char *gColorTableLighten;
extern unsigned char *gColorTableNoCycle;
extern int gbReturnAfterComputeExtent;
extern int gbAllowTextEntryEscape;
extern int giScreenScroll;
extern int giMenuCommand;
extern int gbSendMouseMoveMessages;
extern int gbColorMice;
extern unsigned long *gTownEligibleBuildMask;
extern unsigned char *giMapSizes;
extern int gbUseEvilInterface;
extern char *cEvilTranslate[37][2];  // CodeView size 0x128 = 37*2*4; array-decayed mangling
extern char gcAnimPath[0x160];
extern char *gcGamePath;
extern char *gcMapPath;
extern int gbDontTryRedbook;
extern int gbDontTryMIDI;
extern int gbDontTryDigital;
extern float *gfCombatSpeedMod;
extern int giDialogTimeout;
extern int giNewMonsterCycleFrame;
extern int gbLeaveNetBoxAlone;
extern int gbUseWaveout;
extern int gbShowAllMaps;
extern char *gCombatFxNames[32];
extern short *horseFrameFlip;
extern short *boatFrameFlip;
extern signed char *gCastleResources;
extern short *gCastleAmounts;
extern short *gVesaMode;
DATA(0x004faab8) extern int (*gInitResourcesHuman)[7];
DATA(0x004fab48) extern int (*gInitResourcesComputer)[7];
extern int *gMineCharacteristics;
extern int gSSValues[14][3];
extern unsigned char *gArtifactLevel;
extern int gUltArtifactAvgValue;
extern signed char giVisRangeTown;
extern float *gfStatPower;
extern float *gfBattleStat;
extern signed char *gSpellLimits;
extern float *gfSpellCastableCombatMod;
extern float *gfSpellCastNumMod;
extern float *gfPhilAISpellPowerMod;
extern float *gfPhilAIDurationMod;
extern float *gfSpellTypeNumMod;
extern signed char gbArrow[8][8];
extern unsigned char *giCloudType;
extern signed char *townTheme;
extern signed char gHeroSkillBonus[6][2][4];
extern int giMonoIconSkip;
extern int giScrollX;
extern int giScrollY;
extern int gbNoBorder;
extern int gbEnlargeScreenBlit;
extern int giCurExe;
extern int gbInDialog;
extern struct SMenuEnableStatus *gsMenuEnableStatus;
extern int gbInSetupDialog;
extern int gbMinimized;
extern int gbInSmackMgr;
extern int glBottomRefresh;
extern int gbBothMachinesWin95;
extern int gbGotFirstHeartbeat;
extern char *cMonFilename[66];
extern int gbProcessingCombatAction;
extern int iMPNetProtocol;
extern int iLastDiffSendTo;
extern char *cArmyFrameFileNames[66];
extern unsigned char *gcSpellInfluenceIcons;
extern unsigned char *giSpellInfluenceToSpell;
extern unsigned char *giNumPowFrames;
extern int giSpellEffectShowType;
extern signed char *gcColorToPlayerPos;
extern char *cCombatBkgNames[20];
extern struct SCmbtObstacle *sCmbtObstacles;
extern int *gEstatesGoldLevel;
extern float *gfSSLogisticsMod;
extern float *gfSSNavigationMod;
extern float *gfSSArcheryMod;
extern float *gfSSAIArcheryMod;
extern signed char *giVisRange;
DATA(0x004fc7d0) extern unsigned char (*gStartingHeroStats)[5];
extern int giTerrainCost[10][4][2];
extern char *gTownPrefixNames[6];
extern char *gTownObjNames[32];
extern int giDebugBuildingToBuild;
extern unsigned char *giTerrainToMusicTrack;
extern char *cHeroTypeShortName[6];
extern char *cHeroTypeInitial;
extern int giDeferObjDrawX;
extern int giDeferObjDrawY;
extern class heroWindow *gpInitWin;
DATA(0x004fd888) extern unsigned char (*iGetSSByAlignment)[6];
extern struct SCmbtHero *sCmbtHero;
extern unsigned char *iWallToHexCell;
extern unsigned char *iTowerToHexCell;
extern unsigned short wallPos[4][2];
extern unsigned short towerPos[4][2];
extern unsigned short doorPos[2][2];
extern float *fTradingPostEfficency;
extern struct SElevationOverlay *sElevationOverlay;
extern signed char captainStats[6][4];
extern int gbDrawingPuzzle;
extern int giWalkingFrom;
extern int giWalkingFrom2;
extern int giWalkingTo;
extern int giWalkingTo2;
extern int giWalkingYMod;
extern unsigned char *moatCell;
extern char *congratsText;
extern char *gArtifactNames[104];
extern char *gArtifactDesc[104];
extern char *gArtifactEvent[104];
extern char *gStatNames[4];
extern char *gStatDesc[4];
extern char *gAlignmentNames[8];
extern char *gArmyShortNames[66];
extern char *gTerrainNames[10];
extern char *gResourceNames[8];
extern char *gQuickViewText[124];
extern char *gEventText[96];
extern char *gCPanelHelp[6];
extern char *gCSPanelHelp[8];
extern char *gAPanelHelp[6];
extern char *gInitMenuHelp[6];
extern char *gAdvMenuHelp[8];
extern char *gLuckText[8];
extern char *gMoraleText[8];
extern char *onOffText[12];
extern char *walkSpeedText[6];
extern char *gColors[6];
extern char *gMonthNames[10];
extern char *gWeekNames[16];
extern char *cHeroScreen[26];
extern char *cCastleInfo[16];
extern char *cLuckInfo[22];
extern char *IQnames[6];
extern char *cSpellHelp[10];
extern char *speedText[10];
extern char *cArmyDetail[10];
extern char *cWellDetail[10];
extern char *cKingdomOverview[4];
extern char *cNewTurn[8];
extern char *cViewGeneralLabels[8];
extern char *cViewGeneralHelp[8];
extern char *cViewGeneralLongHelp[4];
extern char *cCombatMessage[12];
extern char *cHeroLevel[4];
extern char *cCombatHelp[6];
extern char *cLongCombatHelp[6];
extern char *cTownCommand[28];
extern char *gHeroDefaultNames[54];
extern char *gNewGameHelp[8];
extern char *gSetupBaudHelp[6];
extern char *gSetupComPortHelp[6];
extern char *gSetupDCBaudHelp[6];
extern char *gSetupDCComPortHelp[6];
extern char *gSetupHotSeatGameHelp[6];
extern char *gSetupModemGameHelp[4];
extern char *gSetupDCGameHelp[4];
extern char *gSetupMultiPlayerGameHelp[6];
extern char *gSetupNetworkGameHelp[4];
extern char *gSetupNetworkGame2Help[4];
extern char *gSetupGameHelp[4];
extern char *cBattleResults[12];
extern char *cMoraleInfo[32];
extern char *cMapSize[4];
extern char *cDifficulty[6];
extern char *cStartDifficulty[4];
extern char *cCampaignLeaders[4];
extern char *cWinText[6];
extern char *cHumanDifficulty[6];
extern char *cHumanInfoDifficulty[6];
extern char *musicQualityText[4];
extern char *gSpellDesc[66];
extern char *gSpellNames[66];
extern char *gSecondarySkillLevels[4];
extern char *gSecondarySkills[14];
DATA(0x004ffa78) extern char *(*cSecSkillDesc)[3];
extern char *cDirections[10];
extern char *cRumourTerrainDescriptions[10];
extern char *gInterfaceTypeText[4];
extern char *cBWMouseText[2];
extern char *combatSpeedText[4];
extern char *combatMiniInfoText[4];
extern char *gcCommandLineHelp[14];
extern char *cOverviewText[6];
extern char *cWinComError[6];
extern char *cMiniViewText[10];
extern char *gFileRequestHelp[16];
extern char *cPersonality[4];
DATA(0x004ffcf0) extern char *(*gArmySizeNames)[3];
extern char *cRandomTavernText[8];
extern char *cRandomSignText[4];
extern char *cCampaignAwards[12];
DATA(0x004ffdc0) extern char *(*cCampaignName)[12];
DATA(0x004ffe20) extern char *(*cCampaignDescription)[12];
extern char *cSlowVideoLevelText[2];
extern char *gSPanelHelp[10];
extern char *xBarrierColor[8];
extern char *xGenericSiteNames[8];
extern char *xRecruitmentSiteNames[6];
extern int gbHeroWindShowing;
extern int gbFullCombatScreenDrawn;
extern int gbLimitedCombatUpdatePalette;
extern int gbFirstTimeThrough;
extern int gbSkipIntro;
extern int gbDoMemCheck;
extern int gbInCombat;
extern int gbDirectConnect;
extern int giForceSwitchMusic;
extern int gbComputeExtent;
extern int gbSaveBiggestExtent;
extern int gbLimitToExtent;
extern int gbCurrArmyDrawn;
extern int gAdvDisposeLevel;
extern int giHighScoreRank;
extern int giHighScoreType;
extern int gbShowHighScore;
extern int gbLowMemory;
extern void *gLowPage;
extern int gbLowPageGrabbed;
extern signed char xSmackFromNetwork;
extern int bKBDone;
extern struct _REDBOOK *hRedbookz;
extern int bForceCheckTimeEvent;
extern unsigned short IMHotSpots[5][4];
extern int lastIMHoverID;
extern int bInCheckEndGame;
extern int gbHitEvent;
extern int giMaxExtentX;
extern int giMaxExtentY;
extern int giRandomClouds;
extern char *cOverrideDigitalDriver;
extern signed char gArmyEffected[2][20];
extern int gbInCampaign;
extern int giResExtra1;
extern int giResExtra2;
extern signed char *puzzlePiecesRemoved;
extern int giSeedingValid;
extern int giLimitPlayer;
extern int giShowClouds;
extern char *gcBotViewText;
extern int giResType1;
extern int gbBlackoutPlayer;
extern int giResType2;
extern int gIndex;
extern int giWeekTypeExtra;
extern int giTCPType;
extern int gCurLoadedSpellEffect;
extern int giCurTempMobility;
extern int giOverviewReturnAction;
extern char *cOverrideMIDIDriver;
extern char *gMapName;
extern int giMinExtentX;
extern int giMinExtentY;
extern int iMPBaseType;
extern int gbTCPFirstTime;
extern int giHeroScreenSrcIndex;
extern int giWeekType;
extern class palette *gpBufferPalette;
extern int gbCampaignSideChoice;
extern int giMonthTypeExtra;
extern int iMPExtendedType;
extern signed char *gcColorToSetupPos;
extern char *gFullMapName;
extern char *gcTCPName;
extern int giShowIntro;
extern int giScore;
extern char gcRegAppPath[0x160];  // CodeView size 0x160; typed char* (array-decayed)
extern unsigned long gTimeMark;
extern char *EXPANSION_AGGREGATE_NAME;
DATA(0x00529028) extern char (*cPlayerNames)[21];
extern class icon *gCurLoadedSpellIcon;
extern unsigned char bSaveMusicPosition[0x3c];
extern char *gcTCPAddress;
extern unsigned char giSetupGameType;
extern char *gLastFilename;
extern int giFullySeeded;
extern int *iCombatControlNetPos;
extern char *cExpAggPathName;
extern int gbMoveShown;
extern signed char *gbSetupGamePosToRealGamePos;
extern char gcRegCDRomPath[0x160];  // CodeView size 0x160; typed char* (array-decayed)
extern class heroWindow *heroWin;
extern int giOverviewReturnActionExtra;
extern int giCurGeneral;
extern int gbIconClipOn;
extern int gbRemoteGameOpen;
extern int giTCPNumPlayers;
extern void *hMainWindow;
extern int giCurWindowsStyleFlags;
extern int giMonthType;
extern char *DEFAULT_AGGREGATE_NAME;
extern int gCurSpellEffectFrame;
extern char *cAggPathName;
extern class highScoreManager *gpHighScoreManager;
extern int gbIAmGreatest;
extern int gMapX;
extern int gMapY;
extern char *gcWinText;
extern int bFreshSave;
extern int gLowPageScreenSelector;
extern int giCurWatchPlayer;
extern char *gcCommandLine;
extern int giMapChangeCtr;
extern struct SMapChange *sMapChangeQueue;
extern int gbWaitForRemoteReceive;
extern unsigned char bMusicIsLooping[0x3c];

#endif // HOMM2_X_GLOBAL_H
