// Reconstructed from CodeView NB09 of HEROES2W.EXE — NOT original source.
// compiland: .\Win32_Re\x_cdtest.obj   from: (directly linked into exe)
// functions: 6   data: 1
// VA(addr,size)=function (size = span to next .text symbol - 0xCC/0x90 pad); DATA(addr)=global/vtable.

#include <va.h>
#include <BASE/Misc.h>
#include <SOURCE/x_cdtest.h>
#include <io.h>
#include <mss.h>
#include <stdio.h>
#include <string.h>

DATA(0x004f5188) struct sCDTest_Track_Data cdTestTrackData[43] = {
    { 2001, 1318508 }, { 1318507, 1431161 }, { 1431161, 1549575 },
    { 1549574, 1658748 }, { 1658747, 1829388 }, { 1829387, 1986001 },
    { 1986001, 2140628 }, { 2140627, 2286001 }, { 2286001, 2438202 },
    { 2438201, 2611988 }, { 2611987, 2730014 }, { 2730014, 2858321 },
    { 2858321, 2974895 }, { 2974894, 3102028 }, { 3102027, 3250041 },
    { 3250041, 3359748 }, { 3359747, 3479761 }, { 3479761, 3609762 },
    { 3609761, 3631735 }, { 3631734, 3637935 }, { 3637934, 3646015 },
    { 3646014, 3703361 }, { 3703361, 3713908 }, { 3713907, 3767734 },
    { 3767734, 3773735 }, { 3773734, 3779735 }, { 3779734, 3785735 },
    { 3785734, 3850108 }, { 3850107, 3856788 }, { 3856787, 3862788 },
    { 3862787, 3869188 }, { 3869187, 3875628 }, { 3875627, 3883441 },
    { 3883441, 3889442 }, { 3889441, 3895442 }, { 3895441, 3902308 },
    { 3902307, 3908308 }, { 3908307, 3914574 }, { 3914574, 3921148 },
    { 3921147, 3927148 }, { 3927147, 3933148 }, { 3933147, 4011108 },
    { 4011107, 4087106 }
};

DATA(0x004f52e0) static HREDBOOK cdTestRedbook = 0;

VA(0x00449f80, 0x3b)
i32 CDTest_Init(void)
{
    cdTestRedbook = AIL_redbook_open(0);
    if (cdTestRedbook != 0)
        return 1;
    else
        return 0;
}

VA(0x00449fbb, 0x33)
void CDTest_Cleanup(void)
{
    if (cdTestRedbook != 0)
        AIL_redbook_close(cdTestRedbook);
    cdTestRedbook = 0;
}

VA(0x00449fee, 0x26)
i32 CDTest_VerifyCDQuick(void)
{
    return CDTest_VerifyTrack(Random(1, 43));
}

VA(0x0044a014, 0x4d)
i32 CDTest_VerifyCDThorough(void)
{
    for (i32 i = 1; i <= 43; ++i) {
        if (!CDTest_VerifyTrack(i))
            return 0;
    }
    return 1;
}

VA(0x0044a061, 0x8f)
i32 CDTest_VerifyTrack(i32 track)
{
    U32 first;
    U32 end;

    if (cdTestRedbook == 0)
        return 0;
    if (track < 1 || track > 43)
        return 0;

    AIL_redbook_track_info(cdTestRedbook, track, &first, &end);
    if (cdTestTrackData[track - 1].start != first || cdTestTrackData[track - 1].end != end)
        return 0;
    return 1;
}

VA(0x0044a0f0, 0x2ce)
i32 CDTest_GenerateTable(char *file)
{
    char line[100];
    U32 first;
    i32 fileHandle;
    i32 count;
    i32 trackNumber;
    U32 finish;

    if (cdTestRedbook == 0)
        return 0;

    count = AIL_redbook_tracks(cdTestRedbook);
    if (count == 0)
        return 0;

    fileHandle = open(file, 0x4301);
    if (fileHandle == 0)
        return 0;

    sprintf(line, "// FILE : %s\n", file);
    write(fileHandle, line, strlen(line));
    sprintf(line, "// DO NOT EDIT.\n");
    write(fileHandle, line, strlen(line));
    sprintf(line, "// THIS FILE WAS AUTOMATICALLY GENERATED BY CDTest_GenerateTable.\n");
    write(fileHandle, line, strlen(line));
    sprintf(line, "\n\n\n");
    write(fileHandle, line, strlen(line));
    sprintf(line, "#define CDTEST_NUMTRACKS %d\n\n\n", count);
    write(fileHandle, line, strlen(line));
    sprintf(line, "sCDTest_Track_Data cdTestTrackData[CDTEST_NUMTRACKS] =\n");
    write(fileHandle, line, strlen(line));
    sprintf(line, "{\n");
    write(fileHandle, line, strlen(line));

    for (trackNumber = 1; trackNumber <= count; ++trackNumber) {
        AIL_redbook_track_info(cdTestRedbook, trackNumber, &first, &finish);
        sprintf(line, "  {%d, %d}", first, finish);
        write(fileHandle, line, strlen(line));
        if (trackNumber != count) {
            sprintf(line, ",");
            write(fileHandle, line, strlen(line));
        }
        sprintf(line, "\n");
        write(fileHandle, line, strlen(line));
    }

    sprintf(line, "};\n");
    write(fileHandle, line, strlen(line));
    close(fileHandle);
    return 1;
}
