// Reconstructed from CodeView NB09 of HEROES2W.EXE — NOT original source.
// compiland: .\Win32_Re\x_cdtest.obj   from: (directly linked into exe)
// functions: 6   data: 1
// VA(addr,size)=function (size = span to next .text symbol - 0xCC/0x90 pad); DATA(addr)=global/vtable.

#include <va.h>
#include <BASE/Misc.h>
#include <SOURCE/x_cdtest.h>
#include <io.h>
#include <mss.h>
#include <stdio.h>
#include <string.h>

DATA(0x004f52e0) static HREDBOOK cdTestRedbook = 0;

VA(0x00449f80, 0x3b)
int CDTest_Init(void)
{
    cdTestRedbook = AIL_redbook_open(0);
    if (cdTestRedbook != 0)
        return 1;
    else
        return 0;
}

VA(0x00449fbb, 0x33)
void CDTest_Cleanup(void)
{
    if (cdTestRedbook != 0)
        AIL_redbook_close(cdTestRedbook);
    cdTestRedbook = 0;
}

VA(0x00449fee, 0x26)
int CDTest_VerifyCDQuick(void)
{
    return CDTest_VerifyTrack(Random(1, 43));
}

VA(0x0044a014, 0x4d)
int CDTest_VerifyCDThorough(void)
{
    for (int i = 1; i <= 43; ++i) {
        if (!CDTest_VerifyTrack(i))
            return 0;
    }
    return 1;
}

VA(0x0044a061, 0x8f)
int CDTest_VerifyTrack(int track)
{
    unsigned long first;
    unsigned long end;

    if (cdTestRedbook == 0)
        return 0;
    if (track < 1 || track > 43)
        return 0;

    AIL_redbook_track_info(cdTestRedbook, track, &first, &end);
    if (cdTestTrackData[track - 1].start != first || cdTestTrackData[track - 1].end != end)
        return 0;
    return 1;
}

VA(0x0044a0f0, 0x2ce)
int CDTest_GenerateTable(char *file)
{
    char line[100];
    unsigned long first;
    int fileHandle;
    int count;
    int trackNumber;
    unsigned long finish;

    if (cdTestRedbook == 0)
        return 0;

    count = AIL_redbook_tracks(cdTestRedbook);
    if (count == 0)
        return 0;

    fileHandle = _open(file, 0x4301);
    if (fileHandle == 0)
        return 0;

    sprintf(line, "// FILE : %s\n", file);
    _write(fileHandle, line, strlen(line));
    sprintf(line, "// DO NOT EDIT.\n");
    _write(fileHandle, line, strlen(line));
    sprintf(line, "// THIS FILE WAS AUTOMATICALLY GENERATED BY CDTest_GenerateTable.\n");
    _write(fileHandle, line, strlen(line));
    sprintf(line, "\n\n\n");
    _write(fileHandle, line, strlen(line));
    sprintf(line, "#define CDTEST_NUMTRACKS %d\n\n\n", count);
    _write(fileHandle, line, strlen(line));
    sprintf(line, "sCDTest_Track_Data cdTestTrackData[CDTEST_NUMTRACKS] =\n");
    _write(fileHandle, line, strlen(line));
    sprintf(line, "{\n");
    _write(fileHandle, line, strlen(line));

    for (trackNumber = 1; trackNumber <= count; ++trackNumber) {
        AIL_redbook_track_info(cdTestRedbook, trackNumber, &first, &finish);
        sprintf(line, "  {%d, %d}", first, finish);
        _write(fileHandle, line, strlen(line));
        if (trackNumber != count) {
            sprintf(line, ",");
            _write(fileHandle, line, strlen(line));
        }
        sprintf(line, "\n");
        _write(fileHandle, line, strlen(line));
    }

    sprintf(line, "};\n");
    _write(fileHandle, line, strlen(line));
    _close(fileHandle);
    return 1;
}

// ---- globals (definitions, RVA order) ----
DATA(0x004f5188) struct sCDTest_Track_Data cdTestTrackData[43];
