#ifndef HOMM2_BASE_DATA_ENTRY_CONSTANTS_H
#define HOMM2_BASE_DATA_ENTRY_CONSTANTS_H

H2_ENUM_BEGIN(DataEntryLayout)
    DATA_ENTRY_WINDOW_X = 0xb1,
    DATA_ENTRY_WINDOW_Y = 0x14,
    DATA_ENTRY_INPUT_BOX_Y_OFFSET = 0x17
H2_ENUM_END(DataEntryLayout)

H2_ENUM_CLASS_BEGIN(DataEntryPhase)
    DATA_ENTRY_PHASE_IMMEDIATE = 0,
    DATA_ENTRY_PHASE_POINTER_SENT = 1,
    DATA_ENTRY_PHASE_READY = 2
H2_ENUM_CLASS_END(DataEntryPhase)

// Widget identifiers serialized in the evntwin*.bin data-entry windows.
H2_ENUM_BEGIN(DataEntryWidgetId)
    DATA_ENTRY_PROMPT_WIDGET = 1,
    DATA_ENTRY_TEXT_WIDGET = 10,
    DATA_ENTRY_BUTTON_ONE = 0x7801,
    DATA_ENTRY_CANCEL_BUTTON = 0x7802,
    DATA_ENTRY_BUTTON_FIVE = 0x7805,
    DATA_ENTRY_BUTTON_SIX = 0x7806,
    DATA_ENTRY_BUTTON_SEVEN = 0x7807,
    DATA_ENTRY_BUTTON_EIGHT = 0x7808
H2_ENUM_END(DataEntryWidgetId)

#endif
