#ifndef HOMM2_BASE_LISTBOX_TYPES_H
#define HOMM2_BASE_LISTBOX_TYPES_H

#include <va.h>

H2_ENUM_CLASS_BEGIN(ListBoxTiming)
    LISTBOX_DOUBLE_CLICK_TICKS = 0x190
H2_ENUM_CLASS_END(ListBoxTiming)

H2_ENUM_BEGIN(ListBoxSourceFileConstant)
    LISTBOX_SOURCE_FILE_SLOT_SIZE = 0x2c
H2_ENUM_END(ListBoxSourceFileConstant)

H2_ENUM_BEGIN(ListBoxDestructorSourceFileOffset)
    LISTBOX_DESTRUCTOR_ITEM_SOURCE_FILE_OFFSET = 0,
    LISTBOX_DESTRUCTOR_LIST_SOURCE_FILE_OFFSET = LISTBOX_SOURCE_FILE_SLOT_SIZE
H2_ENUM_END(ListBoxDestructorSourceFileOffset)

H2_ENUM_BEGIN(ListBoxDeleteSourceFileOffset)
    LISTBOX_DELETE_ITEM_SOURCE_FILE_OFFSET = 0,
    LISTBOX_DELETE_LIST_SOURCE_FILE_OFFSET = LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_DELETE_ALLOCATION_SOURCE_FILE_OFFSET = 2 * LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_DELETE_OLD_LIST_SOURCE_FILE_OFFSET = 3 * LISTBOX_SOURCE_FILE_SLOT_SIZE
H2_ENUM_END(ListBoxDeleteSourceFileOffset)

H2_ENUM_BEGIN(ListBoxMainSourceFileOffset)
    LISTBOX_REPLACE_ITEM_SOURCE_FILE_OFFSET = 0,
    LISTBOX_REPLACE_ALLOCATION_SOURCE_FILE_OFFSET = LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_APPEND_LIST_ALLOCATION_SOURCE_FILE_OFFSET = 2 * LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_APPEND_ITEM_ALLOCATION_SOURCE_FILE_OFFSET = 3 * LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_APPEND_OLD_LIST_SOURCE_FILE_OFFSET = 4 * LISTBOX_SOURCE_FILE_SLOT_SIZE
H2_ENUM_END(ListBoxMainSourceFileOffset)

#endif
