#ifndef HOMM2_BASE_LISTBOX_TYPES_H
#define HOMM2_BASE_LISTBOX_TYPES_H

#include <va.h>

typedef enum ListBoxSourceFileConstant {
    LISTBOX_SOURCE_FILE_SLOT_SIZE = 0x2c
} ListBoxSourceFileConstant;

typedef enum ListBoxDestructorSourceFileOffset {
    LISTBOX_DESTRUCTOR_ITEM_SOURCE_FILE_OFFSET = 0,
    LISTBOX_DESTRUCTOR_LIST_SOURCE_FILE_OFFSET = LISTBOX_SOURCE_FILE_SLOT_SIZE
} ListBoxDestructorSourceFileOffset;

typedef enum ListBoxDeleteSourceFileOffset {
    LISTBOX_DELETE_ITEM_SOURCE_FILE_OFFSET = 0,
    LISTBOX_DELETE_LIST_SOURCE_FILE_OFFSET = LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_DELETE_ALLOCATION_SOURCE_FILE_OFFSET = 2 * LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_DELETE_OLD_LIST_SOURCE_FILE_OFFSET = 3 * LISTBOX_SOURCE_FILE_SLOT_SIZE
} ListBoxDeleteSourceFileOffset;

typedef enum ListBoxMainSourceFileOffset {
    LISTBOX_REPLACE_ITEM_SOURCE_FILE_OFFSET = 0,
    LISTBOX_REPLACE_ALLOCATION_SOURCE_FILE_OFFSET = LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_APPEND_LIST_ALLOCATION_SOURCE_FILE_OFFSET = 2 * LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_APPEND_ITEM_ALLOCATION_SOURCE_FILE_OFFSET = 3 * LISTBOX_SOURCE_FILE_SLOT_SIZE,
    LISTBOX_APPEND_OLD_LIST_SOURCE_FILE_OFFSET = 4 * LISTBOX_SOURCE_FILE_SLOT_SIZE
} ListBoxMainSourceFileOffset;

#endif
