#ifndef HOMM2_BASE_LOG_CONSTANTS_H
#define HOMM2_BASE_LOG_CONSTANTS_H

HOMM2_ENUM_VALUES_BEGIN(LogConstant)
    LOG_FILE_DEBUG_LEVEL = 2,
    LOG_DEBUGGER_OUTPUT_LEVEL = 4,
    LOG_UNUSED_VALUE = -999,
    LOG_FORMAT_BUFFER_SIZE = 200,
    LOG_TEXT_BUFFER_SIZE = 500
HOMM2_ENUM_VALUES_END(LogConstant)

#endif // HOMM2_BASE_LOG_CONSTANTS_H
