#ifndef HOMM2_BASE_MISC_GRAPHICS_CONSTANTS_H
#define HOMM2_BASE_MISC_GRAPHICS_CONSTANTS_H

typedef enum MiscPaletteConstant {
    MISC_PALETTE_COMPONENT_BYTES = 3,
    MISC_PALETTE_BYTE_COUNT = 0x300,
    MISC_PALETTE_LEVEL_COUNT = 0x40,
    MISC_PALETTE_MAX_LEVEL = 0x3f
} MiscPaletteConstant;

typedef enum MiscFadeConstant {
    MISC_FADE_IN_FRAME_DELAY = 0x14,
    MISC_FADE_TO_INCREMENT_SHIFT = 2,
    MISC_FADE_TO_START_LEVEL = 0x30,
    MISC_FADE_TO_FRAME_DELAY = 0x32
} MiscFadeConstant;

typedef enum MiscBlitConstant {
    MISC_BLIT_SCROLL_OFFSET = 0x10,
    MISC_BLIT_SCROLL_EXTENT = 0x1c0,
    MISC_BLIT_SCREEN_WIDTH = 0x280,
    MISC_BLIT_SCREEN_HEIGHT = 0x1e0
} MiscBlitConstant;

#endif // HOMM2_BASE_MISC_GRAPHICS_CONSTANTS_H
