#ifndef HOMM2_BASE_MISC_GRAPHICS_CONSTANTS_H
#define HOMM2_BASE_MISC_GRAPHICS_CONSTANTS_H

H2_ENUM_BEGIN(MiscPaletteConstant)
    MISC_PALETTE_COMPONENT_BYTES = 3,
    MISC_PALETTE_BYTE_COUNT      = 0x300,
    MISC_PALETTE_LEVEL_COUNT     = 0x40,
    MISC_PALETTE_MAX_LEVEL       = 0x3f
H2_ENUM_END(MiscPaletteConstant)

#endif
