#ifndef HOMM2_BASE_MISC_CONFIG_CONSTANTS_H
#define HOMM2_BASE_MISC_CONFIG_CONSTANTS_H

HOMM2_ENUM_VALUES_BEGIN(MiscGameDefaultConstant)
    MISC_DEFAULT_WINDOW_ORIGIN = 10,
    MISC_DEFAULT_SMALL_WINDOW_WIDTH = 0x1e0,
    MISC_DEFAULT_SMALL_WINDOW_HEIGHT = 0x168,
    MISC_DEFAULT_WINDOW_WIDTH = 0x280,
    MISC_DEFAULT_WINDOW_HEIGHT = 0x1e0,
    MISC_DEFAULT_MAP_OFFSET_COUNT = 32001,
    MISC_UNIQUE_ID_RANDOM_MODULUS = 999999,
    MISC_UNIQUE_ID_ALPHANUMERIC_COUNT = 36,
    MISC_UNIQUE_ID_ALPHA_COUNT = 26
HOMM2_ENUM_VALUES_END(MiscGameDefaultConstant)

HOMM2_ENUM_BEGIN(MiscGraphicsFieldIndex)
    MISC_GRAPHICS_SHOW_MENU_FROM_FULLSCREEN = -5,
    MISC_GRAPHICS_X_FROM_FULLSCREEN = -4,
    MISC_GRAPHICS_Y_FROM_FULLSCREEN = -3,
    MISC_GRAPHICS_WIDTH_FROM_FULLSCREEN = -2,
    MISC_GRAPHICS_HEIGHT_FROM_FULLSCREEN = -1,
    MISC_GRAPHICS_FULLSCREEN = 0,
    MISC_GRAPHICS_COLOR_MOUSE_FROM_FULLSCREEN = 1
HOMM2_ENUM_END(MiscGraphicsFieldIndex)

HOMM2_ENUM_VALUES_BEGIN(MiscCDDriveConstant)
    MISC_CD_FIRST_DRIVE_INDEX = 2,
    MISC_CD_DRIVE_SLOT_COUNT = 26,
    MISC_CD_PATH_BUFFER_SIZE = 100,
    MISC_CD_MCI_BUFFER_SIZE = 256,
    MISC_CD_MCI_RESULT_LENGTH = 0xFF,
    MISC_CD_PROBE_TRAILER_SIZE = 100,
    MISC_CD_RETRY_DELAY_MILLISECONDS = 3000,
    MISC_CD_RETRY_LIMIT = 2
HOMM2_ENUM_VALUES_END(MiscCDDriveConstant)

HOMM2_ENUM_BEGIN(MiscCDDriveResult)
    MISC_CD_DRIVE_READY = 0,
    MISC_CD_DRIVE_NOT_FOUND = 2,
    MISC_CD_APP_PATH_UNAVAILABLE = 3,
    MISC_CD_DATA_ARCHIVE_UNAVAILABLE = 4
HOMM2_ENUM_END(MiscCDDriveResult)

#endif // HOMM2_BASE_MISC_CONFIG_CONSTANTS_H
