#ifndef HOMM2_BASE_MISC_CONSTANTS_H
#define HOMM2_BASE_MISC_CONSTANTS_H

// Serialized PCX values emitted by CreatePCXFile.
H2_ENUM_BEGIN(PCXConstant)
    PCX_MANUFACTURER_ZSOFT = 10,
    PCX_VERSION_3_0 = 5,
    PCX_ENCODING_RLE = 1,
    PCX_BITS_PER_PIXEL = 8,
    PCX_PLANE_COUNT = 1,
    PCX_PALETTE_TYPE_COLOR = 1,
    PCX_RLE_RUN_MARKER = 0xc0,
    PCX_RLE_RUN_LIMIT = 0x40,
    PCX_VGA_PALETTE_MARKER = 0x0c,
    PCX_PALETTE_BYTE_COUNT = 0x300,
    PCX_COMPONENT_SCALE_SHIFT = 2
H2_ENUM_END(PCXConstant)

#endif
