#ifndef HOMM2_BASE_MISC_RUNTIME_CONSTANTS_H
#define HOMM2_BASE_MISC_RUNTIME_CONSTANTS_H

// Constants for the deterministic seeded generator owned by BASE/Misc.
typedef enum SeededRandomConstant {
    SEEDED_RANDOM_TERM_MULTIPLIER = 13,
    SEEDED_RANDOM_TERM_MASK = 0xff,
    SEEDED_RANDOM_HIGH_TERM_SHIFT = 5,
    SEEDED_RANDOM_LOW_TERM_MULTIPLIER = 13233,
    SEEDED_RANDOM_FEEDBACK_MASK = 0x3f,
    SEEDED_RANDOM_FEEDBACK_SHIFT = 8,
    SEEDED_RANDOM_SEED_MASK = 0xfff,
    SEEDED_RANDOM_MIX_MULTIPLIER = 7,
    SEEDED_RANDOM_MIX_MASK = 0xff0,
    SEEDED_RANDOM_MIX_SHIFT = 4,
    SEEDED_RANDOM_TOP_BIT = 31
} SeededRandomConstant;

typedef enum DataEntryPhase {
    DATA_ENTRY_PHASE_IMMEDIATE = 0,
    DATA_ENTRY_PHASE_POINTER_SENT = 1,
    DATA_ENTRY_PHASE_READY = 2
} DataEntryPhase;

// Widget identifiers serialized in the evntwin*.bin data-entry windows.
typedef enum DataEntryWidgetId {
    DATA_ENTRY_PROMPT_WIDGET = 1,
    DATA_ENTRY_TEXT_WIDGET = 10,
    DATA_ENTRY_BUTTON_ONE = 0x7801,
    DATA_ENTRY_CANCEL_BUTTON = 0x7802,
    DATA_ENTRY_BUTTON_FIVE = 0x7805,
    DATA_ENTRY_BUTTON_SIX = 0x7806,
    DATA_ENTRY_BUTTON_SEVEN = 0x7807,
    DATA_ENTRY_BUTTON_EIGHT = 0x7808
} DataEntryWidgetId;

#endif // HOMM2_BASE_MISC_RUNTIME_CONSTANTS_H
