#ifndef HOMM2_BASE_SEEDED_RANDOM_CONSTANTS_H
#define HOMM2_BASE_SEEDED_RANDOM_CONSTANTS_H

// Constants for the deterministic seeded generator owned by BASE/Misc.
typedef enum SeededRandomConstant {
    SEEDED_RANDOM_TERM_MULTIPLIER = 13,
    SEEDED_RANDOM_TERM_MASK = 0xff,
    SEEDED_RANDOM_HIGH_TERM_SHIFT = 5,
    SEEDED_RANDOM_LOW_TERM_MULTIPLIER = 13233,
    SEEDED_RANDOM_FEEDBACK_MASK = 0x3f,
    SEEDED_RANDOM_FEEDBACK_SHIFT = 8,
    SEEDED_RANDOM_SEED_MASK = 0xfff,
    SEEDED_RANDOM_MIX_MULTIPLIER = 7,
    SEEDED_RANDOM_MIX_MASK = 0xff0,
    SEEDED_RANDOM_MIX_SHIFT = 4,
    SEEDED_RANDOM_TOP_BIT = 31
} SeededRandomConstant;

#endif // HOMM2_BASE_SEEDED_RANDOM_CONSTANTS_H
