#ifndef HOMM2_BASE_TEXTNTRY_TYPES_H
#define HOMM2_BASE_TEXTNTRY_TYPES_H

#include <va.h>

HOMM2_ENUM_VALUES_BEGIN(TextEntryKeyConstant)
    TEXT_ENTRY_KEY_DELETE = 0x7f
HOMM2_ENUM_VALUES_END(TextEntryKeyConstant)

HOMM2_ENUM_VALUES_BEGIN(TextEntrySourceFileConstant)
    TEXT_ENTRY_SOURCE_FILE_SLOT_SIZE = 0x2c
HOMM2_ENUM_VALUES_END(TextEntrySourceFileConstant)

#endif
