#ifndef HOMM2_WINMGR_H
#define HOMM2_WINMGR_H

#include <Ints.h>
// Declarations of the free functions DEFINED in WINMGR.cpp — the single home for these
// symbols. Other TUs call them by including this header (no local externs).

typedef enum WindowColorCycleMode {
    WINDOW_COLOR_CYCLE_DEFAULT = 0,
    WINDOW_COLOR_CYCLE_COMBAT = 1,
    WINDOW_COLOR_CYCLE_WORLD_VIEW = 2,
    WINDOW_COLOR_CYCLE_COMBAT_ALTERNATE = 3
} WindowColorCycleMode;

typedef enum WindowColorCycleConstant {
    WINDOW_CYCLE_FRAME_COUNT = 8,
    WINDOW_WORLD_CYCLE_COLOR_COUNT = 8,
    WINDOW_ALTERNATE_CYCLE_FRAME_COUNT = 6,
    WINDOW_CYCLE_REFLECTION_THRESHOLD = 5,
    WINDOW_ALTERNATE_CYCLE_REFLECTION_THRESHOLD = 4,
    WINDOW_CYCLE_PALETTE_OFFSET = 0x282,
    WINDOW_CYCLE_PALETTE_BYTES = 84,
    WINDOW_COMBAT_CYCLE_SOURCE_OFFSET = 0x14a,
    WINDOW_ALTERNATE_CYCLE_SOURCE_OFFSET = 0x144
} WindowColorCycleConstant;

typedef enum WindowColorCyclePaletteOffset {
    WINDOW_CYCLE_ROTATION_1_SAVE_OFFSET = 9,
    WINDOW_CYCLE_ROTATION_1_DESTINATION_OFFSET = 3,
    WINDOW_CYCLE_ROTATION_1_BYTES = 9,
    WINDOW_CYCLE_ROTATION_2_SAVE_OFFSET = 21,
    WINDOW_CYCLE_ROTATION_2_SOURCE_OFFSET = 12,
    WINDOW_CYCLE_ROTATION_2_DESTINATION_OFFSET = 15,
    WINDOW_CYCLE_ROTATION_2_BYTES = 9,
    WINDOW_CYCLE_ROTATION_3_SAVE_OFFSET = 51,
    WINDOW_CYCLE_ROTATION_3_SOURCE_OFFSET = 54,
    WINDOW_CYCLE_ROTATION_3_RESTORE_OFFSET = 63,
    WINDOW_CYCLE_ROTATION_3_BYTES = 12,
    WINDOW_CYCLE_ROTATION_4_SAVE_OFFSET = 81,
    WINDOW_CYCLE_ROTATION_4_SOURCE_OFFSET = 72,
    WINDOW_CYCLE_ROTATION_4_DESTINATION_OFFSET = 75,
    WINDOW_CYCLE_ROTATION_4_BYTES = 9,
    WINDOW_CYCLE_ROTATION_5_SAVE_OFFSET = 93,
    WINDOW_CYCLE_ROTATION_5_SOURCE_OFFSET = 84,
    WINDOW_CYCLE_ROTATION_5_DESTINATION_OFFSET = 87,
    WINDOW_CYCLE_ROTATION_5_BYTES = 9,
    WINDOW_DEFAULT_CYCLE_SOURCE_OFFSET = 66,
    WINDOW_DEFAULT_CYCLE_SAVE_OFFSET = 69
} WindowColorCyclePaletteOffset;

typedef enum WindowFadeMode {
    WINDOW_FADE_IN = 0,
    WINDOW_FADE_OUT = 1
} WindowFadeMode;

typedef enum WindowScreenConstant {
    WINDOW_SCREEN_WIDTH = 640,
    WINDOW_SCREEN_HEIGHT = 480,
    WINDOW_FRAMEBUFFER_DWORD_COUNT = 0x12c00,
    WINDOW_FRAMEBUFFER_FILL_COLOR = 0x24
} WindowScreenConstant;

typedef enum WindowPaletteConstant {
    WINDOW_PALETTE_COLOR_BYTES = 3,
    WINDOW_PALETTE_BYTE_COUNT = 0x300,
    WINDOW_PALETTE_DWORD_COUNT = 0xc0
} WindowPaletteConstant;

typedef enum WindowFizzleConstant {
    WINDOW_FIZZLE_DEFAULT_DELAY = 150,
    WINDOW_FIZZLE_CYCLE_TABLE_BYTES = 0x10000
} WindowFizzleConstant;

void CycleColors(i32);
void CreateFizzleTables(void);
void CreateColorTables(void);
void CreateColorLookupTables(void);

#endif // HOMM2_WINMGR_H
