// Experiment: conservative AST expression screen.
// Matrix: 96 source shapes generated by scripts/generate_ast_variants.py.
// Artifact: build/match-variants/iconf2bc-ast-screen-20260726/
// Families: commutative and relational order, independent statement order,
// identifier names, expression inlining, declaration hoist/merge.
// Best: 86.153656%. No arm improved the retained structural maximum.
// Disposition: rejected; generated helpers and spellings were not retained.

#if 0
// Representative tested arms. The artifact JSON contains the complete 96-arm list.
if (0 != color && (ICON_RLE_DIM_RECOLOR_FLAG & flags)) {
}

if (clipY <= currentY && gFCClipB >= currentY && left >= clipX
    && gFCClipR >= X) {
}

static inline int TestedHasColor(i32 color)
{
    return color != 0;
}

static inline int TestedNoClip(i32 clip)
{
    return clip == ICON_DRAW_NO_CLIP;
}

dp = gFCRow + clipX;
count = (X - clipX) + 1;

selectedDst = gFCRow + right;
src = src + (X - right);
#endif
